### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WP_Rocket\Admin\Options' not found in

### ISSUE THREAD

**Issue by jscmal** [wp-media/wp-rocket#1015]
Hi, This is my firsts post on Gitup in all my life. :) 
I tried to activate the master release of the plugin. But I experienced this.

Do you think that it is a good thing, for security reasons, that a tentative to activate the plugin without the license would return a fatal error?

Fatal error: Uncaught Error: Class 'WP_Rocket\Admin\Options' not found in /home/XXXX/wp-content/plugins/wp-rocket-master/inc/functions/options.php:18 Stack trace: #0 /home/XXXX/wp-content/plugins/wp-rocket-master/inc/functions/options.php(491): get_rocket_option('secret_key') #1 /home/XXXX/wp-content/plugins/wp-rocket-master/inc/main.php(191): rocket_valid_key() #2 /home/XXXX/wp-includes/class-wp-hook.php(286): rocket_activation('') #3 /homeXXXX/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /home/XXXX/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /homeXXXX/wp-admin/plugins.php(174): do_action('activate_wp-roc...') #6 {main} thrown in /home/XXXX/wp-content/plugins/wp-rocket-master/inc/functions/options.php on line 18

I am not properly happy to get a fatal error, in any case.

**Comment by Tabrisrp** [comment]
To use WP Rocket from the master, you need to also install the dependencies with composer, running this command: `composer install --no-dev`

**Comment by Phalconline** [comment]
Hello, I have the same issue on my hosting. Locally all works fine. 
I tried two methods:
1. Download from Wp-rocket website
2. Install via composer and run `composer install --no-dev` in wp-rocket folder, but it didn't help.

Plugin could not be activated because it triggered a fatal error.
`Fatal error: Uncaught Error: Class 'WP_Rocket\Admin\Options' not found in /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/app/plugins/wp-rocket/inc/functions/options.php:19 Stack trace: #0 /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/app/plugins/wp-rocket/inc/functions/options.php(498): get_rocket_option('secret_key') #1 /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/app/plugins/wp-rocket/inc/main.php(188): rocket_valid_key() #2 /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/wp-includes/class-wp-hook.php(286): rocket_activation('') #3 /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/wp-admin/plugins.php(174): do_action('activate_wp-roc...') #6 {main} thrown in /srv/bindings/048aa861e4c4496c9d0a747c662048bc/code/app/plugins/wp-rocket/inc/functions/options.php on line 19`

**Comment by ashish168527** [comment]
@Tabrisrp can you please help me to try this plugin I want to know what should I do after downloading the latest release from here https://github.com/wp-media/wp-rocket/releases and uploading to Wordpress plugin? in the readme it says that You can use the composer to install the plugin as a dependency: "composer require wp-media/wp-rocket" but I also tried working from other sources but they don't require this composer step I just downloaded to WordPress plugin and uploaded and activated and that worked!?  

please tell me what should I do in order to try this plugin after downloading and uploading the latest release to WordPress plugin of the WordPress site?
