### ISSUE TITLE
Allow wildcards or domain exclusions for defer js

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1022]
Our current method of excluding files from Deferred JS does not allow the use of wildcards or excluding by domain. These would be useful when you have to exclude a lot of files, or those with changing filenames. 

Example use cases: 

- https://secure.helpscout.net/conversation/601566117/71532?folderId=377611
- https://secure.helpscout.net/conversation/595370239/70450/?folderId=273766

**Comment by arunbasillal** [comment]
Exclusion based on domain would solve #1117

**Comment by blogtutor** [comment]
I'm throwing another vote in here for this.  I've run into this problem on several client sites, who use the JW Player video player (via AdThrive).

This is the code on the site that my clients add. Note that the javascript file name is different for every video, so there are a lot of hardcoded embeds on sites:

`<script src="//content.jwplatform.com/players/z0Orensy-ZrtLyYQw.js"></script>  `

With JS deferral enabled, WP Rocket adds a defer tag, and that breaks the jw player...nothing loads.

`<script src="//content.jwplatform.com/players/z0Orensy-ZrtLyYQw.js" defer ></script>  `


If I can stop deferral for the "content.jwplatform.com" domain, that would solve it, of course...but right now there's no way to block deferral for a whole domain. We can stop concatenation/minification by domain, or stop deferral by specific filename, but that's it.  

So we either need to be able to stop deferral by external domain, or by wildcard filename.

Sidenote: It would also be great if WP Rocket would automatically not defer content.jwplatform.com, since that's a very common one (I have dozens of clients using it). It's annoying to have to set up a custom plugin each time for something that's so common...

Thanks!
