### ISSUE TITLE
3.1 alpha - Combine JS Files - Regression bug - </body></html> tags removed

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1045]
The issue in video:
https://cl.ly/0F1Z1d311k0L

**Comment by Tabrisrp** [comment]
It's probably not since 3.0 (I didn't update yet the version in the test version I gave you, possibly it's confusing).

But after testing with some additional themes, I discovered after a long debugging there was a conflict with the functions for IE conditionals and the DOM Crawler.

I also discovered that those functions are not necessary anymore, so I removed them and it should fix the issue.
