### ISSUE TITLE
3.1 Alpha - Combine JS Files - Create a local copy of 3rd party scripts

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1046]
For performance and avoid to get the content of a 3rd party script on each page, we should have a "busted" version of them.

On the homepage, we can have:
```
<script src="https://google.com/external.js"></script>
<script src="https://mysite.com/internal-1.js"></script>
<script src="https://google.com/internal-2.js"></script>
```

On a post we can have more scripts like:

```
<script src="https://google.com/external.js"></script>
<script src="https://mysite.com/internal-1.js"></script>
<script src="https://google.com/internal-2.js"></script>
<script src="https://google.com/internal-3.js"></script>
<script src="https://google.com/internal-4.js"></script>
```

Then, it means we will have to 2 different concatenated files. 

And we will get the content of external.js two times when just one could be enough.

**Comment by Tabrisrp** [comment]
Here is how I see this working:
- Create a 3rd-party directory in `min` (I prefer to add it there as it's related to combine and not to busting)
- We save the 3rd party scripts local copy there, and use this copy if it exists during combine instead of fetching the remote copy
- We clean this directory when there is a `rocket_clean_minify()` call

Looks good to you?

**Comment by GeekPress** [comment]
Ok, looks good :)
