### ISSUE TITLE
3.1 Alpha-2: Console errors (ReferenceError) with Uncode theme

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1066]
Can be seen in our megasite/uncode/
Its Load JavaScript deferred  of course.

**Comment by Tabrisrp** [comment]
Test website was not updated to 3.1, it was still on 3.0.5.1. With the update, there isn't any error anymore.

**Comment by arunbasillal** [comment]
Please recheck now, the Uncode Visual Composer plugin that was required to render the theme was deactivated. 

These are the console errors I see now:

`TypeError: currentRow is null`
`ReferenceError: Waypoint is not defined`

**Comment by Tabrisrp** [comment]
With the way it works for some of its features, Uncode is not compatible with combine JS and defer JS without adding a number of exclusions:
- there is inline scripts doing a get id on themselves, which will not work anymore of they are combined, since the tag is removed
- those inline scripts depend on the UNCODE variable, which is set in init.js
- init.js depends on the SiteParameters variable set in an inline script

This is completely broken. The best way to improve compatibility for this will be to create a specific 3rd-party file to handle the exclusions in this specific case.
