### ISSUE TITLE
Savvii Compatibility. Caches not in sync

### ISSUE THREAD

**Issue by emlebrun** [wp-media/wp-rocket#1075]
The varnish add-on showed the correct message. But clearing Savvii (via admin bar "Flush All Cache") did not clear WP Rocket cache. 

Couldn't test if WP Rocket cache clear was clearing Savvii cache, response headers always had this: `X-Varnish-Cache: MISS`

I have added `time()` in the website description (top left corner) to see if cache is being served or not. 

Logins: https://wp-media.slack.com/archives/CBJ2KQ0MU/p1531923312000499

**Comment by GeekPress** [comment]
I was able to reproduce the issue on our test website.

Their check is now different than ours:
https://github.com/Savvii/warpdrive/blob/3dea7644e66ab051a992f22f98d9cfbdaa292de7/src/class-cache-flusher-plugin.php#L142

Vs

https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/hosting/savvii.php#L47

It could be the reason.

@wp-media/dev We just have the WP access, will you need FTP?

**Comment by hellofromtonya** [comment]
@GeekPress Yes, we’ll need to FTP access too please?

**Comment by GeekPress** [comment]
> @GeekPress Yes, we’ll need to FTP access too please?

I've just asked for ;)

**Comment by engahmeds3ed** [comment]
**Reproduce the issue** ✅ 
Identified the issue on our test savvii site.

**Identify the root cause** ✅ 
https://github.com/wp-media/wp-rocket/blob/master/inc/3rd-party/hosting/savvii.php#L47-L59
this nonce is failing.

**Scope a solution** ✅ 
we need to restructure this file on our new architecture and use their actions and nonce names.

**Effort** ✅ 
effort `S` needed for the new architecture and tests

**Comment by Davidacu** [comment]
Hey @GeekPress 
Were you able to get FTP Access?

**Comment by Tabrisrp** [comment]
Blocking this waiting for PR #2874

**Comment by Tabrisrp** [comment]
Unblocking after merge of PR #2874
