### ISSUE TITLE
CSS minification: Exclude CSS files from Uncode theme

### ISSUE THREAD

**Issue by ernee** [wp-media/wp-rocket#1194]
Customers report that the cache dir size increases with Uncode theme. Excluding this CSS file path has resolved several cases: 

/wp-content/themes/uncode/library/css/(.*).css

Perhaps auto-exclude as well?

tickets:

https://secure.helpscout.net/conversation/662328344/79959?folderId=1391600

https://secure.helpscout.net/conversation/640260108/76736/

**Comment by GeekPress** [comment]
These files also needs to be excluded from the cache busted option. 

The best solution will be to auto-replace the dynamic query string by the theme version. Or to contact the theme developer to ask them to put the theme version instead of a ramdom query string

**Comment by Tabrisrp** [comment]
@wp-media/supportrocket Is this a common issue?

**Comment by GeekPress** [comment]
I was in contact with Uncode team. The issue is because of the Production Mode option with Off value.

To fix the issue, we can ask to our users to turn on the Production mode.
https://undsgn.d.pr/eLOsFj

On our side we could override or force the value of the Production Mode if our minification option is turned on.

It's also related to this issue:
https://github.com/wp-media/wp-rocket/issues/1628

**Comment by GeekPress** [comment]
This is fixed since Uncode 2.10.
