### ISSUE TITLE
Google Tag Manager detection fails when URL uses relative protocol

### ISSUE THREAD

**Issue by x1024** [wp-media/wp-rocket#1315]
The regex used in `class-google-tag-manager.php` doesn't detect script tags like this:

```
<script async src="...">
```

Unfortunately, that's the code I was given, and I assume it's the default code that GTM generates for end-users.
I presume this `async` issue is also true for other scripts that should be locally-copied.

Another issue I ran into is that when the script is loaded with a protocol-relative URL, the regex doesn't catch it either:

```
<script src="//www.googletagmanager.com/...">
```

Changing the URL to the standard format fixed it:

```
<script src="https://...">
```

However, I feel that this is difficult for non-technical users to figure out, and it's therefore a bug.

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
Tested the 2 cases provided:
- The `async` one works as expected, the replacement is happening ✅ 
- The relative protocol is indeed failing ❌

**Identify the root cause** ✅ 
The relative protocol is failing because it's not possible to do requests on relative URLs using the `wp_remote_*` methods. We currently try to do so, which results in an error, so we can't fetch the URL content and need to bailout.

**Scope a solution** ✅ 
The fix is pretty simple. In the `Google_Tag_Manager::replace_url()` method, we can check if the URL have the `https` scheme or not, and if it doesn't, add it.

**Estimate the effort** ✅ 
Effort `[S]`. We can take the opportunity to move this class to the new architecture too
