### ISSUE TITLE
Please implement an interface to locally-cache arbitrary scripts.

### ISSUE THREAD

**Issue by x1024** [wp-media/wp-rocket#1317]
The new feature to cache Google and Facebook tracking scripts is very useful and seems to be stable-enough.

Please consider adding a feature where arbitrary tracking scripts can be cached in the same way.
Since this is probably only going to be used by power-users, it would be OK to hide this in an add-on that's opt-in, and/or to have it require the user enter regular expressions in inputs.

I imagine the UI can function similarly to the UI for the `Excluded JavaScript Files` feature in the `File Optimization` tab.

Thanks.

**Comment by arunbasillal** [comment]
I have been thinking of the same and considering possibilities on the best way to incorporate this. I am gladly surprised to find a feature request for the same. 

The benefit of doing this is so that we can stop adding more and more add-ons for third party scripts.

**Documenting some thoughts.** 

- Our add-on's are currently for 3rd party integrations. Technically external files are also 3rd party, so maybe we could implement an add-on. 
- Another option is to have a text area in the `Advanced tab`. Enter the external file url one per line. 
- Each script is currently refreshed once a week. We could keep this as the default for every file. If we do the add-on though, we could have a drop down per file. Similar to how we do for CDN.

**Comment by GeekPress** [comment]
@x1024 In 3.7, we have introduced a feature to delay JS execution. Delaying external JavaScript files is better than localizing them. I recommend you to try this new awesome feature :)
