### ISSUE TITLE
The Facebook Pixel add-on breaks the Facebook Comments plugin

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1323]
When enabled, the Facebook Pixel add-on breaks the **[Facebook Comments Plugin](https://developers.facebook.com/docs/plugins/comments/)**.

**To Reproduce**
1. Go to https://www.tediado.com.br/11/improvavel-escolinha-improvavel-20/?nocache
2. There is a comment box there (https://vgy.me/kAd0ow.jpg) 
3. Go to https://www.tediado.com.br/11/improvavel-escolinha-improvavel-20/
4. The comment box is gone

It seems that when we replace the `https:\/\/connect.facebook.net\/pt_BR\/sdk.js`, we change the scheme:
`http:\/\/connect.facebook.net\/pt_BR\/sdk.js`

Check the diff here:
https://www.diffchecker.com/9D4c9PgZ

It's taken from the file downloaded directly from Facebook (on the left) and the one that we produce (on the right).

You can download the files here:
http://bit.ly/2Db4xee

**Related Ticket**
https://secure.helpscout.net/conversation/704026920/85516?folderId=2135277

**Comment by Screenfeed** [comment]
Sorry but I couldn’t reproduce the issue, the file I get has the https.
On a side note, instead of having `"revision": "4520341"` on the same line, I get `"revision":"4521801"`, so it seems it’s more recent. Since we don’t modify this file content, I'm guessing this revision `4520341` was delivered with this bug but not the new release.
I’d advise to do a new test on the customer’ site (by removing all the old files first).

**Comment by webtrainingwheels** [comment]
another case https://secure.helpscout.net/conversation/759292826/93728?folderId=377611

**Comment by alfonso100** [comment]
Another case: https://secure.helpscout.net/conversation/779026599/96657?folderId=2683093

**Comment by viobru** [comment]
Another case: https://secure.helpscout.net/conversation/954924180/122979/

**Comment by crystinutzaa** [comment]
This is not going to work because it needs:
`window.fbAsyncInit = function fbAsyncInit () {FB.init()})}`

However I noticed that this type of URL will not be busted:
`<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v5.0&appId=323009824493514&autoLogAppEvents=1"></script>`

Only this will get busted:
```
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=323009824493514&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
```
