### ISSUE TITLE
Improvement: Exclude cookies with wildcards

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1358]
At this moment all exclusion fields except **Never Cache Cookies** one support wildcards.
It looks like sanitization is not allowing to save the value with (.*).

Related ticket:
https://secure.helpscout.net/conversation/705905265/85916/?folderId=2415573

**Comment by Tabrisrp** [comment]
@wp-media/supportrocket Do you see this as something useeful for the customers and that will reduce support tickets?

**Comment by kieran-wpmedia** [comment]
Related ticket: https://secure.helpscout.net/conversation/947703091/121720/

The customer would have benefited from the Never Cache Cookies field supporting wildcards. All of the cookies begin with wlm_ and therefore could have saved this customer from reaching out for a full list of all cookies from the third-party developer.

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
https://github.com/wp-media/wp-rocket/blob/8b7bce27f67b4eb5e3c96aa62a8de97207271b64/inc/functions/formatting.php#L166

**Scope a solution** ✅ 
Current sanitization allows only a-z0-9_-.
The solution will be to remove `rocket_sanitize_key` for `cache_reject_cookies` and add `rocket_clean_wildcards` + create a new rule which will allow `a-z0-9_-()*.`

**Effort** ✅ 
Effort `[S]` , I think Unit & Integration tests will need almost all the effort

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1252893853/186455/

**Comment by alfonso100** [comment]
While wildcards are not accepted, **partial match** works.
So adding `wp_woocommerce_session_` will be similar to using `wp_woocommerce_session_(.*)` in excluding any tokenized cookie that matches the string.

For example, in [this doc](https://docs.wp-rocket.me/article/875-using-wp-rocket-with-yith-woocommerce-wishlist), we recommend a partial match that will cover any case of `yith_wcwl_session_[TOKEN]`

**Comment by Tabrisrp** [comment]
@arunbasillal Since partial match works, should this be closed?

**Comment by arunbasillal** [comment]
@webtrainingwheels Since partial match works(https://github.com/wp-media/wp-rocket/issues/1358#issuecomment-731167735) we could improve the wording in the UI? 

![image](https://user-images.githubusercontent.com/5751474/102749324-da7ae600-4389-11eb-936f-9cedfcd872af.png)

**Suggested**: Specify partial or full IDs of cookies that, when set in the visitor's browser, should prevent a page from getting cached (one per line)

**Comment by arunbasillal** [comment]
@webtrainingwheels Sorry for the false ping. We already discussed this and validated it here - https://github.com/wp-media/wp-rocket/issues/3334#issuecomment-731976401

(All the time I wrote the reply, I was looking for something similar and couldn't find it. It was the very same thing 😂)
