### ISSUE TITLE
Embed minified CSS into HTML

### ISSUE THREAD

**Issue by dev4press** [wp-media/wp-rocket#1363]
**Is your feature request related to a problem? Please describe.**
When using the minify CSS feature, the plugin generates a single CSS file. But, this file is still labelled as render blocking, because it is a file and it has to be loaded.

**Describe the solution you'd like**
Why not embed the whole minified CSS file inside the HTML head? For my website, that would about 150KB to HTML (and I imagine it would range from 50 to 500 KB for some websites), making little difference to initial loading (especially since the HTML is GZiped before delivery), but all the CSS is part of the page, and it is no longer render blocking!

Add extra option along with the Minify settings, to turn on HTML embedding.

**Comment by GeekPress** [comment]
Hi @dev4press 🤚

Thanks for your suggestion and sorry for the delay, as we send in France, « better late than never ».

Adding the whole CSS into the `<head>` isn't a good practice and it's totally not recommended to do that.

Since you submitted this feature request, WP Rocket can generate CPCSS and "defer" the CSS to not be render-blocking anymore.
