### ISSUE TITLE
PHP Warning: class-homepage.php

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1370]
Several customers are reporting this PHP Warning: 
`Warning: Invalid argument supplied for foreach() in /wp-content/plugins/wp-rocket/inc/classes/preload/class-homepage.php on line 25`

HS tag: `class-homepage.php`

**Comment by vmanthos** [comment]
Similar error regarding the `class-homepage.php`.
```
Undefined index: path in /home/larossy1/public_html/wp-content/plugins/wp-rocket/inc/classes/preload/class-homepage.php on line 112
```
**Related ticket:**
https://secure.helpscout.net/conversation/712073950/86951/

**Comment by Tabrisrp** [comment]
`Notice: Undefined index: host in /home/tekfused/public_html/wp-content/plugins/wp-rocket/inc/classes/preload/class-homepage.php on line 104`

**Comment by vmanthos** [comment]
Activating the preload feature results into this:
```
Warning: Invalid argument supplied for foreach() in /home/example/public_html/wp-content/plugins/wp-rocket/inc/classes/preload/class-homepage.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /home/example/public_html/wp-content/plugins/wp-rocket/inc/classes/preload/class-homepage.php:25) in /home/example/public_html/wp-includes/pluggable.php on line 1219
```
The settings are saved.

Clicking the Preload on the admin bar throughs the same error and the same goes for installing WP Rocket from scratch.

**Related Ticket:**
https://secure.helpscout.net/conversation/713106264/87170/

**Comment by vmanthos** [comment]
Another related ticket here:
https://secure.helpscout.net/conversation/709793447/86599?folderId=273761

His comment about this:
> il faut savoir que le site en question présente un certificat non valide (car local) pour le https ce qui peut expliquer l'erreur.

Translation:
> You should know that the site in question has an invalid certificate (because local) for the https which can explain the error.

**Comment by vmanthos** [comment]
A customer debugged this line:
https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/classes/preload/class-homepage.php#L57
​
Initially, he got this:
​
`cURL error 7: Failed connect to example.com:443; Operation now in progress`

which is a firewall blocking the request, as a result of not adding the `127.0.0.1 example.com` in  `/etc/hosts`. So, the server is trying to reach itself over the internet and it fails.
​
Fixing this brought up another error:
​
`the $response value in class-homepage.php is : cURL error 60: Peer's Certificate issuer is not recognized`

due to not adding the intermediate and root CA certs in the apache configuration.
​
Yet another error:
​
`$response value in class-homepage.php is : cURL error 28: Operation timed out after 5001 milliseconds with 0 out of -1 bytes received.`

After fixing the previous errors on the server, the last one was dealt with our helper plugin which extends the cURL time-out.

**Suggestions**
Apart from adding additional checks, it would be useful to show an admin warning with the returned error when the request fails.

**Related ticket:**
https://secure.helpscout.net/conversation/709793447/86599/
