### ISSUE TITLE
Add a filter to prevent 304 response

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#1423]
This could be useful in solving some weird cases like: 

- https://github.com/wp-media/wp-rocket/issues/1282
- https://wp-media.slack.com/archives/C43T1AYMQ/p1544222777052700

**Comment by Tabrisrp** [comment]
since we're in process.php, using filters is complicated

**Comment by arunbasillal** [comment]
Oww right. So we need a variable instead. 

I think lets give it some time to see if we can find a pattern and see how often these issues occur. Maybe we can find a more perfect solution.

**Comment by piotrbak** [comment]
Aelia Currency Switcher compatibility seems to break because of that. Here's related ticket:
https://secure.helpscout.net/conversation/718054372/88214?folderId=2415573

**Comment by piotrbak** [comment]
Our compatibility with Aelia Currency Switcher breaks when IP Geolocation is disabled and rewrite rules are present. In this scenario:

- Dynamic cookie [is set](https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/3rd-party/plugins/ecommerce/aelia-currencyswitcher.php#L82)
- Mandatory cookie [is not set](https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/3rd-party/plugins/ecommerce/aelia-currencyswitcher.php#L100), because IP Geolocation is turned off
- It's bringing us to the moment when index.html file (without the dynamic cookie value) is created
- Rewrite rules are present, might be because of [this issue](https://github.com/wp-media/wp-rocket/issues/1090) or because of deactivation and activation WP Rocket (It's adding rewrite rules during WP Rocket activation on Mega, [this code](https://github.com/wp-media/wp-rocket/blob/f8def46c4563f555d3c6627362bd78b6260150df/inc/3rd-party/plugins/ecommerce/aelia-currencyswitcher.php#L9) is not preventing)

At this moment everything goes fast:
- index.html file is saved with the default currency after the first visit
- Customer visits product page again, change the currency to different one
- When refreshing the page or coming back to it, the currency will be changed to the default one because the web server is serving index.html file from the rewrite rules.
- It's affecting all cached WooCommerce pages, not only the products
- 304 response code appears there, but it's served from the web server directly because of the rewrite rules

Here's a short video showing the problem:
https://www.useloom.com/share/c17036643f4d444b9580a6b7fecdb010

Possible fixes:
- Making sure Mandatory Cookie is present. It will prevent serving cache until customer choose the currency, in some cases **he won't choose** it during the whole interaction with shop
- Adding a default value for 'aelia_cs_selected_currency' cookie within Aelia code, it will prevent WP Rocket from creating index.html file
- Making sure that there are no Rewrite rules in the .htaccess

**Comment by Tabrisrp** [comment]
Rewrite rules should never be present, and it's most likely linked to #1090, so fixing that issue should fix this one too.

**Comment by vmanthos** [comment]
A similar request about filtering headers: https://secure.helpscout.net/conversation/1266153393/190415/

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1510312134/263353/

**Comment by sandyfzu** [comment]
Related ticket: https://secure.helpscout.net/conversation/1541229218/271141

**Comment by piotrbak** [comment]
For now it's not planned for development. We might revisit this in the future.
