### ISSUE TITLE
Disable lazyload for Divi slider

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#147]

**Comment by glueckpress** [comment]
… and for the parallax feature! :)

**Comment by sedwebdev** [comment]
+ https://diviplugins.com/how-to-disable-wp-rocket-lazy-load/
+ https://docs.wp-rocket.me/article/657-divi-theme

**Comment by arunbasillal** [comment]
I couldn't replicate this for the slider and the parallax effect. We have very few tickets about this. Since Divi is very popular, I would expect to see a lot more tickets about this. Maybe this is one off

**Comment by webtrainingwheels** [comment]
This seems to still pop up from time to time: e.g. https://secure.helpscout.net/conversation/999290948/130253?folderId=273764

We have [documentation with a code edit in the theme](https://docs.wp-rocket.me/article/657-divi-theme#slider-module-and-lazyload), obviously that's not ideal. 

@arunbasillal could you reach out to your contact there about adding a filter to this part of the code so that we could exclude these images as needed? (or I can do it if you prefer)

**Comment by arunbasillal** [comment]
@webtrainingwheels The customer reported that after updating to a newer version of Divi the issue was resolved. 

- Do we have other such reports? Or was it just one off / using old theme? 
- If we need changes at Divi's end, we could simply request an image class to be added, right? Which can them be excluding from LazyLoad as we do for images.
