### ISSUE TITLE
Add admin notice if WP Critical CSS plugin is actived

### ISSUE THREAD

**Issue by sabrina-zeidan** [wp-media/wp-rocket#1536]
Our Optimize CSS delievery option isn't saved and critical css isn't included in the page when plugin [WP Critical CSS](https://wordpress.org/plugins/wp-criticalcss/) is enabled.

**Related ticket**:
https://secure.helpscout.net/conversation/776815167/96324

**Comment by sabrina-zeidan** [comment]
Our Optimize CSS delievery option isn't saved and critical css isn't included in the page when plugin WP Critical CSS is enabled.
**Related ticket**: 
https://secure.helpscout.net/conversation/776815167/96324

**Comment by arunbasillal** [comment]
Hello @Tabrisrp, doing QA for this.

I do not see the notice. As soon as `WP Critical CSS` is active, our Critical Path CSS is disabled. 

In the changelog for WP Critical CSS, there is an entry `Compatibility: Force wp-rocket’s critical css off`. I think this is the reason - https://wordpress.org/plugins/wp-criticalcss/#developers

**Comment by Tabrisrp** [comment]
Ok I possibly didn't have the latest version of the plugin installed when testing, so I missed that.

This mean this issue can just be closed since they handle this on their side already.

**Comment by arunbasillal** [comment]
@Tabrisrp That's not the case. 

In the ticket Sabrina shared, the customer is confused because he enabled `Optimize CSS delivery`, but the option never stays active. That is because of the `WP Critical CSS` plugin and with the notice our aim is to warn the customer about this. 

See the ux when `WP Critical CSS` is active - https://jmp.sh/4yICHRs

We could take a different approach and grey out the `Optimize CSS delivery` option when `WP Critical CSS` is active. 

Re-opening again since we need a solution for this confusion either way.
