### ISSUE TITLE
Proposal: Improve notice when Cloudflare plugin is detected 

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#1566]
When the official Cloudflare plugin is detected, we show our generic deactivation warning:

> The following plugins are not compatible with this plugin and may cause unexpected results:

But we still get tickets about this - it's not clear to customers why they're incompatible or if there will be some other problem if they deactivate one or the other, etc. 

I think we could improve the notice to explain a bit further. Along the lines of:  
```
The Cloudflare plugin is not required because the WP Rocket Cloudflare add-on has the same functionality. 
```

**Comment by ScottTravisHartley** [comment]
I want to note as well that the CloudFlare plugin does have the "auto cache management" this feature automatically purges the Cloudflare cache if it detects any changes such as post edits, or adding a new post. 

This is important if the website is caching the HTML either by page rules or by a worker so that way it can clear the cache when a new post is published so users are able to see it on the homepage/archives when it is published. 

If WPRocket added that functionality either by an option under the addon or by default that would truly replace the Cloudflare plugin in its entirety outside of the analytics data that no one really cares about anyway

**Comment by arunbasillal** [comment]
`auto cache management` is proposed in #1521

**Comment by crystinutzaa** [comment]
WP Rocket shows bulk messages for all plugins which can cause conflicts. So the general error message will look like this:
https://www.screencast.com/t/ILnHxk3f

For Cloudflare should be a new error notice or should I edit the display of the current notice and make the plugin name in bold and add an explainer text next to each plugin (currently only Cloudflare):
example: https://www.screencast.com/t/0hKXgvhfGc6Y

**Comment by Tabrisrp** [comment]
I like the second solution, it looks clean and we can build on that to give more information for each plugins if needed.
