### ISSUE TITLE
Conflict with canonical tag and Force SSL rewriting option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#158]
A customer reports by enabling the "Force SSL rewriting for Images, Scripts, etc" option in WP Rocket's option, it causes a conflict with the canonical tag.

Here the ticket:
https://secure.helpscout.net/conversation/249102087/22058/?folderId=273764

**Comment by arunbasillal** [comment]
@GeekPress Is the option `Force SSL rewriting for Images, Scripts, etc` same as `Relative Protocol` in our Cloudflare add-on? - https://jmp.sh/7zW4d9O

**Comment by GeekPress** [comment]
@arunbasillal I'm closing this one as we never had any complaints about being a problem to not have the HTTP protocol into the canonical tag.

**Comment by webtrainingwheels** [comment]
@GeekPress Reopening this since we have several complaints about "relative protocol" being applied on the canonical tag: 

- https://secure.helpscout.net/conversation/1429100001/240410/
- https://secure.helpscout.net/conversation/1408019992/234769/
- https://secure.helpscout.net/conversation/1405987790/234171/
- https://secure.helpscout.net/conversation/874983744/110949/
- https://secure.helpscout.net/conversation/834139913/105190/

**Comment by GeekPress** [comment]
@webtrainingwheels Thanks for the feedback. I think it's time to get rid of this option. It has no relation with performance and it was added during a time when HTTP & HTTPS versions of a website were accessible. In 2021, we can safely confirm that an important majority of websites using SSL have an automatic redirection from HTTP to HTTPS.

**Comment by remyperona** [comment]
@wp-media/productrocket Should we groom this as "remove relative protocol" option?

**Comment by GeekPress** [comment]
@Tabrisrp I think we need to open a new issue about the remove relative protocol option. I'm still wondering what could be the impact of doing that as Cloudflare still have the Flexible SSL option.

**Comment by piotrbak** [comment]
Closing as it was addressed here:
https://github.com/wp-media/wp-rocket/issues/5781
