### ISSUE TITLE
Database queries in the WordPress dashboard

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1599]
Right now WP Rocket is making approximately 18 queries on each page load in the WordPress admin area.

Queries are related to the transients and return up to 1 record. Basically, they're pretty fast queries.

However, in an environment where the wp_options table is enormous due to the plugins that use it to store a lot of data instead of creating their own tables, the situation might change. The wp_options table could also grow due to the plugins that don't delete their records correctly when deactivating.

We could replace those queries with PHP checks that should be faster even if the wp_options table is not spammed with records.

Execution times of those queries should be checked on environments with the flooded wp_options table. 

Slack thread:
https://wp-media.slack.com/archives/C43T1AYMQ/p1553874846017700

**Comment by alfonso100** [comment]
I have a case similar to what Boniu is describing, here:
https://secure.helpscout.net/conversation/1199735290/174271?folderId=2683093

This website has some big tables, so hitting the DB with multiple queries increases the server load and makes it almost unresponsive. Of course, these issues are not being caused just by WP Rocket queries, but they weren't having issues before with Comet Cache

**Comment by arunbasillal** [comment]
Please refer this issue where the user @Camilo517 have raised few specific concerns as well - https://github.com/wp-media/wp-rocket/issues/3042#issue-688591362

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
We perform some transients checks on all pages in the admin. This is not necessary in all cases, and can cause some slowness in cases where the `wp_options` table is very big.

### Scope a solution ✅ 
#### Some checks should be performed only on WP Rocket settings page:
- Check for `wp_rocket_pricing` transient
- Check for `wp_rocket_customer_data` transient

#### Some checks should be performed only if the option is enabled:
- Check for `rocket_critical_css_generation_triggered` only if optimize CSS delivery is enabled
- Check for `sucuri_purge_result` only if sucuri add-on is enabled
- Check for `rocket_preload_triggered` only if preload is enabled

#### Check only on the plugins page:
- Check for `_donotdeactivaterocket` only on the plugins page

### Estimate the effort ✅
Effort `[S]`

**Comment by jazir555** [comment]
Anything new with this? I have a pretty slow admin dashboard and this might contribute to it
