### ISSUE TITLE
Kinsta wp-config editing bug in staging

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#1619]
When installing wp-rocket in kinsta staging then going to another page you get a 500. It is due to bad regex assumptions. See below:

```
<?php
define('WP_CACHE', true); // Added by WP Rocket
<?php if ( !defined('KINSTA_DEV_ENV') ) { define('KINSTA_DEV_ENV', true); /* Kinsta staging - don't remove this line */ } ?>
<?php if ( !defined('JETPACK_STAGING_MODE') ) { define('JETPACK_STAGING_MODE', true); /* Kinsta staging - don't remove this line */ } ?>
```

Adding php like this ideally should be done with tokenization rather than regex. but this basically fatal's everything.

**Comment by piotrbak** [comment]
Another case:
https://secure.helpscout.net/conversation/1098839443/149079/

**Comment by vmanthos** [comment]
Another case:
https://secure.helpscout.net/conversation/1179007502/168829/

**Comment by vmanthos** [comment]
Another one:
https://secure.helpscout.net/conversation/1184276986/170253?folderId=2135277

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
The root cause is in this function: 
https://github.com/wp-media/wp-rocket/blob/8b7bce27f67b4eb5e3c96aa62a8de97207271b64/inc/functions/files.php#L288

**Scope a solution** ✅ 
A solution is to change how WP_CACHE is added by WP Rocket. In order to be way more independent I would go to be added on the first line on wp-config.php file and should contain <?php and ?>
like this: 
```
// Get WP_CACHE constant define.
$constant = "<?php define('WP_CACHE', $turn_it_on); // Added by WP Rocket ?>";
```

**Effort** ✅ 
Effort `[S]` , I think Unit & Integration tests will need almost all the effort

@Tabrisrp & @hellofromtonya what do you think about this approach?

**Comment by Tabrisrp** [comment]
@crystinutzaa Isn't it what Ahmed did there? https://github.com/wp-media/wp-rocket/pull/2740

**Comment by crystinutzaa** [comment]
@Tabrisrp this is not 100% what I meant, but it seems that the PR is fixing the issue 

This can be closed due to this PR https://github.com/wp-media/wp-rocket/pull/2740
