### ISSUE TITLE
Content is not preloaded for secondary languages on multi-language sites using The SEO Framework

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1634]
**The SEO Framework** plugin, when used in multi-language sites using a subdirectory install for the added languages, e.g. using the WPML plugin, creates separate sitemaps for each language. Those are accessible like this:
* example.com/sitemap.xml, for the main language
* example.com/de/sitemap.xml for German
* example.com/fr/sitemap.xml for French etc.

The `get_sitemap_xml_url()` function which WP Rocket uses here:
https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/3rd-party/plugins/seo/the-seo-framework.php

only returns the sitemap for the main language. So content for added languages is not preloaded.

Disabling the **The SEO Framework XML sitemap** option and directly adding the `sitemap.xml`'s in the **Sitemaps for preloading** text area resolves this.

**Related ticket:**
Intercom: https://app.intercom.io/a/apps/llnz7wr8/inbox/inbox/conversation/20776896450#part_id=comment-20776896450-2711617546

**Note**

Having the URLs for added languages in one sitemap was considered a bug for the TSF developer:
https://github.com/sybrew/the-seo-framework/issues/293/

**Comment by Tabrisrp** [comment]
@sybrew Is there a way to get the sitemap URL for the different languages?

**Comment by sybrew** [comment]
Hello!

The answer is no<sup>1</sup>, maybe<sup>2</sup>, and no<sup>3</sup>. 

Also, yes, if you've queried the right language; but, that's [already in place](https://github.com/sybrew/the-seo-framework/blob/3.2.4/inc/classes/sitemaps.class.php#L468-L493), and [implemented](https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/3rd-party/plugins/seo/the-seo-framework.php#L99). So, as I don't know why this is an issue, probably still: no.

<strong>No<sup>1</sup>:</strong>
We don't have a mechanism in place to provide these URLs programmatically. This is because The SEO Framework is "unaware" of any possible environmental changes, it just "takes" them as provided, and uses that. 

What this means is that we only register the endpoints, i.e. `/sitemap.xml`, and WordPress creates the environment when that's called: the blog id, the locale, etc. From there, we query the WordPress Posts API for the posts, and WPML (or any other translation plugin) filters the query as it normally would. 

There's no targeted interaction towards or from WPML (or any other translation plugin) in this regard.

1. https://github.com/sybrew/the-seo-framework/blob/3.2.4/inc/classes/sitemaps.class.php#L87
1. 1. https://github.com/sybrew/the-seo-framework/blob/3.2.4/inc/classes/init.class.php#L113
    1. https://github.com/sybrew/the-seo-framework/blob/3.2.4/inc/classes/sitemaps.class.php#L100-L107

<strong>Maybe<sup>2</sup>:</strong>
The URL is predictable and not (intended to be) filterable.
`(sub.)?domain.tld(/path)?/sitemap.xml(\?query=args)?`, e.g.:
1. `example.com/sitemap.xml`
1. `example.com/de/sitemap.xml`
1. `de.example.com/sitemap.xml`
1. `example.com/sitemap.xml?lang=de`

Moreover, if you have mechanisms in place that can detect translation endpoints, then you can follow them by replacing this line...
https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/3rd-party/plugins/seo/the-seo-framework.php#L99

...and looping over each registered language instead, like so:

```php
while ( my_loop_language_query() ) 
	$sitemaps[] = the_seo_framework()->get_sitemap_xml_url(); 
```

However, I doubt that this is possible without resetting the WordPress filter & action loop. So, this specific solution should be ruled out.

Method reference: [the_seo_framework()->get_sitemap_xml_url()](https://github.com/sybrew/the-seo-framework/blob/3.2.4/inc/classes/sitemaps.class.php#L495-L533)

<strong>Final word: No<sup>3</sup>.</strong>
I believe this issue should be flagged as a "can't fix" corner case scenario. I also believe the same holds for any other plugin that registers a non-multilingual sitemap. Keep in mind that we're now trying to make four systems compatible... one of which has to completely hijack WordPress' query system.

In any case, the best solution would be to introduce this feature: https://github.com/sybrew/the-seo-framework/issues/69, which isn't worth my time as both Google and Bing are phasing out sitemaps in favor of newer APIs (live indexing, hreflang headers, etc.), and they aren't reliant upon them for ranking or crawling anyways.

<strong>Workaround</strong>
I can't propose a workaround, as I don't have access to WP Rocket. But, keep in mind that The SEO Framework has its custom self-managed caching mechanism (via transients) in place for the sitemaps, which should be sufficient for its intended use-case: Allow search engines to download the file, and prevent useless regeneration on every subsequent request.

**Comment by Tabrisrp** [comment]
Thank you for your detailed input, I was not expecting so much!

From what you said, this will be a `wontfix`, as there is no easy way to do that automatically, and users can fallback to the manual input.
