### ISSUE TITLE
Disable background images lazyloading for the Enfold theme

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#1652]
When an image is set as a background for a section on a site using the **Enfold theme**, the image is blurry if WP Rocket's lazyload is enabled.

![Screenshot](https://i.vgy.me/MkNqVY.jpg)

Installing our [helper plugin](https://github.com/wp-media/wp-rocket-helpers/tree/master/lazyload/wp-rocket-no-lazyload-background-images) resolves the issue.

**Proposed solution**

Automatically disable lazyload for background images as we do for the Bridge theme:
https://github.com/wp-media/wp-rocket/blob/7de6e7024760c4e4021d09e335c59005f30d3c33/inc/classes/subscriber/third-party/Themes/class-bridge-subscriber.php

**Related Ticket**
https://secure.helpscout.net/conversation/825262205/103888?folderId=2135277

**Comment by arunbasillal** [comment]
@Tabrisrp During QA, @vmanthos and I dug a bit more into this and the issue is only happening:

- On mobile
- when background image is `fixed`

You can see a demo here - http://mega.wp-rocket.me/enfold/wp-admin/post.php?post=3293&action=edit
(what to look for - https://jumpshare.com/v/hpo2pqTYUwCJIRR9lOQe )

These images have the class `avia-bg-style-fixed` added to it - https://jumpshare.com/v/hL3bA65VYQrcMEO5zCGN
So if we could exclude only these specific images, that would be a more ideal solution.
