### ISSUE TITLE
Preloading works on Update and NOT on Publish

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1692]
Our doc states that:
> when you publish or update posts/pages/custom post types, WP Rocket automatically clears the cache for that specific content and any other content related to it (i.e. home, category, tag, pagination etc.). This content and the related pages will be preloaded automatically.

But Preloading works on Update and NOT on Publish.
 
@arunbasillal tested it in this tread: https://wp-media.slack.com/archives/C43T1AYMQ/p1557220541017500

Ref ticket: https://secure.helpscout.net/conversation/846017721/106780/

**Comment by Tabrisrp** [comment]
Was it tested with Gutenberg and the classic editor?

**Comment by vmanthos** [comment]
I'm investigating that ticket now. 

The issue Romain reported, takes place with both Gutenberg and the classic editor.

Publishing the post clears the respective taxonomies, but that post is _not_ preloaded.

**Comment by Tabrisrp** [comment]
**Since when?**
This is happening since 3.3.1

**Why?**
In 3.3.1, we did a change to use the `$post` object passed from the `clean_post_cache` action to `rocket_clean_post()`. Apparently, the `post_status` property of the object passed is not yet up to date, so it's returning `draft` instead of `publish`.

If performing a `get_post()` directly instead, the `post_status` property value is correct.

**Solution**
Don't rely on the `$post` object passed, but perform a `get_post()`. This is done by changing the line 240 and removing the `$accepted_args` parameter.
