### ISSUE TITLE
mod_deflate rules conflict with Divi Builder on OVH hosting

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1743]
mod_deflate rules can conflict with Divi Builder. 
You can’t save/load a template when these rules are in place.
It only happens on OVH hosting.

tickets: https://secure.helpscout.net/search/?query=%20tag:divi%20builder%20tag:mod_deflate

**Comment by alfonso100** [comment]
Another case here: 
https://secure.helpscout.net/conversation/875615609/111032?folderId=2683093

**Comment by camilamadronero** [comment]
Another one:
https://secure.helpscout.net/conversation/913412283/117433/

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/971295941/125321?folderId=377611

**Comment by WordPresseur** [comment]
https://secure.helpscout.net/conversation/989053047/128316/

**Comment by vmanthos** [comment]
Another one:

https://secure.helpscout.net/conversation/993022675/129038/

**Comment by WordPresseur** [comment]
Another one: https://secure.helpscout.net/conversation/1086317397/146648?folderId=1213662

**Comment by vmanthos** [comment]
@GeekPress 

It seems the `mod_deflate` rules are causing other issues too on OVH, e.g. export options are not working.
This is fixed by disabling those rules with the respective helper plugin.

OVH is automatically applying compression, regardless of the removal of the rules, so this doesn't have an impact.

Since we are getting a few tickets about these issues, it'd be good if we considered adding compatibility with OVH.

HelpScout tags: `ovh` `export_settings` `mod_deflate`

**Comment by GeekPress** [comment]
@vmanthos Do we know exactly on which kind of OVH hosting do we have here problem? Is it only on shared hosting? If so, is it on all plans?

@vmanthos  @Tabrisrp Do we have a way to know at 100% we are on an OVH hosting?

**Comment by vmanthos** [comment]
> Do we know exactly on which kind of OVH hosting do we have here problem?

I'm not sure.

I've asked one of the customers experiencing this to tell me. I'll update the thread when I hear back from them.

If I had to guess, that would be shared hosting. This is because "export settings" is working fine on our MEGA.

> Do we have a way to know at 100% we are on an OVH hosting?

There aren't any host-specific headers, as far as I can tell.

We can reach out to them, and ask if there is any other way to detect this.

**Comment by piotrbak** [comment]
In general we have 5 tickets related to this issue during 5 years. It's not enough for it to be implemented. Feel free to reopen it if needed.
