### ISSUE TITLE
Can't import settings on clean WordPress Multisite site

### ISSUE THREAD

**Issue by codetipi** [wp-media/wp-rocket#1765]
Describe the bug:
Can't import settings file on a WordPress Multisite site. Exporting a settings file using the latest WP Rocket (3.3.4) and then trying to import that same file on another site in the same multisite installation gives the following error:

`Settings import failed: incorrect filetype.`

This error first appeared after WordPress 5.X was released and they seemingly changed some security checks.

To Reproduce

On a multisite, export settings of one site then go to import the file in a fresh other site within the same multisite installation.

Expected behavior
Import settings successfully.

**Comment by arunbasillal** [comment]
@Tabrisrp I could recreate this. 

`rocket_allow_json_mime_type` hooked onto `mime_types` is overridden by `check_upload_mimes` on `upload_mimes`. 

Previously we had https://github.com/wp-media/wp-rocket/issues/526 which was reverted because of https://github.com/wp-media/wp-rocket/commit/00560e0b55307a12de21c8e37b1fbbde6bc874cf#diff-fe26f00b0857bdb8dd1d33ff55fb5b08

**Manual fix:** 

For multisites, the network admin can allow `json` in Network Admin > Settings > Upload Settings > Upload file types - https://jmp.sh/tqcSrbk

Related ticket - https://secure.helpscout.net/conversation/876135649/111084/#thread-2465308997

**Comment by EdithAllison** [comment]
I'm having the same error on a site which used to be multisite and was converted to single site. So now I'm stuck. I can't allow .json and am unable to import.
