### ISSUE TITLE
Problem with big inline scripts

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#1784]
We had a couple of tickets when it's not possible to exclude inline script due to its size. 

The problem is related to the preg_match function which is not able to fetch the results:
https://github.com/wp-media/wp-rocket/blob/3fd199ed5dc05c080a691e747f0d8ef850e4e7e7/inc/classes/optimization/JS/class-combine.php#L169
https://github.com/wp-media/wp-rocket/blob/3fd199ed5dc05c080a691e747f0d8ef850e4e7e7/inc/classes/optimization/JS/class-combine.php#L218

Related tickets:
12500 lines of script
https://secure.helpscout.net/conversation/795241497/99280/
420kb of inline script
https://secure.helpscout.net/conversation/862292227/109234/
337kb of inline script
https://secure.helpscout.net/conversation/866721821/109884/

While sizes of inline scripts are for sure not correct, we should be able to handle them. Right now, no matter what, they're getting combined.

**Comment by webtrainingwheels** [comment]
Also: https://secure.helpscout.net/conversation/800981715/100157/

HS tags: `preg_match`, `inline js`

**Comment by camilamadronero** [comment]
This other ticket, here: https://secure.helpscout.net/conversation/909562231/116896?folderId=2675957.

**Comment by crystinutzaa** [comment]
The issue is related to preg_match from here:

https://github.com/wp-media/wp-rocket/blob/3fd199ed5dc05c080a691e747f0d8ef850e4e7e7/inc/classes/optimization/JS/class-combine.php#L218

This one fails with PREG_BACKTRACK_LIMIT_ERROR and it returns an empty string instead of the inline JS code.

I made a temp fix by skipping the JS code from minify if PREG_BACKTRACK_LIMIT_ERROR is in there, so the JS code will still be present and will not be minified even if is not in the excluded list.

However, I think we need to consider another solution to avoid this issue.

**Comment by vmanthos** [comment]
Another ticket:
https://secure.helpscout.net/conversation/923115893/118662?folderId=2135277
