### ISSUE TITLE
Disable associated print styles when disabling emoji

### ISSUE THREAD

**Issue by girlie** [wp-media/wp-rocket#1800]
Reference: https://developer.wordpress.org/reference/functions/print_emoji_styles/

Called twice in this file: 
https://github.com/WordPress/WordPress/blob/master/wp-includes/default-filters.php

We should do this:
```
remove_action( 'wp_print_styles', 'print_emoji_styles' );
remove_action( 'admin_print_styles', 'print_emoji_styles' );
```

Related: https://secure.helpscout.net/conversation/879739703/111724

**Comment by arunbasillal** [comment]
Related article - https://woorkup.com/disable-emojis-in-wordpress/
Related conversation - https://wp-media.slack.com/archives/C43T1AYMQ/p1560958149009500

As @vmanthos suggested in the conversation, I also think we should limit ourselves to `wp_print_styles` and leave the admin area alone.

**Comment by Tabrisrp** [comment]
the CSS from `print_emoji_styles()` is also controlling the styling of the WP smilies, which are the old school emojis using gif images. If we remove this styling, it might affect the display of some posts where those smilies are used.

That's why it was kept when we added the remove emojis feature.

**Comment by arunbasillal** [comment]
Thanks @Tabrisrp 
We could move this to a helper plugin instead then and provide that for customers requesting this :)
