### ISSUE TITLE
Conflict between Divi video module & Replace YouTube iframe with preview image option

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#1803]
When you enable Divi video module sub-option called **Overlay** and you set an **Overlay image** and that the **Replace YouTube iframe with preview image** option is enable, you can’t play the video anymore.

Ticket: https://secure.helpscout.net/conversation/882236070/112834?folderId=1213662

**Comment by WordPresseur** [comment]
**Describe the bug**
When you use the Divi video module and you set an Overlay image, if the Replace YouTube iframe with preview image option is enable, you can’t play the video anymore.

**To Reproduce**
Steps to reproduce the behavior:
1. Create a page with a **Divi video module** & add an **Overlay** image to it like here: https://share.getcloudapp.com/v1urQg4j
2. It works fine as you can see here https://share.getcloudapp.com/qGuox7B0
3. Activate the **Replace YouTube iframe with preview image** sub-option in Media tab.
4. Test the page, it doesn’t work anymore as you can see here https://share.getcloudapp.com/bLum5KLr

**Expected behavior**
I was expecting the video to load.

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
Reproduced on http://mega.wp-rocket.me/divi/iframe-ll-test/

**Find the root cause** ✅ 
This is happening because our replacement is removing the `iframe` element from the page, and the Divi JavaScript code is looking for it to launch the video.

**Scope a solution** ✅ 
Unfortunately, right now we don't have a way to make those compatible. The solution:

We can auto-disable the option when we detect the current theme is Divi to prevent the issue, it will make the iframe lazyloaded normally instead of using the replacement.

**Estimate the effort** ✅ 
Effort `[S]`
- Move our Divi compatibility file to the new architecture
- Add a callback method to disable the replacement option when Divi is the current theme
- Disable the checkbox on the settings page, with a message explaining why
- Write tests

**Comment by WordPresseur** [comment]
another case: https://secure.helpscout.net/conversation/1192067794/172127/

**Comment by kierantaylorio** [comment]
Related ticket: https://secure.helpscout.net/conversation/1230856807/181473/

**Comment by SimonThSorcerer** [comment]
Could you take another look at this, I'm using Divi on [my blog](https://simonsblogpark.com/onlinegambling/simons-casino-blog/) as well (along with WPRrocket and I really could use the speed boost. 2 years have passed (almost 3) perhaps a solution presented itself in the meantime (because it still does not work)? 

I love your plugin otherwise and I'm paid customer for years, but this should have been addressed a long time ago.

**Comment by ixns** [comment]
This needs to be looked into.. Also experiencing a similar issue!
