### ISSUE TITLE
Proposal: Compatibility with Instagram Feed plugin

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1807]
We have a couple of tickets related to an issue with Instagram Feed (800,000 active installs).

This message is displayed when a specific option isn't turned on:

"Cache Error: Looking for cache that doesn't exist. Now using a backup feed. 
This error is only visible to WordPress admins. 

If you are using a caching plugin, try enabling the option on the Customize tab 'Cache error API recheck' or 'Force cache to clear on interval' 

https://secure.helpscout.net/file/5de4805abf96951b/42565/2474407632/201102643/

Our users think the message is displayed by WP Rocket or open a ticket to know how to fix the issue (even if everything is explained into the message ^^).

We've just created an auto-reply workflow which is great for a first step.

We could go further WP Rocket compatible with Instagram Feed by forcing the  'Cache error API recheck' or 'Force cache to clear on interval' option to be on.

**Comment by arunbasillal** [comment]
Thought: Changing the setting in another plugin imo should be user initiated. We could show a notice with a button prompting the user to make these changes. But the notice displayed by Instagram Feed is on the front end. 

Even if we provide the easy button, this is a burden on us and we will have to track changes in Instagram feed in case something changes in the future. 

An alternate suggestion would be to reach out to Instagram Feed and inform them about this confusion and ask them to improve their notice so that users are not confused. This would be ideal imo.

**Comment by arunbasillal** [comment]
The auto reply setup in HS is taking care of this issue very well. Closing this issue for now as our current approach is working very well 👍
