### ISSUE TITLE
Automatically clear the cache when Gravity Forms is saved or updated

### ISSUE THREAD

**Issue by kierantaylorio** [wp-media/wp-rocket#1830]
When a form is updated in Gravity Forms the cache is not automatically cleared, therefore the changes are not reflected on the front end, and manual intervention from the user is required. Considering that this is a widely used plugin I believe it would make sense to add compatibility. 

Ticket: https://secure.helpscout.net/conversation/895060473/114514

**Comment by arunbasillal** [comment]
Gravity forms has `gform_after_save_form` action (Thanks @kieran-wpmedia) - https://docs.gravityforms.com/gform_after_save_form/

Realistically we only need to clear the cache for the posts with the form. But there is no straight forward way to find where all the shortcodes are used. The plugin GF Form Locator uses a string search for this - https://plugins.trac.wordpress.org/browser/gf-form-locator/trunk/classes/class-gravity-form-locator.php#L214

Since such detection is overkill for our purpose, maybe all we need to (or can do) is clear the entire WP Rocket cache when GF is saved.

**Comment by GeekPress** [comment]
I will be careful by automatically clearing the entire cache when a GF forms is updated / added. 

This behavior is expected by the user on the ticket, it doesn't mean that the majority of our users would like to have this.

**Comment by arunbasillal** [comment]
Had a discussion about this with Jonathan. Main takeaways 

- Most websites use GF's on few pages only. 
- Clearing the entire cache is overkill. 
- Not every customer would appreciate this. 

**Ideas:**

- Figure out an efficient way to find the posts / pages where GF is used
- Alternatively, show an admin notice reminding the customer that the cache needs to be cleared

**Comment by GeekPress** [comment]
@arunbasillal It's been a long time since the discussion :D 

We know we have thousands users using GF. As we didn't get more complaints about that, I'm wondering if we should just keep the actual behavior.

**Comment by arunbasillal** [comment]
@GeekPress You are right. I scanned our tickets and we do not have complaints. 

Let's close this one for now and re-open it in the future if needed. 

@kierantaylorio Please note. In the past we tried to have as many automatic integrations as possible. But over time maintenance is very difficult and expensive. So inconveniences that affect a minor subset of customers that have alternate solutions are best handled via documentation or helper plugins. In this case, it doesn't look like we have many customers facing the issue. Closing this one.
