### ISSUE TITLE
Proposal: Detect if DONOTCACHEPAGE is set on homepage and display a notice

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#1858]
Sometimes a plugin is using DONOTCACHEPAGE constant and WP Rocket can't cache the website.

Until to debug the website ourself by having FTP access, we can't know why the pages aren't cache.

If we can detect that DONOTCACHEPAGE is set on the homepage, we could display a notice to warn our user about that and to use our helper plugin to fix the issue.

**Comment by arunbasillal** [comment]
Having the tool in #1813 will help with self diagnosis during situations like this.

**Comment by Tabrisrp** [comment]
I'm thinking about this, and I have some issues with the notice:
- This requires the user to visit the admin to see it, which might not be the case
- This would be limited to a check for the homepage, but the constant can be set for other pages individually

How about as an alternative solution, we take inspiration from our helper plugin: https://github.com/wp-media/wp-rocket-helpers/tree/master/various/wp-rocket-debug-helper

We could only keep the part about the `DONOTCACHEPAGE` constant, and display a comment message in the HTML when the constant is set.
- This would be an easy way for our support to quickly see what's wrong, and it can be documented in our support pages to invite our users to check for that too
- It will check all pages individually, instead of only the homepage

**Comment by arunbasillal** [comment]
I am all in for the idea of adding comment in the footer. This makes things easier for everyone and more holistic. 

One suggestion I have is to prevent this if `WP_ROCKET_WHITE_LABEL_FOOTPRINT` is set to `true`. So if a customer complains about this comment, we can suggest them to set the constant to turn it off.

**Comment by GeekPress** [comment]
The idea to have a notification into the source code is a good one. For your support, it could be very helpful.

For our users, a notice will still be required. 
Why?

Most of them won't check the source code to know if WP Rocket is working properly.

I noticed many times on refunds that people complaint about no speed improvement after installing WP Rocket. Sometimes the reason was because another plugin added the DONOTCACHEPAGE. And our users have no idea about that and won't try to understand the why.

**Comment by piotrbak** [comment]
We didn't have any complains about this. We might revisit it together with the following one in the future:
https://github.com/wp-media/wp-rocket/issues/2598
