### ISSUE TITLE
Cache not clearing when post permalink (slug) changes

### ISSUE THREAD

**Issue by Dibbyo456** [wp-media/wp-rocket#1936]
we have a post with the slug: `this-is-a-random-post`
now if we change the post slug to: `this-is-updated-post`
then the cache files of `this-is-a-random-post` is not cleared. The directory along with html files exists on cache directory.

Expected behaviour: `this-is-a-random-post` cache directory should be cleared because it's now obsolete. 

**Why fix it?**
Because it's breaking wordpress inbuilt feature: 301 redirect from `old-slug` to `new-slug`.
when a user lands on the `old-slug`, wp-rocket shows the old cache files (because it exists),
if the cache file wasn't there, wordpress would have made a 301 redirect to new slug.

**Comment by Dibbyo456** [comment]
Although I made a patch to fix the issue.

````php
// Fires immediately before an existing post is updated in the database.
add_action( 'pre_post_update', function( $post_ID ) {
	rocket_clean_files( get_the_permalink( $post_ID ) );
});
````
Using `rocket_clean_files` instead because `rocket_clean_post` breaking preload feature.

**Comment by mark0x** [comment]
This patch causes the cache to be constantly cleared when using Mailchimp for WooCommerce plugin (v2.3). Suggest checking post_data['post_type'] for 'scheduled-action' and returning.

**Comment by arunbasillal** [comment]
@mark0x Thanks for the report. This is the plugin you are talking about right? - https://wordpress.org/plugins/mailchimp-for-woocommerce/

How can I recreate this issue? I checked the source code of the plugin, but I couldn't find anything that would fire the action `pre_post_update`. 

Looking forward to your feedback.

**Comment by mark0x** [comment]
@arunbasillal That's the plugin yes. 

I'm not entirely sure why it happens, I just know that I fixed the cache being constantly erased by checking for "scheduled-action" post type and exiting the function.

It looks like Mailchimp plugin internally uses "action-scheduler" which creates a lot of "scheduled-action" posts. These posts have a guid/permalink of the index of the website with a query string. get_post_field( 'post_name', $post_id ) returns nothing on these posts (not sure why) so rocket_clean_files gets called and since the get_the_permalink call returns the index of the site, it wipes the whole cache.

**Comment by arunbasillal** [comment]
Thanks again for the feedback. I will re-open the issue for now and do some testing to figure out what is happening.
