### ISSUE TITLE
Offer an easy way to turn on and off the cache

### ISSUE THREAD

**Issue by ctschach** [wp-media/wp-rocket#1937]
**Is your feature request related to a problem? Please describe.**
Sometimes things go wrong during the Minify optimisation or you need to debug and do some tweaks on the template code. This all doesn't work when the cache is running.

Okay, I know what you think now: By default the cache is off for logged-in users, but this loads extra WP resources. And this does not give you the same environment that a regular users has.

So if you want to turn off the caching at the moment the only way is to either disable the wp-rocket plugin or to remove the cache definition from the wp-config.php file.

**Describe the solution you'd like**
A simple checkbox under the WP-Rocket settings which would allow to turn on and off the cache completely. All it would need to do is turning off the caching and let Wordpress build the page instead of delivering the page from the cache.

**Describe alternatives you've considered**
Well...tweaking the wp-config.php would be one option, but not a smart one. 

**Additional context**
We have different type of developers. Some are code-monkeys editing everything in VI via the console, other are DreamWeaver users that think this is the best editor ever. If I should tell those DreamWeaver users that they should go into the wp-config.php and change a settings to turn off the cache they would look at me with question marks in their eyes. So they would probably end up deactivation the cache from the plugins instead.

**Comment by arunbasillal** [comment]
Hello @ctschach Thanks for your feedback. 

Having a disable button creates its own set of problems. Users will leave it disabled and contact support saying that the website isn't cached. 

We are are always trying to keep the UI as minimal as possible. Adding more buttons makes it look complicated. 

Disabling WP Rocket plugin temporarily is the way to go here for you. The effort from a developer perspective is not any more than disabling using a dedicated UI button. Also its easy to say if WP Rocket is disabled or not because the admin bar item will be gone. 

Cheers.
