### ISSUE TITLE
Lazy Load Breaks Zoho Campaign Forms

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#1976]
When using [Zoho Campaigns For WordPess](https://wordpress.org/plugins/zoho-campaigns/) the forms will load an image via JS.

The code looks like this (I truncated it as the actual full JS is quite lengthy this is the area though where the error occurs)
```
                                    contactxml += "</xml>";
                                    url += contactxml;
                                    jQuery('#background_div').css('display','block');
                                    jQuery('#response_div').css('display','block');
                                    jQuery('#response_div').css('z-index','999');
                                    jQuery('#headval').attr('align','center');
                                    jQuery('#bodyval').attr('align','center');
                                    jQuery('#headval').html('Loading...');
                                    jQuery('#bodyval').html("<img src='https://example.com/wp-content/plugins/zoho-campaigns/assets/images/uploadImg.gif' />");
```
          
(I removed the domain as this was found on a client website). 

The rewrite will go ahead and replace the <img src with the lazy load code. However due to the src attribute being rewritten as an encoded svg
"data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%200%200'%3E%3C/svg%3E"

This breaks the JavaScript causing the form to be unusable. 

The workaround was too simply exclude the image via a code snippet
what I excluded:  "/wp-content/plugins/zoho-campaigns/assets/images/uploadImg.gif" 

Then I simply cleared the cache.

**Comment by GeekPress** [comment]
Hi @ScottTravisHartley 🤚

Thanks for your contribution.

To help us working on this issue, it will be awesome if you can edit your initial post by respecting our template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. '...'
2. '....'
3. '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by piotrbak** [comment]
We didn't have enough feedback to move forward with this one.
