### ISSUE TITLE
CDN - Incorrect path rewriting for relative paths in a srcset attribute

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2041]
CDN feature doesn’t recognize relative paths and apply the CNAME twice on an empty domain in a srcset attribute and it results in broken URLs.

`/images/images.webp` is rewritten like this `https://cdn.cname.comhttps//cdn.cname.com/images/images.webp`

Ref: https://wp-media.slack.com/archives/C43T1AYMQ/p1571230717054300

**Comment by WordPresseur** [comment]
This bug reappeared: https://wp-media.slack.com/archives/C43T1AYMQ/p1611658067019100

`<img src="/wp-content/themes/test/img/test.png" loading="lazy" width="900" srcset="/wp-content/themes/test/img/test-2.png 500w, /wp-content/themes/test/img/test-2.png 800w" sizes="(max-width: 767px) 37vw, (max-width: 991px) 34vw, 37vw" alt="">`

**Comment by WordPresseur** [comment]
Ticket: https://secure.helpscout.net/conversation/1403856345/233510/

This is the line causing the error due to double replacing:
https://github.com/wp-media/wp-rocket/blob/b0606e2061b184c7d35169113a84ab6a99d5e73a/inc/Engine/CDN/CDN.php#L74

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue with the sample HTML provided

### Identify the root cause ✅ 
This is happening because the same URL is used for multiple sources in the `srcset`, and our current replacement using `str_replace()` is looping over each source, so the relative URL part is rewritten on each iteration.

### Scope a solution ✅ 
Instead of rewritting in the whole srcset for the matching URL, we can rewrite the source part, and then rewrite this source part in the whole srcset after.

New code:
```
foreach ( $sources as $source ) {
	$url                = preg_split( '#\s+#', trim( $source ) );
	$cdn_source = str_replace( $url[0], $this->rewrite_url( $url[0] ), $source );
	$cdn_srcset  = str_replace( $source, $cdn_source, $cdn_srcset );
}
```

### Estimate the effort ✅
Effort `[XS]`, update the code and add new test case

**Comment by vmanthos** [comment]
This is still an issue when the CDN's CNAME matches the hostname, for example, when the hostname/CNAME are:
* **hostname:** `example.com`
* **CNAME:** `cdn.example.com`

Code sample:
```HTML
<picture class="skip-lazy" data-skip-lazy="1"><source srcset="//example.com/wp-content/uploads/2021/08/T_1_front.webp" type="image/webp" media="(max-width: 425px)" class="skip-lazy" data-skip-lazy="1">
<source srcset="//example.com/wp-content/uploads/2021/08/T_1_front2.webp" type="image/webp" class="skip-lazy" data-skip-lazy="1">
<img id="n2-ss-2item1" alt="Image is not available" class="skip-lazy" width="720" height="440" data-skip-lazy="1" src="//example.com/wp-content/uploads/2021/08/T_1_front.jpg">
</picture>
```

In the `$html` here:
https://github.com/wp-media/wp-rocket/blob/290c89ed141b814641bae71b5238b46498c1f4e8/inc/Engine/CDN/CDN.php#L63

the `srcset` URLs are already rewritten to point to the CDN.  

So, `//cdn.example.com/wp-content/uploads/2021/08/T_1_front.webp` is passed to the `rewrite_url()`:
https://github.com/wp-media/wp-rocket/blob/290c89ed141b814641bae71b5238b46498c1f4e8/inc/Engine/CDN/CDN.php#L74

Because of the lack of a scheme `rewrite_url()` returns here:
https://github.com/wp-media/wp-rocket/blob/290c89ed141b814641bae71b5238b46498c1f4e8/inc/Engine/CDN/CDN.php#L118

and the URL that's returned is:
```HTML
//cdn.cdn.visionclimax.com/wp-content/uploads/2021/08/T_1_front.webp
```
Note the double `cdn` at the beginning, which results in a non-valid URL.

**Ticket:** https://secure.helpscout.net/conversation/1715624027/312369?folderId=2135277

**Comment by piotrbak** [comment]
We didn't have enough feedback to move forward with this one.
