### ISSUE TITLE
Pages excluded from cache - slug change

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#2055]
**Before submitting an issue please check that you’ve completed the following steps:**
Everything up to date

**Describe the bug**
Assume that a page is set to be excluded from caching by enabling the box "Never cache" into the WP Rocket setting within the page. Once saved, if the user changes the slug of the link and save again, WP Rocket will only add the new slug and not remove the previous one => causes pollution on WP Rocket settings.

**To Reproduce**
1) Create a page and publish
2) Assign the page as "never cache" and update
3) Change slug of the page and update
4) Go in admin WP Rocket "exclude page" setting

**Expected behavior**
Only the new slug should remain and old one should be deleted.

**Screenshots**
N/A

**Additional context**
N/A

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
I was able to reproduce this issue on my localhost.

**Identify the root cause** ✅ 
The issue is in here: https://github.com/wp-media/wp-rocket/blob/fbb9380bcb79bc617ad5bfa27c513da1c44a5b78/inc/admin/ui/meta-boxes.php#L115
When the slug changes, the info is not cleaned in `cache_reject_uri` , so the old slug and the new slug are both available.

**Scope a solution**  ✅
A solution would be that on slug change, when the old & new slug are different to simply remove the old slug. We should need to use the hook: `pre_post_update` to check if the slug has changed.


**Estimate the effort** ✅ 

`Effort: [S]`

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future. We might reopen this in the future.
