### ISSUE TITLE
Duplicate ID caused by Optimize CSS Delivery option

### ISSUE THREAD

**Issue by Tobias-Keller** [wp-media/wp-rocket#2059]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✓
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
Have developed a theme for a client and checked my theme with w3 validator. There are some Errors caused by a duplicate id for all Stylesheet and JavaScript Files.
Its came from the noscript at the bottom of the page, where i think you pushed it.

And the other warnings is coused by type attributes on css/js files. 
So there are unnecessary, maybe you can delete them.

**To Reproduce**
1. Activate minimize files
2. logout
3. check page with w3 validator https://validator.w3.org

**Expected behavior**
No w3c errors caused by wp-rocket? xD

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39527519/67238935-51e37b80-f44e-11e9-82b6-570614640a81.png)

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
This is in fact caused by the optimize CSS delivery option, creating `noscript` tags containing the original CSS markup in case of JS being disabled.

We could remove the `id` attribute from them to prevent the validator error, but since it has no impact on the actual behaviour of the website, this won't be a priority to fix.

**Comment by Kipperlenny** [comment]
Same problem here - many SEO Tools are mentioning this as well (because W3C does) - so my customer is complaining and wants to switch to a different cache tool. I know it's inside the noscript, but f.e. ryte (a seo tool) shows this as RED, VERY IMPORTANT error to the clients...

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
I was able to reproduce this issue

**Identify the root cause** ✅ 
The CSS tags we add inside `<noscript>` tags at the end of the HTML are preserving the `id` attribute, creating duplicate for HTML validation analyzers.

**Scope a solution**  ✅ 
We can remove the `id` attribute from those tags to prevent the issue

Estimate the effort ✅ 
Effort [S]: easy to reproduce, develop and test
