### ISSUE TITLE
WP Rocket Options meta boxes doesn't stay checked when saving a Draft

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#2088]
None of our checkboxes from the **WP Rocket Options** meta box, at the post edit view, stays enabled when you save a post with a **draft** status.

In comparison, if you select a WordPress category and save a draft, the category is saved.

Recording 1
http://recordit.co/pwCXDaAe8S

Recording 2
https://jmp.sh/9arYe5n

Philosophical Slack convo: 
https://wp-media.slack.com/archives/C08N8J6VC/p1572473682026000

**Comment by Tabrisrp** [comment]
That's the expected behaviour with the current code:
https://github.com/wp-media/wp-rocket/blob/281eb493f44e873a9685f379cec701e8ebcf3532/inc/admin/ui/meta-boxes.php#L121

Do we want to exclude a page from cache when it's not even published yet, so not accessible to the public?

Should the metabox not be displaying until the post is published, which will be related to issue #522?

**Comment by GeekPress** [comment]
@arunbasillal What are your thoughts about that?

**Comment by GeekPress** [comment]
@alfonso100 Did you create the issue after a user complaint about that? If not, and if we don't have any customers asking use to change this behavior, do we have to go further? :D

**Comment by alfonso100** [comment]
@GeekPress Yes, I only had one ticket asking about this and confirmed it on my end. But I never had another request.
this was the ticket: https://secure.helpscout.net/conversation/993440556/129117/

**Comment by GeekPress** [comment]
@alfonso100 Thanks for the feedback.

As we have only one complaint about that, let's close it for now. We will monitor if we have other people asking for an improvement. Then we will re-open the issue.
