### ISSUE TITLE
JS Errors With: WooCommerce PayPal Powered by Braintree Payment Gateway

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#2094]
When using the WooCommerce PayPal Powered by Braintree Payment Gateway there are JavaScript errors that are generated on a single product page on the website. 

Uncaught ReferenceError: WC_Braintree_PayPal_Product_Button_Handler is not defined

There was a similar issue reported on the wordpress.org support forums regarding the plugin's compatibility with autoptimize. 

https://wordpress.org/support/topic/after-update-pictures-dont-shown-in-page-products/

The files will need to be ignored otherwise the product page will be busted images don't load you can't add to cart, etc.

**Comment by GeekPress** [comment]
Hi @ScottTravisHartley 🤚

Thanks for your contribution.

To help us working on this issue, it will be awesome if you can edit your initial post by respecting our template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. '...'
2. '....'
3. '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by piotrbak** [comment]
@ScottTravisHartley For more than 2 years noone contacted us with this issue. If you're still experiencing it, please open a support ticket and we'll investigate this.
