### ISSUE TITLE
Disable cache clearing when a term is not public

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2170]
Currently, when a term is created/edited/deleted we clear the whole cache:
https://github.com/wp-media/wp-rocket/blob/7723e789d158d2bf00ee5da49ef9158061e158eb/inc/common/purge.php#L14-L16

There are cases, e.g. Yoast Premium, where a taxonomy is registered having `'public' => false`. In this case, it's not necessary to clear the cache.

This can be an issue on sites where terms are constantly created/changed.

**Steps to reproduce the issue**
1. Register a non-public taxonomy: http://snippi.com/raw/iqs1jwq
2. Check `/wp-content/cache/` and make sure there is cached content.
3. Create a post and add a term to the taxonomy created👆.
4. Publish the post.
5. The cache from step 2 will be cleared.

**Proposed solution:**

Check if a term is `public` before clearing the cache with `rocket_clean_domain()`.

**Related ticket:**
https://secure.helpscout.net/conversation/1027543602/135931/

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
Issue reproduced on local test

**Identify the root cause** ✅ 
Vasilis has done a good job identifying the root cause already 👍 

**Scope a solution** ✅ 
- Remove the 3 identified `add_action` related to terms from  `purge.php`
- Create a new method in `PurgeActionsSubscriber.php` to handle terms deletion
- In this method, check the term is public, and if yes, clean the domain with `rocket_clean_domain`
- Add automated tests

**Effort** ✅ 
`[S]` not a lot of complexity, most of the time will be spent on automated tests
