### ISSUE TITLE
Flush all cache on plugin deactivation

### ISSUE THREAD

**Issue by Dibbyo456** [wp-media/wp-rocket#2210]
Upon plugin deactivation (_not delete_), the cache files does not delete, which causes trouble when using [Rocket-Nginx](https://github.com/SatelliteWP/rocket-nginx), because of the cached pages exists Nginx serves those caches.

**Comment by arunbasillal** [comment]
Thoughts: 

- Wondering if we can be smart about this and detect the presence of Rocket-Nginx config. Can't think of a way. 
- At the very least, we only have to do this (if we decide to do this that is), on Nginx servers.

**Comment by Dibbyo456** [comment]
> Can't think of a way.

Nor can I.

> At the very least, we only have to do this (if we decide to do this that is), on Nginx servers.

Yeah, that would work I guess.

**Comment by trendymail** [comment]
Hi!

Having exactly the same problem with Varnish (even after tweaking VCL).

When WP Rocket is disabled, cached files are still present in wp-content/cache folder and Varnish cannot know if these files are "fresh" or not.

Upon deactivation, WP Rocket should do two things (if possible):
1) clear all caches
2) remove its configuration from .htaccess (because the rewrite rule should no longer send stall files)

Have a nice day!

**Comment by arunbasillal** [comment]
@trendymail Removing the rewrite rules from .htaccess is something that is already being done. You can see the related code here - https://github.com/wp-media/wp-rocket/blob/4b8b155c0a3c5543f70867a4b26725e1dbd8457e/inc/main.php#L135-L136

If this isn't happening, then it's something else. Maybe a permission issue. Please contact support so that we can take a look - https://wp-rocket.me/support/

Thanks for the other idea :)

**Comment by trendymail** [comment]
Many, many thanks for your quick answer!

Found the "culprit": WP-CLI (https://wp-cli.org)
(it works perfectly when using Wordpress Admin panel)

a) sudo -u <website_user> wp-cli plugin deactivate wp-rocket

Does not remove WP Rocket rules from .htaccess 

a) sudo -u <website_user> wp-cli plugin activate wp-rocket

Does not add WP Rocket rules to .htaccess 

No errors in PHP log file so it looks like some hooks are not called.

Any hint to debug this case? ^^

**Comment by alfonso100** [comment]
A very similar request https://secure.helpscout.net/conversation/1094075960/148114?folderId=2683093

**Comment by trendymail** [comment]
Sorry, I have no access and can't login into helpsout.net.

I will double-check the documentation of WP-CLI to be sure I have not forgot an option.

Have a nice day!

**Comment by trendymail** [comment]
Maybe it would/can help:

"Why does not WP-CLI execute 'register_activation_hook' when activating the plugin?"

https://github.com/wp-cli/wp-cli/issues?utf8=%E2%9C%93&q=register_activation_hook

WP CLI related: it seems that register_[de]activation_hook functions are not called.

So it would explain why WP Rocket does not delete cache/rewrite .htaccess upon deactivation.

**Comment by GeekPress** [comment]
I'ms closing this one, we have a fresh discussion on #2500
