### ISSUE TITLE
Fixing false positives on CRON status detection

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2211]
This is a copy paste from here for better issue tracking and organisation - https://github.com/wp-media/wp-rocket/issues/1472#issuecomment-527544891

**With the 3.3.7 update, here is what we did:** 

- An admin notice is displayed if a scheduled event missed it's schedule time. 
- This will accommodate for WordPress installations that use server cron as well. 
- The notice displayed on WP Rocket dashboard can be dismissed and will not come back once dismissed. 
- This is basically what WordPress health check tool uses as well

**False positives**

At the time of writing, we have 9 false positives reported where customers saw this notice even when cron was working correctly. This could be because of an edge case. 

- Say an event is scheduled for 15:02
- Server cron is set to run every 5 minutes.
- It runs at 15:00
- Customer visits the dashboard at 15:03 and the notice will be displayed because the even scheduled for 15:02 is missed and will only be done at 15:05 when the server cron runs again. 

**Next Steps**

We will continue to monitor tickets about this and make a decision about whether to make changes in a future update.

**Steps to Replicate:** 

This is a tricky one to replicate. After multiple attempts, here is what worked: 

- Add `define('DISABLE_WP_CRON', 'true');` to `wp-config.php`
- Set a schedule for database optimization and save settings (by clicking `Optimize`). 
- The notice should show up immediately - https://jmp.sh/dWafjWY
- Here is proof of the issue being replicated - https://youtu.be/qqyzUJsRO4o

Now in my case, server CRON was not setup. But the notice doesn't wait for a ping from server cron to show up. 

**Related conversations:**

- https://wp-media.slack.com/archives/C08N8J6VC/p1567075962002300

**Proposed Idea:** 

- It looks like in the current approach, WP Rocket looks for a missed schedule. 
- If the theory in the section titled "False Positives" (above) is possible, then our current approach will obviously fail. 
- What if we add a buffer? (say 60 minutes) before determining if a schedule is missed or not?

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅
Issue reproduced on local test site

**Identify the root cause** ✅
In our current check, we compare the scheduled event timestamp with the current time, so there is no margin of error for cases where someone goes on WP Rocket settings page in the small window between the event time and the next cron trigger.

**Scope a solution** ✅
In WordPress site health tool, they have defined a 5 minutes window for missed event, and even a 60 minutes window if `DISABLE_WP_CRON` is enabled.

We could follow the same pattern to prevent the false positive encountered.

**Estimate the effort** ✅
effort: `[S]`, requires writing automated tests for `rocket_warning_cron()` function
