### ISSUE TITLE
Update AMP compatibility with ?amp

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2216]
The official AMP plugin is now using `?amp` as the default for URLs instead of  `/amp/`

ref: https://wordpress.org/support/topic/change-amp-to-amp-and-amp-home-page-not-working/#post-11636178

This means WP Rocket won't cache amp pages at all.

**Steps to reproduce**

1. Install AMP plugin - https://wordpress.org/plugins/amp/
2. Go to Amp > General
3. Choose Transitional template mode
4. Now for each page on your site the AMP equivalent is available at example.com/?amp - this isn't cached

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by webtrainingwheels** [comment]
*To reproduce*
1. Install AMP plugin - https://wordpress.org/plugins/amp/
2. Go to Amp > General
3. Choose Transitional template mode
4. Now for each page on your site the AMP equivalent is available at example.com/?amp - this isn't cached

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Issue reproduced on local testing. AMP version in transitional mode is not cached.

To note, AMP version on standard and reader modes is cached.

**Identify the root cause** ✅ 
Transitional mode uses the `?amp` query string, which is not cached by default by WP Rocket.

**Scope a solution** ✅ 
We can update our AMP compatibility code to add the `amp` query string to the `cached query strings` automatically, when transitional mode is enabled:
- callbacks on AMP plugin activation/deactivation
- callback on AMP plugin option change

It can be a good opportunity to move the compatibiliy code to OOP at the same time.

**Estimate the effort** ✅ 
`Effort: [S]`

Most of the effort will be spent on writing automated tests.

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

- Install [AMP plugin](https://wordpress.org/plugins/amp/). 
- Go to Amp (Main Menu Option) > General > Choose Transitional template mode.
- Visit `domain.com/post-title/?amp`
- Check if the page is cached and the cache file is generated.
- Switch to "Reader" mode in AMP settings.
- Visit `domain.com/post-title/?amp` and `domain.com/post-title/amp/`. 
- Make sure both caches are generated as expected.

**What If**

No edge cases came to mind.
