### ISSUE TITLE
Multiple "Settings Saved" Notice for Import Settings

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2240]
This is extremely trivial, but documenting this as part of perfecting WP Rocket. 

WP Rocket generates two noticed when settings are imported in `Tools` > `Import Settings` > `Upload file and Import Settings`

<img width="602" alt="settings saved" src="https://user-images.githubusercontent.com/5751474/72022771-46f2f700-3297-11ea-888b-271ed0b31a1c.png">

**Steps to Reproduce:** 

- Go to Tools tab of WP Rocket and export WP Rocket settings
- Import settings and click `Upload file and import settings`
- The multiple notices will appear

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Reproduced on my local test site

**Identify the root cause** ✅ 
The issue is in here:
https://github.com/wp-media/wp-rocket/blob/fbb9380bcb79bc617ad5bfa27c513da1c44a5b78/inc/functions/admin.php#L449-L457
`add_settings_error( 'general', 'settings_updated', $message, $status );` is generating a new error meesage.


**Scope a solution** ✅ 
The solution will be to remove totally `add_settings_error( 'general', 'settings_updated', $message, $status );` and add the message in the `settings_errors` transient. 

**Estimate the effort** ✅ 

`Effort: [S]`

The code change itself is very low effort, however at integration tests I am not 100% sure. 
@hellofromtonya can you please check the integration tests?

**Comment by hellofromtonya** [comment]
@crystinutzaa Glad to help. For this one, we already have a model we can use in RocketCDN. 

It'll take a change to the last line:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/subscriber/CDN/RocketCDN/AdminPageSubscriber.php#L208

Here's the integration test we can use a model:
https://github.com/wp-media/wp-rocket/blob/master/tests/Integration/inc/classes/subscriber/CDN/RocketCDN/AdminPageSubscriber/purgeCdnCache.php

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

- Go to `WP Rocket` > `Tools` > `Download Settings`
- Import the settings that was downloaded. 
- Only the `Settings Imported and Saved` notice should appear. 
- Import settings without selecting a file. Error notice should say, `Settings import failed: no file uploaded.`
- Edit the downloaded settings (`.json` file) and remove few settings, then import it. The error notice should say `Settings import failed: unexpected file content.`
- Try importing a random file, the error notice should say `Settings import failed: incorrect filename.`

**What if**

I think all the edge cases were considered as part of the AC

**Comment by piotrbak** [comment]
It will not be implemented anywhere soon
