### ISSUE TITLE
The "display" parameter isn't added when there is just one Google Font

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2241]
When there are more than one Google Fonts on a page, WP Rocket will add the `&display` parameter:
https://github.com/wp-media/wp-rocket/blob/dfb5e1cf4fe9486b528d6ca9eaf33605acc7bceb/inc/classes/optimization/CSS/class-combine-google-fonts.php#L153-L165

However, if there is just one this parameter is not added. The processing stops here:
https://github.com/wp-media/wp-rocket/blob/dfb5e1cf4fe9486b528d6ca9eaf33605acc7bceb/inc/classes/optimization/CSS/class-combine-google-fonts.php#L93

Although this is not a big issue, since the code is there, we should add the parameter.
Changing the previous to this will work:
```PHP
		if ( count( $matches ) == 0 ) {
```
**Steps to reproduce:**

1. Add one Google Font on a page.
2. Enable the **Combine Google Fonts** feature.
3. The `display` parameter isn't appended to the URL that WP Rocket "produces".

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by arunbasillal** [comment]
@Tabrisrp Any idea why this is tagged as an enhancement? Was it part of the original design not to add this parameter for single fonts? Can't think of a reason why. 🤔

**Comment by webtrainingwheels** [comment]
To be a bit pedantic, the option is called "**Combine** Google Fonts" so it makes logical sense that if there isn't anything to combine (i.e there isn't more than 1 font), nothing is going to be done. I would propose that we should rename the option "**Optimize** Google Fonts" then it will make sense to process a single font and it takes into account the fact that we're doing more than just combining.

**Comment by vmanthos** [comment]
There is confusion about this among some of our customers who think that we combine Google Fonts. There is no way for us to either combine or optimize the actual fonts. We optimize Google fonts' requests. 

On top of what @webtrainingwheels suggested, I'd propose we call it "Optimize Google Fonts' requests".

**Comment by Tabrisrp** [comment]
This will need product team input before going further, because we are looking at changing the meaning of what this option does.

Currently, it's combining Google fonts if there is more than one on the page, to reduce HTTP requests.

Working on this would be transforming this issue from that, to an optimize google fonts, where we would make sure the `display` parameter is set if there is only one font.

So it requires an option name change, and an option description change if we go through.

What do we want to do? Combine only, or optimize?

I also don't agree with the `bug` label on this, as this issue was never part of the feature design.

**Comment by arunbasillal** [comment]
@Tabrisrp We definitely want to optimize even if there is only one single Google font. 

During grooming, please assume that there will be an `option name change` and `option description change`. We can make the final decision after a discussion with the team.

**Comment by Tabrisrp** [comment]
Ok, let's go with this assumption for now. Follow-up question: what if there is one google fonts, and it's using a different `display` value than `swap`? Do we preserve the existing value, or do we force the `swap` value?

**Comment by GeekPress** [comment]
@Tabrisrp I replaced the type label to `enhancement`. You're right on the fact it's a case we decided to not handle. And then, it was a normal behavior and not a bug.

> Do we preserve the existing value, or do we force the swap value?

Let's force the value to `swap`. It's the best for performance. We could still adjust later if we have complaints.

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Reproduced on local site

**Identify the root cause** ✅ 
Vasilis did a great job alredy at highlighting what was causing this 👍 

We currently stop the process if there is zero or one Google font on the page

**Scope a solution** ✅ 
There is multiple steps to achieve this:
- Stop the process only if there is no Google fonts on the page
- Add a new condition for the case when there is only one. We don't want to go through the whole parsing and rewriting in this case, we only want to add the display parameter to it. Faster code
- Create a new method to check if the display parameter is already present in the URL
- If no, add it with the `swap` value by default, filtered with the exisiting filter `rocket_combined_google_fonts_display`
- If yes, check its value. If it's not `swap`,  force the value, still using the filter above

**Estimate the effort** ✅ 
S task, we already have some unit & integration tests in place here, we will have to write additional ones for the one Google font case

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

Case 1: 
- Input: A page with just one Google font. No display parameter set. 
- Output. Display parameter of `swap` added to the single Google font. 

Case 2: 
- Input: A page with just one Google font. Display parameter set to `swap`
- Output: Output same as input. 

Case 3: 
- Input: A page with just one Google font. Display parameter sent to something other than `swap` (let's say `block`)
- Output: Display parameter changed to `swap`. 
- We should be able to filter it with `rocket_combined_google_fonts_display`

Case 4:
- Input: Multiple Google fonts present on a page. 
- Output: Fonts combined and display parameter sent to `swap` as we do with WP Rocket 3.5.0.x

**What if**

- What if `display` parameter exists, but it's empty (&display=). This must be invalid syntax. 
^ We can process it just like when `display` parameter exists.

**Comment by arunbasillal** [comment]
Related discussion for UI change: https://wp-media.slack.com/archives/CFSCRLVGB/p1583496051012400
