### ISSUE TITLE
Issues with Ti WooCommerce Wishlist

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#2244]
**Describe the bug**
There is an issue with TI WooCommerce Wishlist. TI Wishlist adds a tinv_wishlistkey and since then, the caching/minification etc stops working

**To Reproduce**
1. Install TI WooCommerce Wishlist
2. Add ti_wishlist_products_counter on header
3. If cookie is in your browser, wp rocket won't work. If you remove cookie, everything works as should.
Also, open the website in incognito mode. Caching will work. Login and then logout as user (login as user will create the wishlist cookie). Cookie is not destroyed so caching stops working on guest.

That also cause issues on preload (I think)

**Comment by arunbasillal** [comment]
Hello @seldimi 

Thanks for creating this issue. I believe you were in touch with my colleague Violeta regarding the same. 

This is by design on the end of `TI WooCommerce Wishlist`. Since the Wishlist is unique to a user, it makes sense to disable caching once the wishlist is created. 

A little better approach would be to set the cookie `tinv_wishlistkey` as a dynamic cookie. This will create a unique cache for each user (even logged out ones). Not sure if this is the right approach (because I don't know the ins and outs of Ti WooCommerce Wishlist). However, this is something that you / we can contact their team about. 

To set dynamic cookie we have this helper plugin for reference: https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-dynamic-cookie

Related ticket (for internal reference): https://secure.helpscout.net/conversation/1049518828/139767/

**Comment by seldimi** [comment]
Unfortunately, it didn't work. I've tried it

**Comment by arunbasillal** [comment]
Can you please share the code you have used? To confirm that it is right. 

When you check the cache folder in `wp-content/cache/wp-rocket/YOUR-DOMAIN.com/ANY-FOLDER` do you see pages created with index-XXXXX.html (XXXXX will be some random numbers or characters).

**Comment by seldimi** [comment]
The line I have used is the one below
`define( 'WPROCKETHELPERS_CACHE_DYNAMIC_COOKIE', 'tinv_wishlistkey' );`

It still had my cache broken, unless I removed the cookie myself or via wp_logout as mentioned here
https://github.com/TemplateInvaders/ti-woocommerce-wishlist/issues/20#issuecomment-573815997

**Comment by arunbasillal** [comment]
If I am understanding it correctly, you added just that line to `wp-config.php`? That is not the right way to use the helper plugin. 

I have customized the helper plugin for your case. Please remove the line you added before ( https://github.com/wp-media/wp-rocket/issues/2244#issuecomment-574228760 ) and install and activate this helper plugin: 

[wp-rocket-cache-dynamic-cookie.zip](https://github.com/wp-media/wp-rocket/files/4059988/wp-rocket-cache-dynamic-cookie.zip)

**Comment by seldimi** [comment]
I'm also a web developer, I know how things work.. I have downloaded your zip, modified the line, uploaded to plugins and activated.. It didn't work.
I can provide stating so you can see it yourself in an email or something :)

**Comment by piotrbak** [comment]
Resolved on their end:
https://github.com/TemplateInvaders/ti-woocommerce-wishlist/issues/20
