### ISSUE TITLE
Clear Cache for Multisite Site Deactivate

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#2248]
**Describe the bug**
In MU, upon site **_Deactivate_** or **_Archive_** the site is still visible if the cache file is available.

**To Reproduce**
Steps to reproduce the behavior - in a MU network:
1. Click on **_Sites > Deactivate_**. 
![image](https://user-images.githubusercontent.com/23031592/72349275-36cd8400-36aa-11ea-9aae-fb29b932b4e1.png)
2. Visit the deactivated site.
3. If the cache file exists you'll see the site.
http://mega.wp-rocket.me/multisite/clone/
![image](https://user-images.githubusercontent.com/23031592/72349540-b52a2600-36aa-11ea-85c0-3da10e962282.png)
4. If the cache file doesn't exist you'll see the `This site is no longer available.` message.
http://mega.wp-rocket.me/multisite/clone2
![image](https://user-images.githubusercontent.com/23031592/72349515-a774a080-36aa-11ea-9c78-d14aafa92d24.png)

**Expected behavior**
A deactivated site should not be available but show the `This site is no longer available.` message.

**Additional context**
**Related ticket:** https://secure.helpscout.net/conversation/1051359845/140115?folderId=2675957.
**Slack thread:** https://wp-media.slack.com/archives/C08N8J6VC/p1578580855031400.
**Notes:** the WP Rocket config file is not cleared after MU site deactivation.

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
Reproduced on local

**Identify the root cause** ✅ 
We currently don't have any actions linked to the a site deactivation on multisite. So when a site is deactivated, the cache is not cleaned, neither is the corresponding config file.

**Scope a solution** ✅ 
There is an action hook available `deactivate_blog`, which we can use to trigger the following actions:
- Delete the cache for the site
- Delete the config file for the site

We can take this issue to start a dedicated Multisite module. The first step will be to have a Multisite class & a subscriber, with one callback to perform the 2 actions above on `deactivate_blog`.

**Estimate the effort** ✅ 
Effort `[S]`

- Create new classes and the method
- Write tests for it

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
