### ISSUE TITLE
Subdirectory CDN incompatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2278]
For example, GoDaddy is using the following CDN URL markup:
_https://secureservercdn.net/110.150.138.55/lpq.31c.myftpupload.com_

Having CDN URL with subdirectories doesn't seem to work with WP Rocket now. Get_file_path function returns empty string, for example here:
https://github.com/wp-media/wp-rocket/blob/4b8b155c0a3c5543f70867a4b26725e1dbd8457e/inc/classes/optimization/JS/class-combine.php#L207

The combined file gets created and added to the source, while original scripts are not removed though.

**Steps to reproduce:** 
- Please add CDN URL like `example.com/cdn` 
- Enable JavaScript combination
- The combined JS file will be rewritten correctly with `example.com/cdn`
- However, all the JS files will still remain - https://jmp.sh/cS4Y6av

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1055041314/140803?folderId=2135277

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Issue reproduced on local testing

**Identify the root cause** ✅ 
This issue has multiple factors going into play:
- This line is removing the `path` part of the CDN URL(s) added in the settings: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/classes/subscriber/CDN/CDNSubscriber.php#L145
- Fixing the above makes this conditional fail. It is checking the asset file `host` vs the known `hosts` values which include the CDN URL(s). So right now it won't correctly match: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/classes/optimization/class-abstract-optimization.php#L61
- The function `rocket_url_to_path()` needs to be updated too to keep things working: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/functions/formatting.php#L467

This means it impacts:
- Cache dynamic resources
- Remove Query Strings
- Minify/Combine CSS
- Minify/Combine JS

**Scope a solution** ✅ 
Solving the issue would mean at least fixing the 2 points above, and also making sure there is no side-effects.

- Fixing first point: don't use the `host` only, but both `host` and `path`
- Fixing second point: instead of using the file `host` only, check if the there is a match between the hosts list and the full URL of the file
- Fixing third point: same approach as second point

**Estimate the effort** ✅ 
At first it seemed like a small change to make, but with how many parts of the plugin this impacts, I believe it will be a lot of work to make sure everything works as expected in the different possible configurations.

Fixing the 3 points above is likely to take a small amount of time. But there will be a lot of tests to write because we have pretty much nothing around that currently, and we can't risk breaking anything.

I don't see this as something that can be broken down into smaller parts, because it's all linked, so I think it's a medium to big time bucket that will be needed here.

**Comment by hellofromtonya** [comment]
@Tabrisrp What do you think on the effort? `[M]` 3-5 days or `[L]` 6-10 days for release-ready? Let's talk through it.

This one is impacting multiple areas. How do we handle this?

- _Before changing the code_, ensure there are tests in place for each piece of code that will be impacted by these changes.

Why? This gives a safety net.

How? We have a baseline state where the original code works and passes its tests. Then we make the fix changes, our safety net kicks in to validate the changes did not break those tests. It should still work.

- Then make the changes.
- Add new tests to validate the original issue. Use the CDN URL markup @piotrbak shared as the test data for the new tests.

What do you think @Tabrisrp?

**Comment by Tabrisrp** [comment]
I agree on the path to take, build tests as safeguards to validate the current behaviour, and build upon it to make sure everything still works after changes + the new conditions work too.

I would lean to an `[L]` because I see a lot of conditions to take care of, which are impacting multiple areas. Also because writing tests isn't yet a fast process for us, so it's safer to allocate more time and do it right.

**Comment by hellofromtonya** [comment]
Thank you, @Tabrisrp. I updated the estimate, removed `needs: grooming`, added the effort label, and moved the issue in the project into the Groomed column. 

This issue is ready for development.

**Comment by arunbasillal** [comment]
**Acceptance criteria:** 

- Enable CDN with a CDN CNAME that looks like `domain.com/path`
- Enable JS Combination
- Combined JS file uses the CDN CNAME with the full CNAME
- Disable JS combination and have only JS minification. Check if the result is as expected. 
- Repeat the same for Minify CSS, Combine CSS, Remove Query Strings
- The functions work as expected with the CDN CNAME as entered by the customer. 
- Test with a CDN CNAME that has a trailing slash (`domain.com/path/`). The resulting URL shouldn't have double slashes. 
- For the case where the CDN CNAME has no path. i.e. Just `domain.com` as we have now, everything works as expected. 

**What if:** 

- Customer enters CDN URL with and with double trailing slash? 
^ Should we fix this during sanitation?
