### ISSUE TITLE
WebP: Cache recreated on every load, when there aren't any images on a page

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2280]
The cache is recreated on every page load when:
* The WebP feature is enabled
* There aren't any images at all, or any supported images on a page.
A background image added e.g. with Elementor, doesn't count as a supported image.

We check for images on a page here:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/subscriber/Media/class-webp-subscriber.php#L170-L171

If there aren't any, the comment about the existence or not of WebP is not added:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/subscriber/Media/class-webp-subscriber.php#L199-L222

That's being used to determine the creation of the `.no-webp` file:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/Buffer/class-cache.php#L284-L306

In this case, the file is not created which leads to the issue.

_Note: This issue isn't related to issues #2156 or #2158._

**Related ticket**
https://secure.helpscout.net/conversation/1059666026/141735/

**Steps to reproduce:**
1. Enable WP Rocket's WebP feature in the Media tab.
2. Create a page where there aren't any images at all.
3. Check the page's cache folder (/cache/wp-rocket) and note the file's timestamp
4. Visit the page in a browser and refresh it.
5. Check the timestamp again. It will change after every refresh of the page.

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1064614467/142703?folderId=377611

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1076423425/144882?folderId=377611
cache file was being recreated on every page load until the webp option was disabled. The site does not have any webp images.

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Reproduced the issue on local site

**Identify the root cause** ✅ 
Vasilis made a great work on identifying everything already 👍 

**Scope a solution** ✅ 
I believe the solution would be to add `$html .= '<!-- Rocket no webp -->';` in the first conditional to make sure it's always included and the `.no-webp` file is correctly created even if there is no images on the page.

I tested it quickly, and it seemed to be working well after doing that.

@Screenfeed Please double-check, to see if you agree with this solution or if there is a better way you see

**Estimate the effort** ✅ 
If we go with the above solution, it's a small time investment needed. Testing will be the most important part, to add new unit tests and add integration tests that are missing currently.

**Comment by hellofromtonya** [comment]
@Tabrisrp Please specify the t-shirt size (story points) estimate for us.

**Comment by Screenfeed** [comment]
@Tabrisrp Sorry, I spent an hour on this and I'm still unable to reproduce. Either folders and files keep the same timestamp for me :/

**Comment by arunbasillal** [comment]
**Acceptance criteria:**

- A page with no images. 
- WP Rocket's WebP is enabled. 
- Generate the cache. Normal cache is generated and the `.no-webp` file. 
- On a page with images, but no `.webp` images.
- Generate the cache. Normal cache is generated and the `.no-webp` file. 
- On a page with `.webp` images. 
- Generate the `index-webp.html` file on a webp supported browser. And `index.html` on a non-web browser like IE. 

**What if**

Couldn't think of any edge cases so far. This issue is an edge case in itself.
