### ISSUE TITLE
Append date and time to database optimization complete notice

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2285]
To follow on the style for #1867, we could add the timestamp for database optimization. Since the optimization process runs in the background, it makes sense to have the timestamp added alongside the notice. 

This was a feature request sent in and documented here: https://www.wrike.com/open.htm?id=403723617

This is the notice that needs a timestamp: 

![image](https://user-images.githubusercontent.com/5751474/76755676-46e90900-67aa-11ea-9078-edce6a8a9586.png)

**Steps to replicate the notice:** 

- WP Rocket > Database optimization
- Enable Automatic Cleanup and set a schedule - https://jmp.sh/F6aZ8VU
- Click Otimize
- You will see a `Database optimization is running` notice (this notice doesn't need a timestamp)
- Wait for a minute or two and refresh the page. `Database optimization process is complete` notice will appear with the details.

**Comment by Tabrisrp** [comment]
**Reproduce the issue** :white_check_mark:
I was able to reproduce this issue

**Identify the root cause** :white_check_mark:
There is no timestamp currently

**Scope a solution**  :white_check_mark:
We can do the same as we do for the preload, and set a transient when the process is complete in the `complete()` method, to display it along the rest in the notice.

`set_transient( 'rocket_database_optimization_complete_time', date_i18n( get_option( 'date_format' ) ) . ' @ ' . date_i18n( get_option( 'time_format' ) ) );`

This transient will need to be deleted in the `uninstall.php` file.

**Estimate the effort** :white_check_mark:
Effort [S]: easy to develop & test

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1217543215/178518?folderId=273766
