### ISSUE TITLE
Heartbeat Control: "minimalInterval" value incorrecly set to 120,000 seconds

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2293]
WP Rocket's heartbeat control feature sets the `minimalInterval` value to "120":
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/subscriber/class-heartbeat-subscriber.php#L86

That setting alters the frequency of autosave when creating and editing posts.

WordPress, when that value is lower than 600, multiplies it by 1,000:
https://github.com/WordPress/WordPress/blob/143c6a1de818d54beb27bb7870fae7fede03ab07/wp-includes/js/heartbeat.js#L158

This can cause issues with the autosaving of articles when front-end builders are used, e.g. Divi's.

**Related ticket:** 
https://secure.helpscout.net/conversation/1071099564/143874/

**To Reproduce**
1. Enable the **Heartbeat Control** feature.
2. Use Divi's front-end builder to create a page and add blocks.
3. Check the **heartbeat** value of the AJAX request.
4. It should be "120,000".
5. Disabling WP Rocket's heartbeat control sets that value to "60".

These videos should help:
* heartbeat "off": https://youtu.be/eYP8uUY1Cac
* heartbeat "on": https://youtu.be/2hy0WcIeSIk

**Comment by GeekPress** [comment]
@vmanthos Does the solution is to set our `minimalInterval ` value to `600`?

**Comment by GeekPress** [comment]
@vmanthos Does the solution is to set our `minimalInterval ` value to `600`?

**Comment by vmanthos** [comment]
When I was checking the ticket, changing the value to **601** fixed this.
This was based on trial and error. I'm not sure if this is the actual value to use.

For future reference, here is how to check for the issue:

* heartbeat off: https://youtu.be/eYP8uUY1Cac
* heartbeat on: https://youtu.be/2hy0WcIeSIk

**Comment by GeekPress** [comment]
@vmanthos Thanks the video ;)

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
I think @vmanthos made a great job with videos included. 

**Identify the root cause** ✅ 
This is the line: https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/subscriber/class-heartbeat-subscriber.php#L85-L86

It should be changed from 120 to 601 to prevent this multiplication to occur.

**Scope a solution** ✅ 
Change interval and minimalInterval to 601.

**Estimate the effort** ✅ 

`Effort: [S]`

The code change itself is very low effort, however the missing tests will increase the duration of this task

**Comment by remyperona** [comment]
Looking at the code of `heartbeat.js`, I think there is a bug in it when `minimalInterval` is used:
- If `minimalInterval` is set, and is between 0 and 120, it's multiplicated by 1000
- After that, if `minimalInterval` is superior to `mainInterval` (which is likely always the case with the multiplication), the new value of `mainInterval` is `minimalInterval`
- And then a bit further down, the value of `mainInterval` is multiplied by 1000 to convert to microseconds. But it was already the case when using `minimalInterval`, so the value ends up being incorrect 120 000 000 microseconds instead of the expected 120 000 ms

Setting the value to `601` is not a valid fix, because it just ends up falling back to `0`, and thus using the default value for the interval.

Created a ticket on the core trac: https://core.trac.wordpress.org/ticket/54825#ticket

**Comment by remyperona** [comment]
The fix on the core side has been added in WP 6.0, so this should be working correctly now. @vmanthos Could you do a test to confirm?

**Comment by vmanthos** [comment]
@Tabrisrp I checked this with **Heartbeat** set to **Reduced activity** and the value was `120`:

![](https://i.vgy.me/3OA7x4.jpg)

@piotrbak I'm guessing we can close this one.
