### ISSUE TITLE
CPCSS is not always automatically generated

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2302]
When the Optimize CSS Delivery option is enabled, if the critical CSS files do not already exist, they should be automatically generated. 

However we started noticing a lot of cases where the option was activated on the customer's site but not applied on the front end. In these cases, manually clicking the "regenerate critical css" link solved the problem. 

I was able to reproduce it on my own test site, but not on mega. 
https://jumpshare.com/v/wncsZaccHptWTEio6O6e

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by arunbasillal** [comment]
I have seen the same issue few times. Can't pin down to an exact reason. 

I tried this on Mega/Divi

- Enable CPCSS (Optimize CSS delivery). 
- CPCSS was not regenerated. But `/divi/wp-content/cache/critical-css/1` already had the CPCSS files from previous generation. 
- Deleted the CPCSS from `/divi/wp-content/cache/critical-css/1` manually
- Disable CPCSS, save settings. Then Enable CPCSS again. 
- This time CPCSS was regenerated. 

However, similar steps didn't work for Lucy - https://jumpshare.com/v/wncsZaccHptWTEio6O6e

**Comment by webtrainingwheels** [comment]
I think you have to have a fresh install of WP Rocket to recreate this. So:

- Delete WP Rocket
- Manually remove the existing CSS files from the server ([not done automatically](https://github.com/wp-media/wp-rocket/issues/2352) 
- Reinstall WP Rocket
- Activate Optimize CSS Delivery
- Check if CPCSS is generated

On an existing install, if you regenerate the critical css, then later you delete the files and turn off/on the option, then the regeneration happens automatically. At least that's what I can reproduce on the site where I have this issue.

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
I was able to reproduce this issue on my localhost.

**Scope a solution** ✅ 
The issue is that critical css is saved in the folder `/wp-content/cache/critical-css/1`, however on a first activation of Critical CSS this folder does not exist, so there will be an error and a return which will not allow to create the critical CSS. 
I trigged it down to these lines:
https://github.com/wp-media/wp-rocket/blob/a37e46f58259e38dbf895061536551763f8aace7/inc/classes/subscriber/Optimization/class-critical-css-subscriber.php#L132-L140

process_handler() function never runs because of the return on line 147. 

** Scope a solution**  ✅
The solution should be to check before if the folder structure exists otherwise create it and allow to run the process_handler() function.

**Estimate the effort** ✅ 
The effort for creating the directory before running it, should be minimal.
The major effort should be set in adding Unit and Integration tests which are totally missing on this part.

**Comment by hellofromtonya** [comment]
@crystinutzaa Please add the t-shirt size effort estimate. Then remove the `needs: grooming` label and add the `effort` size label. Thanks!

**Comment by arunbasillal** [comment]
**Acceptance Criteria:**

- New WP Rocket install
- Activate Optimize CSS delivery 
- CPCSS should be generated automatically. 

**What if**

- Customer deactivates Optimize CSS delivery 
- Manually deletes CPCSS from the folder
- Enables Optimize CSS delivery 

^ This should be a very edge case and since it's a manual action, we can expect our customers to use the `Regenerate CPCSS` button to generate the CPCSS. 
^ However, since many customers do not know if CPCSS is generated or not, they might end up with a website with no CPCSS. 
^ We "could" opt for a simple check where if the `wp-content/cache/critical-css/1` folder is empty, then regenerate the CPCSS automatically.
