### ISSUE TITLE
W3C Error: Attribute loading not allowed on element iframe at this point.

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2312]
According to W3 Validator using the "loading" attribute on iframes is apparently not allowed.  and throw this **"ERROR: Attribute loading not allowed on element iframe at this point"** 

This refer to the attribute we add to our iFrame Lazyload: <iframe **loading="lazy"** src="about:blank" width="1280" height="720" frameborder="0" allow="autoplay; …n data-rocket-lazyload="fitvidscompatible" data-lazy-src="https://player.vimeo.com/video/xxxxxxxxx">

**Comment by Tabrisrp** [comment]
The `loading` attribute is only added if using native lazyload.

Currently the official HTML spec supports the attribute only for images, not yet for iframes. I don't think the validator has been updated yet either, because the spec was validated yesterday.

In any case, this is not something we can fix. The attribute will be interpreted correctly by Chromium-based browsers, and ignored by the rest.
