### ISSUE TITLE
The Clear Cache button is missing on the Edit screen in Gutenberg

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#2320]
The Clear Cache button that was there on the post or page _Edit_ screen of the Classic Editor (placed in the Publish meta box) is not visible on Gutenberg. 

When switching to the Classic Editor the button is visible again.

**Related ticket:** https://secure.helpscout.net/conversation/1084451726/146328/

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
I was able to reproduce this issue

**Identify the root cause** ✅ 
The block editor is not backward compatible for this. It needs a different implementation to offer this UI aspect again.

**Scope a solution**  ✅ 
This require using React to add a new button element in the DocumentSettingPanel, using slotFill: https://developer.wordpress.org/block-editor/developers/slotfills/plugin-document-setting-panel/

The button would perform the same action as on the classic editor.

**Estimate the effort** ✅ 
I can't estimate this, none of our dev for the plugin have the required skills to do that currently

**Comment by Tabrisrp** [comment]
@gradam Can you have a look at this, and see if you can help estimate how much effort is needed?

**Comment by Tabrisrp** [comment]
After discussing with Jakub:
- One of the PHP developer will handle the PHP part: enqueue script on edit screen, etc
- Jakub will handle the React code needed to display the button

Combined effort [S]

**Comment by piotrbak** [comment]
It's not going to be implemented anywhere soon.
