### ISSUE TITLE
Cache Busting Exemption 

### ISSUE THREAD

**Issue by a3d0n** [wp-media/wp-rocket#2325]
**Is your feature request related to a problem? Please describe.**
The amount of caching material is causing a performance hit on our site.

**Describe the solution you'd like**
Keep specific kind of post longer from the cache busting, if a post related to this isn't update it isn't being refreshed unless manually called upong. 

**Additional context**
If something trigger the big cache bust, we encoure a big performance hit when the cached is being rebuilt. Our context would be to prevent **singles** from being busted from that cache since they don't change often and there is little in regards to nonce being used in those context. Unless they were manual updated they would still live in a cache. A longer cache for single page would save us an incredible amount of processing and possible/potential downtime.

**Comment by arunbasillal** [comment]
@a3d0n Our team is already working n something similar to this where WP Rocket will be more deterministic about when to clear the cache. The details are still in discussion, but an example would be pages without nonces can stay longer (as you suggested). 

Since this issue doesn't have anything specific that will be tied to a release, I am going to close this. Please know that we are aware of this issue and it's something we are working on 👍
