### ISSUE TITLE
Character ">" in the CPCSS Fallback Field is Replaced by its HTML Name "&gt;"

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#2333]
**Describe the bug**
The `>` symbol is being replaced by its HTML name, `&gt;` when `>` is used in the **Fallback critical CSS** field. 

**To Reproduce**
1. Use the Fallback critical CSS feature (disable automatic CPCSS generation, delete content in wp-content/cache/critical-css/1 folder, add the custom code in the field).
2. Add any CSS rule with the `<` character:
![image](https://user-images.githubusercontent.com/23031592/75040226-49489380-5488-11ea-8d33-76546869575d.png)
3. Save changes in WP Rocket.
4. See the error in the source code:
![image](https://user-images.githubusercontent.com/23031592/75040285-62e9db00-5488-11ea-94b2-5db853f07047.png)

**Expected behavior**
The  `<` character should not be replaced.

**Additional context**
Happens in the 3.4.4 version (latest) and has been tested in customer's site, my test site and the Mega/multisite site.
**Slack thread:** https://wp-media.slack.com/archives/C43T1AYMQ/p1582209375163400.
**Ticket:** https://secure.helpscout.net/conversation/1088000268/146959?folderId=2675957.

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
Reproduced on my local test site

**Identify the root cause** ✅ 
This is the line: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/classes/admin/settings/class-settings.php#L315

The use of `wp_kses()` is changin the character to it's HTML-encoded version on save to the database. This is causing the output to be incorrect once inserted in the HTML.

**Scope a solution** ✅ 
Like we did for the output issue in #1654, we can replace `wp_kses()` by `wp_strip_all_tags()` before saving.

**Estimate the effort** ✅ 
The code change itself is very low effort. The current state of the `sanitize_callback()` method though might make writing automatic tests for this change very complicated.

**Comment by Tabrisrp** [comment]
@hellofromtonya will need your input for the testing part of `sanitize_callback()`

**Comment by hellofromtonya** [comment]
@Tabrisrp No problem. I can help here. Effort size: [S] for the `sanitize_callback()` integration tests.

Please update the `Estimate the effort` with the effort size. Thanks.

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

- Enter `>` in the `Fallback critical CSS` text area and save settings
- The CPCSS produced in the front end should have `>` instead of `&gt;`

**What if:**

- Input contains malicious code? Will `wp_strip_all_tags` catch it?
