### ISSUE TITLE
Use jQuery from Google CDN

### ISSUE THREAD

**Issue by laurentdebricon** [wp-media/wp-rocket#2334]
you could advise in your documentation user to put :

in function.php 

```
add_action('init', 'use_jquery_from_google');

function use_jquery_from_google () {
	if (is_admin() || is_customize_preview()) {
		return;
	}

	wp_deregister_script('jquery');
	wp_register_script('jquery', "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js", null, null);
}
```

If a lot of wp-rocket user do that, we will all share the same jquery version, then SPEED !

**Comment by Tabrisrp** [comment]
This is not something we're ever gonna recommend, for the following reasons:
- It is highly discouraged to replace the core jQuery by an external one, because the core one includes specific changes back-ported from newer versions
- It can easily lead to an increase in support on our side because it can create incompatibilities
