### ISSUE TITLE
On plugin deletion, cleanup is incomplete

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2352]
When you delete WP Rocket from the plugins screen in WordPress, it should completely cleanup after itself. 
However, these 2 folders are not deleted: 
- `cache/wp-rocket` (the cache files are removed but the folder itself and the htaccess within it are not)
- `cache/critical-css` - folder and the css files remain after the plugin has been deleted

Additionally it seems some database entries are left. After deleting the plugin and then re-installing, I saw this notice:
![WP_Rocket_‹_WordPress_Tutorials_—_WordPress_-_Mozilla_Firefox](https://user-images.githubusercontent.com/1043076/75613214-fe5dfa00-5adf-11ea-8013-d104d17545e7.jpg)
I would not expect that to happen on a fresh install. 

How to reproduce: 

- Install WP Rocket
- Enable Optimize CSS Delivery
- Currently you'll likely have to click "regenerate cpcss" to create the CSS files
- Make sure some CSS files are created
- Delete WP Rocket from the plugins screen

I haven't done a more thorough test to see if other files are leftover (I think /min/ is correctly deleted), I just discovered these while testing the other CPCSS generation issue :)
I'm able to reproduce this on 2 of my own sites, on different servers.

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
**Reproduce the issue** ✅ 
Reproduced on my local test site for the `cache/critical-css` folder

**Identify the root cause** ✅ 
The `uninstall.php` file was not updated when some of the new features were added.

There is a number of transients, options, cron jobs that are not deleted on uninstall, so we need to fix that.

Here is the list of what is missing:

**Critical CSS**
- Removal of `cache/critical-css` folder
- Deletion of `rocket_critical_css_generation_process_running` transient
- Deletion of `rocket_critical_css_generation_process_complete` transient
- Deletion of `rocket_critical_css_generation_triggered` transient

**RocketCDN**
- Deletion of `rocketcdn_user_token` option
- Deletion of `rocketcdn_process` option
- Deletion of `rocketcdn_check_subscription_status_event` scheduled event
- Deletion of `rocketcdn_status` transient
- Deletion of `rocketcdn_pricing` transient
- Deletion of `rocketcdn_purge_cache_response` transient

**Cloudflare**
- Deletion of `rocket_cron_deactivate_cloudflare_devmode` scheduled event
- Deletion of `rocket_cloudflare_is_api_keys_valid` transient

**Preload**
- Deletion of `rocket_preload_triggered` transient
- Deletion of `rocket_preload_complete` transient
- Deletion of `rocket_preload_complete_time` transient
- Deletion of `rocket_preload_errors` transient

**Database optimization**
- Deletion of `rocket_database_optimization_process` transient
- Deletion of `rocket_database_optimization_process_complete` transient

**Generic**
- Deletion of `wp_rocket_customer_data` transient
- Deletion of `rocket_notice_missing_tags` transient
- Deletion of `rocket_clear_cache` transient
- Deletion of `rocket_check_key_errors` transient

**Scope a solution** ✅ 
Add `delete_option`, `delete_transient` and `wp_clear_schedule_hook` calls for all the missing options/transients/events deletions missing.

I also think we should rewrite the `rocket_uninstall_rrmdir()` function, to not use glob, and use the PHP Iterator classes instead, as it is more reliable. We use that in other places of the code already.

The function could be called once on the whole `cache` folder, instead of doing it individually for each items in this folder. It's an uninstall anyway, so we want to remove everything. 

**Estimate the effort** ✅ 
[S] task. One function to rewrite, and we'll have to add tests for everything in the file to make sure it works as expected

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

This is tricky. The following criteria was written in the expectation that once WP Rocket is uninstalled, there shouldn't be anything left behind. 

The following approach relies on comparing a database snapshot to see if everything was deleted correctly. 

- Create a new WordPress install. 
- Install WP Reset plugin - https://wordpress.org/plugins/wp-reset/
- Go to `Tools` > `WP Reset` > `Snapshot` and create a database snapshot. 
- Install WP Rocket. Enable all the options. Save settings. 
- Deactivate and delete WP Rocket 
- Go to WP Reset and from `Actions` of the previously made snapshot, choose `Compare snapshot to current data` - https://jmp.sh/DJYhY5M
- Check if WP Rocket related entries were deleted correctly. Some WordPress items like `recently_activated` will remain and that is okay. 

**What if**

This change shouldn't call for any edge cases.
