### ISSUE TITLE
Fatal Error: Call to undefined function wp_unslash() on 3.5

### ISSUE THREAD

**Issue by sliday** [wp-media/wp-rocket#2376]
Original edited by Remy.

**Describe the bug**
During 3.5 development, we updated all the files to pass the coding standards. This included the `process.php` file, which is deprecated but still present for backward compatibility.

The file is not supposed to be used on WP Rocket installations since 3.3, but some installations seems to not have updated the `advanced-cache.php` file correctly since (even though that was part of the upgrade routine). So in some cases, it's still used currently.

We skipped the part where `process.php` can't have WP core functions in it, since WP is not loaded yet when the file is executed. So some functions like `wp_unslash()` made their way into this file, causing the fatal error.

**To Reproduce**
- Have an installation with the old version of the `advanced-cache.php` file
- Update to 3.5
- The fatal error should occur

**Expected behavior**
There should be no fatal error there, and `advanced-cache.php` should be updated with the correct content.

**Additional context**
This impacts a limited pool of installations that are still using the old version of the `advanced-cache.php` file for whatever reason. But it still creates support tickets.

For the support team, the fix for now is to delete the `advanced-cache.php` file so that it can be recreated with the correct content.

**Comment by GeekPress** [comment]
Hi @sliday  🤚

Thanks for your contribution.

To help us working on this issue, it will be awesome if you can edit your initial post by respecting our template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

'...'
'....'
'....'
See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Issue reproduced on multiple customer websites

**Identify the root cause** ✅ 
Root cause is fully detailed in the original post

**Scope a solution** ✅ 
Solving the issue with the following:
- Remove any WP core functions from `process.php`
- Make sure the upgrade routine for `advanced-cache.php` is running on the next plugin update

**Estimate the effort** ✅ 
`effort: [XS]`

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

- WP Rocket install with old `advanced-cache.php` (that uses process.php)
- On update to `3.5.0.3`, the `advanced-cache.php` is re-written with new links and no references to `process.php`
- No fatal error on update

**What if**

- The write permissions to `advanced-cache.php` no longer exist? 
^ Best approach would be to be prepared for this and make sure that even if WP Rocket uses `process.php`, there won't be fatal error. 
^ We need to think about how much into the future we want to support `process.php`.
