### ISSUE TITLE
Conflict between WP Rocket mobile preload and wp_is_mobile()

### ISSUE THREAD

**Issue by seldimi** [wp-media/wp-rocket#2383]
**Describe the bug**
WP Rocket uses `iPhone` in its user agent for mobile preload requests, but `wp_is_mobile()` doesn't use this string in its detection, so `wp_is_mobile()` will serve desktop content to preloaded mobile pages.

**To Reproduce**
- Activate separate cache for mobile device
- Activate preloading
- Have a theme/plugin that uses `wp_is_mobile()`
- The preloaded mobile page will contain for desktop output instead of for mobile output

**Expected behavior**
Mobile preload should be compatible with `wp_is_mobile()` and preloaded mobile pages should have the appropriate content

**Comment by Tabrisrp** [comment]
Hi @seldimi  🤚

Thanks for your contribution.

To help us working on this issue, it will be awesome if you can edit your initial post by respecting our template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

'...'
'....'
'....'
See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by seldimi** [comment]
Thank you Tabrispr for editing my post. I was so desperate in the morning so I made a quick post here and tried to restore the website with the issue.
Really keen on finding solution as I was expecting 3.5 so long 😃

**Comment by hellofromtonya** [comment]
Hello @seldimi, Thank you for reporting this issue. Today, we released 3.5.0.2 which includes the fix in PR #2388.
