### ISSUE TITLE
Partial Preloading doesn't create a mobile file in 3.5

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2399]
When updating a post, partial preloading will update the cached file.

**Expected behavior**

In 3.5, I'd expect partial preloading would create cached files for both desktop and mobile when the following options are enabled:
1. **Preload**
2. **Separate cache for mobile devices**

**To Reproduce**
1. Make sure the previously mentioned options are enabled.
2. Update a post.
3. Check the post's folder in `/cache/wp-rocket/`.
4. Only the desktop version will be there.

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Screenfeed** [comment]
Reproduce the problem ✅
This is true for all processes that use partial preload.

Identify the root cause ✅
Partial preload hasn’t been included in "mobile preloading".

Scope a solution ✅
Add mobile URLs within `WP_Rocket\Subscriber\Preload->maybe_dispatch()`, it will work for all "partial preload"-based processes.

Estimate the effort ✅
effort: [M]

Most of the effort will be on writing automated tests.

**Comment by arunbasillal** [comment]
**Acceptance Criteria**

- Enable "Separate Cache or Mobile Devices" option in WP Rocket "Cache" tab. 
- Enable "Activate Preloading" in the "Preload" tab. Keep "Sitemap Preload" disabled. 
- Clear WP Rocket cache.
- Preload the cache. 
- Make sure mobile specific files are created during preload in addition to desktop files. 
- Edit a post and update it. 
- Make sure the homepage and the post specific cache is updated and the necessary mobile and desktop files are generated. 

**What if**

- WebP is enabled and WP Rocket is indeed generating separate webp file.
^ This is infact not an edge case, but by design WP Rocket should be generating the webp versions for both desktop and mobile.
