### ISSUE TITLE
filter_input() function returns NULL instead of the correct value with FastCgi

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2421]
**Describe the bug**
Website with Cloudflare flexible SSL. After update to 3.5, too many redirects issue happens in the browser.

`filter_input` is returning a NULL value instead of the IP when we check for it in the Cloudflare flexible SSL code: https://github.com/wp-media/wp-rocket/blob/a45f7625f202c775b080efa4e7ab18fc7791df37/inc/common/cloudflare-flexible-ssl.php#L35

There seems to be a bug with filter_input and FastCGI, so that would impact some setups: https://www.php.net/manual/en/function.filter-input.php#115960

**Expected behavior**
Website should be loading as expected.

**Solution**
Using filter_var with the global SERVER variable directly solves the issue. Confirmed on the customer website.

**HS ticket**
https://secure.helpscout.net/conversation/1106736317/150693?folderId=637040

**Comment by hellofromtonya** [comment]
## Old PHP Bug

The `filter_input( INPUT_SERVER, ...` returning `null` is an old old old PHP bug, i.e. dates back 12 years or more. You can see the [old comment from 12 years ago about it](https://www.php.net/manual/es/function.filter-input.php#77307) in the PHP Manual. With FastCGI, it impacts both `INPUT_SERVER` and `INPUT_ENV`. 

I've heard stories that the problem was resolved with PHP 7. But to be safe, let's eliminate its usage.

## When was this change introduced into Rocket?

This change was introduced in PR #2048, as part of our compliance to WPCS. Previous version was not filtering `$_SERVER['REMOTE_ADDR']`, which is a security issue.

**Comment by hellofromtonya** [comment]
## Can't Reproduce

We can't reproduce this problem. Therefore, we can't find the root cause. Why? This is not a PHP or Rocket bug. Rather, it's a problem within this customer's specific stack, potentially in the ini file.

In talking with some PHP core engineers, there seems to be a misunderstanding of the comments and threads in Google search about this. The `filter_input` is specifically built to filter external variable such as `$_SERVER`. 

The problem reported when using it with FastCGI is likely caused by something else and not a PHP bug itself.

## Why does using `filter_var` fix the issue?

It doesn't. Rather, it provides a bandaid for whatever problem exists in the stack.

## Is `filter_var` as safe as `filter_input`?

No. It depends upon how we are using it. When processing for storage or rendering, it is not. We will want to be more strict and intentional. But for this specific issue, it's "safe and secure _enough_."

## When was this change introduced into Rocket?

This change was introduced in PR #2048, as part of our compliance to WPCS. Why? To filter the input for safety and security. The previous version was not filtering `$_SERVER['REMOTE_ADDR']`, which is a security issue.

**Comment by piotrbak** [comment]
We haven't received any further tickets about this one. Going to close it, feel free to reopen if the issue persists.
