### ISSUE TITLE
Optimize Preload to run desktop and mobile in parallel instead of waterfall

### ISSUE THREAD

**Issue by hellofromtonya** [wp-media/wp-rocket#2428]
In 3.5, we added Mobile Preload. The processing shipped is desktop runs first, then pauses, and then mobile runs. It's being processed a stepped waterfall mode. The result: preload takes 2x as long as it did prior to 3.5. This is a regression.

The feature request is to optimize Preload by:

- queuing "preload" into the background processor
- then when triggered, doing desktop and mobile together for that webpage. 

In doing so, we iterate through the web pages and links 1x and then generate the desktop and mobile files.

**Comment by Screenfeed** [comment]
@hellofromtonya You mean for one page, preload desktop + mobile, then do the same for the next page, right?
There is one issue here: you hypothesize that a page must be preloaded for both desktop and mobile.
How homepage preload currently works:
- request homepage (desktop), grab its links, add them to the queue.
- request homepage (mobile), grab its links, add them to the queue.
The detail here is that the homepage may be different for desktop and mobile, and may not contain the same links: in this situation, wanting to preload links for desktop and mobile alternately has no sense.

**Comment by hellofromtonya** [comment]
@Screenfeed Does mobile preload _only_ process mobile-only web pages? How does it determine that this web page is mobile-only?

**Comment by Screenfeed** [comment]
As I said earlier, we currently:
- Request homepage with **desktop** UA (so the page preloaded at the same time), grab its links, add them to the queue: when the queue is processed, these URLs will be preloaded using a **desktop** UA.
- Request homepage with **mobile** UA (so the page preloaded at the same time), grab its links, add them to the queue: when the queue is processed, these URLs will be preloaded using a **mobile** UA.

After further thinking, I can see two solutions to try to improve things:
- Manipulate the queue once all desktop and mobile URLs are in it, and try to pair desktop/mobile URLs when possible. This will alternate desktop/mobile, but this will not reduce the processing time since we still have the same number of URLs in queue, only the order changes.
- Create two queues: one for desktop and one for mobile. This should reduce the processing time by a half or so, since it will process two queues in parallel and the queues will probably contain quite the same number of links. This will somehow alternate desktop/mobile preload, or at least, we won’t wait until desktop is done to start mobile.

I’m not sure if the 2nd solution is what you meant in the first place, but it seems quite close if I understood it correctly.

Now, this was for homepage preload only. For sitemap it's a bit different:
- Request a sitemap (with desktop UA, but we don't care), grab its links.
- If the sitemap is a "classic" sitemap, it contains only desktop links: push each link as desktop link to the queue, then push it again to the queue as mobile link. This means each link will be processed as desktop/mobile alternatively.
- If the sitemap is a "mobile" sitemap, it contains only mobile links: push each link as mobile link to the queue, no desktop here.
- If the sitemap contains links to other sitemaps, they are processed recursively.
- Then everything is processed in the same queue.

So, here too, doubled processing time since we have more links to preload. We can probably use the same solution used for the homepage preload.

**Comment by hellofromtonya** [comment]
Okay, I see. Mobile Preload processes the homepage in mobile mode to crawl its links _just in case_ its links are different than desktop. Hmm... 🤔

**Comment by Screenfeed** [comment]
Of course a 3rd solution would be to consider that "different links for mobile" are an edge case and forget it: 1 less crawl, able to alternate desktop/mobile. I admit I haven't considered this one until now 🤔

**Comment by piotrbak** [comment]
It's also affecting UX for bigger sites a bit. 

When there are a lot of links on the homepage, we're preloading all of them and incrementing counter correctly. Then we're preloading all mobile pages, so the counter is stuck for a long period of time.

In my case, the counter was stuck for 16 minutes:
https://secure.helpscout.net/conversation/1107833503/151289/

**Comment by GeekPress** [comment]
@hellofromtonya @Screenfeed I do a friendly up on this issue to continue the discussion and find a solution to be able to plan this improvement for 3.6 :)

**Comment by hellofromtonya** [comment]
@GeekPress I agree. We need to continue brainstorming to figure out how to optimize and improve the performance of Preload. 

@crystinutzaa will take the lead on this one while collaborating with @Screenfeed and me.

**Comment by hellofromtonya** [comment]
This issue will be fixed in 3.7. It's blocked until the new Preload module is built.

**Comment by hellofromtonya** [comment]
This issue will be fixed in a future major release. It's blocked until the new Preload is built.

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1207091608/176158?folderId=377611

**Comment by piotrbak** [comment]
Preload is running Mobile/Desktop requests in parallel since 3.12
