### ISSUE TITLE
Kinsta hosting improvement compatibility

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#247]
As we do for a couple of hostings (SiteGround, WP Engine, Flywheel, Pagely, etc...), we can also provide a better compatibility for Kinsta hosting. I mean to not generate caching files and purge the Kinsta cache when a customer decides to clear the WP Rocket cache.

**Comment by glueckpress** [comment]
There’s a dev resource here that may help to get this on the road:
https://kinsta.com/knowledgebase/kinsta-cache-plugin/#extending-functionality-with-hooks

**Comment by danielpataki** [comment]
Hi everyone,

Daniel Pataki here, I'm the CTO at Kinsta. I thought I'd chime in with some info and perhaps we can build something nice together here :) 

Currently we have three hooks, all of them for modifying the list of URLs to be purged. We'll work on exposing our actual cache clearing functions to you so you can make this happen.

I'll get back to you with an update early next week and we'll update the knowledge base accordingly. 

Have a nice weekend :)

**Comment by pcfreak30** [comment]
@danielpataki I am being sponsored by a kinsta client to get this working with a PR myself. As it stands it is possible to do it with your current code base. Though it would be good to store the `KinstaCache` instance in a variable so I don't need to scan the `$wp_filters` array to get a reference.

I assume you landed on this issue because I gave your tech support staff a link as well :). What do you think is the best way to handle this as I was planning on implementing this in a few hours now, but if your refactoring code then I likely need to wait.

**Comment by ketanshah79** [comment]
@danielpataki Any updates on this. We have 40+ sites hosted on kinsta. We really love WP Rocket and would love to see them work well together.

Cheers,
-Ketan.

**Comment by robin-scott** [comment]
@danielpataki please add a +1 from us too! Just wondering if this is on your roadmap at all?
