### ISSUE TITLE
Preload fetches wrong WPML URLs when cache expires

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2478]
**Describe the bug**
When WPML is being used in subdirectories, we're not able to preload language URLs after the cache expiration.

That's because we're passing URL with a double slash here:
https://github.com/wp-media/wp-rocket/blob/9b175725a5c568f27808875c041fc67cba264ae7/inc/Engine/Preload/PartialPreloadSubscriber.php#L149

`$data['home_path']` value: `/home/domain/public_html/wp-content/cache/wp-rocket/domain.com/da`

`$data['home_url']` value: `https://domain.com/da/`

`$file_path` value: `/home/domain/public_html/wp-content/cache/wp-rocket/domain.com/da/store/path-to-file/`

After `str_replace`:
`https://domain.com/da//store/path-to-file/`

**To Reproduce**
1. Use WPML subdirectory environment
2. Make sure that the subdirectory, language content is cached, preload is turned on, cache lifespan is set to the low value, so we don't have to wait
3. The cache should be purged but not preloaded

**Expected behavior**
The cache should be preloaded correctly. A possible solution is to make sure there are no double slashes in the URL.

Related ticket:
https://secure.helpscout.net/conversation/1107833503/151289?folderId=2415573

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Reproduced on mega website.

**Identify the root cause** ✅ 
The root cause is related to `$data['home_path']` which has the missing / at the end, so the str_replace() will have double // .
`home_path` trims the `/` in here:
https://github.com/wp-media/wp-rocket/blob/0bdcd1d0f9897541af2b589731d04af166ba1504/inc/classes/Cache/class-expired-cache-purge.php#L117-L118


**Scope a solution** ✅ 
The solution is to add back the '/' in `home_path` if the permalink_structure has the trailing slash:
```
$file_path = untrailingslashit( $file_path );
$data['home_path'] = untrailingslashit( $data['home_path'] );
if ( '/' === substr( get_option( 'permalink_structure' ), -1 ) ) {
		$file_path .= '/';
		$data['home_path'] .= '/';
}
```


**Estimate the effort** ✅ 
Effort [S] - All the effort should go in writing Unit & Integration tests for `preload_after_automatic_cache_purge()` function

**Comment by piotrbak** [comment]
Another case:
https://secure.helpscout.net/conversation/1141755787/159291?folderId=2415573
