### ISSUE TITLE
.no-webp files not deleted from date archives when clearing related cache

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2491]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔
- Used the search feature to ensure that the bug hasn’t been reported before ✔

**Describe the bug**
The `.no-webp` file created during webp caching isn't cleared from the date archives when a post is updated. 

**To Reproduce**
1. Enable webp caching in WP Rocket. Make sure `.no-webp` files are generated for pages without webp images. 
2. Disable Preload. 
3. Visit the date archives to generate it's cache. 
4. Update the post. It's cache and all related caches will be cleared. 
5. However, `.no-webp` files will not be cleared. 

**Expected behavior**
The `.no-webp` file should be deleted as well. In case the archive page now has webp images, having the `.no-webp` file here will cause issue. 

**Screenshots**
Video: https://youtu.be/D8cA_h06WoA

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Reproduced on local test site

**Identify the root cause** ✅ 
The issue is happening because in here: https://github.com/wp-media/wp-rocket/blob/6168eb4f3a013f5c542a69b6b15312eee43223f3/inc/functions/posts.php#L66

We don't pass the whole date dir, but the files themselves. **This is on purpose in case the permalink structure uses the date in it.**

And then, in here: https://github.com/wp-media/wp-rocket/blob/6168eb4f3a013f5c542a69b6b15312eee43223f3/inc/functions/files.php#L1062

We only delete the `no-web` file if the current element is a dir, not a file.

**Scope a solution** ✅ 
I thought of a lot of different approaches, but what makes the most sense to me would be to create a new function to handle dates archives deletion on its own, instead of relying on `rocket_clean_files` and `rocket_rrmdir` after, which both use `glob` and makes handling this tricky.

The function `rocket_clean_dates_archives()` would receive the dates archives URLs, and use the `FileSystemIterator` to only delete files in the root directory, without being recursive. That way a permalink structure with dates would be preserved, and the `no-web` file would be deleted correctly.

It would also fix a related existing issue, where the cache files are not correctly deleted, because they use a different name than `index.html(_gzip)`, which is quite common now with ssl/mobile/WebP/Dynamic cookies cache.

`get_rocket_post_dates_urls()` can be updated to return the base URLs for dates instead of the `index.*` files, and be used in `rocket_clean_dates_archives()`

**Effort** ✅ 
Effort `[S]`
- Create new function `rocket_clean_dates_archives()`
- Update `get_rocket_post_dates_urls()`
- Update `rocket_clean_post()`
- Write tests
