### ISSUE TITLE
Externally hosted jQuery not excluded from defer when safe mode + combine js are active

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2493]
**Describe the bug**
We automatically exclude Jetpack-hosted jQuery (from their Site Accelerator feature) from being deferred when Deferred JS with Safe Mode is active. 

However, when Combine JS is also active, this file is no longer excluded. 
This is not consistent with what happens when Jetpack Site Accelerator is OFF. 

When using default WordPress-included jQuery, if _both_ Deferred JS w/ Safe Mode AND Combine JS are active, this file will be excluded and not deferred. 

So I would expect the behaviour to be the same when it's an externally-hosted version of jQuery that we detect.

I haven't checked if Jetpack is the only affected external JS or if it also applies to the [other external hosts we detect:](https://github.com/wp-media/wp-rocket/issues/1196) 

**To Reproduce**
Requires a site with Jetpack enabled. 
1. Enable Combine JS and Deferred JS with Safe Mode
2. Observe that jQuery.js is excluded from Combine and is not deferred. 
3. Enable Jetpack Site Accelerator with _Speed up static file load times_
4. Clear the Cache
5. Observe that jQuery is no longer excluded, but is included in the Combined JS file.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
**Reproduce the problem** ✅ 
Reproduced on test installation

**Identify the root cause** ✅ 
In https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/classes/optimization/JS/class-abstract-js-optimization.php#L145

We only get the URL for the WP core jQuery, not for any externally hosted jQuery like we do for deferred JS.

**Scope a solution** ✅ 
Improve this method to also exclude known externally hosted jQuery, like from Jetpack, googleapis.com or cdnjs.cloudflare.com

**Effort** ✅ 
Effort `[S]`
