### ISSUE TITLE
Browser still load cached file after trashed comment although cache file on server is deleted

### ISSUE THREAD

**Issue by thanh25896** [wp-media/wp-rocket#2496]
**Describe the bug**
Adter I trashed comment, the cached page file linked with that comment was clear but browser still load old saved cache on cilent. 

**To Reproduce**
1. Go to 'comment of any post and post a comment'
2. After that the cached file was removed 
3. Refresh the page , browser will load latest file ( no ploblem here)
4. Use admin account go to comments manager and trash that comment ( the cached file was clear)
5. Refresh the page and that comment still exit , the new cached file didn't create 

Solution to solve this problem:
Preload that page after trashed comment to create the cached file and browser will surf new cached file

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the problem** ✅ 
Issue reproduced on local testing

**Identify the root cause** ✅ 
Comments are trashed with ajax call, so the Partial Preload bails out at this condition.
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/Engine/Preload/PartialPreloadSubscriber.php#L185

**Scope a solution** ✅ 
@Screenfeed , @Tabrisrp , @hellofromtonya any idea for a solution in here?
Why `maybe_dispatch` is hooked on `shutdown` and why it bails out if `wp_doing_ajax()`?

**Estimate the effort** 🔴

**Comment by Screenfeed** [comment]
@crystinutzaa That's related to how `->save()` and `->dispatch()` work. As you probably already now:
- `->save()` saves a queue in the database,
- `->dispatch()` triggers a HTTP request to start the process.

That means if we do `->save()->dispatch()` in each method that adds items to the queue (`preload_after_clean_post'()`, `preload_after_clean_term()`, `preload_after_automatic_cache_purge()`), we save several queues and launch several requests in one single page.
Hooking `shutdown` allows us to save all the items in one single queue and start only one process. Also, it removes duplicates.

I don't know about the ajax thing.

**Comment by jazir5** [comment]
I have this same issue, but unrelated to comments, as comments are disabled on my site. I've had plenty of times where i'll gtmetrix test my site and see it trying to load a cache file with a 404 error at the end of the waterfall chart. I have to assume the issue is related to this one and has a similar root cause.

**Comment by piotrbak** [comment]
That part of the code was changed, not happening anymore
