### ISSUE TITLE
Allow page cache deactivation by admin UI setting

### ISSUE THREAD

**Issue by JanThiel** [wp-media/wp-rocket#2501]
**Is your feature request related to a problem? Please describe.**
When we have scenarios where we need to check whether caching is the source of an issue, or not, our customers and partners tend to deacticate the whole plugin. This also disables all the other features (Lazy loading, etc.) the plugin provides and creates a somewhat inconsistent state on the page as more features are missing than necessary.

**Describe the solution you'd like**
On the "Cache" tab within the WP-Rocket Admin UI I would like to be able to disable the page caching only. This should remove all page cache files below wp-content/cache/wp-rocket/[DOMAIN] (like purge cache) and stops creating new page cache files there.

**Describe alternatives you've considered**
Disabling the whole plugin is currently the only other way to disable the page caching.

**Additional context**
- WP-Rocket 3.5.2
- nginx

**Comment by GeekPress** [comment]
Hi @JanThiel 🤚

Not having a « Page Cache » option is a part of our « Decision, not option » philosophy since day 1.

We won't change our mind for that point.

Why?
We try to avoid as most as possible the number of « option » to keep WP Rocket simple to use.
The page caching shouldn't be an option. All websites has to be cached, so it's automatically activated.

For your specific needs to be able to disable page caching and keep other features working, you can use this:
https://pastebin.com/n7Qpc99i

You have to put this into a file in your wp-content/mu-plugins/ folder.

**Comment by JanThiel** [comment]
Hi @GeekPress,
thanks for your feedback. I do understand and respect your decission.

So after all - disabling the whole plugin remains the "official" way to go. 
As I am no fan of adding more code which can break on updates, make issues in our Multisites, etc. etc. the "custom addon plugin" is no feasable way for our customers.

Thx and best regards anyway,

Jan
