### ISSUE TITLE
Add a mention about Google Tag Manager in Google Tracking add-on

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2515]
**Is your feature request related to a problem? Please describe.**
I noticed too much time customer asking us to be « compatible » with Google Tag Manager for our Google Tracking add-on.

But we are already optimizing GTM script!

The problem is the add-on mention only Google Analytics.

**Describe the solution you'd like**
1. Change the Google Analytics logo with a mixed logo about GA and GTM.
2. Change the title by `Improve browser caching for Google Analytics and Google Tag Manager`

**Comment by GeekPress** [comment]
@arunbasillal @webtrainingwheels Are you ok with that change?

**Comment by arunbasillal** [comment]
@GeekPress Our doc - https://docs.wp-rocket.me/article/1103-google-tracking-add-on

says:

> Heads up! If your Google Analytics script is installed using Google Tag Manager, this add-on will not work. This Add-on currently only works with the tracking code taken from a Google Analytics account.

So this isn't relevant anymore? In fact, we do locally host `https://www.googletagmanager.com/gtag/js`. 🤔 
It seems I am missing something. 

The changes you suggested look good to me 👍

**Comment by webtrainingwheels** [comment]
I think we are talking about 2 separate things here, unless something has changed on Google's side.

The script we optimize: https://www.googletagmanager.com/gtag/js
is specifically the Global Site Tag Analytics script. While it has googletagmanager in the src, it comes from your Analytics account:
https://developers.google.com/analytics/devguides/collection/gtagjs/

Google Tag Manager is a separate account used to add many different kinds of scripts to your site. Adding Analytics or anything else this way isn't compatible. And this is what I think customers are referring to with this request.
You can see the format of that script here: 
https://developers.google.com/tag-manager/quickstart

So based on this we should not make any changes since it would be misleading and more confusing than it already is.

**Comment by jkarttunen** [comment]
Seconded, just spend one full day troubleshooting GTM in a WP site. The source of broken analytics was the 'delay js exceution' that caused GTM (and analytics) to be loaded not on page visit but on first click. 

For anyone troubleshooting Google Tag Manager on wp-rocket: Do not include tagmanger in delay js field.
