### ISSUE TITLE
LazyLoad CSS and JS file not removed on search page

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2535]
The usual WordPress search query page isn't cached by default. The URL is like this: 
`example.com/?s=query`

But if LazyLoad is active, the inline CSS and JS file are still there. 

**To Reproduce**
1. Enable LazyLoad
2. Perform a search, or visit a URL like: `example.com/?s=query`
3. View the page source. At the bottom you'll see the code above-mentioned code: 
https://jmp.sh/AEj7oAP

**Expected behavior**
It should not be there :)

**Additional context**
Very similar to this issue: https://github.com/wp-media/wp-rocket/issues/2523

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
My question is if LazyLoad should work also on a page which is not cached. 
@hellofromtonya , @GeekPress , @Tabrisrp 

**Reproduce the issue** ✅ 
I reproduced this issue on my localhost.

**Identify the root cause** ✅ 
The root cause is in here:
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/classes/subscriber/Optimization/class-lazyload-subscriber.php#L299

**Scope a solution** ✅ 
This function should bailout if the page is not cached and cannot be cached.

**Effort** ✅ 
Effort `[S]`

**Comment by hellofromtonya** [comment]
@GeekPress Should lazy load work on a page that is not cached and cannot be cached? What do you think?

**Comment by GeekPress** [comment]
@hellofromtonya As for now the LazyLoad isn't applied on uncached page, we should keep the same behavior on the search page which are excluded from the cache
