### ISSUE TITLE
500 error on WP Rocket activation - Opening comment tag in wp-config.php removed 

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#2537]
**Before submitting an issue please check that you’ve completed the following steps:**
- Version 3.5.2

**Describe the bug**
When the opening comment tag is set on the **1st** line of the `wp-config.php` file, the WP Rocket activation will remove it causing a 500 error (parse error).

**To Reproduce**
1. Edit the 1st line of the `wp-config.php` file like this: http://snippi.com/s/pcr3v72.
Note that the opening comment tag of the default comment is placed on the 1st line instead of the 2nd line.
2. Activate WP Rocket. This will add the `define( 'WP_CACHE', true ); // Added by WP Rocket` line in the `wp-config.php` file.
3. See the **500 error** on the website.
4. The resulting `wp-config.php` file looks like this: http://snippi.com/s/t4a6o7o.

**Expected behavior**
Adding the `define( 'WP_CACHE', true ); // Added by WP Rocket` line in the `wp-config.php` file should not remove the opening comment tag.

**Additional context**
Only happens for the  `wp-config.php` files where default comment opening tag is placed on the 1st line instead of the 2nd line.
**Ticket**: https://secure.helpscout.net/conversation/1129985389/156210?folderId=2675957.
**Slack** thread: https://wp-media.slack.com/archives/C08N8J6VC/p1586811121269400.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by GeekPress** [comment]
I added `type: enhancement` as the issue is related to a custom modification. By default, the wp-config.php isn't like that. It's also why I decided to have a low priority on this issue.

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
The root cause is in here:
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/functions/files.php#L355

**Scope a solution** ✅ 
A solution can be to modify the constant to contain an extra line before like this:
`$constant = "\r\ndefine('WP_CACHE', $turn_it_on); // Added by WP Rocket\r\n";`
and insert the constant right after `<?php` . 

**Effort** ✅ 
Effort `[S]` , I think Unit & Integration tests will need almost all the effort
