### ISSUE TITLE
Set the CDN to be active for images on AMP pages

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#2548]
**Describe the bug**
The CDN rewrite is not working on the AMP pages
Currently, the rewrite is not expected since we remove all optimizations in the AMP pages.

**To Reproduce**
1. Install the [AMP](https://wordpress.org/plugins/amp/) plugin and enable the CDN in WP Rocket
2. Enable the _Transitional_ template in _AMP -> General_ settings.
3. Visit an AMP version of a page
4. Check the source of the images in the developer tools (the CDN rewrite is not applied)

**Expected behavior**
The CDN rewrite could be active for images only.

**Screenshots**
![image](https://user-images.githubusercontent.com/26235782/79567646-e43ea200-80b4-11ea-8cb6-f1646564ca4c.png)
_Full-size image: https://share.getcloudapp.com/qGudyY4v_ 

￼![image](https://user-images.githubusercontent.com/26235782/79555769-64a6d800-80a0-11ea-85c7-d5e1d5dcec7b.png)
_Full-size image: https://share.getcloudapp.com/wbu0rv0r_
 
**Additional context**
Ticket: https://secure.helpscout.net/conversation/1137020355/158076/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1587049067360300
Related plugin: https://wordpress.org/plugins/amp/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified this issue on localhost.

**Identify the root cause** ✅ 
The root cause is because rocket_buffer is removed totally from AMP compatibility.
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/ThirdParty/Plugins/Optimization/AMP.php#L103

**Scope a solution** ✅ 
The solution will be to add in AMP.php file CDN rewrite & rewrite_srcset from CDNSubscriber.

**Effort** ✅ 
Effort seems minimal , however I assume that Integration & Unit tests will take longer time. 
[S]
