### ISSUE TITLE
Add filter to stop purge cache

### ISSUE THREAD

**Issue by jakubkaderavek** [wp-media/wp-rocket#258]
Hi,

there is a problem when I save draft, then all urls are purged when I update post, cache comment count etc. so it would by great if you add filter like:

$stop_purge = apply_filters( 'before_rocket_purge_post', $post);
 if($stop_purge == false) {
 return;
 }

to inc/common/purge.php to stop execute of function.

**Comment by GeekPress** [comment]
Hi @jakubkaderavek You can also directly remove our filter instead of creating a new one like this:
remove_action( 'clean_post_cache' , 'rocket_clean_post' );

I will also suggest you to open a ticket support: https://wp-rocket.me/support 

Bt default, the normal behavior is no purge is triggered if a post is in draft.

**Comment by jakubkaderavek** [comment]
Hi @GeekPress ,
thanks for reply - I try to remove action but I test WP Rocket and cache is purged when you save draft (it's not pruged when is auto-draft). We discuss this with Remy frm WP Rocket

**Comment by foliovision** [comment]
@jakubkaderavek WP Rocket does too many cache purges, we posted some summary here: https://github.com/wp-media/wp-rocket/issues/478

**Comment by Tabrisrp** [comment]
Seems to be related to #2124

**Comment by GeekPress** [comment]
I'm closing it as the purge issue when a post is saved as draft as been fixed with WP Rocket 3.4.3 (https://github.com/wp-media/wp-rocket/issues/2124)
