### ISSUE TITLE
Expired cache preload doesn't work on IIS

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2584]
**Describe the bug**
Expired cache preload doesn't work on IIS due to the slashes and backslashes usage in the paths.

That's because we treat the paths as logged in ones here:
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/Engine/Preload/PartialPreloadSubscriber.php#L134

The `$data['logged_in']` is true, because the paths don't match here:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/Cache/class-expired-cache-purge.php#L131

The values:
`Dir path: D:\inetpub\vhosts\domain.com\blog.domain.com/wp-content/cache/wp-rocket\blog.domain.com`

`Cache path: D:\inetpub\vhosts\monteleone.it\blog.domain.com/wp-content/cache/wp-rocket/blog.domain.com`

Please note the slash after `wp-rocket`. 

**To Reproduce**
1. Go to the WP Rocket dashboard hosted on IIS
2. Set cache lifespan to 10 minutes
3. Preload cache
4. After 10 minutes confirm that it's not preloaded

**Expected behavior**
It's expected to preload the cache correctly

**Additional context**
I don't know if there's any other feature that could be affected by this problem.

Related ticket:
https://secure.helpscout.net/conversation/1141100768/159114?folderId=2415573

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by crystinutzaa** [comment]
There is already a PR for this one. Needs to be updated to fix this issue, however as I've had a longer discussion with @hellofromtonya , the root issue seems to be related to the conversion from URLs to filepaths which is constantly made and is prone to errors.

A temporary solution is to revisit and finish this PR: https://github.com/wp-media/wp-rocket/pull/2251

A long term solution is to have a single function responsible for this transformation (URL to path and path to URL) and to prevent as much as possible this conversion and pass both values as once.


**Reproduce the issue** ✅ 
I was able to recreate the issue on my local while I was on this PR.

**Identify the root cause** ✅ 
The root cause is in here: https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/Cache/class-expired-cache-purge.php#L131

**Scope a solution** ✅ 
Temp solution is this https://github.com/wp-media/wp-rocket/pull/2251

**Effort** ✅ 
Effort `[S]`

**Comment by hellofromtonya** [comment]
@crystinutzaa Per our conversations, I agree with the incremental approach of first solving the IIS problem with PR 2251. As we are laying out the workflow diagram and refactor "desired" diagram/designs, we will work in the optimizations you mentioned.

And as part of PR 2251 and this fix, let's also wire up Rocket to[Appveyor](https://www.appveyor.com/) which will run our CI on Windows to validate the directory separator and all code works on Windows too.

**Comment by hellofromtonya** [comment]
This issue is directly related to how we normalize and escape directory separators for RegEx processing. With PR #2643, we now have an internal pathing normalizer function that works for IIS and Linux `_rocket_normalize_path()`:

https://github.com/wp-media/wp-rocket/blob/622f9212eb98c908079aa232f7c048f9cae35067/inc/functions/files.php#L1471-L1489

I'm going to explore using this function within PR #2251 that @crystinutzaa opened. Let's see if we can quickly fix this issue.

**Comment by hellofromtonya** [comment]
This issue will be fixed in 3.7. It's blocked until the new Preload is built.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1862118963/339614?folderId=3864740

**Comment by piotrbak** [comment]
Not enough feedback here to be implemented in the nearest future.

**Comment by girlie** [comment]
Related: https://secure.helpscout.net/conversation/2758394667/522270/
