### ISSUE TITLE
Leveraging WordPress Site Health Tools to warn about plugin/theme conflicts

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2598]
Starting with WordPress 5.4, there is a widget on WordPress dashboard for site health tools. This gives more visibility to potential issues. 

On multiple occasions, @Tabrisrp has recommended to use site health tools as a central location for our notices. We could start by displaying [plugin or theme conflicts](https://www.notion.so/wpmedia/Known-Conflicts-8d0a97af9b9c49dd991b28b24550e3de#a403a2de94d24a6ba4a299958bae1110) in Site Health Tools. 

This could help resolve issues like #1593 or #2577 without the need for specific admin notices that crowd up WordPress UI of customer websites. (Of course, wherever possible, our first step should be to contact the developer to see if the issues can be resolved. This is best ux for the user.)

We could update our documentation to ask customers to check the site health tools for potential issues and its resolution. 

Eventually, we could think of moving other notices to site health and thus have a non-intrusive way to provide non-critical feedback to customers.

**Comment by GeekPress** [comment]
To be direct, I'm not a fan to relay on Site Health tools.

Why?
When someone has a problem, do they have the habit to go on the Site Health Tools? I don't think so. I did a survey to get data => https://twitter.com/GeekPressFR/status/1256206171536531456

Also, sometimes people doesn't know they have a problem. They don't have the need to go on the Site Health Tools as they don't necessary know the plugin isn't working. The issue #2577 is a good example. The customer didn't know that WP Rocket didn't work properly and asked for a refund.

A notice is displayed everywhere. Ok, it could be annoying if you have a ton. It's still more visible to something hidden into the Site Health Tools. Our interest is to show our notice/message to the maximum of our users to let them know there is an issue. It's into our interest to provide the best visibility.

We don't display 10 notices at the same time. And when we have to display something everywhere, it's because WP Rocket can't work properly which is a critical information to know.

> We could update our documentation to ask customers to check the site health tools for potential issues and its resolution.

We relay on the fact that 100% of our users will read our documentation. It's not the case.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
