### ISSUE TITLE
Improve the sub-feeds exclusions

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#2607]
**Describe the bug**
WP Rocket automatically exclude the https://example.org/feed/ from being cached:
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/functions/options.php#L234-L235

but some Podcast plugin like [https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/](https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/) are using this `/feed/` base to add URLs like `/feed/mp3/` which won’t be automatically excluded from being cached. WP Rocket will then change `MIME-types` from `content-type: application/rss+xml;` to `content-type: txt/html;`.

This is because the current pattern we use will only match for URLs ending with `/feed/` or `/feed`, if there is anything after, it won’t work.

**To Reproduce**
1. Install and configure this plugin [https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/](https://wordpress.org/plugins/podlove-podcasting-plugin-for-wordpress/)
2. Check the URL it will create
3. Test it in this tool [https://gf.dev/mime-sniffing-test](https://gf.dev/mime-sniffing-test)
4. See the `MIME-type` : `content-type: txt/html;`

**Expected behavior**
The `MIME-type` in should [https://gf.dev/mime-sniffing-test](https://gf.dev/mime-sniffing-test) have been `content-type: application/rss+xml;`

**Fix propostion**
https://regex101.com/r/Rp1rix/2

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/functions/options.php#L234-L235

**Scope a solution** ✅ 
The feed url should include also all sub-urls (eg. `/feed/`, `/feed/mp3/`)
Regex which should work:
`$uris[] = '/(.+/)?' . $GLOBALS['wp_rewrite']->feed_base . '/?.+/?';`

**Effort** ✅ 
Effort `[S]` , I think Unit & Integration tests will need almost all the effort
