### ISSUE TITLE
BNFW plugin - Duplicate emails are send when preload is enabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#2620]
The [Better Notifications for WP](https://wordpress.org/plugins/bnfw/) plugin sends each email notification twice when WP Rocket's preload feature is enabled.

Both plugins are hooking to the shutdown action:
https://github.com/jackmcconnell/bnfw/blob/8560dc81d33b17418aadf06abeed33a7a4fa4e19/bnfw.php#L207
https://github.com/wp-media/wp-rocket/blob/adab7a846f85e1edbdeb7e6a63575789d0f0bf7b/inc/Engine/Preload/PartialPreloadSubscriber.php#L72

I figured out this was an issue of how priorities are applied. @crystinutzaa confirmed this and found that changing our priority to `PHP_INT_MAX` resolved the issue.

**To Reproduce**
1. Install the [Better Notifications for WP](https://wordpress.org/plugins/bnfw/) plugin
2. Create a new Notification: ![https://i.vgy.me/WwzUSz.jpg](https://i.vgy.me/WwzUSz.jpg)
3. Edit it to define yourself as the recipient for the email: ![https://i.vgy.me/YrAtoj.jpg](https://i.vgy.me/YrAtoj.jpg)
4. Publish a new post.
5. Check your inbox.

**Expected behavior**
Only one email should be sent each time.

**Additional context**
I have already confirmed the fix is working both on my site and on the customer's site.

**Related ticket**
https://secure.helpscout.net/conversation/1151770831/161928/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified this issue on Vasilis test website.

**Identify the root cause** ✅ 
https://github.com/wp-media/wp-rocket/blob/adab7a846f85e1edbdeb7e6a63575789d0f0bf7b/inc/Engine/Preload/PartialPreloadSubscriber.php#L72

The issue is that both plugins run on shutdown action and this may end up in conflict. 

**Scope a solution** ✅ 
The solution is to move our Partial Preload the last with  `PHP_INT_MAX` 
```
'shutdown' => [ 'maybe_dispatch', PHP_INT_MAX ], 
```

**Effort** ✅ 
Effort seems minimal [XS]
@hellofromtonya any tests should be written in this case?

**Comment by hellofromtonya** [comment]
>any tests should be written in this case?

@crystinutzaa No. Why? 

- This code will be written in the new Preload module. 
- This is edge case with one specific plugin. I see these types of problems as something we can solve in a QA process with testing on live sites and in different pre-built testing envs.
