### ISSUE TITLE
Divi is clearing our cache, no clear possibility to stop it

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2630]
**Describe the bug**
Divi is clearing our cache when updating the post. There's no way to disable this call to `rocket_clean_post` in `wp-content\themes\Divi\core\components\init.php:53` :
http://snippi.com/s/n0lkbo5

**To Reproduce**
1. On a site with Divi install our [Disable Cache Clearing addon](https://docs.wp-rocket.me/article/137-disable-automatic-cache-clearing)
2. Update the post
3. Confirm that our cache is being cleared

**Expected behavior**
It would be good to have a way to disable this option with a filter or `remove_action` function. After combination with this issue, many cached files are removed and we can't control it at all:
https://github.com/wp-media/wp-rocket/issues/2549

**Related ticket**
https://secure.helpscout.net/conversation/1141100768/159114/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@piotrbak I guess this is an issue to post on Divi repository, isn't?

**Comment by arunbasillal** [comment]
There isn't anything clean we can do about it and as @GeekPress said its for Divi's repository. 

The customer could define a dummy function `et_core_clear_wp_cache` (just a funciton definition and `return`) and load it before Divi is loaded. So that when Divi checks for `function_exists( 'et_core_clear_wp_cache' )` it would come up as true and wouldn't define the function. A hack rather than a solution.

**Comment by piotrbak** [comment]
The solution should be released on Divi's end.
