### ISSUE TITLE
Error when clearing cache on O2Switch when using PHP7.1+

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2640]
**Describe the bug**
We're getting the following error when clearing the post cache on O2Switch with PHP7.1+

`Uncaught Error: [] operator not supported for strings in /home/domain/public_html/wp-content/plugins/wp-rocket-compat-varnish-ip/wp-rocket-compat-varnish-ip.php:29`

That's because the short array push syntax is not allowed on a string or non-existing variables since PHP7.1.

I was able to fix it in the helper plugin by declaring the variable as an array:
https://github.com/wp-media/wp-rocket-helpers/blob/9f7186010f3d405d0b614cafd008ba359006f1ec/compatibility/wp-rocket-compat-varnish-ip/wp-rocket-compat-varnish-ip.php#L30

However, it ended up with the following notice each time the post is cleaned (14+ times on post update):
`PHP Notice:  Array to string conversion in /home/domain/public_html/wp-content/plugins/wp-rocket/inc/3rd-party/hosting/o2switch.php on line 122`

This problem happened after updating our helper to be compatible with multiple Varnish IPs.

**To Reproduce**
1. On a site on O2Switch enable their caching
2. Make sure that PHP version is at least 7.1
3. Enable Varnish Add-on
4. Install and configure the helper:
https://fr.docs.wp-rocket.me/article/1113-utiliser-wp-rocket-avec-xtreme-cache-o2switch
5. Clear the post cache and check PHP logs

**Expected behavior**
Correctly cleaned cache without errors nor notices

**Additional context**
We could create a specific Varnish helper plugin for O2Switch, since they're using only one IP, the array is not needed.

The other solution is to fix this problem on the WP Rocket's end.

Ticket:
https://secure.helpscout.net/conversation/1158506945/163617/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Did not reproduced the issue because it needs O2Switch hosting.

**Identify the root cause** ✅ 
The root cause is related to this filter which returns an empty string instead of array.
https://github.com/wp-media/wp-rocket/blob/0aa1fd37f2df21ecbc5ca63bfae4964991431473/inc/3rd-party/hosting/o2switch.php#L106

**Scope a solution** ✅ 
https://github.com/wp-media/wp-rocket/blob/0aa1fd37f2df21ecbc5ca63bfae4964991431473/inc/3rd-party/hosting/o2switch.php#L106 
change it to: 
`$varnish_ip = apply_filters( 'rocket_varnish_ip', [] );`

If we are touching this file I would move it to the new structure:
`inc/ThirdParty/Hosting/o2switch.php`
and write Unit & Integration tests for full coverage.
@Tabrisrp , @hellofromtonya what do you think?

**Estimate the effort** ✅ 
[M] - There are 6 functions which need Unit & integration tests and this will take more time.

**Comment by Tabrisrp** [comment]
This whole compatibility file needs to be revisited to be less a copy of what the old Varnish code was, and to work with the new one instead.

Ideally the compatibility file should only be some callbacks methods to hook on available filters, extending the core Varnish code we have.

So we have to compare both and see what changes need to happen not only for `o2switch` but possibly for Varnish Add-on too.

**Comment by crystinutzaa** [comment]
I got O2Switch account from @piotrbak and I was able to recreate the issue.

@Tabrisrp I am not sure if I totally understand this:

> `Ideally the compatibility file should only be some callbacks methods to hook on available filters, extending the core Varnish code we have.`

**Comment by Tabrisrp** [comment]
Right now the compatibility file contains duplicated code with our Varnish Add-on. So this code needs to be updated to remove duplicate code, and only extend the Varnish Add-on where needed using the filters

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1171679248/166913?folderId=2135277

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1188562955/171240?folderId=377611

**Comment by piotrbak** [comment]
Related
https://secure.helpscout.net/conversation/1206359363/176039/

**Comment by WordPresseur** [comment]
Related: https://secure.helpscout.net/conversation/1226091030/180443?folderId=1213662
