### ISSUE TITLE
Update our load CSS asynchronously method

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2658]
We currently use [this technique](https://www.filamentgroup.com/lab/async-css.html#a-modern-approach) to load CSS asynchronously when Optimize CSS delivery is enabled:
- `rel="preload"` instead of `rel="stylesheet"`, with and `onload` event to switch the value of the `rel` attribute

This technique works fine, but `preload` support is still not full for browsers, so that requires us to also insert the `loadCSS` polyfill script in the page, and it might cause some issues when testing pages on PageSpeed for key requests.

The [new technique](https://www.filamentgroup.com/lab/load-css-simpler/) is an improvement, where the switch occurs on the `media` attribute, using by default the value of `print`, and switching it back to its original value with the same `onload` event.

As described in the article, the advantages are:
- Better browser support out of the box
- No need for polyfill script
- using `preload` will trigger fetches very early, often too early compared to what is needed
- the browser will load the stylesheet without delaying page rendering, asynchronously!

**Comment by GeekPress** [comment]
@Tabrisrp Thanks for sharing this new technique to load CSS!

I did some benchmarks on our own website to compare several situations:

I used only webpagetest for the benchmark which is the most accurate tool to get a proper waterfall. The test has been done with the « Combine CSS » on.

**Current method to load CSS (preload):**
https://www.webpagetest.org/result/200518_Y8_bb26561249d23302e7473b991b07c429/

Best loaded time for CSS file: 197ms
CSS file is loaded early.

**New technique without preload:**
https://www.webpagetest.org/result/200518_BZ_e2ef92f0d4614317acfc197106050c22/

Best loaded time for CSS file: 584ms
CSS file is loaded later.

**New technique with preload:**
https://www.webpagetest.org/result/200518_X1_7078e83e1abe6ad497cae9f5faba20db/

Best loaded time for CSS file: 198ms
CSS file is loaded earlier.

We can conclude that the preload has an important impact on the CSS loading time. If we go with the new technique, we should also preload the combined CSS file.

**New technique with preload + CSS file loaded from footer:**
https://www.webpagetest.org/result/200518_2Q_99d795c5d3f92586f96dd56629254aaa/

Best loaded time for CSS file: 200ms
CSS file is loaded earlier.

Putting the combined CSS file into the footer will provide the same performance. I also didn't notice a FOUC effect. I noticed a small FOUC effect if we put the combined CSS in the footer without the preload.

I'm wondering if we can put the CSS file in the footer before the `<noscript>` tag instead of placed it just below the preload tag. Will it have an impact on PageSpeed Insight for render-blocking ressource? 

Swift Performance moves the combined CSS file into the footer. Same for Nitropack or Pegasaas.

What we are sure is we also need to preload the combined CSS file to be faster. But what about when the CSS files are just minified? Do we want to preload all CSS files? I don't know the impact of preloading a lot of HTTP requests.

**Comment by ScottTravisHartley** [comment]
Just want to add a comment to this thread that firefox nightly is adding support for preload 

https://bugzilla.mozilla.org/show_bug.cgi?id=1639607

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
#### inc/Engine/CriticalPath/CriticalCSSSubscriber.php
- Remove the `insert_load_css()` method, as it's no longer needed with the new technique
- Update the `async_css()` method, to use the new `media="print"` technique instead of the preload one. Also do some refactoring in it, as it's currently too complex
- Write tests for `async_css()`

### Estimate the effort ✅ 
Effort `[S]`, will need time to refactor & write tests

**Comment by hellofromtonya** [comment]
@Tabrisrp @crystinutzaa The current implementation for this issue requires a lot of code and a complex, huge regex pattern. While it works, that's not easily maintainable. 

Currently, I'm working on a server-side DOM object. I have a prototype of it that extends off of PHP's `DOMDocument`. 

The plan is this:

- I'll take what Cristina built and adapt it to use the new `HTMLDocument` in the DOM Module.
- We'll run analysis on this new approach to ensure that it delivers the enhancement we need for all customers.
- This will serve as a _baby step_ towards traversing and modifying HTML via the DOM, i.e. instead of via string manipulation.

**Comment by hellofromtonya** [comment]
Status Update:

The PR for this issue now includes the new DOM Module (which extends off of the PHP `DOMDocument` class. 

The new approach has added benefits:

- It's much easier to work with HTML as a DOM instead of as a large string.
- Eliminates regex, which for this issue would have required a huge regex string.
- The DOM object:
    - natively fixes malformed HTML, similar to what the browser DOM does.
    - removes whitespace in the elements and their attributes. Less bytes.
    - converts single quotes around attribute values to double quotes.
- It empowers us to work at the element and attribute level.
- We can query the DOM to find all elements that match different criteria.

For this specific issue, we need to validate the `onload`, `media` and `rel` attributes, while retaining the existing `onload` attribute values that are not in conflict with ours. That's really hard to do with regex and HTML strings. The new approach makes it easier.

**Comment by SirLouen** [comment]
Any plans to include the latest async method? 
https://www.filamentgroup.com/lab/load-css-simpler/#the-code
https://github.com/filamentgroup/loadCSS#changes-in-version-30-no-more-preload-polyfill
https://stackoverflow.com/a/46750893/4442122

The preloaded CSS requests are killing the LCP of all my sites. 
It's not much but savings of 0.3-0.4s is for me the difference from 2.7s (orange) to 2.4 (green).

**Comment by crystinutzaa** [comment]
### Scope a solution ✅ 
The solution is already implemented in the PR: 
https://github.com/wp-media/wp-rocket/pull/2786
However, the PR contains also the changes with DomDocument which was not reliable.
Grab the code, including the tests and refactor it.

The solution is to use Regex to identify and mix the media and preload attributes. However, the current implementation has 2 downsides:
1. `A bug`:  If there are missing attributes on link, then this change will not work. 
This link example should be added in tests to make sure that will pass correctly:
<link rel="stylesheet" href="" />

2. The code is hard to read and to maintain. 

The new solution will aim to fix all bugs, add more Fixtures to catch all possible bugs and to make the code more reable and easy to maintain. 

To make the Code much more readable split the regex:
```
$css_pattern = apply_filters(
			'rocket_async_css_regex_pattern',
			'/(?=<link[^>]*\s(rel\s*=\s*[\'"]stylesheet["\']))<link[^>]*\shref\s*=\s*[\'"]([^\'"]+)[\'"]\s*(type\s*=\s*[\'"].*[\'"])\s*(media\s*=\s*[\'"].*[\'"])(.*)>/iU'
```
https://github.com/wp-media/wp-rocket/pull/2786/commits/9a08efc63709345d9b4384173e3cd613af52dfe5#diff-535a87e3b5fde41fbdf9a1c973c438fa47eab64b24a4616d46418c3784a136c5R597

1. Capture the full link 
2. From the full link create regex to match the :`media`, `onload`, `as` and `type`
3. Mix and match the found link attributes to implement the new `media="print" onload="this.media='all'"` solution.
4. Add new fixtures to the code and make sure that if onload there are already other implemented solution will be preserved and add only this.media="all' at the end of it.


#### inc/Engine/CriticalPath/CriticalCSSSubscriber.php
- Remove the `insert_load_css()` method, as it's no longer needed with the new technique
- Update the `async_css()` method, to use the new `media="print"` technique instead of the preload one. Also do some refactoring in it, as it's currently too complex
- Write tests for `async_css()`

### Estimate the effort ✅ 
Effort `[M]`, will need time to refactor & write tests and due to code complexity we shall provide extra time to make sure that we covered all cases.

**Comment by piotrbak** [comment]
RUCSS is currently recommended option.
