### ISSUE TITLE
Exclude WOW Modal Window file from being deferred. 

### ISSUE THREAD

**Issue by kierantaylorio** [wp-media/wp-rocket#2662]
**Before submitting an issue please check that you’ve completed the following steps:**
✔ Made sure you’re on the latest version
✔ Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

The modal from WOW Modal Window & WOW Modal Window Pro will not load when Load JavaScript deferred is enabled.

**To Reproduce**

Steps to reproduce the behaviour:
1. Create any modal in WOW Modal Window
2. Enable Load JavaScript deferred in WP Rocket
3. Reload the homepage/check console

**Expected behaviour**

The modal window should load immediately

**Additional context**
Excluding these two files for the free/pro version allows the modal to load as expected.

Free:
/wp-content/plugins/modal-window/public/assets/js/jquery.modalWindow.min.js

Pro:
/wp-content/plugins/wow-modal-windows-pro/public/assets/js/jquery.modalWindow.min.js 

I have confirmed this on Mega and the following customer site: https://secure.helpscout.net/conversation/1163867445/164971

Plugin: https://wordpress.org/plugins/modal-window/

**Comment by GeekPress** [comment]
@piotrbak @vmanthos Can one of you make a test with the exclusion from the code, and then make a PR?

**Comment by vmanthos** [comment]
@wp-media/dev 

I was able to reproduce this for the free version of the plugin.

The issue occurs when: 
* JavaScript minification/combination is disabled **AND**
* JavaScript deferring is enabled.

Should we:

1. Add the exclusions here:
https://github.com/wp-media/wp-rocket/blob/f2409313a6179a22da50fc46296df89ad7ee9c19/inc/functions/options.php#L413-L423

or 

2. Create a separate 3rd-party compatibility file?

Since excluding the file from deferring won't take place when JavaScript combination is enabled, it could be simpler to go with the first one.

**Comment by GeekPress** [comment]
@hellofromtonya I guess you can help @vmanthos 👆

**Comment by piotrbak** [comment]
Looks like the problem is solved with the newest versions of the plugins.
