### ISSUE TITLE
Missing trim in Image::addLazyloadClass

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/wp-rocket#2705]
In `Image::addLazyloadClass`, we need to trim the value of the `classes` key in the matches, to make sure it works when `class=" "`

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
https://github.com/wp-media/rocket-lazyload-common/blob/fde493535ca389882484327af32c99c839d2527f/src/Image.php#L92

**Scope a solution** ✅ 
Check if trimmed $class['classes'] is empty in order to add the `class="rocket-lazyload"`
Something like should do the trick:
```
$classes = trim( $class['classes'] );
 if (empty($classes)) {
```

**Effort** ✅ 
Effort `[S]`

**Comment by crystinutzaa** [comment]
This is fixed in lazyload-common under this PR: https://github.com/wp-media/rocket-lazyload-common/pull/75
