### ISSUE TITLE
Replacing YouTube video with image targets wrong iframe

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2707]
Customer is using the following code to add the YouTube subscribe button:
`<iframe class="big" src="https://www.youtube.com/subscribe_embed?usegapi=1&channel=channel&layout=full&theme=dark&count=default&origin=https://domain.com/"></iframe>`

Our feature is manipulating this markup causing broken layout:
`<div class="rll-youtube-player" data-src="https://www.youtube.com/subscribe_embed" data-id="subscribe_e" data-query="usegapi=1&amp;channel=channel&amp;layout=full&amp;theme=dark&amp;count=default&amp;origin=https://domain.com"></div>`

The solution, for now, is to exclude this iframe from being lazy-loaded:
`data-skip-lazy=""`

Related ticket:
https://secure.helpscout.net/conversation/1093716861/148043?folderId=2415573

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
This is not a youtube video url.

**Scope a solution** ✅ 
A solution is to exclude this from the lazyloaded iframe.
https://github.com/wp-media/rocket-lazyload-common/blob/fde493535ca389882484327af32c99c839d2527f/src/Iframe.php#L92
Add either: `subscribe_embed` or `'https://www.youtube.com/subscribe_embed'` to the excluded patterns.

**Effort** ✅ 
Effort `[S]`
