### ISSUE TITLE
Multiple backgrounds markup issue

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2708]
When [correct markup](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds) for multiple backgrounds is applied, our process is erasing the second background value completely.

Markup:
`<div style="background-image: 
url('http://example.me/wp-content/uploads/2019/08/beach-cliff-clouds-1168742.jpg'), url('http://example.me/wp-content/uploads/2019/08/undraw_responsiveness_irhh.png');">`

After backend processing:
`<div data-bg="url(http://example.me/wp-content/uploads/2019/08/beach-cliff-clouds-1168742.jpg)" 
class="column-image-bg rocket-lazyload" 
style=" , url('http://example.me/wp-content/uploads/2019/08/undraw_responsiveness_irhh.png'); "></div>`

After JavaScript execution:
`<div data-bg="url(http://example.me/wp-content/uploads/2019/08/beach-cliff-clouds-1168742.jpg)" 
class="rocket-lazyload" 
style="background-image: url('http://example.me/wp-content/uploads/2019/08/beach-cliff-clouds-1168742.jpg');" data-was-processed="true"></div>`

I believe we should preserve second images in the style attribute. In the reported case, the customer is using the second field as a fallback to WebP image.
The other option could be catching this kind markup in regex and excluding from the lazy load process.

Checked on our testing environment.

Related ticket:
https://secure.helpscout.net/conversation/933522721/119920?folderId=2415573

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced on local

### Identify the issue ✅ 
Our current implementation of lazyload for background images is not compatible with multiple backgrounds

### Scope a solution ✅ 
The lazyload script we use can lazyload multiple background images, but we will need to change our code to handle that, as the markup is different.

We will need to:
- Check if there is a `background` or `background-image` property, and using `url()`
- If yes, check how many `url()` there is
- If only one, we use the current method
- If more than one, we will use another method, which will need to extract all `url()`, but also `linear-gradient()` from the property, and lazyload them using the `data-bg-multi` attribute.

The `linear-gradient()` need to be extracted too because it's a generated image, and we need to preserve the order of the images to keep the correct display.

### Estimate the effort ✅ 
Effort `[M]`, it will need an important update on the code and more tests

**Comment by iCaspar** [comment]
Another related ticket:
https://secure.helpscout.net/conversation/1360926852/221314

**Comment by Mai-Saad** [comment]
These markups are not LL as well:
```
<span style="height: 900px;width: 700px; background-image: #ccc url('https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/fixtheissue.jpg?span') no-repeat;"></span>
<span style="height: 900px; background: url('https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/fixtheissue.jpg?span') no-repeat;"></span>
<div style="height: 900px; background-image:none; background: bottom right repeat-x blue url(https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/fixtheissue.jpg?div2)"></div>
<span style="background-image: #ccc url('https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/fixtheissue.jpg?span');"></span>
```

**Comment by piotrbak** [comment]
Closing it in favor of https://github.com/wp-media/wp-rocket/issues/3616
