### ISSUE TITLE
Cache of the subsites is erased when purging the main site's cache in the multisite environment

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2746]
**Describe the bug**
It happens in the multisite environment which is based on subdirectories:
`example.com`
`example.com/site1/`
`example.com/site2/`

Calling `rocket_clean_domain` function on the main site `example.com` will pass the whole cache directory to be purged, including the cache of the subsites.

**To Reproduce**
1. On a subdirectory multisite make sure that there are cached files for various sites
2. Log in to the main site
3. Clean the cache from the top menu
4. Confirm that the cache of subsites is also erased

**Expected behavior**
The cache of subsites should be preserved.

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by iCaspar** [comment]
✅ Reproduced.
✅ Cause: `rocket_clean_domain()` does not check/exclude directories associated with the sub-sites.
✅ Scope a solution:
`rocket_clean_domain()` does already check/exclude for language versions, so we can piggy-back on that.
A new function, `get_rocket_multisite_subdirs_to_preserve()` should add subsite dirs to `$dirs_to_preseve`.
Pseudo-code:
```
function get_rocket_multisite_subdirs_to_preserve( $cache_path ) {
    if ( ! is_multisite ) {
        return;
    }
    $multisite_dirs = [];
    foreach ( 1st-level-dir-in-cache-path as $dir ) {
        $subsite_path = <path corresponding to $dir>;
        if ( get_sites( $subsite-path ) {
            $multisite_dirs[] = $dir;
        }
    }
    return $multisite_dirs;
}
```
Then array merge result into `$dirs_to_preserve` on return.

Also, need to add path data to test fixtures for `rocket_clean_domain()`.

✅ Estimated Effort: [S - M]

**Comment by iCaspar** [comment]
Also, in light of the possibility of a new `Cleaner` class, this might become part of a `Multisite` class, which could be passed into the `Cleaner`. (@see https://github.com/wp-media/wp-rocket/issues/2698#issuecomment-654305753)

**Comment by s-a-s-k-i-a** [comment]
Any news here? This is somewhat of an issue when the Multisite environment ist very large.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1651065353/299257

**Comment by mviniciosbarreto** [comment]
Related case: https://secure.helpscout.net/conversation/2434066252/459890?folderId=7546764

**Comment by wordpressfan** [comment]
@Miraeld let's discuss here so the team can collaborate too.

I tried the following code:
```
$urls = array_filter( $urls, function ( $url ) {
    if ( ! $url ) {
        return false;
    }
    $current_site = function_exists( 'get_blog_details' ) ? get_blog_details() : false;
    if ( ! $current_site ) {
        return true;
    }
    return str_starts_with( $url, $current_site->siteurl );
} );
```

instead of this line:
https://github.com/wp-media/wp-rocket/blob/ea5ae60c0b2dd2f9b7cb3ae97c23b4db330ba4f1/inc/functions/files.php#L822

and it does the following:
* If we are on the main site and called the function `rocket_clean_domain`, it will erase everything for all subsites.
* If we are on the subsite and called the mentioned functon, it will erase only this subsite.

If this is exactly what we want to do we have two options here:
1. Use the above code in its mentioned place as is.
2. Use the filter `rocket_clean_domain_urls` with the same code (maybe in our core code, compatibility file for multisite, or helper plugin)

What do u think?

**Comment by Miraeld** [comment]
@wordpressfan , It could be a solution, maybe @piotrbak can confirm to us what's the expected behavior. 
But from what I understood in the first message of the issue: 
> Calling `rocket_clean_domain` function on the main site example.com will pass the whole cache directory to be purged, including the cache of the subsites.
> Expected behavior
> The cache of subsites should be preserved.

From this I understand the opposite. When we purge from the main site, it should preserve the subsites. 
While purging from subsite, it should preserve main and other subsites.

**Comment by piotrbak** [comment]
@Miraeld @wordpressfan The cache of subsites should be preserved when clearing the cache of the main site.

```
If we are on the main site and called the function rocket_clean_domain, it will erase everything for all subsites.
If we are on the subsite and called the mentioned functon, it will erase only this subsite.
```
Isn't this a current behaviour on trunk?

What we need here is:
1. `rocket_clean_domain` called on the `domain.com` will clear only `domain.com` cache. We'll need to preserve `domain.com/site1` directory, but make sure to remove `domain.com/#query-string/index.html`, `domain.com/example-category/post/index.html`, etc.
2. `rocket_clean_domain` called on the `domain.com/site1` will clear only `domain.com/site1` cache. It means that `domain.com/example-category/post/index.html` needs to be preserved. It also means that `domain.com/#query-string/index.html` needs to be preserved.
3. We should not introduce any regressions to handling the `site1.domain.com` type of multisite.

Does it help?

**Comment by danielmt2k** [comment]
Hi,

If you clear the main's site cache, it has sense that the whole network is cleared. It's the same when you update a plugin, it affects the whole network and can be only done on the main's site.

So, I think that when you are on the main site and you clear the cache... it would clear the whole network. 

Or.. if possible, it could be **offered as an option** for the users. A checkbox where you can specify the behavior of the cache clearing on the main site: just wipe the main site / wipe the whole network.

The **problem/bug** here I reported to WP Rocket via ticket was that, after the cache files where deleted from the disk on the subsites (when you clear the cache in the main site), they were not being regenerated because the database is not properly updated.

I recorded a video: https://take.ms/3LFDI

Regards.

**Comment by wordpressfan** [comment]
@danielmt2k Thanks for this amazing explanation.
If the main issue here is the synchronization between the cache table and the filesystem so I believe you could use the following snippet:
```
add_action( 'rocket_after_clean_domain', function() {
    if ( ! is_multisite() ) {
        return;
    }
    $container = apply_filters( 'rocket_container', [] );
    if ( ! $container ) {
        return;
    }
    $preload_subscriber = $container->get( 'preload_subscriber' );
    if ( empty( $preload_subscriber ) ) {
        return;
    }

    $all_sites = get_sites();
    foreach ( $all_sites as $site ) {
        switch_to_blog( $site->blog_id );
        $preload_subscriber->clean_full_cache();
        restore_current_blog();
    }
} );
```

This code will clear the cache table for all sites at once **but be careful because with big number of data this code will consume CPU and memory**

The solution that I can think of is to provide a new filter for this variable:
https://github.com/wp-media/wp-rocket/blob/ea5ae60c0b2dd2f9b7cb3ae97c23b4db330ba4f1/inc/functions/files.php#L830

This variable can provide directories to be preserved so in this case we can add a new callback for this filter to check if this is the main site so preserve the directories of all subsites.

### Pros:
- The synchronization between Cache table and filesystem will be better
- Low CPU usage as we will remove only current site filesystem cache files

### Cons:
- For websites that need to clear the whole network cache they will need to open site by site and click on clear cache.

What do u think @piotrbak

**Comment by Khadreal** [comment]
@wordpressfan will it be too much to add an option for the user to clear all sites cache(maybe out of this scope) and throttle it so it doesn't take affect the cpu and memory too much.

**Comment by wordpressfan** [comment]
> @wordpressfan will it be too much to add an option for the user to clear all sites cache(maybe out of this scope) and throttle it so it doesn't take affect the cpu and memory too much.

I think it's @piotrbak @DahmaniAdame call.
from my point of view, having the solution I provided with this new url in adminbar to clear all sites cache, will help a lot.
but again when the whole sites cache is cleared this will consume the CPU and memory because we remove from filesystem and the database in case preload is enabled, those are my thoughts.

**Comment by piotrbak** [comment]
@DahmaniAdame What do you think? I think we should:
1. Limit the clearing of the cache for only the specific website (if we clear domain.com, domain.com/site1/ won't be cleared)
2. Create and enhancement issue to implement `Clear All Sites Cache` button in the network admin.

**Comment by DahmaniAdame** [comment]
@piotrbak @wordpressfan We can't provide a way to clear the network in full in the UI unless we control the preload-induced workload.

Let's stick with the scope of the current issue, and strictly clear the root site cache, while preserving cache on other websites on the network. 

This is the behavior that most of our users would expect. 

Open a new feature request related to dealing with `Clearing network cache`. At first implemented as a filter, documented on our help center + with proper warning of what it might induce as workload. 

Depending on interest, we can decide afterward if it will make it to the UI or not.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
