### ISSUE TITLE
Load Google Fonts asynchronously

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2772]
**Describe the solution you'd like**
We are missing one enhancement to our Google Fonts optimization feature.

Like it's described on this post, we could load asynchronously the Google Fonts:
https://csswizardry.com/2020/05/the-fastest-google-fonts/

This method is also going to be implemented to load the CSS files when the « Optimize CSS delivery » option is activated:
https://github.com/wp-media/wp-rocket/issues/2658

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
#### inc/Engine/Optimization/GoogleFonts/Combine.php
- Rename the class to `Optimize`, to have it make more sense about what it is doing now
- Add a class alias in `deprecated/3.6.php` for the old name
- Add a new method `preload()` to add a preload link on the page for the Google Fonts link
- Add a new method `async()` to use the `media="print"` solution for asynchronous, non-blocking fetching of the link
- Add a new method `fallback()` to insert a `noscript` fallback in the footer
- Use the 3 above methods in the `optimize()` method to apply everything needed

We'll also have to make sure we don't double apply those optimization when `Optimize CSS Delivery` is enabled at the same time as `Optimize Google Fonts`.

### Estimate the effort ✅ 
Effort `[M]`

**Comment by crystinutzaa** [comment]
Blocking this one due to [DOM Module](https://github.com/wp-media/module-dom)
Exactly as in PR https://github.com/wp-media/wp-rocket/pull/2786 , we need DomDocument to be able to handle easily the link attributes.

**Comment by hellofromtonya** [comment]
In 3.6.2, we added the new strategy for Async CSS with the DOM Module. Google Fonts also get the same async css treatment as any other stylesheet does. PR #2786 added this strategy for all stylesheet links, i.e. `<link rel="stylesheet" href="..."...>`.

For example, the [original Google Fonts link before the Async CSS runs](https://github.com/wp-media/wp-rocket/blob/master/tests/Fixtures/inc/Engine/CriticalPath/content/twentyseventeen.html#L31):

```html
<link rel="stylesheet" id="twentyseventeen-fonts-css" href="https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&amp;subset=latin%2Clatin-ext&amp;display=fallback" media="all">
```

[after Async CSS runs](https://github.com/wp-media/wp-rocket/blob/master/tests/Fixtures/inc/Engine/CriticalPath/content/twentyseventeen-async_css.html#L37-L38):

```html
<link rel="preload" href="https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&amp;subset=latin%2Clatin-ext&amp;display=fallback" as="style">
<link rel="stylesheet" id="twentyseventeen-fonts-css" href="https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&amp;subset=latin%2Clatin-ext&amp;display=fallback" media="print" onload="this.onload=null;this.media='all'">
```

and it adds to the `<noscript>` element too which [you can see here in the test data](https://github.com/wp-media/wp-rocket/blob/master/tests/Fixtures/inc/Engine/CriticalPath/content/twentyseventeen-async_css.html#L431).

**Comment by Tabrisrp** [comment]
Issue is blocked until we get the new system to transform the HTML without the issues we encountered with DOMDocument

**Comment by ScottTravisHartley** [comment]
I want to add to this particular issue. With the introduction of the remove unused CSS feature on the sites that can run it without issue, with very little used CSS it often times makes sense to simply inline all the used CSS. This is what I did on my own site, this does cause a warning to appear though since the optimize CSS delivery option is not checked that the google font CSS file is now render-blocking. This issue seems to hit the nail on the header of what I was going to suggest so didn't want to make a new issue / suggestion for it.

**Comment by GeekPress** [comment]
@Tabrisrp Like we talked about it during our last call, could we implement this by using the current preload system? If so, can this be scheduled for 3.9.1?

**Comment by remyperona** [comment]
Yes, I re-added the grooming tag, and added it to the 3.9.1 milestone

**Comment by remyperona** [comment]
### Scope a solution ✅ 
We can go with an intermediate approach where we're going to re-use the solution we are currently using for Optimize CSS Delivery, with the swap of the `rel` attribute between `stylesheet` and `preload`.

In both `Combine` and `CombineV2` classes, we can update the `get_combine_tag()` method to give an output like the following:

```
<link rel="preload" href="$CSS" onload="this.onload=null;this.rel='stylesheet'" />
<noscript><link rel="stylesheet" href="$CSS" /></noscript>
```

We can skip the preload polyfill now, because all the majors browsers support preload in 2021.

Another change we need to make is to remove the check for the number of Google Fonts found on the page. Currently we bailout if the number of fonts is equal to 1, but we do want to optimize this one now, because we are not only combining, we are also adding the `display` parameter, and now the preload.

Finally, we need to update our tests and fixtures to adapt for the above changes.

### Estimate the effort ✅
Still estimate this task to be an `[M]` taking into consideration QA time for exploration and to prepare scenarios

**Comment by mostafa-hisham** [comment]
@Tabrisrp 
I found out that we use this function "get_font_with_display" in both  Combine and CombineV2 classes 
https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/Optimization/GoogleFonts/AbstractGFOptimization.php#L62-L76

if the page has only one google font that adds font display swap 

https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/Optimization/GoogleFonts/Combine.php#L68-L71

https://github.com/wp-media/wp-rocket/blob/50cb2df771c028fce57c95e0d7cd1a2a1dd6bfe8/inc/Engine/Optimization/GoogleFonts/CombineV2.php#L67

can you please confirm if this is the same change you mentioned in the solution or if we should change something else?

> Another change we need to make is to remove the check for the number of Google Fonts found on the page. Currently we bailout if the number of fonts is equal to 1, but we do want to optimize this one now, because we are not only combining, we are also adding the `display` parameter, and now the preload.
