### ISSUE TITLE
Get rid of « Rocket Tester » option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#2773]
**Describe the solution you'd like**
Few months ago, we decided to stop our beta program. As we have a new QA process and a staggered release process, we don't need it anymore.

We can remove the « Rocket Tester » option from the dashboard.

**Additional context**
The « "Rocket Tester" Beta Program » will have to be removed:
https://docs.wp-rocket.me/article/1293-wp-rocket-release-process

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
Remove all code related to Beta program

**Scope a solution** ✅ 
Remove & deprecate all code for Beta program from the following files:
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/views/settings/page.php#L70
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/src/js/global/main.js#L116
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/admin/options.php#L51
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/admin/upgrader.php#L235
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/classes/subscriber/Plugin/class-updater-api-common-subscriber.php#L151
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/Engine/Admin/Settings/Page.php#L255
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/Engine/Admin/Settings/Page.php#L382
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/Engine/Admin/Settings/Settings.php#L212
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/inc/Engine/Preload/PreloadSubscriber.php#L170
https://github.com/wp-media/wp-rocket/blob/3a90928a58218e1d7847ed714fbd2d3852bc3bc9/tests/Fixtures/inc/admin/rocketFirstInstall.php#L70

**Effort** ✅ 
Effort `[S]`

@Tabrisrp & @hellofromtonya if is a removal, do we need tests for all code which is going to be modified?

**Comment by hellofromtonya** [comment]
>if is a removal, do we need tests for all code which is going to be modified?

@crystinutzaa Code being removed, no. Modifications to remaining code, yes.

**Comment by Tabrisrp** [comment]
**To note**:  we need to keep a way for our team to have automatic notification for alpha versions, which is relying on the activation of this option currently.

**Comment by hellofromtonya** [comment]
Note 2: In talking with @GeekPress this morning, we would also modify the staggered pool by removing "beta" opt-ins as criteria. This change would impact our private wp-rocket.me repo though.

**Comment by hellofromtonya** [comment]
>To note: we need to keep a way for our team to have automatic notification for alpha versions, which is relying on the activation of this option currently.

@Tabrisrp How so? Share with us.

**Comment by Tabrisrp** [comment]
To get the alpha version, this option needs to be checked, as it's a condition in the check update endpoint: https://github.com/wp-media/wp-rocket.me/blob/458aaf2c0d6ceb49dbb9615e365f95161d1477f6/check_update.php#L88

If we remove the option, we will also need to change this part of the code on our private repo to make sure the team receives the correct one.

**Comment by GeekPress** [comment]
All teammates will get alpha notification without checking if the website is in beta or not. As their version will be updated to the alpha version, they will automatically receive the update on all their websites.

**Comment by GeekPress** [comment]
> All teammates will get alpha notification without checking if the website is in beta or not. As their version will be updated to the alpha version, they will automatically receive the update on all their websites.

For doing that, we will have to remove the beta check into the check_update.php file

**Comment by webtrainingwheels** [comment]
Why would we take away the ability of customers, who **want** to be early adopters, to do that? 
Even if we don't call it Beta anymore, we still need feedback on the early stages of a release. Now customers have no way to opt-in to getting the new versions sooner.

**Comment by GeekPress** [comment]
With the staggered process and our new QA process, the priority should be avoided. We don’t have a beta version anymore. The version we are deploying is more a RC if we don’t want to say a final or stable, but not a beta anymore.

> Betas should be activated on staging/testing sites, not live production sites.

source: https://docs.wp-rocket.me/article/1293-wp-rocket-release-process

We can’t really control that for our users and we are suggesting to not test on live website. Which isn’t not true anymore with the staggered release. There is no difference from users randomly selected at 20% than 50%, etc...

Before, it’s was more clear as the name of the version was 3.X-betaX. 

> we still need feedback on the early stages of a release.

This is the goal of the staggered release and it's is working well. We release to more users depending to the feedbacks of the previous users who had access to the new version.

The beta process is now totally useless. This is why it's going to be deleted from the plugin too.

**Comment by Tabrisrp** [comment]
@webtrainingwheels I believe we also want to work with people who want to be early adopters, but in a different way. Involve them earlier in the process, like we did with our QA, to get their feedbacks on specific feature early on.

@hellofromtonya am I correct?

**Comment by hellofromtonya** [comment]
@Tabrisrp Yes, you're correct. Both that initiative of early product feedback will be reimagined into something where we get customers and/or 3rd party developers involved and integrated into the process vs. just at the end of it. That's a future vision.
