### ISSUE TITLE
Incorrect text formatting in Rocket Analytics modal window

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2777]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
Formatting is not applied correctly. Please see screenshot. 

**To Reproduce**
- Go to WP Rocket dashboard
- Click on `what info will we collect` 
![image](https://user-images.githubusercontent.com/5751474/84763796-629ebe00-afea-11ea-9937-b66681bbcd32.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/5751474/84763708-43a02c00-afea-11ea-8a39-f6caf209ab93.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
Test is escaped :
https://github.com/wp-media/wp-rocket/blob/c2edfaafb24d7feeb84c08c6edd6b64343cb5674/views/settings/page.php#L94

**Scope a solution** ✅ 
Change that line with this one:
`<p><?php esc_html_e( 'Below is a detailed view of all data WP Rocket will collect ', 'rocket' ); ?><strong><?php esc_html_e( 'if granted permission.', 'rocket' ); ?></strong></p>`

**Effort** ✅ 
XS

**Comment by Presskopp** [comment]
I have another proposal:

`<p><?php printf(__( 'Below is a detailed view of all data WP Rocket will collect %sif granted permission.%s', 'rocket' ), '<strong>', '</strong>' ); ?></p>`

Using this you avoid splitting the string into two, which would make the translation more complicated.

See https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders
