### ISSUE TITLE
Delete files in cache/min when switching themes

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#2842]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the bug**
When a new theme is activated, we do not clear out the old combined and minified files. Since we know that these files are going to change, it's best if we can clear them. 

Video: https://youtu.be/NRPUp6Fr_SU

**To Reproduce**
- Enable CSS and/or JS combination and make sure files are generated in `cache/min`
- Change the theme. Existing files are not deleted. New files are generated.
- Change the theme again. The above will repeat. 

**Expected behavior**
When switching a theme, clear everything in `cache/min` folder. 

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
**Reproduce the issue** ✅ 
Identified the issue on my localhost.

**Identify the root cause** ✅ 
There is no call to `rocket_clean_minify();` on `switch_theme` action.

**Scope a solution** ✅ 
In there I can see 2 different solutions:
1. Create a class AdminSubscriber.php in inc/Engine/Optimization/Minify which will share the common code between CSS and JS optimization. In here the  call to `rocket_clean_minify();` on `switch_theme` action will be added.
2. Use the current class AdminSubscriber from inc/Engine/Optimization/Minify/CSS and add in there the call to `switch_theme` where `rocket_clean_minify( 'css' );` will be called.
Create a new class AdminSubscriber in inc/Engine/Optimization/Minify/JS and add in there the call to `switch_theme` where `rocket_clean_minify( 'js' );` will be called.

**Effort** ✅ 
Effort `[S]` , I think Unit & Integration tests will need almost all the effort

@hellofromtonya , @Tabrisrp , @engahmeds3ed & @iCaspar which solution seems more appropiate in this case? What do you think?

**Comment by Tabrisrp** [comment]
I would go with option 1, I don't really see a need to separate the actions for the different types of files in this case. Switching theme will always create a different set of both CSS & JS files.

**Comment by jazir555** [comment]
You already have a solution, can you please implement it?
