### ISSUE TITLE
Exclude jQuery from combine is not working when WP is in a subfolder

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#2846]
Used latest version

**Describe the bug**
If we have a wordpress site installed in a subfolder: http://example.org/qa/ then exclud jQuery from combine and defer is not working because the regex fails to match the url:
https://github.com/wp-media/wp-rocket/blob/0036b86142cc4083a9192a892cacb4223ddb456c/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L110
https://regex101.com/r/XHUL9t/1

**To Reproduce**
1. http://mega.wp-rocket.me/qa
2. Enable Combin JS, Minify JS, load js deffered & Safe Mode for jQuery (recommended)
3. Clean cache and see that jquery is combined on all pages

**Expected behavior**
JQuery to be excluded from combination.

A solution is to modify the regex to ignore the start of the string comparison like this:
https://regex101.com/r/cpqPkE/1
 
**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Issue reproduce on mega site above

### Identify the root cause ✅ 
This happens because we don't append the base path to the internal jQuery URL anymore when fetching it from `$wp_scripts` in the `JS\AbstractOptimization::get_jquery_urls()` method. Thus, the following RegEx doesn't find the match anymore. This was introduced when fixing #2493

### Scope a solution ✅ 
As we did before PR #2783, we can make sure to get the correct path for the internal jQuery URL with the following code:

```
if ( '' === wp_parse_url( $wp_scripts->registered['jquery-core']->src, PHP_URL_HOST ) ) {
	return wp_parse_url( site_url( $wp_scripts->registered['jquery-core']->src, PHP_URL_PATH ) );
}
```

### Estimate the effort ✅ 
Effort `[XS]`, small change in the above method and in the exisiting tests
