### ISSUE TITLE
Incorrect RegEx exclusion matches on URLs that contain the string "feed"

### ISSUE THREAD

**Issue by JohnTorvik** [wp-media/wp-rocket#2852]
**Before submitting an issue please check that you’ve completed the following steps:**
**WP Rocket version:** 3.6.1
Issue not found on the Github repository.
**Not happening on the previous major version**3.5.5.1

**Describe the bug**
WP Rocket config file applies this RegEx:

$rocket_cache_reject_uri = '/(.+/)?feed/?.+/?|/(?:.+/)?embed/|/(index\.php/)?wp\-json(/.*|$)';

but the URL is excluded from the cache if a customer adds some URL path containing the word "feed" like _domain.com/category/**feed**ing/_

**To Reproduce**
1. Create a category called "feeding"
2. Go to this category page (example: yourdomain.com/category/feeding/)
3. Go to page source and notice that isn't cached.

**Expected behavior**
Only URLs with the string /feed/ on the path should be excluded automatically.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by JohnTorvik** [comment]
Related to https://secure.helpscout.net/conversation/1216659818/178240?folderId=3773397

**Comment by girlie** [comment]
I've got another customer affected by this issue as well: https://secure.helpscout.net/conversation/1316989743/204765/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1324266808/207173?folderId=3864740

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
The pattern used to match feed URLs is not robust enough, and can match unexpectedly

### Scope a solution ✅ 
An updated pattern with some tests URLs to validate: https://regex101.com/r/htcjjq/1

We can update the pattern used in `inc/functions/options.php` to use this one instead.
We will also have to update the configuration file on plugin upgrade, to make sure it's using the updated pattern right away.

### Estimate the effort ✅
Effort `[S]`

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1387196269/228795/

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1394818919/230923?folderId=4130683

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1460572002/249649/

**Comment by DahmaniAdame** [comment]
I tested the new pattern by replacing as suggested: 

`$uris[] = '/(.+/)?' . $wp_rewrite->feed_base . '/?.+/?';`

with 

`$uris[] = '/(?:.+/)?' . $wp_rewrite->feed_base . '(?:/(?:.+/?)?)?$';`

On https://github.com/wp-media/wp-rocket/blob/develop/inc/functions/options.php#L279

The "feed" exclusion is working without affecting other posts or taxonomies with "feed" on their slugs. 

PS.: This will require deactivating and activating WP Rocket in order for the changes to be applied until the fix is released.

**Comment by girlie** [comment]
Related ticket: https://secure.helpscout.net/conversation/1573174507/280207/

**Comment by WordPresseur** [comment]
Related ticket: https://secure.helpscout.net/conversation/1615839743/290984?folderId=1213662

**Comment by alfonso100** [comment]
Using this helper to cache the feeds, has the side effect of allowing the cache of these URLs: 
https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-feed
