### ISSUE TITLE
Optimize CSS Delivery compatibility with inline CSS from themes

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#2861]
Some themes, like Astra and others, insert blocks of inline styles into the HTML. These aren't currently detected by our CPCSS generator and there can end up being FOUC when our CPCSS is applied. We don't have any solution for this besides disabling our option. Is there anything we can do here? Detect the inline CSS from specific themes and remove it, or save ti to a static file, for example?

**Comment by jazir555** [comment]
I *absolutely* have this issue. Didn't realize it was an incompatibility with Astra. As that's one of the most common themes, this should be fixed. I can't use the optimize css delivery feature on my site at all.

Why does it seem like every single major feature of this plugin has some massive bug?

**Comment by GeekPress** [comment]
@webtrainingwheels As the CSS is into an inline tag, and not async, I'm not sure to understand how it could lead to a FOUC.

**Comment by webtrainingwheels** [comment]
@GeekPress this is what Seb told us a long time ago. Here’s a reference 
https://wp-media.slack.com/archives/C08N8J6VC/p1537864602000100

**Comment by GeekPress** [comment]
@webtrainingwheels Thanks, I better understand now why it causes the problem.

We have two solutions to fix the problem:
- Include inline CSS during the Combine CSS process
- Detect inline CSS during the CPCSS generation

The first solution isn't good as we will generate `cache dir size` issues as we have for Combine JS.

The second solution is more trustable, but we have nobody to work on the CPCSS since Sebastien left the company. I noticed that we already have an opened issue there:
https://github.com/wp-media/criticalpath-css-generator/issues/150

I will discuss with Jean-Baptiste to know how / who can work on this enhancement.
