### ISSUE TITLE
Combine Google Fonts causes whitescreen in specific case

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#2962]
**Describe the bug**
When `Combine Google Fonts` feature is enabled with Asset CleanUp `Inline CSS Files` we might experience a white screen. That's because this regex is breaking and returning empty value:
https://github.com/wp-media/wp-rocket/blob/bdcfdca33b5040219bb3a9c5f8d6d3916290a8bb/inc/Engine/Optimization/GoogleFonts/Combine.php#L79

**To Reproduce**
Steps to reproduce the behavior on customer's website:
1. In WP Rocket's settings enable the `Combine Google Fonts` feature
2. In Asset CleanUp settings in the CSS section enable `Inline CSS Files` 
3. Open Woo product's category (in this specific case)

**Expected behavior**
`Combine Google Fonts` working fine with `Inline CSS Files` feature.

**Additional context**
The amount of added CSS is pretty huge, however, I wasn't able to reproduce it on our Mega even with more CSS added. I've tested it with regex101 and it also broke the tool due to the amount of code:
https://regex101.com/r/dtxzF7/1/

We'll need to improve our regex here, I've already talked with @Tabrisrp about that.

Related ticket:
https://secure.helpscout.net/conversation/1232413326/181791?folderId=2415573

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the problem
Can be seen at https://regex101.com/r/dtxzF7/1/

### Identify the root cause
The RegEx used is causing a catastrophic backtracing error, which result in a PHP fatal error and a white screen

### Scope a solution
Replace the RegEx by a simpler one, similar to what is used for combine CSS or critical CSS insertion `<\/title>`

### Estimate the effort
Effort `[XS]` small code update, no tests changes required
