### ISSUE TITLE
WP_CACHE defined multiple times in wp-config.php

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3035]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When in the `wp-config.php` file:
1. there are more than one `<?php` , e.g. as part of an `echo`, _and_ 
2. it's a first-time installation, 

WP Rocket adds the `define( 'WP_CACHE', true ); // Added by WP Rocket` multiple times. That can break the code and lead to an `error 500`. 

**To Reproduce**
1. Deactivate WP Rocket, if it's activated.
2. Remove the `define( 'WP_CACHE', true ); // Added by WP Rocket` line from the `wp-config.php`.
3. Add the following PHP code in the `wp-config.php` file: http://snippi.com/s/ehbw80c.
4. Activate WP Rocket.
5. Check the `wp-config.php` file. The `WP_CACHE` will have been added twice, with the second one breaking the code.

**Expected behavior**
Define the `WP_CACHE` only once, regardless of the number of `<?php`'s in the `wp-config.php`.

**Additional context**
If the constant has been already defined in `wp-config.php` the issue doesn't take place, even when deactivating/activating the plugin.

**Related ticket:** https://secure.helpscout.net/conversation/1266341015/190442/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
We don't limit the number of time the replacement is performed when adding the constant, so if there is multiple occurrences of `<?php` in the file, the constant will be added each time.

### Scope a solution ✅ 
In `Engine/Cache/WPCache::set_wp_cache_constant()`

Since we use `preg_replace()` we can use the limit parameter to only replace the first occurence, and stop after that.

We can assume that the first occurence of `<?php` will be the one we want, as it's the necessary opener for a PHP file.

We can update our fixtures for the corresponding method to validate the change and prevent future regression.

### Estimate the effort ✅
Effort `[XS]`

**Comment by gmmedia** [comment]
Problem still exists
![wpcache](https://github.com/wp-media/wp-rocket/assets/7474702/de9fd318-abb7-4741-9d73-146594c93f18)
