### ISSUE TITLE
Add compatibility with Google XML Sitemap to Preload based on sitemap

### ISSUE THREAD

**Issue by mifrero** [wp-media/wp-rocket#3038]
**Is your feature request related to a problem? Please describe.**
Google XML Sitemap generates the sitemap URL in this way: 
http://example.com/index.php?xml_sitemap=params=. when you add this URL on URL sitemaps in WP Rocket the URL doesn't stored. 

Even if the Preload based on sitemap is enabled won't work, the website will be preloaded but like only the preload option was enabled. 

**Describe the solution you'd like**
Allow these types of URLs to be added and the preload based on these site-maps to work properly.

**Describe alternatives you've considered**
If adding compatibility is not possible, please specify in a note that this type of URL is not supported. 

**Additional context**
To test this: 
- Install Google XML Sitemaps
- Activate the preload based on the site map. 
- Add the URL to the sitemap
Note this plugin has 2+ Million active installations

Ticket: https://secure.helpscout.net/conversation/1266700847/190517?folderId=2952229

**Comment by arunbasillal** [comment]
We will be reworking our entire preload module, so this wouldn't be an issue once that is out. 

However, we do not know yet when that is available. And Google XML sitemaps has 2+ million installs!! So we can think of an interim solution to help our users. 

- We do NOT have to do automatic detection
- Let's have a way to bypass sanitization for this kind of URL's.

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
We use the function `rocket_sanitize_xml()` to perform the sanitization in this field, which checks if the file extension is `xml`. This prevents using different sitemap URL format, like the one specified here.

### Scope a solution ✅ 
We can use a different type of validation, like `esc_url()` to make sure the input are at least an URL.

This also means that we can deprecate `rocket_sanitize_xml()`, because the function is not used anywhere else in the plugin.

We can also move the current code for the sitemap field sanitization out of the `Settings::sanitize_callback()` method, to the `rocket_sanitize_textfield()` function instead, to continue standardization on that part.

### Estimate the effort ✅
Effort `[XS]`

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
