### ISSUE TITLE
3.7 - Combine CSS - issue with @import

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3039]
On the customer's site Combine CSS works fine in 3.6.4
One of the CSS files (Divi/style.css) is loaded via an @import rule. 
In 3.6.4 the @import rules are at the top of the combined CSS file: 
http://snippi.com/s/9uj16a8

When Combine CSS is active in 3.7, the @import rules are found in the file, but they are not at the top: 
https://jmp.sh/we9W52x

The stylesheet is therefore no longer loaded on the site and the layout breaks. 

More details here: https://secure.helpscout.net/conversation/1267311463/190654?folderId=377611#thread-3634042849

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by hellofromtonya** [comment]
Conversation from Slack - by @Tabrisrp 

**Combine CSS before 3.7:**
- Merged all the CSS content before passing it through the minification process
- `@import` was moved correctly to the top of the resulting file by the minification process

**Combine CSS after 3.7:**
- CSS content is minified one by one before being merged together at the end
- `@import` is not moved to the top of the final file because of that

**Why was this changed?**
Minifying each content individually then merging it is more performant, as the minification process using RegEx to remove whitespace and all. It’s faster to go through multiple small strings instead of one big string.

But in the CSS case, it’s important for the minification process to be aware of the full content, to know where to put the `@import` rule(s) if there is any.

**How to fix it?**
Update the code in `CSS/Combine.php` to go back to the previous way, merge all CSS content before passing it through the minification process.

**Comment by sawalwalker** [comment]
nice
