### ISSUE TITLE
Google Tracking Add-on: Host /ecommerce.js & /ec.js locally

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3049]
With the [Google Tracking Add-on](https://docs.wp-rocket.me/article/1103-google-tracking-add-on), we currently target these specific files:
- https://www.google-analytics.com/analytics.js
- https://www.googletagmanager.com/gtag/js

We could also store locally the Ecommerce (ecommerce.js) and Enhanced Ecommerce GA tracker (ec.js):
- https://www.google-analytics.com/plugins/ua/ecommerce.js
- https://www.google-analytics.com/plugins/ua/ec.js

Ref:
- https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce
- https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

Ref ticket: https://secure.helpscout.net/conversation/1262046900/189363?folderId=1213662

**Comment by webtrainingwheels** [comment]
Another related file is linkid.js (Enhanced  Link Attribution): 

- https://www.google-analytics.com/plugins/ua/linkid.js
- https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution

Ref tickets: https://secure.helpscout.net/search/?query=tag%3Alinkid.js

**Comment by arunbasillal** [comment]
Can we ask our users to delay these scripts using our `Delay JS` feature and see if these scripts can be successfully delayed. 

Let me explain the approach:
- The main reason why we locally hosted these files is not for performance gains, but to satisfy testing tools. 
- Google's servers are probably going to be faster than most customer servers. Since these files are shared across websites, it's highly probably that these files are cached in users browser as compared to downloading a locally hosted file. 
- Delaying the JS file will satisfy testing tools and in real practice create noticeable performance gains since they are not loaded until the page is loaded. 
- We could eventually think about retiring our add-ons if this is the case rather than build more into it. Less code for us to maintain and less stuff to break. Everyone wins. 

Looking forward to your thoughts.

**Comment by GeekPress** [comment]
Closing this issue as Google Tracking add-on will be removed started to WP Rocket 3.9
