### ISSUE TITLE
CDN File Exclusions Not Applied When Remove Query Strings Enabled

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#306]
When excluding a file from the CDN, the original URL is required (like with minification), but when Remove Query Strings option is enabled, the busted version is served from the CDN. It's not practical to use the busted version for exclusions, since it will change based on the version number. 

Expected behaviour would be that the original URL is provided and is still excluded when Remove Query Strings option is enabled.

**Comment by Screenfeed** [comment]
Reproduced.
Same issue when files are minified, since the file name becomes something like `style-774dfe9405d282e1b1596a0a7bfd1c34.css`.

**Comment by arunbasillal** [comment]
Was able to reproduce as well: https://wp-media.slack.com/archives/C43T1AYMQ/p1536039545000100

**Comment by arunbasillal** [comment]
From: https://github.com/wp-media/wp-rocket/issues/2043 @webtrainingwheels said:

In one of the patch updates to 3.4 this fix stopped working:
#1878 

Can be reproduced in 3.4.0.5

**Expected behaviour**: file excluded from the CDN is still optimized but served from original domain

**What's happening**: file excluded from the CDN still needs to be excluded from file optimization options as well. In this way it will be served from the original domain but no longer optimized.

Related ticket: https://secure.helpscout.net/conversation/977671542/126377?folderId=377611
Related Slack conversation: https://wp-media.slack.com/archives/CBJ2KQ0MU/p1571184724026400
