### ISSUE TITLE
Delay JavaScript - Pixel Caffeine is breaking

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3088]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When the Pixel Caffeine plugin is used along with the **Delay JavaScript scripts** feature, there is a JavaScript console error:
```
 aepc_extend_args is not defined
```

This is because they are using `fbq( 'init' )` and we automatically delay `fbq(`.

**To Reproduce**
1. Install/Set up the [Pixel Caffeine](https://wordpress.org/plugins/pixel-caffeine/) plugin.
2. Enable **Delay JavaScript scripts**
3. Check the JavaScript console for the error.

**Expected behavior**

There shouldn't be any errors in the JavaScript console.

**Screenshots**
![screenshot](https://i.vgy.me/5Knvu7.jpg)

**Additional context**

Delaying the following script fixes the error:
```
/wp-content/plugins/pixel-caffeine/build/frontend.js
```

**Related Ticket:** https://secure.helpscout.net/conversation/1279175035/193966/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by arunbasillal** [comment]
@GeekPress Shall we change our keyword from `fbq(` to `fbq( 'track'`? OR: 

Since we included `fbq(` to include [Facebook for WooCommerce plugin](https://wordpress.org/plugins/facebook-for-woocommerce/) (right?), we could even  use `wc-facebook-pixel-event-placeholder` as the keyword. It's more descriptive and does the job.

**Comment by webtrainingwheels** [comment]
Related ticket: https://secure.helpscout.net/conversation/1277705875/193437?folderId=377611

**Comment by GeekPress** [comment]
@arunbasillal We can't rely only on `track` event. There are also the `init` and `trackCustom` events. The last one could be used into another inline JS.

I'm not sure to understand what we are going to target with `wc-facebook-pixel-event-placeholder`. I checked on the website, and I didn't find this pattern into an inline JS.

**Comment by arunbasillal** [comment]
@webtrainingwheels Are you suggesting that delaying `/wp-content/plugins/pixel-caffeine/build/frontend.js` in addition to existing `fbq(` fixed this issue? 

@GeekPress 

> I'm not sure to understand what we are going to target with wc-facebook-pixel-event-placeholder. I checked on the website, and I didn't find this pattern into an inline JS.

We added `fbq(` to target this: 
![image](https://user-images.githubusercontent.com/5751474/92960535-69bf5600-f48b-11ea-9f02-47d7f64fefca.png)
(from wp-rocket.me)

So if `fbq(` is conflicting with other plugins, maybe we can select a more specific one.

**Comment by webtrainingwheels** [comment]
@arunbasillal Yes, that's right

This was the pixel code from the site: https://snippi.com/s/xkgz4zv

**Comment by iCaspar** [comment]
### Reproduced Locally
✅ 

### Identify Root Cause
As noted above, `fbq` is delayed. However caffiene script is not delayed and assumes that JS variables defined when `fbq('init') runs are already on the page, causing the undefined error.

### Scope a Solution
Delaying the caffiene script as well stops it from running and thus expecting the variable until the `fbq('init')` can also be run. Add `/wp-content/plugins/pixel-caffeine/build/frontend.js` to the automatically delayed list in
`Engine/Optimization/DelayJS/Admin/Settings.php` @ `private $defaults` should fix.

### Estimate Effort
[XS]
