### ISSUE TITLE
rocket_init_config_dir run on config save

### ISSUE THREAD

**Issue by pcfreak30** [wp-media/wp-rocket#309]
`rocket_init_config_dir` and `rocket_init_cache_dir` should run when saving configs and not just when activating. deleting the config folder prevents wp-rocket from operating correctly.

**Comment by Screenfeed** [comment]
Confirmed for the `wp-rocket-config` folder, not for the `cache` folder.

```php
add_action( 'admin_init', 'rocket_init_cache_dir' );
add_action( 'admin_init', 'rocket_maybe_generate_advanced_cache_file' );
add_action( 'admin_init', 'rocket_maybe_generate_config_files' );
add_action( 'admin_init', 'rocket_maybe_set_wp_cache_define' );
```

Everything is generated on `admin_init`, but the issue here, is that `rocket_maybe_generate_config_files()` doesn't recreate the `wp-rocket-config` folder if it doesn't exist. Then the config files are not created (`fopen()` fails silently in `put_contents()`).
