### ISSUE TITLE
WP Rocket does not cache pages after [Edit: manually] deleting wp-content/cache

### ISSUE THREAD

**Issue by patrick-b-at-work** [wp-media/wp-rocket#3096]
I have to fix it by manually creating wp-content/cache/wp-rocket or (going by memory) going to WP Rocket settings.
Can you add [if dir not exist create dir], please?
I updated to the newest version to test this (3.7.0.1).

**Comment by arunbasillal** [comment]
@patrick-b-at-work Thanks for your feedback. 

Everyone: 

I tested this: https://youtu.be/1GoS3iZmWhM

Notes: 
- `/wp-content/cache` was deleted
- On page reload, `cache/min` was created. Other folders were not.
- On reload of WordPress admin, `cache/min/wp-rocket` and other folders were created. 

We need to make a decision on how to move forward. Deleting `wp-content/cache` folder is a manual action. @Tabrisrp how easy / hard is to create all folders if they are missing?

**Comment by jazir555** [comment]
I also notice that if i delete all the files out of the min folder, the site's styling permanently breaks until I restart the server

**Comment by piotrbak** [comment]
We haven't received any feedback about this for 3 years. Going to close it.

**Comment by patrick-7-7-7** [comment]
This is still broken as ever, but if nobody cares, so be it.

**Comment by jazir555** [comment]
> We haven't received any feedback about this for 3 years. Going to close it.

Please fix this, it is still an issue. I don't see why further feedback is needed considering nothing has changed. Please reopen this issue. This is a big problem for, as on hosting providers that are not VPS hosting, fully restarting the server is impossible.

**Comment by piotrbak** [comment]
@patrick-7-7-7 @jazir5 Thanks for the feedback, could you tell me how to reproduce the situation when `/wp-content/cache/` doesn't exist? Is there any specific scenario or it's about manual deletion of the directory?

**Comment by patrick-7-7-7** [comment]
Give me a few weeks to answer, rather than giving you something half-baked. ^^

**Comment by jazir555** [comment]
> @patrick-7-7-7 @jazir5 Thanks for the feedback, could you tell me how to reproduce the situation when `/wp-content/cache/` doesn't exist? Is there any specific scenario or it's about manual deletion of the directory?

Sure. If you install a file manager plugin or use an ssh client and manually delete the cache files in the cache/wp-rocket/min folder, the files do not regenerate as they should when the first page is loaded. The cache is supposed to auto-regenerate, and fails in this scenario until you fully reboot the server/vps.

This issue is even more of an issue on shared and managed hosting where restarting the server is sometimes not possible. Sometimes the cache needs to be regenerated forcefully/manually whenever wp-rocket fails to delete the cache upon using the clear function, so this is a basically a last resort scenario where the files must be removed in this way.
