### ISSUE TITLE
Exclude our scripts from combine JS and add them after the combined file

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3100]
Exclude our 3 new scripts (browser checker, lazyload-scripts, and preload-links) from the Combine JS feature, but make sure it appears after the combined script in the DOM.

**Comment by piotrbak** [comment]
One of the scripts is not excluded in specific conditions. The `rocket-preload-links-js-extra` is excluded also in the 3.7.0.1 version because of this code:
https://github.com/wp-media/wp-rocket/blob/7e8d54aaf5ad8ddffda404d7011931f1a43f3a53/inc/Engine/Optimization/Minify/JS/Combine.php#L261

It's not excluded by the #3095 PR which is using the 'RocketBrowserCompatibilityChecker' pattern.

It works in most cases, however, it fails when the theme doesn't support HTML5 scripts:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class.wp-scripts.php#L233-L235

The following comment is added then to the script:
/* <![CDATA[ */

The localization exclusion stops working then.

Can be seen here:
https://rocketlabsqa.dev/?nocache

Script:
https://snippi.com/s/3e6pvk4
