### ISSUE TITLE
Detect Page Preload feature in Flatsome and display a notice when Preload Links option is activated

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3101]
**Is your feature request related to a problem? Please describe.**
Flatsome theme has a feature _Page Preload_ similar to our _Preload Links_. There is no notice displayed when _Preload Links_ option in WP Rocket is activated. There is no need to have both of the options activated at the same time.

**Steps to reproduce:**

- enable option Page Preload in Flatsome settings: screenshot: https://jmp.sh/AFA8HYA
- then enable option Preload Links in WP Rocket settings and save the changes.
- no notice will be displayed.

**Describe the solution you'd like**
Automatically detect the option in Flatsome, and show a notice that the option needs to be disabled when Preload Links feature is activated in WP Rocket. Similarly, as we do it for instant.page

Ticket: https://secure.helpscout.net/conversation/1279458884/194103/

**Comment by Tabrisrp** [comment]
Did having both enabled caused any issue for the customer?

I'm asking because if it doesn't, we would have a whole set of compatibility code (detecting Flatsome theme/child theme, detection enabled options, etc) for something that doesn't cause a problem. Adding more compatibility code always have an impact on performance, so we have to make sure the trade-off is worth it/necessary.

@arunbasillal

**Comment by arunbasillal** [comment]
@Tabrisrp Thanks for the feedback. I did a test and it seems that it doesn't matter if both options are enabled - https://youtu.be/yLnEAyLJLI4

I have requested our customer to test the same. Let's see if they report otherwise. Removing this issue from the sprint until we know differently.

**Comment by GeekPress** [comment]
The user didn't get feedback. I'm closing this issue until someone else will report a new problem about it.
