### ISSUE TITLE
Remove Clear Cloudflare cache button from Admin bar

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3112]
**Describe the solution you'd like**

Right now, when you want to clear the cache using WP-Rocket, you have to press the clear cache and the clear Cloudflare cache button. As you have to do both when you make changes, it would be useful to have a clear all caches button.

**Additional context**
From Productboard:
https://wp-media.productboard.com/insights/shared-inbox/notes/9314363

**Comment by vmanthos** [comment]
@GeekPress Clearing Cloudflare's cache should rarely be done from the admin menu.

When the customer doesn't have "cache everything" enabled, which means the HTML files are not cached in Cloudflare, they will only need to clear Cloudflare's cache if, e.g. they replaced an image without changing its name, i.e. they haven't performed cache-busting.

When they have "cache everything" enabled, WP Rocket automatically clears Cloudflare's cache when we are clearing our own:
https://github.com/wp-media/wp-rocket/blob/8f7f67b621e5085ccf6424a08a15ce636e4fbf2f/inc/Addon/Cloudflare/Subscriber.php#L64-L65

So, unless I missed something, clearing Cloudflare's cache whenever our own is cleared, looks like overkill, and could increase requests to Cloudflare.

**Comment by GeekPress** [comment]
@vmanthos Thanks for the info.

If I understand right, the Clear Cloudflare Cache is usless when CF Cache Everything is applied on the website. If so, what about removing the Clear Cloudflare Cache link as our own will trigger the purge of CF cache.

**Comment by arunbasillal** [comment]
@GeekPress afaik, the `Clear Cloudflare cache` is only provided because some users might want to do that to be extra sure. As Vasilis explained, there is no real reason to do it. 

> If so, what about removing the Clear Cloudflare Cache link as our own will trigger the purge of CF cache.

I am all for removing it from the Admin bar. We can simply preserve the one in the Add-on, so that in the rare instances where customers want to do it, they can still do it from WP Rocket without logging into their CF account. 

![image](https://user-images.githubusercontent.com/5751474/93462999-bd56f700-f904-11ea-84e4-de0e1452b88c.png)

**Comment by vmanthos** [comment]
I agree with both of you about the admin bar menu. 

From some tickets I had in the past, I have the feeling it was being "misused", the same way our "Clear cache" and "Regenerate CPCSS" sometimes is.

It is part of a routine, where people will clear our cache, Cloudflare's cache, OPCache, and sometimes also regenerate CPCSS, because they believe that's the "normal" way to do when making changes.

Removing the button will "remedy" this. I'd expect tickets from people asking about this, though.

**Comment by arunbasillal** [comment]
Thanks for the feedback Vasilis!

> I'd expect tickets from people asking about this, though.

We can tackle this to an extend by improving our messaging via https://github.com/wp-media/wp-rocket/issues/2186

**Comment by arunbasillal** [comment]
@GeekPress If you agree to the feedback, we can rename this issue to `Remove Clear Cloudflare cache button from Admin bar` and send it for grooming?

**Comment by GeekPress** [comment]
@arunbasillal Yes you can rename the title.

I have the same concern than @vmanthos. When we will decide to do that, I think we should do #2186 during the same release.

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
In `inc/common/admin-bar.php`, remove the cloudflare related code (line 31, and line 199 to 215)

### Estimate the effort ✅
effort `[XS]`

**Comment by jazir555** [comment]
If you could add a clear all caches button, that would be ideal. It's pretty annoying to have to separately clear the cache and opcache.

**Comment by dwdonline** [comment]
This was a huge mistake to remove this! One of the benefits of this plugin with the add-on was being able to quickly clear the Cloudflare cache - the js and css files. I think you should have consulted more than one of your users. Why not move it to an option if you must remove it, so users can go into the Cloudflare add-on settings and choose to show the menu?

**Comment by julioabarca** [comment]
Yes, removed was a mistake, should be a option in the add-on cloudfare on-off if you want add the button as quick action in the menu bar

**Comment by sammyaxe** [comment]
This is a disaster decision, we are running news website, what happens now, is that for some reason poster image doesn't make into initial cache after publishing the post, I suspect that it's todo with hook order and Yoast SEO premium adding og:image after post is cached. 

There must be an option to force clearing specific url cache on cloudflare after post is saved.
