### ISSUE TITLE
3.7: External CSS Minify exclusions are not working as intended

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3118]
The specs for excluding an external CSS file from minify are: 

>3rd Party: Use either the full URL path or only the domain name, to exclude external CSS. 

However there are some cases where this is not working as expected. 

Samples: 
- https://use.fontawesome.com/releases/v5.14.0/css/all.css
Had to be excluded like this: /releases/v5.14.0/css/all.css

- https://cloud.typography.com/7231672/6270372/css/fonts.css
Had to be excluded like this: /7231672/6270372/css/fonts.css

Seems only to be an issue with Minify, not Combine

Tickets: 
- https://secure.helpscout.net/conversation/1281498132/194658?folderId=3572910
- https://secure.helpscout.net/conversation/1278389385/193723?folderId=2675957

**To Reproduce**
1. Include one of the above URLS in the HTML of a site
2. Enable Minify CSS
3. Try to exclude the file with either the domain or full URL

**Expected behavior**
The files should be excluded using either the domain or full URL

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1310458122/202765?folderId=2135277

I further investigated this.

This is because of the  `preg_match()` we run here:
https://github.com/wp-media/wp-rocket/blob/6c811c18c1739349a51753b07816b7260b1e2c07/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php#L141

If the excluded file is e.g. `cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css`, the `$file_path` is `/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css`, and `preg_match()` returns `0`.

Hence the file is _not_ excluded and is cached locally.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1308669776/202288/

**Comment by iCaspar** [comment]
Can Reproduce [X]

Identified cause: per @vmanthos, the regex fails to identify domain names. [X]

Scope Solution:
- [ ] Add testcases for domain names and full URLs to fixtures for `inc/Engine/Optimization/Minify/CSS/Minify`
- [ ] Make tests pass by adjusting regex for `preg_match()` in `AbsstractCSSOptimization::is_minify_excluded_file()`

Estimated Effort:
[S]
