### ISSUE TITLE
Calling wp_enqueue_scripts more than once can cause some of our inline scripts to be added twice

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#3125]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a 3rd party is re-calling `wp_enqueue_scripts` some of our scripts like lazyload-scripts.js will be enqueued twice, causing a JavaScript error like this:
` RocketLazyLoadScripts class is defined `

The same will happen if the Preload Links feature is enabled. 

For example the [Table of Contents Plus](https://wordpress.org/plugins/table-of-contents-plus/) plugin is calling `wp_enqueue_scripts` under certain circumstances [here](https://github.com/zedzedzed/table-of-contents-plus/blob/master/trunk/toc.php#L277)

**To Reproduce**
1. Enable **Table of Contents Plus**
2. Add a table of contents to the page
3. Enable DelayJS
4. See the console error

**Expected behavior**
Our scrips should be included only once.

**Additional context**
**Related ticket:** 
https://secure.helpscout.net/conversation/1278505927/193773?folderId=2683093

**Slack convo:**
https://wp-media.slack.com/archives/C43T1AYMQ/p1599768257124600

Per Tonya's feedback, we can check and guard our code from this happening.
There are 2 possible ways:
1 - `wp_script_is` [https://developer.wordpress.org/reference/functions/wp_script_is/]
2 - Set a property in the subscriber and check as a guard clause.

The 2nd approach is more performant. Both guard Rocket from 3rd parties doing weird stuff like firing the enqueue event more than once.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
While reproducing, it looks like many different plugins would be affected by that problem:
![image](https://user-images.githubusercontent.com/26767037/94854069-3cc7e880-0424-11eb-8320-5fbef104d30d.png)

**Comment by Tabrisrp** [comment]
### Reproduce the problem
Reproduced with the table of contents plus plugin

### Identify the root cause
`wp_enqueue_scripts` action is called multiple times, which causes our scripts to be enqueued multiple times too, because `wp_add_inline_script()` doesn't have any verification to check if the extra inline is already added.

### Scope a solution
Add a property `is_enqueued` to the subscriber, with a default value of `false`. Once the method callback has been called once, set `is_enqueued` to `true`. In the method, check if the `is_enqueued` property value is `true`, and if yes, bail out early

### Estimate the effort
Effort `[XS]`

**Comment by hellofromtonya** [comment]
@Tabrisrp This ticket is a perfect candidate to take a baby step towards our Tech Support Group being capable to do the fix themselves and contribute to the plugin's codebase. Please schedule a kick-off coaching session with @vmanthos and @alfonso100 to empower them to create the PR themselves.
