### ISSUE TITLE
Delay JS - Add scripts to the default list

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3128]
Dear,

Just a suggestion to include scripts from mailchimp to the list of scripts that can be safely delayed.
I tried on my site, no issue with it.

Thanks

**Comment by arunbasillal** [comment]
Hello @gevcen. Thanks for your contribution. 

Internally we have decided to not expand the current default list except to improve the compatibility for existing keywords. 

The reason is that we need to accomplish two thing before we further improve the feature. 
- Make the UI better so that its easier for users to disable a specific script. Right now the keywords doesn't make much sense to most users. 
- Adding and removing keywords makes the code quite clunky because of the extra upgrade routine that needs to be added each time. We are brainstorming ideas.

So we will save these for a later time. Thanks once again.
