### ISSUE TITLE
"Optimize CSS" provokes strange layout on pageload on Firefox only

### ISSUE THREAD

**Issue by gevcen** [wp-media/wp-rocket#3130]
If you check the video below, you'll notice that **on Firefox only** the "Optimize CSS" is provoking really weird issues
=> this does not occur on Chrome/Edge

I was able to localize the scenario, that is to activate **at the same time** all CSS related features : 
- minify css
- combine css
- optimize css

Once I disable the below setting, the behavior on Firefox returns to normal : 
- combine css

video : https://sgevcen.tinytake.com/tt/NDY0NTE0Ml8xNDcxOTA2OQ
link : https://www.staging159.gevcen.be/

**Comment by ScottTravisHartley** [comment]
This is probably because firefox has still yet to implement preload support but it is coming -> https://www.janbambas.cz/firefox-enables-link-rel-preload-support/

**Comment by GeekPress** [comment]
Hi @gevcen 

As @ScottTravisHartley explained, you should get this issue because Firefox didn't support the preload tag at this time. 

FF is now supporting preload correctly.

I'm closing this issue as it should be fixed. 

Feel free to comment if you still have the problem, we will reopen the issue.
