### ISSUE TITLE
Add time-based trigger for Delay JS

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3160]
**Describe the solution you'd like**
A time-based trigger will help execute delay-locked JS for idle desktop users (to render the layout or display ads), or recover from a failed touch event reporting on mobile.

**Describe alternatives you've considered**
Only enable the time-based trigger on specific scripts. Like ads for example.

**Additional context**
Related ticket - https://secure.helpscout.net/conversation/1290393863/197019/

**Comment by arunbasillal** [comment]
@DahmaniAdame When we originally planned the feature as https://github.com/wp-media/wp-rocket/issues/2581 we considered adding the time delay. Please see the `Technical Specs`. 

However, we decided to go with an infinite delay because the delay had an impact on GTmetrix performance scores. GTmetrix waits for 2 seconds of no network activity. We experimented and found that depending on the website, the delay has to be different and to be on the safe side, the delay has to be really high. So we figured it's best to have an infinite delay. 

> or recover from a failed touch event reporting on mobile.
Wouldn't the the next touch or scroll load the delayed JS?

**Comment by DahmaniAdame** [comment]
> Wouldn't the the next touch or scroll load the delayed JS?

Yes, it should. Unless something is preventing it from triggering. But I guess this will be an edge case.

Thanks for sharing the thread. I get now the logic behind skipping the time-based trigger. 

It doesn't make sense to overcomplicate a feature where flexibility might seem a good thing to have, but might also drag other issues that can be prevented and won't really add to how the feature works or performs on its core. 

Thanks @arunbasillal for the extra information.

**Comment by arunbasillal** [comment]
> It doesn't make sense to overcomplicate a feature where flexibility might seem a good thing to have, but might also drag other issues that can be prevented and won't really add to how the feature works or performs on its core.

We will definitely find ways to improve this feature. The performance gain with this feature is really amazing. What we have now can be considered as a MVP of the feature. 

I will close the issue for now 👍
