### ISSUE TITLE
Add HTTP protocol version to Rocket Analytics

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3168]
**Describe the solution you'd like**
To help us to make some important decisions related to combine options, we will need to know the HTTP protocol version used by ours users.

Having the version like 1.1, 2 and 3 will be enough.

**Comment by Tabrisrp** [comment]
### Scope a solution
Add the HTTP version to the analytics data in `rocket_analytics_data()`. To do so, use the `$_SERVER['SERVER_PROTOCOL']` value, and parse it with the following expression `^http\/(.*)$` to preserve only the number.

### Estimate the effort
Effort `[XS]`

**Comment by gevcen** [comment]
@GeekPress : Is the target to get rid of Combine CSS/JS features?

**Comment by GeekPress** [comment]
@gevcen Yes. Combine JS/CSS doesn't make sense on a HTTP2 website and slow down the loading time.

**Comment by ScottTravisHartley** [comment]
I will add to the discussion that while in theory HTTP 2 makes concatenation pointless the average WordPress website still sees obvious performance gains from merging assets. This is due to the merged file size being smaller due to better compression ratios with Brotli & Gzip. WordPress websites tend to have a lot of redundant code especially in the era where Elementor and similar builders reign supreme. 

As an example, a site I am working on today is built using elementor and doing a quick pass through just with basic wp rocket settings for example. 

Page Speed Insights / Lighthouse (http2)

No File Merging
Mobile Score was a 5 
FCP: 7.6
TTI: 18.5
Speed Index: 11.5 
Blocking Time: 2690ms
LCP: 14.9s
CLS: 0.231

File Size
Script: 34 Requests (461.7KB)
Style: 31 Requests (254KB)

File Merging
Mobile Score Was a 40
FCP: 2.8 Seconds
TTI: 8.1 Seconds
Speed Index: 3.1
Blocking Time: 1500MS
LCP: 7.6 
CLS: 0

File Size
Script 3 (361.8KB) the three files are the merged js, rocket's lazyload script, and jquery (though jquery could also likely be merged I simply don't have time to test it right now)
Style: 2 (235.9KB) (gfonts, and merged stylesheet) 

So, while in practice I have seen it be recommended to avoid merging files I have yet to find an average Wordpress website where even in an HTTP 2 or HTTP 3 environment there were noticeable performance improvements. 

The above test was also conducted with just GZIP and not brotli compression (I add brotli towards the end of the optimization)

**Comment by gevcen** [comment]
On top of what @ScottTravisHartley is saying, as an online business owner, I'd like to show you some analytics from my Cloudflare account with the screenshots below.

**Over the last 24 hours, HTTP/1.1 represents a share of 65%**

![image](https://user-images.githubusercontent.com/51261962/94701697-3b6fc080-033d-11eb-8b85-53ea547492b7.png)

**Over the last 7 days, HTTP/1.1 represents a share of 55%**

![image](https://user-images.githubusercontent.com/51261962/94701730-462a5580-033d-11eb-8e5e-1cec347dd129.png)

**Over the last 30 days, HTTP/1.1 represents a share of 51%**

![image](https://user-images.githubusercontent.com/51261962/94701929-7bcf3e80-033d-11eb-8b16-8a8a63bbdb45.png)

These are only statistics from my own website, but I think it's a biased perspective to take into account ONLY the fact that websites are "supporting" HTTP/2. You should consider the fact that there is still a high percentage of clients still passing through HTTP/1.1, so it may be a bit too premature to argue that combine is slowing down websites and that we should get rid it.

**Comment by arunbasillal** [comment]
Thanks for the feedback @ScottTravisHartley and @gevcen 

Please note that we haven't made any decisions yet and we are simply trying to collect data to make an analysis. Of course, we want to do what is best for our users. 👍

**Comment by GeekPress** [comment]
@gevcen We didn't say we are going to remove Combine options for all users. If we do, it will be only for HTTP2 websites.

As Arun said, there is no decision yet. We want first to get more details of HTTP2 usage on our users base. And sure we will do benchmarks on HTTP2 websites to know the performance with and without Combine options.

**Comment by GeekPress** [comment]
@ScottTravisHartley @gevcen I made some benchmarks too on a couple of HTTP2 websites. I confirm the Combine CSS & JS options don't have any impact on the loading time.

But surprisingly, both are improving Core Web Vitals and then the PageSpeed Insight global grade.

**Comment by gevcen** [comment]
@GeekPress Indeed this is what I'm saying, Core Web Vitals and PageSpeed score **substantially** improve with the Combine CSS/JS, even if the actual speed does not improve.

If you remove this feature, I think you will make us (all users) big headache to try to find alternatives that does the combine along with WP Rocket. I think it would be a really bad move for WP Rocket to remove this.

Google PageSpeed core is really making a big difference with Combine, so if you wish to reduce our scores, then go ahead but personnally this would mean I'd need to install Autoptimize along with WP Rocket to make the combine, which I absolutely do NOT want...
