### ISSUE TITLE
Ignore Query String Parameter Doesn't Work With & Character

### ISSUE THREAD

**Issue by ScottTravisHartley** [wp-media/wp-rocket#3171]
This is a very odd use case so going to provide some context. I have a URL where a query string is passed back to the site for analytics data among other items. I provided an example below

Id=946&Email=example%40example.com&cid=846&vgo_ee=T1Ko6FP0DcScJeH%2Bz40Wg9n5w5clLtqSgaG%2BTmc0hoc%3D

I used the helper plugin and added Id to the exclusion and this part works. If I go to the URL such as example.com/?id=999 or id=996 it is ignored. 

However, when I add an example addon such as the above the &Email... Then the URL is not cached. However, if I try the same URL as the above but instead of & I replace it with any other symbol such as + Id=946+Email=example%40example.com+cid=846+vgo_ee=T1Ko6FP0DcScJeH%2Bz40Wg9n5w5clLtqSgaG%2BTmc0hoc%3D

Then the URL is cached. 

I also tried adding all variables such as EMAIL, CID, and VGO_EE to the ignore list as well and it makes no difference. As soon as the query string includes an & at any point before the end of the URL it no longer gets cached. 
 
IS CACHED: Id=946+Email=example%40example.com+cid=846+vgo_ee=T1Ko6FP0DcScJeH%2Bz40Wg9n5w5clLtqSgaG%2BTmc0hoc%3D

IS CACHED:
Id=946+Email=example%40example.com+cid=846+vgo_ee=T1Ko6FP0DcScJeH%2Bz40Wg9n5w5clLtqSgaG%2BTmc0hoc%3D&

IS NOT CACHED
Id=946+Em&il=example%40exmple.com+cid=846+vgo_ee=T1Ko6FP0DcScJeH%2Bz40Wg9n5w5clLtqSgaG%2BTmc0hoc%3D

and then of course obviously the original URL was not cached. 

Here is the full list of ignored query string parameters I have tried to no avail...

function define_ignored_parameters( array $params ) {
	
	$params['Id'] = 1;
	$params['Email'] = 1;
	$params['cid'] = 1; 
	$params['&'] = 1;  
	$params['vgo_ee'] = 1;          

	return $params;
	
}

Expected Behavior: If I include the beginning of a query string to the ignore parameter list I expect no matter what appears after it the URL should be cached.

**Comment by arunbasillal** [comment]
@ScottTravisHartley Thanks for the detailed report. 

I did some testing. 

If I add `test` to the `Cache Query Strings` section of the `Advanced Tab` of WP Rocket 
![image](https://user-images.githubusercontent.com/5751474/96566084-c57acb80-12e2-11eb-9393-c4794b516ad0.png)

- Then WP Rocket (as expected) creates a different cache file for each value of `test`  
- Creates a different cache file when `&` is present. 

Some examples: 

![image](https://user-images.githubusercontent.com/5751474/96566303-07a40d00-12e3-11eb-8103-e6bc7314890c.png)

However, if `test` is added to the `$rocket_cache_ignored_parameters`, then 

- (as expected) serves the same cache file for all values of `test`. 
- And as you described does not cache additional parameters. 

I think it comes down to a design decision now

@GeekPress Would love your feedback on this please. 

What should be the behavior in your opinion? When a parameter is added to `$rocket_cache_ignored_parameters`, should additional query strings be ignored? Or should the same cache file be served even when there are additional query strings. 

Personally I am thinking that for most use cases, when a user wants the same cache file for all values of a particular query string, then additional query strings can be ignored and same cache can be served regardless of additional query strings.

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.

**Comment by blogtutor** [comment]
@piotrbak We just ran into this issue.  We normally add `test` to the "Cache Additional Query Strings" option, so we can easily fetch a "fresh" version of a page while still applying WP Rocket's optimization.  We also use Cloudflare page caching heavily, so changing the value of the query is essential to seeing a fresh version.

So our process is:

1. Make a change to settings.
2. In an incognito window (so we're logged out), view a page with the `?test=1` parameter.
3. If more settings changes are necessary, increment the query so it's `?test=2` - and so on.

This way we can effectively "bypass" Caching.  I know that `?test=1` will serve the same result once it's cached, but this way we're able to fetch a fresh version.

We just tried to add this programmatically via `$rocket_cache_ignored_parameters` and found the same issue that @ScottTravisHartley  ran into... that it doesn't behave the same way, and suddenly the value of the parameter has no effect.  This defeats the purpose for us.

We have a plugin we install on all our clients' sites, so we were hoping to be able to add this via the filter, rather than always having to add it to the settings in the UI.  

Any other suggestions on how to do this via code?

**Comment by piotrbak** [comment]
Hello @blogtutor your issue doesn't sound like the one mentioned in the initial.

As far as I understand, you should be using `rocket_cache_query_strings` filter:
https://github.com/wp-media/wp-rocket/blob/504c5ae5c26164b96c9047c83da12ed2df140993/inc/functions/options.php#L402
