### ISSUE TITLE
Google Font Preconnect is added even when no requests are made

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#3219]
The Google font preconnect is added in the header even when there are no Google fonts that are requested. For example, websites that host fonts locally don't need this to be added in the header adding extra load times. How to remove it?

**Comment by arunbasillal** [comment]
Hello @MuhammedSwalihct 

Please refer to the `Deactivate` section of this doc - https://docs.wp-rocket.me/article/1312-optimize-google-fonts#deactivate

The helper plugin can be removed once activated since the option is saved in the database.

**Comment by webtrainingwheels** [comment]
@GeekPress I'm re-opening this since we have a related ticket about it: 
https://secure.helpscout.net/conversation/1431566989/241100?folderId=377611
Customer is hosting Google Fonts locally and does not want the unnecessary preconnect added. 
The helper plugin to disable the option has been suggested, but the customer has more than 40 sites they would have to install it on.

**Comment by camilamadronero-zz** [comment]
Related ticket https://secure.helpscout.net/conversation/1433807770/241682?folderId=273766.

**Comment by kisabelle** [comment]
I ran into this issue this week. I do not think that installing a separate plugin is an ideal solution here.

I would very much like the option to disable this from the settings. Automatic detection seems like a good alternative, but perhaps an option to disable it could still be included under Advanced Settings.

Will automatic detection work if the stylesheet is inlined? (For more info on this technique see: [https://johnfraney.ca/posts/2019/12/09/improve-page-speed-google-fonts/](https://johnfraney.ca/posts/2019/12/09/improve-page-speed-google-fonts/))

Regarding the current solution I would also like to note the documentation fails to indicate the following:

> The helper plugin can be removed once activated since the option is saved in the database.

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1434167479/241803/

**Comment by iCaspar** [comment]
Reproduced ✔️ 

**Root Cause**: We are adding the preconnect link to the google fonts api on the `wp_resource_hints` hook whenever the `Optimize Google Fonts` feature is enabled (see [here](https://github.com/wp-media/wp-rocket/blob/7ab0299dd91b7b5e3263b826b02add53cdbeeed8/inc/Engine/Optimization/GoogleFonts/Subscriber.php#L70)), which it is by default on most WP Rocket installations, and the option to disable it has been removed from the UI, making it difficult to access without a helper plugin.

**Solution**
First, we need a new flag property in the `AbstractGFOptomization` that will hold whether the `Combine` classes have actually found/processed any Google Fonts. Those flags would be set in each of the `Combines` at the same time the Logger is called for `No Google Fonts Found`, before returning. The `AbstractGFOptimization` also needs a public getter method to access the flag.

Second, in the `Subscriber::process()` before returning the optimized HTML, we need to check both Combine flags, and if both flags are set, we know that there are not Google Fonts to call. That being the case, we can filter the HTML again to find/remove the `preconnect` link.

Third: Relevant tests need to be updated to check the expectation that preconnect is removed from HTML when Optimizers finish early.

(Note: It may be possible, and easier, to simply check the returned HTML from each optimizer to the original HTML, and if there is no change after either `Combine` we can remove the preconnect. However, comparing BIG strings of HTML twice -- 1x per API -- may not be as performant as a fast flag check.)

**Estimate: [S]**

**Comment by mdrejhon** [comment]
Oh wow, I searched "fonts.gstatic.com" and this bug did not appear. Oh why wasn't that keyword added to this github item (or any replies to this github item) so I didn't have to accidentally duplicate-post #3636, I did search first! 😋

Anyway, crossposting to add useful info
(1. Mentions new PageSpeed feature, and 2. Adds extra keywords that people might use to search to find this item)

___________
___________
___________

My business uses a WP Rocket license on a **custom Wordpress theme we created** by @jorimt to accelerate the Blur Busters website.  

But there's some weirdness going on.  I host all fonts via my CDN (paid CloudFlare) instead of Google because I am using certain fonts that (appears) to be infrequently loaded by our users. There were found situations where there was fewer FOUT issues when we used the combination of CloudFlare+Argo Routing (their 79 terabit/sec backbone!) with certain less-frequently-used used font (Patua One).  

WP Rocket insists on an unnecessary preconnect to fonts.gstatic.com that I cannot disable.

1. Run [PageSpeed test on blurbusters.com](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbeta.blurbusters.com) 

2. Scroll down "Passed Audits", expand the section, and see the unnecessary preconnect (if I haven't fixed it by now with another plugin):

> ![image](https://user-images.githubusercontent.com/59981975/109622264-8b77cc80-7b01-11eb-8316-d0aa730fa2ca.png)

3. I have traced this problem to **hardcoded stuff** in WP Rocket's source code at
 `/wp-rocket/inc/Engine/Optimization/GoogleFonts/Subscriber.php`

```
        public function preconnect( array $urls, $relation_type ) {
                if ( ! $this->is_allowed() ) {
                        return $urls;
                }

                if ( 'preconnect' !== $relation_type ) {
                        return $urls;
                }

                $urls[] = [
                        'href' => 'https://fonts.gstatic.com',
                        1      => 'crossorigin',
                ];

                return $urls;
        }

```

**Expected behavior**
Provide an option to avoid preconnecting to gstatic if I'm not loading fonts from Google's CDN.  I use font preloading and optimizations that eliminates the need for any preconnects.

Anyway, that's my two cents.  Thanks for the great plugin!
