### ISSUE TITLE
Shouldn't Prefetch Same Domain

### ISSUE THREAD

**Issue by MuhammedSwalihct** [wp-media/wp-rocket#3220]
According to this article by Mozilla (https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch)

**"dns-prefetch is only effective for DNS lookups on cross-origin domains, so avoid using it to point to your site or domain. This is because the IP behind your site’s domain will have already been resolved by the time the browser sees the hint."**

But I can see that some of the websites with Wp-rocket have a header to prefetch the same domain which is not a best practice according to the above article. is it something added by WP Rocket? Thoughts?

**Comment by arunbasillal** [comment]
Hello @MuhammedSwalihct 

Is the domain filled in within in the UI? If so that could be the case. 
![image](https://user-images.githubusercontent.com/5751474/96423431-f42b7000-1216-11eb-81a7-7b9ef74d7350.png)

Please use the support channel for questions like these or for issues specific to a website - https://wp-rocket.me/support . Refer to GitHub issues once you have a confirmed bug that can be reproduced, or have a feature request. 

Best regards.
