### ISSUE TITLE
Sanitization on exclude from combination fields prevents from excluding certain scripts

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3232]
**Describe the bug**
When the theme contains space in the directory name, the sanitization of the Exclude JS/CSS Files prevents us from excluding the files:
- `/wp-content/themes/twenty%20sixteen/genericons/genericons.css` becomes `/wp-content/themes/twentysixteen/genericons/genericons.css`
- `/wp-content/themes/twenty sixteen/genericons/genericons.css` doesn't fetch the files
- The only solution is to use the wildcard `/wp-content/themes/twenty(.*)sixteen/genericons/genericons.css`

**To Reproduce**
1. Work on a theme that has a space in the directory name
2. Enable JS and CSS combination
3. Try to exclude the CSS and JS file using either `/twenty%20sixteen/` or `/twenty sixteen/`
4. Confirm that the first one doesn't save correctly and the second one doesn't work in the frontend

**Expected behavior**
Possibility to exclude the files in a correct way

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the problem ✅ 
Reproduced on local installation

### Identify the root cause ✅ 
This is happening because we are using `sanitize_text_field()` to sanitize the input. This function is cleaning up too much in this case, stripping the `%20` encoded char for example.

### Scope a solution ✅ 
We can replace `sanitize_text_field()` by `esc_url_raw()`, since the inputs for these fields are going to be URLs, either relative or absolute. This concerns the functions `rocket_validate_css()` and `rocket_validate_js()`.

### Estimate the effort ✅ 
Effort `[XS]`
