### ISSUE TITLE
Embed post block from WP block editor is not lazy loaded

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#3251]
**Describe the bug**
On the frontend, the embed post block generates an iframe that loads the embedded posts, but when the Lazyload for iframes is enabled, embedded posts are not loaded in the Chrome browser.

Lazy load status for iframe does not change from `data-ll-status="loading"` to `data-ll-status="loaded"`.

On Firefox embedded post iframe is lazy loaded.

**To Reproduce**
1. Create a post using default block editor
2. Add "Embed a WordPress post" block
3. Save the post
4. Open post in incognito Chrome borwser

**Expected behavior**
Embedded post iframe should be lazy-loaded.

**Screenshots**
https://i.imgur.com/Im6SZxE.jpg

**Additional context**
Tickets: 
https://secure.helpscout.net/conversation/1314013093/203820/
https://secure.helpscout.net/conversation/1183701992/170083/
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1603814117045800

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on local test site

### Identify the root cause ✅ 
Root cause is unclear, as there is no errors in the console, and it happens only in Chrome (Safari + Firefox have no issue).

In fact, the iframe is correctly loaded, but what is happening is that the inline style on the iframe is not removed, and that inline style is hidden the iframe itself. On the other browsers, the style is correctly removed.

So it seems to be a weird interaction between the lazyload script and the wp-embed JS, only in Chrome.

### Scope a solution ✅ 
The easiest solution would be to exclude this iframe from lazyload, by adding the `wp-embedded-content` value to the exclusion array.

The iframe would still have the `loading="lazy"` attribute, that is added by WordPress itself, so the native lazyload would kick-in instead of the JS-based from us. Not as efficient, but a good fallback.

Also, the embed feature itself is not that much used, so the impact overall is pretty low.

### Estimate the effort ✅
Effort `[XS]` based on the solution above.

@arunbasillal Would need your feedback on the above, to make sure that's alright in term of product.

**Comment by arunbasillal** [comment]
@Tabrisrp With the new plan to switch to native LazyLoad, the proposed solution will happen as a side effect. 🌟

**Comment by piotrbak** [comment]
Not enough customer feedback here to implement this in the nearest future.
