### ISSUE TITLE
Call to undefined function rocket_clean_post() when updating product variations.

### ISSUE THREAD

**Issue by khag7** [wp-media/wp-rocket#3252]
**Before submitting an issue please check that you’ve completed the following steps:**
This was reported previously as Issue #1933 but that was closed due to no response from the issue submitter.

**Describe the bug**
WP Rocket throws a fatal error when doing updates to product variations via ajax. I installed WP Rocket but do not have it configured (no API key entered yet).

**To Reproduce**
0. Install WP Rocket and WooCommerce, but do NOT enter any API key for WP Rocket, and do not configure it or set it up in any way.
1. Edit a product variation.
2. Observe the response returned is a 500 error.
3. View the fatal error which is logged.

**Expected behavior**
I would expect the variation update to work.

**Screenshots**

**Additional context**
```
Uncaught Error: Call to undefined function WP_Rocket\ThirdParty\Plugins\Ecommerce\rocket_clean_post() in /wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php:134
Stack trace:
#0 /wp-includes/class-wp-hook.php(289): WP_Rocket\ThirdParty\Plugins\Ecommerce\WooCommerceSubscriber->clean_cache_after_woocommerce_save_product_variation(1456)
#1 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(541): do_action('woocommerce_sav...', 1456, 7)
#4 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2126): WC_Meta_Box_Product_Data::save_variations(1107, Object(WP_P in /wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php on line 134
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by khag7** [comment]
Possibly you could change [Plugin.php lines 109-113](https://github.com/wp-media/wp-rocket/blob/e49355167e75f1d3cf51ee65c429b75f3e28682e/inc/Plugin.php#L109):

```
		$this->is_valid_key = rocket_valid_key();

		foreach ( $this->get_subscribers() as $subscriber ) {
			$this->event_manager->add_subscriber( $this->container->get( $subscriber ) );
		}
```

```
		$this->is_valid_key = rocket_valid_key();

		if( $this->is_valid_key ) foreach ( $this->get_subscribers() as $subscriber ) {
			$this->event_manager->add_subscriber( $this->container->get( $subscriber ) );
		}
```

**Comment by Tabrisrp** [comment]
@arunbasillal Having the plugin enabled, but no license validated, seems to be an edge case and unexpected behaviour.

We could fix this specific issue by not requiring a valid key to load the file containing the `rocket_clean_post()` function, it's not a big deal though.

**Comment by arunbasillal** [comment]
@Tabrisrp Couldn't we go the other route and prevent the WooCommerce compatibility file when the license is not validated? I am guessing that file is the source of this issue?

**Comment by crystinutzaa** [comment]
@Tabrisrp and @arunbasillal I think this will open a bigger discussion related to which subscribers need a valid licence and which do not need a valid licence. 
Currently there are a lot of common subscribers which are loaded without the need of a valid licence. I assume this is the issue and I believe that a lot of `Common Subscribers` actually need a valid licence.

For example: CDN, Preload, DelayJS, CriticalCSS, Expired Cache Purge, Partial Preload, DB Optimization, Addons, all third party compatibilities I believe will need a valid licence, right?
Take a look at this function:
https://github.com/wp-media/wp-rocket/blob/7f3d1aedc5d2da7b008d3f128bed7ff04bbed31e/inc/Plugin.php#L224-L280

**Reproduce the problem**
I was able to recreate it on my local

**Identify the root cause**
Woo Commerce subscriber is called even if there is not a valid key.
https://github.com/wp-media/wp-rocket/blob/7f3d1aedc5d2da7b008d3f128bed7ff04bbed31e/inc/Plugin.php#L252

**Scope a solution**
A quick solution only for the WooCommerce subscriber is to move the loading of this subscriber after the validation of the key:
https://github.com/wp-media/wp-rocket/blob/7f3d1aedc5d2da7b008d3f128bed7ff04bbed31e/inc/Plugin.php#L292
However, this opens up a bigger discussion about what code needs to run with and without a licence.

**Estimate the effort**
[XS] - I don't think there are Unit/Integration tests for this method.
@Tabrisrp do you think that we shall add at least some Integrations tests for this method?

**Comment by arunbasillal** [comment]
> However, this opens up a bigger discussion about what code needs to run with and without a licence.

Since there is no urgency to fix the issue at hand, if we are going to fix it, let's do it the right way and make a decision on the bigger discussion that @crystinutzaa pointed out. Thanks Cristina 🙏

**Comment by thd-fox** [comment]
There is an other situation now, that pushes this issue higher again.

My situation is: valid license, but I needed to add the license like below:
```
/*
 * WP Rocket
 */
// Your license KEY.
if ( ! defined( 'WP_ROCKET_KEY' ) ) {
	define( 'WP_ROCKET_KEY', 'XXXXXXXXXXX');
}
// Your email, the one you used for the purchase.
if ( ! defined( 'WP_ROCKET_EMAIL' ) ) {
	define( 'WP_ROCKET_EMAIL', 'XXXXXXXXXXXX' );
}
```

Due to that situation I run into the bug even if I pay and have a valid license.
I can't save variations and this is no acceptable situation for a paying customer.

I worked around with this rewrite:
```
/**
* Clean product cache on variation update
*
* @since 2.9
* @author Remy Perona
*
* @param int $variation_id ID of the variation.
* @return bool
*/
public function clean_cache_after_woocommerce_save_product_variation( $variation_id ) {
    $product_id = wp_get_post_parent_id( $variation_id );

    if ( ! $product_id ) {
	return false;
    }

    if(function_exists('rocket_clean_post')) {
	rocket_clean_post( $product_id );
    }

    return true;
}
```

But I now have no clean cache feature upon product update :(

**Comment by jmslbam** [comment]
I'm came here to post the same situation as @thd-fox 

Paying customer, license is working, so that's not the problem.

To anwser the questions of in #1933

Can you please provide more feedback on the actual steps to take to reproduce this issue?

> Is it when editing a WooCommerce product with variations?
Yes, on the detail edit page.

> Are you using the block editor (aka Gutenberg) or the classic editor?
Still just the Classic editor


Might this be because the hook of the add_ons loaded is to late?

**Comment by piotrbak** [comment]
@thd-fox @jmslbam If the issue is still present, could you reach our Support Team or me directly at piotr[at]wp-media.me and share the access to your website? We'll then investigate the issue and provide the correct context. Will reopen it when done.
