### ISSUE TITLE
LiteSpeed compatibility

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3282]
**Describe the bug**
In our LiteSpeed compatibility, we're looking for the [HTTP_X_LSCACHE](https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L22) server variable, while it seems that the [X_LSCACHE](https://docs.litespeedtech.com/lscache/lscwp/admin/#testing) is the correct one. I also tested the cache purging on one of the hostings and clearing the whole cache worked as expected but the partial purge nor single URL purge doesn't seem to work.

**To Reproduce**
1. Make sure that the LiteSpeed cache is enabled
2. Check the PHP INFO file
3. Confirm that the X-LSCACHE is there while HTTP_X_LSCACHE is not
4. Change the value in our code to X-LSCACHE
5. Visit the homepage in the incognito mode and confirm with the headers that it's cached 
6. Clear the whole cache and confirm with the headers that the cache was purged
7. Visit the single post page and confirm with the headers that it's cached 
8. Update this post in the dashboard and confirm with the headers that the cache of this post wasn't purged

**Expected behavior**
We should be able to detect LiteSpeed cache correctly and clear the whole cache and also single post's cache as expected.

**Additional context**
The above was tested on the Raiola Network hosting, I was able to clear the single post's cache by sending PURGE requests, just like we're doing with Varnish:
https://docs.litespeedtech.com/lscache/basics/#curl-command

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
After further investigation, it looks like the problem with cache clearing of the posts is pretty easy to fix. While performing a single request we're adding a couple of `X-LiteSpeed-Purge` headers. Each next header replaces the previous one and we end up with cleaning only the last URL that was passed to the `rocket_clean_files` function.

The solution would be to set the `replace` parameter to `false` here:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L102

Documentation:
https://www.php.net/manual/en/function.header.php

**Comment by piotrbak** [comment]
@arunbasillal Our compatibility with LiteSpeed needs your attention. In order to enable LiteSpeed caching, we need to put some rules to the `.htaccess`. I checked lots of our tickets, it looks like customers are either staying on WP Rocket but not using the LiteSpeed server cache, or they moved to the LSCache plugin and they're using LiteSpeed server cache. I wasn't able to find a customer using WP Rocket + LiteSpeed server cache.

The LiteSpeed server cache is fully handled by `.htaccess` if we would like to take advantage of it, we'd need to add rules there and also consider things like logged-in cache, exclusions, dynamic cookies, etc.

**Comment by piotrbak** [comment]
On our partner's servers, the LiteSpeed Cache is also recognized with `X-LSCACHE`
![image](https://user-images.githubusercontent.com/26767037/107075014-726d4b80-67e1-11eb-97ef-6b33b444fdb3.png)

**Comment by sandyfzu** [comment]
I have a case related to this issue: https://secure.helpscout.net/conversation/1436626902/242518

I checked and indeed, X_LSCACHE exists but HTTP_X_LSCACHE doesn't.

For testing purposes I changed
if ( ! isset( $_SERVER['HTTP_X_LSCACHE'] ) )
to
( ! isset( $_SERVER['X-LSCACHE'] ) )

Here:
https://github.com/wp-media/wp-rocket/blob/trunk/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L22

And it worked perfectly, LiteSpeed cache is being cleared without issues in my tests.

**Comment by NataliaDrause** [comment]
Likely related: https://secure.helpscout.net/conversation/1454772464/247919/
A2 hosting

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
No but I can see the issue on the code itself, we will need an environment for testing after adjusting that code.

**Identify the root cause**
For the first issue of the sever global variable, yes I can see that on [their documentation](https://docs.litespeedtech.com/lscache/lscwp/admin/#testing) so we need to use the environment variable `X-LSCACHE`

For the second issue, Yes we are sending the header on the first url [here](https://github.com/wp-media/wp-rocket/blob/58b612d1a808917f2abc6e393f061026bdfb3ad7/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L102) and on the next purge it bails out [here](https://github.com/wp-media/wp-rocket/blob/58b612d1a808917f2abc6e393f061026bdfb3ad7/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L82) as headers are already sent for the previous url.

**Scope a solution**
1. Here https://github.com/wp-media/wp-rocket/blob/58b612d1a808917f2abc6e393f061026bdfb3ad7/inc/classes/subscriber/third-party/Hostings/class-litespeed-subscriber.php#L82
change `HTTP_X_LSCACHE` to `X_LSCACHE`

2. Don't user header function and instead use the filter `wp_headers` documented here: https://developer.wordpress.org/reference/hooks/wp_headers/
Then send all urls comma separated

3. Refactor the class code to be under new architecture

4. Add tests (unit+integration)

**Estimate the effort**
[S]

**Comment by vmanthos** [comment]
Related ticket on A2 hosting:
https://secure.helpscout.net/conversation/1511415292/263626

Changing `HTTP_X_LSCACHE` to `X_LSCACHE` allowed caches to be cleared in sync.

**Comment by engahmeds3ed** [comment]
Blocked by #3690 to just add class alias to deprecated 3.9 file not to add conflicts.

**Comment by camilamadronero-zz** [comment]
new potentially related case https://secure.helpscout.net/conversation/1553032649/274338?folderId=2675957

**Comment by alfonso100** [comment]
Another case here: https://secure.helpscout.net/conversation/1563208085/277015?folderId=2683093
