### ISSUE TITLE
RocketCDN - UI enhancement to avoid confusion between Deactivation and Cancelation of RocketCDN

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3286]
**Is your feature request related to a problem? Please describe.**
When they have an issue, very often, RocketCDN customers are cancelling their RocketCDN subscription and then ask help to support, instead of simply deactivating it by unticking the **Activate Content Delivery Network** option. 

Support can’t help them anymore in this case and this leads to a lot of frustration and confusion for customers who have paid a subscription once and don’t understand why they’ll have to re-subscribe and pay again.

**Describe the solution you'd like**
A real **Manage subscription** button on the Dashboard, in front of the RocketCDN info instead of the link into the CDN tab could avoid this confusion for our customers.

**Describe alternatives you've considered**
Adding a pop-up warning that explains clearly the difference between Cancelation and Deactivation and their consequences when clicking on the Manage subscription link at the bottom of the CDN tab .

**Additional context**
Typical ticket where there was an issue with RocketCDN but the customer canceled it instead of deactivate it: https://secure.helpscout.net/conversation/1332991283/210306?folderId=4075513

**Comment by arunbasillal** [comment]
As a first step, shall we try updating the message in the pop-up. (As per this [discussion](https://wp-media.slack.com/archives/G087NJ788/p1610111547032100))

![image](https://user-images.githubusercontent.com/5751474/104763332-b7c2ce00-578b-11eb-9716-99cef32b39c3.png)

After:
> If you decide to unsubscribe, your RocketCDN URL will be deactivated immediately.
You will no longer have access to our high-performance CDN, and you won't benefit from our automatic set-up that boosts your loading time.

If we can add: 
**If you only want to pause RocketCDN** in order to troubleshoot or reach support for help, **just untick the Enable Content Delivery Network option from the CDN tab**.

**Comment by crystinutzaa** [comment]
Please confirm the text and styling are the required one:
https://www.screencast.com/t/bBKMSBD66

PR: https://github.com/wp-media/wp-rocket.me/pull/2213

**Comment by arunbasillal** [comment]
@crystinutzaa Looks good to me. Thank you 💪

**Comment by crystinutzaa** [comment]
@arunbasillal released to live website.
