### ISSUE TITLE
Add Missing Width And Height Attributes On Images - Frontend [2/2]

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#3307]
Sub-task for epic https://github.com/wp-media/wp-rocket/issues/3301

## Frontend

- Move `https://github.com/wp-media/wp-rocket/blob/master/inc/front/images.php` into new structure `/inc/Engine/Media/Images/ImagesSubscriber.php` 
- In case the option `image_dimensions` is enabled it will apply this change.
- The filter 'rocket_specify_image_dimensions' still works and enables the feature even if the UI is disabled. (To use the filter add add_filter( 'rocket_specify_image_dimensions', '__return_true' ); to functions.php)
- Modify the ServiceProvider.php to provide the ImagesSubscriber
- Deprecate `rocket_specify_image_dimensions()`
- Revisit the compatibility with  LayerSlider - https://github.com/wp-media/wp-rocket/blob/3b8b2d7debc83641045f9af82baa08b14e41daed/inc/3rd-party/plugins/slider/layerslider.php#L10-L13
- When the option is enabled, any images with missing “width” and “height” attributes have the appropriate width and height added. 
- Write Unit & Integration tests

**Comment by engahmeds3ed** [comment]
Sharing here my concerns after discussing with @hellofromtonya during the weekend:-

I will use [getimagesize](https://www.php.net/manual/en/function.getimagesize.php) to get image width and height from the image src URL, and I have multiple concerns related to this function and need to validate with u before using it:-

1. for external images, **getimagesize** will try to download the image and then read its contents till reaches the data (headers I think) related to the image info so for large images it will big headache so I read a solution to make custom code to stream the image till reaching the width/height info
**I will use getimagesize as is, will not use this workaround.**

2. for internal images, it would be better to pass the relative/absolute path instead of the url to deal with it locally.
**I have to do that as when we pass image url (even local url) it will deal with it as external and this requires allow_url_fopen ini setting to be On so I will convert the url into absolute path.**

3. WebP files: Support for Google’s WebP format was not added until PHP version 7.1. As a result, the getimagesize function will return a boolean FALSE value if client is using an earlier version than that.
**I added a check if it returned false, skip this image.**

4. Do I need to validate that this is an image before calling this function? as I read the following: getimagesize function does not attempt to validate the format of the image. In the past, I have come across examples that showed how a GIF file containing PHP code was accepted by the function.
**I did a check if the image exists (for internal and external images) and will do the check on mime type now.**

@wp-media/php I built my code based on these assumptions, if you have any concern please check and feed me back.
