### ISSUE TITLE
Too many requests to unknown domains or authorities ?

### ISSUE THREAD

**Issue by prakash4mail** [wp-media/wp-rocket#3378]
Hi Team,

What on the world is this? i also saw some requests to stripe site. Why would you do that ?
is this some scam which most of the folks have never come to know except they see that on WP rocket's home page.

![image](https://user-images.githubusercontent.com/63975693/100803363-0f61e000-3451-11eb-90ba-ff66141e4b83.png)

Regards,
Prakash

**Comment by arunbasillal** [comment]
Hello @prakash4mail 

The request to strip is from the RocketCDN iframe. The requests to wistia are for the videos in the `Tutorials` tab. Nothing sinister here. 

The POST requests do not show up for me. Can you please check if they happen on other pages other than WP Rocket please? Once you do, I will bother a developer for the same.

**Comment by prakash4mail** [comment]
Yes, these all requests only show up in the WP Rocket page only. So then should we assume that if the js that you are **downloading externally**(which is bad)., you should get only json/xml as data on what all videos exists, but loading an executable file on Admin page when the person is with admin rights is a big security Risk. And its all because you guys are loading files dynamically from another server instead of loading data. This is serious buddy, your reputation at risk & millions of blogs at risk who use your product, Trusting you to keep them safe in this era of huge cyber risks.
So it must be priority hotfix release and the second issue of those requests , yes have someone to look at them.

**Comment by Tabrisrp** [comment]
I'm not able to reproduce the `POST` requests either coming from `litix.io`, even on a browser with no adblock.

The external domains loading content on the settings page:
- `wp-rocket.me` for RocketCDN iframe
- `stripe` as part of RocketCDN payment
- `wistia` for the tutorials videos
- `helpscout` for the support beacon

**Comment by arunbasillal** [comment]
Thanks for the confirmation @Tabrisrp I don't have these at my end either. 

@prakash4mail I am wondering if something is up with the version of WP Rocket you are using. Please re-install with a new one from your account to make sure you are using the good version.  

We have no intention to be sinister about things. Our entire source code is public for you and everyone to take a look at. 

Closing this issue since this is not reproducible. Please reach out to us directly via our support channel - https://wp-rocket.me/support so that our tech team can take a look at this issue for you.
