### ISSUE TITLE
Sanitization Delay JS field problem

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3384]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In 3.7.6 we made a change in the sanitization for JS/CSS exclusion fields:
https://github.com/wp-media/wp-rocket/pull/3295

Delay JS is using the same sanitization:
https://github.com/wp-media/wp-rocket/blob/82b99b9b15e9b1144e2e24f06993d05c825fb8a4/inc/functions/formatting.php#L190

It ends up that only `.js` ending files are accepted

**To Reproduce**
1. Update to 3.7.6
2. Enable Delay JS
3. Add a new pattern without the .js ending and save settings
4. Confirm that it's not present after saving settings

**Expected behavior**
List saved correctly

**Additional context**
Change `rocket_validate_js` to the `sanitize_text_field` might be a solution.
https://github.com/wp-media/wp-rocket/blob/82b99b9b15e9b1144e2e24f06993d05c825fb8a4/inc/functions/formatting.php#L190

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
Trying the update on a test site, right after the update the Delay JS `scripts to delay` were the following:

```
a.omappapi.com/app/js/api.min.js
feedbackcompany.com/includes/widgets/feedback-company-widget.min.js
snap.licdn.com/li.lms-analytics/insight.min.js
static.ads-twitter.com/uwt.js
platform.twitter.com/widgets.js
/sdk.js
static.leadpages.net/leadbars/current/embed.js
translate.google.com/translate_a/element.js
xfbml.customerchat.js
smartsuppchat.com/loader.js
pinit.js
/gtm.js
fbevents.js
google-analytics.com/analytics.js
adsbygoogle.js
ft.sdk.min.js
apps.elfsight.com/p/platform.js
livechatinc.com/tracking.js
pixel-caffeine/build/frontend.js
```

I have never modified the default list. So I think it confirms that the update changes the default list even without saving settings.

**Comment by arunbasillal** [comment]
@Tabrisrp @piotrbak @hellofromtonya When we fix this, we also need to restore the default list of keywords for `Delay JS` if users already updated to 3.7.6 (and not do that if they are not updating from 3.7.6). Don't you think? 

If they had custom Delay JS list, and they already updated to 3.7.6 that won't be recoverable, right?

**Comment by hellofromtonya** [comment]
>If they had custom Delay JS list, and they already updated to 3.7.6 that won't be recoverable, right?

Hmm, not sure. @iCaspar thoughts to this question?

**Comment by iCaspar** [comment]
If they had a custom Delay JS list, and it got messed up by 3.7.6, it is indeed unrecoverable.

The question is whether restoring to defaults _automatically_ when updating from 3.7.6 is the best course of action.
Pro: Customers who were using the default list, and had it mess up (as @arunbasillal example above) would have the list automatically restored when updating to a fixed version.
Con: Customers who were using a custom list, then fixed it after it got messed up, will experience it being "broken" a second time when it is automatically reset to default -- because they don't want the default.

On balance, the more I've been thinking on it, it may be better to _not_ do the automatically applied fix - because affected customers who want the default list can use the 'Reset' button for the list to restore the defaults.
