### ISSUE TITLE
Set a customer as non-grandfathered is date_created = 0

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3388]
**Describe the bug**
For an unknown reason, some of our customers have the date_created set to 0 in Redis. Each time we noticed the issue, it was from non-grandfathered customers.

The problem is they will get the wrong renewal offer from the plugin.

**Expected behavior**
If we detect that date_created is equal to 0, we need to consider the customer as a non-grandfather customer.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Issue reproduced on multiple cases

### Identify the root cause ✅ 
In `Engine/License/User::get_creation_date()`, we return `0` if the `date_created` is not set. We also don't check for a specific value if the property is set, so when the value is `0` we just return it currently.

### Scope a solution ✅ 
Instead of returning `0`, we can return the current value of `time()` whenever:
- the property is not set
- the value returned by the API is `0`

### Estimate the effort ✅
effort `[XS]`
