### ISSUE TITLE
Uncaught TypeError in the wpr-cpcss.js, in case where CPCSS buttons are not displayed on some post types

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#3395]
**Describe the bug**
On some custom post types, such as Layout Builder in Avada theme, on the edit screen, the sidebar is not displayed/loaded. If the Optimize CSS delivery is enabled, on those custom post types that will cause the following error in the browser console: Uncaught TypeError: Cannot read property 'addEventListener' of null.

**To Reproduce**
1. Enable Optimize CSS delivery in WP Rocket
2. Go to Avada → Plugins / Add-ons → and enable Fusion Builder
3. Go to Avada → Layouts → Global Layout → Add a new section
4. Edit previously created section → open Developer tools and check the Console tab

**Expected behavior**
There should be no error in the browser console.

**Screenshots**
[https://i.imgur.com/mi5SVmM.jpeg](https://i.imgur.com/mi5SVmM.jpeg)

**Additional context**
Ticket: [https://secure.helpscout.net/conversation/1356827349/219899?folderId=3572910](https://secure.helpscout.net/conversation/1356827349/219899?folderId=3572910)

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Issue reproduced

### Identify the root cause ✅ 
The issue is happening because the selectors for the `addEventListener` function don't exist when the sidebar is not displayed.

### Scope a solution ✅ 
in `wpr-cpcss.js`, we should be checking if the variables `rocketDeleteCPCSSbtn` and `rocketGenerateCPCSSbtn` are not `null` before trying to use them with `addEventListener`.

This can be done with conditional check wrappers. 

### Estimate the effort ✅
Effort `[XS]`

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1406513140/234288?folderId=377611

**Comment by piotrbak** [comment]
Just a note, as we talked on a standup. Maybe there's a way to prevent this file from being loaded at all 🤔

**Comment by webtrainingwheels** [comment]
Just an update on [this ticket](https://secure.helpscout.net/conversation/1406513140/234288?folderId=377611) that I posted above. In this case the error was affecting the front end display of the site because the customer is using a plugin to serve /wp-admin/post.php and wp-admin/edit.php pages in the frontend in an iFrame.

**Comment by camilamadronero-zz** [comment]
New case https://secure.helpscout.net/conversation/1713946495/311979/
