### ISSUE TITLE
Compatibility with ClusterCS

### ISSUE THREAD

**Issue by jazir5** [wp-media/wp-rocket#3407]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
![error](https://user-images.githubusercontent.com/31750063/102005056-c3bdfa80-3cca-11eb-8fef-d64fcc736a89.PNG)

Minified files are 404'ing. I've already cleared all the caches, including server level caches such as varnish or redis. The 404 errors remain. In addition, I receive this error: "Refused to apply style from 'https://www.placeholder.com/wp-content/cache/min/1/fdd8a433cc10801a9edac3df98ba6074.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

**To Reproduce**
Install wordpress on a ClusterCS managed server. Enable WP-rocket. Enable minification and concentation for css and js files. Generate the cache. Then clear the cache and visit the front end, you will receive 404 errors for the cleared cache files.

**Expected behavior**
The cache to clear normally, and no 404 or mime type errors on the page after cache clear.

**Additional context**
ClusterCS is a 3rd party management console for VPS server providers. It automatically logs in to a VPS server via SSH credentials and completely configures a VPS to be wordpress ready and compatible. I've already checked for issues such as permissions, and I have ensured all wordpress directories and files have the correct permission set.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@jazir5 The 404 on the assets is usually because of a layer of cache that caches the HTML. When this happens, the old HTML will refer to expired versions of combined CSS or JS files and that causes a 404. Since you confirm that all caches were cleared, I am not sure how it's possible. 

Could you please open a support ticket so that our team can investigate? Please do so here: https://wp-rocket.me/support

That will be faster and we could figure out if it's specific to your website or something to do with hosting.

**Comment by jazir5** [comment]
> @jazir5 The 404 on the assets is usually because of a layer of cache that caches the HTML. When this happens, the old HTML will refer to expired versions of combined CSS or JS files and that causes a 404. Since you confirm that all caches were cleared, I am not sure how it's possible.
> 
> Could you please open a support ticket so that our team can investigate? Please do so here: https://wp-rocket.me/support
> 
> That will be faster and we could figure out if it's specific to your website or something to do with hosting.

This is an issue with varnish caching on clustercs.com. I have resolved the issue by following Cloudways guide for solving the minification issue, linked here: https://support.cloudways.com/how-to-configure-wp-rocket-plugin-wordpress/

They add a url exclusion for "(.*)/?f=(.*)". Clustercs has more granular permissions for varnish, and considers this instead a query string exclusion. Could you please reach out to the clustercs team to automate this?

**Comment by jazir5** [comment]
I also submitted a ticket to them and asked them to reach out to automate this. Hope that helps. Shouldn't be a hard fix.

**Comment by jazir555** [comment]
Ok, so I think I may have potentially narrowed down a second issue. I had apache, nginx and varnish enabled in clustercs. ClusterCS allows you to choose the primary webserver you want to serve with, mine was set to apache. So nginx shouldn't even be involved afaik.

Clearing redis, varnish, opcache, browser cache, wp-rocket cache did not fix the broken page layout. Before clearing varnish cache was what worked. The varnish fix which worked previously(query string exclusion of (.)/?f=(.))

It turned out to be the nginx cache which was caching files even though it was not supposed to. The clear cache rule on ClusterCS only had varnish ticked. 

My solution to the new cache clear/404 issue was to disable nginx entirely. 

Does WP-Rocket clear both nginx and varnish caches at the same time if both are active? It may be because it's only clearing varnish and not nginx if they are both active.

This seems to be both a varnish and nginx issue, the solution here would be to clear both the varnish and nginx clustercs caches at the same time, as they are both enabled by default on clustercs.

So there are 2 fixes needed to be implemented:

• Clearing nginx and varnish caches at the same time if they are both active. Also adding a URL exclusion for "(.)/?f=(.)" for nginx cache by default, not just varnish.

(from earlier in the thread) 

•An issue with varnish caching on clustercs.com. I have resolved the issue by following Cloudways guide for solving the minification issue, linked here: https://support.cloudways.com/how-to-configure-wp-rocket-plugin-wordpress/

They add a url exclusion for "(.)/?f=(.)". There are supposed to be a asterisk next to the periods, but they aren't appearing. Clustercs has more granular permissions for varnish, and considers this instead a query string exclusion.

**Comment by GeekPress** [comment]
> Does WP-Rocket clear both nginx and varnish caches at the same time if both are active? It may be because it's only clearing varnish and not nginx if they are both active.

But why using two web server caching layers at the same?

**Comment by jazir555** [comment]
It was not intentional, nginx *should* have been disabled, but was not. I'm
not sure how it happened, but clearing the nginx cache worked for me.
