### ISSUE TITLE
WP Rocket delete entire preloaded cache while browsing Woocommerce product page

### ISSUE THREAD

**Issue by psyray** [wp-media/wp-rocket#3410]
**Describe the bug**
WP Rocket delete entire preloaded cache while browsing Woocommerce product page

**To Reproduce**
1. Generate preload cache form Wordpress WP Rocket admin
2. Look into the `wp-content/cache/wp-rocket/www.mysite.com`, preloaded page are present,
3. Browse to a Woocommerce page
4. Look into the `wp-content/cache/wp-rocket/www.mysite.com`, preloaded page has been deleted and only a product folder is present,

**Result** 
Preload pages are constantly regenerated, resulting in a high load for the server, et high latency to display pages.
So the only way is to deactivate page preloading or WP Rocket
Without WP Rocket site is faster.

**Expected behavior**
Preloaded pages must not be deleted until the cache expires

**Additional context**
- PHP 7.4
- Nginx 1.10.3 with [WP Rocket rules](https://github.com/SatelliteWP/rocket-nginx)
- Wordpress 5.6
- WP Rocket 3.7.6.1

**Comment by arunbasillal** [comment]
Hello @psyray 

I tried to replicate the same based on your instructions and couldn't. I did the test on WP Rocket 3.8 and Apache, those were the only differences. PHP was 7.4.1 though. 

This is definitely not the intended design and something is off. But it must be specific to your configuration and will need some investigation from our tech team. 

Please open a ticket using our support page - https://wp-rocket.me/support
This way we will have more information about your website to investigate. You can simply link to this GitHub issue for the content. 

Going to close this here since it's not a global issue.
