### ISSUE TITLE
Ability to inject critical CSS programatically

### ISSUE THREAD

**Issue by hogash** [wp-media/wp-rocket#3419]
**Is your feature request related to a problem? Please describe.**
Hey guys! Sometimes the generated critical CSS is not pulling some css, and there's still a layout shift.

**Describe the solution you'd like**
I would like to be able to filter the critical CSS or inject some custom styling. Unfortunately i haven't found any filter that would do this. I mean i found `rocket_critical_css_generation_process_complete` action but i'm not sure how much it would help me.

Thanks!
Marius

**Comment by arunbasillal** [comment]
Hello @hogash 

One immediate solution is to hook on `rocket_critical_css_generation_process_complete` action and write the custom CSS to the CSS files generated in `/wp-content/cache/critical-css/1` folder. This is the folder where Critical CSS is saved. Then clear the cache of course. 

We are working on phasing out CPCSS with something better. So adding a filter right now wouldn't make sense at the moment. 

I hope that helps.

**Comment by vmanthos** [comment]
Although this was tagged as `wontfix`, there are a couple of cases where having such a filter would be useful.

In both cases, translation plugins were used with different domains per language, e.g. example.com, example.de.

Since CPCSS is generated using the latest post of each post type or taxonomy, it can be that the CPCSS generator receives the following:
* https://example.com/this-is-a-post/
* https://example.de/this-is-a-product/

The CPCSS generated can contain URLs, e.g. of fonts, pointing to both example.com, and example.de.

This can cause `CORS` issues.

For the ticket I worked on, I created a helper plugin to rewrite the TLDs to the CDN the customer was using:
https://secure.helpscout.net/conversation/1449026564/245988?folderId=273766#thread-4210592533

This can be customized to rewrite to the correct TLD if a CDN is not used.

The change was applied to the `rocket_buffer`, and it could, in other cases, have unwanted effects.
It would be great if that could be applied only to the CPCSS.
 
**Related tickets:**
https://secure.helpscout.net/conversation/1449026564/245988
https://secure.helpscout.net/conversation/1430919998/240969

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1532468157/268917/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1559076163/275840?folderId=3864740

**Comment by alfonso100** [comment]
related: https://secure.helpscout.net/conversation/1603490634/287940/
