### ISSUE TITLE
Elementor - CSS Print method: External file - the whole cache is cleared after saving a post 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3426]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When an Elementor post is saved the whole cache is cleared if Elementor's **CSS Print Method** is set to **External file**, which is the default setting:
![](https://i.vgy.me/dbjNYA.jpg)

In Elementor's `core/base/document.php` they are calling the `save()` method when a post is saved.

That triggers the action `elementor/document/after_save`, which calls WordPress's `add_metadata()`.

The `added_post_meta` action fires:
https://github.com/WordPress/WordPress/blob/670500c73955d42a80de164d883c7601ffa58bae/wp-includes/meta.php#L133

and that in its turn runs `rocket_clean_domain()`:
https://github.com/wp-media/wp-rocket/blob/0c6c60c8246907979bb2075e37c412f5efaeea21/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L48-L49

At the same time, `deleted_post_meta` is fired with the same result.

**To Reproduce**

1. Make sure Elementor's **CSS Print Method** is set to **External file**.
2. Log `rocket_clean_domain()` and/or check the cache folder.
3. Create a post using Elementor.
4. The cache will be cleared.

**Additional context**

Revisit this to see if it's indeed necessary to hook `rocket_clean_domain()` to:
* `added_post_meta`
* `deleted_post_meta`

Kind of related issue: #3327.

**Related ticket:** https://secure.helpscout.net/conversation/1364738701/222493?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
See https://github.com/wp-media/wp-rocket/issues/1516 for why this was added

**Comment by vmanthos** [comment]
Thanks for the reminder, Remy.

I'm wondering if this is the way to go here though. 
I can take a look at Elementor's code or we can reach out to them and see if there is a more appropriate way of doing this.

**Comment by piotrbak** [comment]
While fixing it, we should also consider this one:
https://github.com/wp-media/wp-rocket/issues/3327

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1714525891/312138/

**Comment by NataliaDrause** [comment]
Likely related: https://secure.helpscout.net/conversation/1740316903/316213/

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1754437330/318772/

**Comment by piotrbak** [comment]
@Tabrisrp Do you see any way we can move forward with this problem? 🤔

**Comment by remyperona** [comment]
@piotrbak Since the CSS is updated, we have to clear the minified files, and that results in having to clear the whole cache too, else we would get a 404 on cached pages for the combined CSS file.

It's not ideal, but it's the safest way to make sure there is no errors. Note that it's only for cases where combine CSS is enabled.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
New approach for this: since Elementor CSS files are already minified, we're going to exclude them from minify/combine CSS. It's also going to fix the issue #3327.

This way, we don't have to clear the minify folder anymore, and thus don't have to clear the whole cache.

In the Elementor compatibility class:
- add a new method hooked on `rocket_exclude_css`, that will be excluding Elementor CSS files. The files are located in the uploads directory `elementor/css/`. Add tests for this method.
- Remove the `maybe_clear_cache()` method, as it's no longer needed

### Estimate the effort ✅
Effort `[S]`
