### ISSUE TITLE
Images inside the <picture> tag are not excluded from lazy loading if the <picture> tag is excluded from lazy loading

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#3437]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Images inside the <picture> tag are not excluded from lazy loading if the <picture> tag is excluded from lazy loading. 

**To Reproduce**
1. Add a `<picture class="picture_class">` with a class with a couple of `<img>` inside.
2. Enable lazy loading for images.
3. Exclude "picture_class" from lazy loading.
4. `<img>` are still lazy-loaded.

**Expected behavior**
When the picture tag is excluded, images should be excluded as well. 

**Screenshots**
![Exclusions tested](https://i.vgy.me/6C1zyK.png)
https://i.vgy.me/6C1zyK.png

**Additional context**
Notes from Slack discussion: 

- Excluding picture via class is working correctly
- But the images inside picture are processed twice. So the LazyLoad rewrite happens on it regardless
- ^ This means the images in the picture needs to be excluded separately.
- The goal is to exclude all images mentioned within picture from LazyLoad if a picture is excluded.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
Slack discussion - https://wp-media.slack.com/archives/C08N8J6VC/p1608641227031000
Related ticket - https://secure.helpscout.net/conversation/1372144122/224619 (I had to use our helper plugin to exclude images by width)

**Comment by NataliaDrause** [comment]
Could be useful for this ticket: https://secure.helpscout.net/conversation/1381406721/227275

**Comment by engahmeds3ed** [comment]
# Grooming

**Reproduce the problem**
Yes I can see the issue locally by using the following HTMl snippet
```
<picture class="picture_class">
<img height="386px" width="auto" src="https://wprocket.adame.io/wp-content/uploads/2020/10/52073709-94bb-320f-9d19-4e1628997252-1024x682.jpg">
</picture>
<img height="auto" width="580px" src="https://wprocket.adame.io/wp-content/uploads/2020/10/51bc9ec2-5b4b-3358-9cd9-d21d10968f9f-1024x683.jpg">
<img src="https://wprocket.adame.io/wp-content/uploads/2020/12/rhino-3T8VZWT-1024x683.jpg">
<img class="picture_class" src="https://wprocket.adame.io/wp-content/uploads/2020/10/e080cd85-5c59-3c48-b688-1ebf2f763799-1024x683.jpg">
```

**Identify the root cause**
We lazyload img tags inside picture tag twice as follows:-
1. Dealing with this img tag as standalone image here: https://github.com/wp-media/wp-rocket/blob/cfe483d7f55934bc912c71628d95fe7dce751d85/inc/Dependencies/RocketLazyload/Image.php#L25 
2. As Picture tag here: https://github.com/wp-media/wp-rocket/blob/cfe483d7f55934bc912c71628d95fe7dce751d85/inc/Dependencies/RocketLazyload/Image.php#L277

and in both cases we exclude images by class for example so if picture tag has a class we will exclude this full picture and when excluding img tag with its class name it will be also excluded.
The main problem is on point 1.

**Scope a solution**
We need to exclude pictures from being processed inside lazyloadImages method as follows:-
https://github.com/wp-media/wp-rocket/blob/cfe483d7f55934bc912c71628d95fe7dce751d85/inc/Dependencies/RocketLazyload/Image.php#L24
duplicate this line and replace `noscript` with `picture`

**Estimate the effort**
effort [XS]
