### ISSUE TITLE
Changelog tab in Plugins updates window has extra spacing

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#3439]
**Describe the bug**
On the _Updates_ page in wp-admin, when you click on the _View version x.x.x details_ link, there is extra spacing before the first heading so the user has to scroll down to see details. The heading that is used is H2, so the following CSS rule is applied and causing this issue:

`
.plugin-install-php h2 {
    clear: both;
}
`

**To Reproduce**
1. Go to _Dashboard → Updates_
2. Click on _View version 3.8.1 details_
3. See an error in the _Changelog_ tab

**Expected behavior**
There should be no extra spacing above the first heading in the Changelog tab. Other plugins use H4 for headings in Changelog, while WP Rocket uses H2.

**Screenshots**
[https://i.imgur.com/jgQkFr2.jpeg](https://i.imgur.com/jgQkFr2.jpeg)

**Additional context**
Support ticket: https://secure.helpscout.net/conversation/1376211148/225867/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Tabrisrp** [comment]
### Reproduce the issue ✅ 
Yes easily reproducible

### Identify the root cause ✅ 
As said, we use `h2` for headings in there. The content of the changelog is pull from our website directly, and on the website it makes sense for the heading structure there.

### Scope a solution ✅ 
Changing all `h2` to `h4` would break the heading structure on the website, so it's a no go.

Ideally, the change would be made at the source: https://github.com/wp-media/wp-rocket.me/blob/6ff59fdf570e538e9ceb34c33ef5305d0b2c963f/plugin_information.php#L33

Doing a quick `str_replace()` to change all occurences of `h2` to `h4` before sending the data over to the plugin.

@wp-media/productrocket See above to validate.

### Estimate the effort ✅
Effort `[XS]`

**Comment by arunbasillal** [comment]
I can't think of a downside for this plan just yet. 

Maybe if we re-design the website later and use `h3` instead of `h2` and this would break again. But that is not happening with the new website I hope. Right @GeekPress ?

**Comment by GeekPress** [comment]
I did the change directly on the website. The Rocket Updater has h3 and the website is replacing h3 with h2.
