### ISSUE TITLE
Increase pricing data transient expiration time to decrease our stats API calls

### ISSUE THREAD

**Issue by engahmeds3ed** [wp-media/wp-rocket#3441]
**Is your feature request related to a problem? Please describe.**
Currently we are saving pricing details for only 6 hours so after that when client opens any admin page, WP Rocket will send a request to our stats pricing API to save them again and this results in flooding our server with not needed requests.

https://github.com/wp-media/wp-rocket/blob/55e722d07a857fea52eed9f186ed93231d23d24e/inc/Engine/License/API/PricingClient.php#L30

**Describe the solution you'd like**
We need to increase this expiration time or only hitting the API on the specific pages that needs those pricing details.

**Comment by arunbasillal** [comment]
For the attention of @GeekPress @Tabrisrp. I believe we set this to 6 hours so that changes to the pricing can reflect for the customer asap. So increasing the time to more than 6 hours might not be ideal. 

I believe this was created in relation to #3440 and Slack conversation - https://wp-media.slack.com/archives/GUT7FLHF1/p1608738969001400

@engahmeds3ed Is it still needed if #3440 is in place?

**Comment by GeekPress** [comment]
@arunbasillal We can increase it to 12 hours if needed. It's better to be a little less accurate during the promo campaign than having our website done.

In fact, we need to change the price only during the promo campaign. We could also imagine relaying on the next promo campaign date. In the Pricing API, we can check when the next promo campaign will be. We can save this date, and then ping our API when it will be really needed at the start date of the promo campaign.

**Comment by Tabrisrp** [comment]
### Scope a solution ✅ 
Increase the transient timeout to 12 hours in the PricingClient class

### Estimate the effort ✅
Effort `[XS]`
