### ISSUE TITLE
KK Star Rating auto-compatibility doesn't work anymore

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3458]
**Describe the bug**
Our auto-compatibility with KK Star Rating doesn't work. It seems the plugin updated its code and the class we are checking doesn't exist and the hook seems different too.

**To Reproduce**
1. Install KK Star Rating
2. Go on a post
3. Vote
4. Refresh the page and you can still vote again. It's because the cache hasn't been cleared. If you vote again you will get an error.

**Expected behavior**
The cache page should be cleared after voting.

** Related ticket **
https://secure.helpscout.net/conversation/1382435865/227533/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by florianguillaumin** [comment]
Hello 👋

I just looked into a similar issue for the [Cache Enabler plugin](https://github.com/keycdn/cache-enabler/pull/306). I am not an user of Wp Rocket.

KK Star Rating is using [`update_post_meta` and `add_post_meta`](https://github.com/kamalkhan/kk-star-ratings/blob/7406eeb4ebcbd3d137e9bed4a41f9ceaa1d63b17/src/functions/post_meta.php#L46L52) to save new ratings. You can hook here.

Otherwise, [the Ajax action is here](https://github.com/kamalkhan/kk-star-ratings/blob/7406eeb4ebcbd3d137e9bed4a41f9ceaa1d63b17/src/core/wp/actions/wp_ajax_kk-star-ratings.php), now named `wp_ajax_kk_star_ratings`.

But I think the step to reproduce here are incomplete: you need to enable the option "Unique votes (based on IP Address)". With this option, if the current IP was already used for rating, the stars will be read-only, you won't be able to click on them.

With this option, another problem is created: if the cached post was made from an already known IP for the ratings, the cached post will have the ratings disabled. And everybody will be served this disabled ratings version.

I did not find a good solution here. I just force kk star to be active (by removing the css class kksr-disabled), and IPs that have already rate the post are making errors on wp-ajax.

**Comment by alfonso100** [comment]
Just had a [case](https://secure.helpscout.net/conversation/2326145064/434930?folderId=273766), the post cache can be cleared using KK Stars Rating action `kksr_vote`. 

The following snippet worked:
https://github.com/wp-media/wp-rocket-snippets/blob/main/wp-rocket/wp-rocket-kk-star-ratings-compatibility.php

**Comment by piotrbak** [comment]
There's not enough feedback from our customers related to this issue. It'll not be implemented anywhere soon.
