### ISSUE TITLE
Force Include CSS Selectors?

### ISSUE THREAD

**Issue by ketoweb** [wp-media/wp-rocket#3468]
Using Critical CSS increases the CLS for a lot of WordPress Themes. The layout shift only happens when critical CSS is enabled. However, this can be fixed if specific CSS Selectors are forced inside critical css.

Can this be added?

**Comment by arunbasillal** [comment]
Hello @ketoweb 

Given our current plans for CPCSS, this is unlikely to be done. However I can suggest you a hack as described here: https://github.com/wp-media/wp-rocket/issues/3419#issuecomment-747241944

Hope that suits your requirement.

**Comment by hogash** [comment]
Hi @arunbasillal 

Any news in regards to the upcoming CPCSS engine? 

Currently with CPCSS enabled, i get these stats https://d.pr/i/Qz81JX while without it i get this https://d.pr/i/7kmMHI . 

I've already developed the script mentioned in #3419 and inject CSS inside those stylesheets, but it's getting too frustrating to keep adding all sorts of styles. Plus, i'm seeing selectors added from the bottom of the page. Shouldn't it just scanned the above the fold screen and grab the critical css? 

Anyway, i know there's a lot of work, but would be really appreciated if the new CPCSS engine is prioritised. Thanks!

PS: Do you happen to know if manual improvements could be made?

**Comment by arunbasillal** [comment]
@GeekPress please note the reply above.

**Comment by hogash** [comment]
Thanks @arunbasillal !

@GeekPress may i ask, what is currently generating the CPCSS? PhantomJS? I'm asking because i can try to research into it, somehow to add hints of some specific styles. 

Also, i'm thinking of building a minimal base of critical css styles i know and want to load as CPCSS. Do you think there's a way to avoid duplication, or it's best to just rely either on WPRocket or my custom styles?

Thanks!

**Comment by GeekPress** [comment]
> Any news in regards to the upcoming CPCSS engine?

No news yet, we need more R&D to understand the root cause of the problem.

> Currently with CPCSS enabled, i get these stats https://d.pr/i/Qz81JX while without it i get this https://d.pr/i/7kmMHI .

@hogash Is it possible to share the URL of the website where you have the problem? If you're comfortable sharing it here, you can contact me on jonathan[at]wp-media.me

> @GeekPress may i ask, what is currently generating the CPCSS? PhantomJS? I'm asking because i can try to research into it, somehow to add hints of some specific styles.

We are using NodeJS.

> Also, i'm thinking of building a minimal base of critical css styles i know and want to load as CPCSS. Do you think there's a way to avoid duplication, or it's best to just rely either on WPRocket or my custom styles?

I think the best will be to improve the CPCSS generated to be more accurate than trying to patch it like that ^^
