### ISSUE TITLE
Install with composer v2 requirements fail

### ISSUE THREAD

**Issue by Alt0car** [wp-media/wp-rocket#3478]
I just trying to install last release of wp-rocket 3.8.2 using composer 2.0.8 and php 7.4
```
  Problem 1
    - woocommerce/woocommerce[3.9.0, ..., 3.9.3] require composer/installers 1.7.0 -> satisfiable by composer/installers[v1.7.0].
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires woocommerce/woocommerce ^3.9 -> satisfiable by woocommerce/woocommerce[3.9.0, 3.9.1, 3.9.2, 3.9.3].
```

This problem was `woocommerce/woocommerce 3.9` in dev requirements.

Updated with `woocommerce/woocommerce 4.8.0` solved this issue

**Comment by remyperona** [comment]
Yes this is something we need to update, but it also requires some updates in our test suite to work correctly with newer versions of WooCommerce.

**Comment by crystinutzaa** [comment]
**Reproduce the problem** ✅ 
Issue reproduced on local testing

**Identify the root cause** ✅ 
We need to upgrade to WooCommerce v3.9.2 (the latest version).
However, upgrading will bring a lot of new errors due to a lot of code modification inside WooCommerce.
Errors will popup at Integration test (Unit tests are running just fine)

**Scope a solution** ✅ 
The solution is to upgrade to WooCommerce v4.9.2
This needs to modify the composer.json file to use this: `"woocommerce/woocommerce": "^4.9.2",`

Next, in Integration/bootstrap.php file we need to manually include some WooCommerce files due to the errors which popup when running WithWoo integration tests.
https://github.com/wp-media/wp-rocket/blob/c88e099454ba5b1e2dba3e6cd46936f0525856ed/tests/Integration/bootstrap.php#L55-L60
We need to add a couple of includes and defines:
`define( 'WC_ABSPATH', WP_ROCKET_PLUGIN_ROOT . '/vendor/woocommerce/woocommerce/' );`
```
// Include the main WooCommerce class.
if ( ! class_exists( 'WooCommerce', false ) ) {
	include_once WP_ROCKET_PLUGIN_ROOT . '/vendor/woocommerce/woocommerce/includes/class-woocommerce.php';
	include_once WP_ROCKET_PLUGIN_ROOT . '/vendor/woocommerce/woocommerce/includes/wc-core-functions.php';
}
```


These 2 changes will make the tests pass, however there will be Warnings in console which needs to be fixed:
```
Warning: file_get_contents(/app/public/wp-content/plugins/wp-rocket/vendor/woocommerce/woocommerce/packages/woocommerce-admin/src/Install.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/wp-rocket/vendor/antecedent/patchwork/src/CodeManipulation.php on line 121

Warning: Use of undefined constant WC_PLUGIN_BASENAME - assumed 'WC_PLUGIN_BASENAME' (this will throw an Error in a future version of PHP) in /app/public/wp-content/plugins/wp-rocket/vendor/woocommerce/woocommerce/includes/class-wc-install.php on line 171

Warning: file_get_contents(/app/public/wp-content/plugins/wp-rocket//vendor/woocommerce/woocommerce/packages/action-scheduler/action-scheduler.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/wp-rocket/vendor/antecedent/patchwork/src/CodeManipulation.php on line 121
````

WooCommerce moved the "modules" inside `packages` folder. However while installing the dependencies, WP Rocket will place those under `woo-commerce/woocommerce-admin` folder and not inside `woo-commerce/packages/woocomerce-admin` folder. We need to find a way to move these folders in the proper location.


**Estimate the effort** 
[S]

**Comment by remyperona** [comment]
This needs to be groomed again, because the provided solution doesn't work with WC 5.0, and it is also not complete.
