### ISSUE TITLE
LiteSpeed mod_pagespeed detection

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3482]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When displaying the mod_pagespeed notice, we should also look for the LiteSpeed extension header:
`X-LS-PageSpeed`

https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:config:enable_pagespeed

**To Reproduce**
1. Enable WP Rocket on LiteSpeed with mod_pagespeed
2. Go to the WP Rocket dashboard
3. No notice is displayed

**Expected behavior**
We should display the notice also for this (most likely rare) environemnt

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `ThirdParty/Plugins/ModPagespeed`, also check for `$headers['X-LS-PageSpeed']` in `has_pagespeed()` method.

Update the related tests to add a test for this change.

The integration test should also be updated, to use the filter `pre_http_request` instead of using Brain Monkey expectation for `wp_remote_get()` and `wp_remote_retrieve_headers()`.

### Estimate the effort ✅
Effort `[XS]`

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
