### ISSUE TITLE
Turn off « Delay JS » option when Safe Mode is activated

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3498]
**Describe the solution you'd like**
When a user tries to deactivate WP Rocket, our Deactivation Intent is displayed.

If the user chooses "The plugin broke my layout or some functionality", he can click on Click "Apply Safe Mode"  to quickly disable LazyLoad, File Optimization, Embeds, and CDN options.

We are missing the Delay JS option from  File Optimization to be turned off.

**Describe alternatives you've considered**
Turn off « Delay JS » when a user clicks on "Apply Safe Mode".

**Comment by crystinutzaa** [comment]
### Reproduce the issue ✅ 
Issue reproduced

### Identify the root cause ✅ 
We need to add `delay_js => 0` in `rocket_safe_mode_reset_options` filter.

### Scope a solution ✅ 
https://github.com/wp-media/wp-rocket/blob/7f3d1aedc5d2da7b008d3f128bed7ff04bbed31e/inc/Engine/Admin/Deactivation/DeactivationIntent.php#L138
Edit this file and add delay_js = 0 to the array of options to be reset when activate safe mode is selected.


### Estimate the effort ✅
Effort `[XS]`
