### ISSUE TITLE
CSS & JS minification don't work when WP_CONTENT_URL contains a relative URL

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3499]
**Describe the bug**
Our minification options don't work when a custom content directory is used with a relative URL. 

It can be configured in wp-config.php like that:
define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/app' );
define( 'WP_CONTENT_URL', '/app' );

To have our minification options working properly, we need to have an absolute URL:
define( 'WP_CONTENT_URL', 'https://mywebsite.com/app' );

**To Reproduce**
1. Define a relative custom URL for WP_CONTENT_URL constant into wp-config.php
2. Turn on our CSS and JS minification options.
3. Check the source code.
4. See error: the files won't be minified

**Expected behavior**
The minification should work whatever the WP_CONTENT_URL dir constant is defined (relative or absolute URL).

**Additionnal context**
https://secure.helpscout.net/conversation/1382399741/227523?folderId=273768

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by crystinutzaa** [comment]
### Reproduce the issue ✅ 
Reproduced on local site.

### Identify the root cause ✅ 
Root cause is the `define` . Wordpress WP_CONTENT_URL should be always an URL, however is not forced or validated.
`define( 'WP_CONTENT_URL', '/wp-content' );`
If this constant is not defined, then Wordpress will set it as:
```
if ( !defined('WP_CONTENT_URL') )
        define( 'WP_CONTENT_URL', get_option('siteurl') . '/wp-content');
```


### Scope a solution ✅ 
A solution is to check in Minify.php if the URL has a host. If there is no host setup, then simply add the host as : 
`get_site_url() . $url;`
This should happen in here:
https://github.com/wp-media/wp-rocket/blob/c9b302823c14481ccf1a6f56919b7fc9b446dd73/inc/Engine/Optimization/Minify/CSS/Minify.php#L128

and the code should be similar to:
```
		if ( empty( $parsed_url['host'] ) ) {
			$wp_host            = wp_parse_url( get_site_url() );
			$parsed_url['host'] = $wp_host['host'];
			$url                = get_site_url() . $url;
		}
```

This happens also in JS Minification, so this should be applied also in JS/Minify.php


### Estimate the effort ✅
Effort `[S]`

@wp-media/php This is a bandaid due to the fact that `WP_CONTENT_URL` should always be a URL.
This will fix this issue, however I am wondering if we should handle it like this.

**Comment by remyperona** [comment]
I think your solution is good considering the problem reported.

@GeekPress Considering that `WP_CONTENT_URL` should always be an absolute URL, and not a relative one, this is an edge case where the user is "doing it wrong" even though it might be working when nothing else is involved.

Do we still want to go ahead with the proposed solution?

**Comment by GeekPress** [comment]
@Tabrisrp If we are sure at 100% the bandaid can't cause any issues, we can go with it. If we have doubts, let's forget the fix.

**Comment by CrochetFeve0251** [comment]
@GeekPress Is this problem still actual? Because I tried to reproduce the issue but the CSS minify normally on my local environnement even if I set WP_CONTENT_URL constant.

**Comment by GeekPress** [comment]
Nobody reported this problem. It seems to be an edge case which happens very rarely. 

I'm closing the issue, as we don't need to fix it, and the workaround is easy on the user side to follow the WordPress standard.

**Comment by johan-las** [comment]
Related ticket: https://secure.helpscout.net/conversation/2855647265/541870?viewId=8127840
