### ISSUE TITLE
Useless scroll displayed in RocketCDN modal when get started first time

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3500]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version -> Version 3.8.2 with fix https://github.com/wp-media/wp-rocket/pull/3487

**Describe the bug**
Useless scroll displayed in RocketCDN modal when get started

**To Reproduce**
1. In incognito: Go to https://rocketlabsqa.dev/wp-admin -> login
2. Click on WP Rocket in header -> Settings -> CDN in side bar
3. click on Get Started Btn
4. Wait & see modal

**Expected behavior**
Modal displayed with no vertical scroll

**Screenshots**
![VerticalScroll](https://user-images.githubusercontent.com/76941962/104883307-42165800-596d-11eb-9ed5-1dc5b79eddcf.png)

**Additional context**
- It appeared once in normal chrome tab (probably 1st time login to dashboard)
- In incognito, when refresh the URL and open modal, scroll won't be displayed

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by crystinutzaa** [comment]
@Mai-Saad & @arunbasillal 
This issue is related that the height of the popup is updated dynamically. The height is communicated between the iframe and WP Rocket with a message. In case the connection was slow then this scroll might appear (until the message is received and the correct height is applied).

The scroll is visible in other pages too in case the connection is low, because this an iframe and WP Rocket opens the popup in a modal with a fixed height. So, on each page change, the height of the modal is updated dynamically with a JS message.

After WP Rocket gets the correct height, it will update the modal and recompute the modal height. 
At this point we get a 1px difference which causes this scrollbar to popup.
The modal adds dynamically the scrollbar based on the browser size and the iframe height. 

The solution could be to add `1px` automatically to the iframe height when the height is changed dynamically, however this needs to be tested.

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
