### ISSUE TITLE
UI of RocketCDN banner needs to handle ar local

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3501]
**Describe the bug**
UI of RocketCDN banner needs to handle ar local

**To Reproduce**
1. Go to https://rocketlabsqa.dev/wp-admin/options-general.php?page=wprocket#dashboard while dashboard is arabic
2. Click on CDN in side bar
3. See banner

**Expected behavior**
- no overlap between text and dismiss icon
- text be logically in order

**Screenshots**
![popupAr](https://user-images.githubusercontent.com/76941962/104885795-4b092880-5971-11eb-91d3-9ce873977b34.png)

**Additional context**
- I think we may need multiple fixes in other pages while ar local
- In case our audience usually using En local so no need to do this now
- Recommend review with other local based on our audience

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by arunbasillal** [comment]
@Mai-Saad Can you please asses the amount of changes needed? If it's for a single page or just a few elements, we can do this right now. 

On the contrary, if a lot of changes are needed, lets plan this for future. We are planning on a UI rework soon where the visual elements might change. Investing a lot of time right now might not be ideal with that change coming up.

**Comment by Mai-Saad** [comment]
@arunbasillal Well I had a fast look across views and here what I noticed:
1- Regarding punctuation signs i.e !, ? , . , : ...etc -> this is common issue across other plugins so it's huge effort to do across all pages ( Do we really need this now? I don't think so, there is a question here we may ask: while ar local shall we display En text or Ar text? can this wok for all text?)
2- The overlapping between icon/text is not common or not existing so far in other plugins I saw , thus recommend fix this.
Mainly in 3 views so far: 
![dashboard1](https://user-images.githubusercontent.com/76941962/104904837-50bf3800-598a-11eb-99de-b6e5b0a58bee.png)

![extras in DB](https://user-images.githubusercontent.com/76941962/104904760-384f1d80-598a-11eb-973c-3ed3cacb6dfe.png)

beside the one in RocketCDN banner

**Comment by arunbasillal** [comment]
Thanks for the detailed feedback @Mai-Saad 🙏 

> 2- The overlapping between icon/text is not common or not existing so far in other plugins I saw , thus recommend fix this.
Mainly in 3 views so far:

I think the button is not designed to accommodate longer words. We could do one of these:

- Keep the words in the translation as `ON/OFF` so that it stays in English. (We would be making an assumption that most Arabic users would understand these words even if it's in English. Please suggest otherwise if you don't think so. [Related discussion](https://github.com/wp-media/wp-rocket/issues/906#issuecomment-376838274))
- Change the button design to accommodate longer words like these and other languages possibly. 

@GeekPress Is there a way to talk to our Arabic translators to get feedback on the first suggestion?

**Comment by GeekPress** [comment]
I have no discussion with our Arabic translators or any other translators. I think we have nobody in charge of that since Alice left the team.

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
