### ISSUE TITLE
Enhance user experience with Fallback critical CSS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3515]
**Is your feature request related to a problem? Please describe.**
Too much manual steps needed from user to use fallback critical CSS

**Describe the solution you'd like**
As a user, expected to have checkbox beside Fallback critical CSS so that I can be able to use the feature in case regenerate CPCSS failed.
Acceptance criteria:
- once Fallback critical CSS is clicked while user added the CRITICAL PATH CSS in text field, the critical CSS folder will be autodeleted and auto clear cache 
- User has option to use regenerate CPCSS  for generated files and use fallback for failed files

**Describe alternatives you've considered**
All the fallback critical CSS feature work from BE without any need for user intervention once regenerate CPSS failed

**Comment by arunbasillal** [comment]
> User has option to use regenerate CPCSS for generated files and use fallback for failed files

This is exactly how it should be right now. Let's say, CPCSS was not generated on the homepage and if fallback CPCSS is specified, then the fallback is used. Isn't this the case? 

Deleting the CPCSS folder manually is a hack to use the Fallback CPCSS for all post types where the generated CPCSS isn't a good fit.

**Comment by Mai-Saad** [comment]
@arunbasillal 

> Deleting the CPCSS folder manually is a hack to use the Fallback CPCSS for all post types where the generated CPCSS isn't a good fit.

Then this is just the part that needs enhancement (Use Fallback CPCSS for all post types flow)

**Comment by GeekPress** [comment]
To provide context, we added the fallback option at the time when our CPCSS option was the same for all pages.

As we do now a CPCSS per post type/taxonomy, I don't see a reason to keep this option. Because it means that the fallback is used for the entire website.

@webtrainingwheels @vmanthos I would love to have your thought about that 👆

**Comment by vmanthos** [comment]
I have rarely seen customers using the fallback CSS.

An edge case where the feature can be useful is if a site is not publicly accessible, therefore CPCSS cannot be generated, e.g. a protected local network.

Other than this, I agree with your comment, Jonathan. Even more, since we provide the ability for page-specific CPCSS.

**Comment by webtrainingwheels** [comment]
Most customers I see are using it incorrectly. But that's also the nature of support, we don't know about the customers who are successfully using our  plugin features without problems :) 
Overall, I would like to see it removed - maybe make it available in a helper plugin, just in case. 

If for any reason we keep it, [a customer made a good point](https://secure.helpscout.net/conversation/1433355031/241572?folderId=377611#thread-4155739880) that we should be more explicit that the field is not required and in most cases should be left blank. 
There is a misconception amongst many that because the field is there, it should be used.

**Comment by GeekPress** [comment]
> Most customers I see are using it incorrectly. But that's also the nature of support, we don't know about the customers who are successfully using our plugin features without problems :)
> Overall, I would like to see it removed - maybe make it available in a helper plugin, just in case.
> 
> If for any reason we keep it, [a customer made a good point](https://secure.helpscout.net/conversation/1433355031/241572?folderId=377611#thread-4155739880) that we should be more explicit that the field is not required and in most cases should be left blank.
> There is a misconception amongst many that because the field is there, it should be used.

We can hide the UI and still let the possibility to use a CPCSS fallback with a filter.

**Comment by piotrbak** [comment]
We didn't receive enough feedback from our customers to move forward here. Feel free to reopen if needed.
