### ISSUE TITLE
Exclude wp.serviceworker JS file created by PWA plugin from being cached as a page

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3520]
**Before submitting an issue please check that you’ve completed the following steps:**

- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When PWA plugin is enabled, it is loading a JavaScript file with the path `example.com/wp.serviceworker`. The file is generating a cache file as for a non-existing page/post with the URL `example.com/wp.serviceworker` 

**To Reproduce**
1. Install PWA plugin https://wordpress.org/plugins/pwa/
2. Clear cache in WP Rocket
3. Open the site in the browser
4. Check the cache folder. The cache/example.com/wp.serviceworker cache file will be generated.

**Expected behavior**
The file has to be excluded from caching.

**Screenshots**

**Additional context**
Adding `/wp.serviceworker` to the Never Cache URS(s) resolves the issue.

Issue thread with the plugin developers: 
https://wordpress.org/support/topic/pwa-is-not-compatible-with-cloudflare-rocket-loader/

> `/wp.serviceworker` returns with these HTTP response headers:
> `cache-control: no-cache`
> `content-type: text/javascript; charset=utf-8`
> WP Rocket should include this in the list of URLs that are excluded, and/or avoid caching anything that returns with a non-HTML content type.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by NataliaDrause** [comment]
Related ticket: https://secure.helpscout.net/conversation/1402675901/233201/

**Comment by GeekPress** [comment]
@Tabrisrp Does this one is good for `good first issue`?

**Comment by remyperona** [comment]
It is, we will add it once the grooming is done.

**Comment by viobru** [comment]
Related ticket: https://secure.helpscout.net/conversation/1441234382/243766?folderId=4130683

**Comment by iCaspar** [comment]
Reproduced ✅ 

**Root cause**: We are caching PWA's `wp.serviceworker` file as if it were an html page.

**Scope a solution**:
Unfortunately, we cannot exclude this by setting a blanket exclusion of non-html content types, per Weston's suggestion, because we also need to cache restAPI responses, which are json.
A second possibility moving forward is that we might create a universal exclusion based on the `cache-control: no-cache` header. However, this will need more discussion and discovery about whether our caching should conform to it, since that header is for intended primarily for browsers.

For now, we can create a `inc/3rd-party/plugins/pwa.php` compatibility with a new Subscriber that will:

1. Check for PWA's `WP_Service_Workers` class
2. If the class exists, add a filter on the `rocket_cache_reject_uri` hook, that adds the `/wp.serviceworker` file to that settings array.
3. Add the new subscriber to the `$provides` array and `register()` in the `ThirdParty/ServiceProvider`
4. Add the new subscriber to the `$common_subscribers` array in `Plugin.php`
5. Add an Integration test for the new subscriber.

**Estimate Effort:**
[S]

**Comment by NataliaDrause** [comment]
Possibly related: https://secure.helpscout.net/conversation/1600989218/287411/

**Comment by WordPresseur** [comment]
Another case: https://secure.helpscout.net/conversation/1732966426/315258?folderId=1213662

**Comment by westonruter** [comment]
> Unfortunately, we cannot exclude this by setting a blanket exclusion of non-html content types, per Weston's suggestion, because we also need to cache restAPI responses, which are json.

At the very least, the response's original `Content-Type` should be preserved, and when it is not `text/html` there should not be any HTML comment appended to the response. We're seeing that when WP Rocket caches `/wp.serviceworker` it is then serving `text/html` instead of the expected `text/javascript`, and then appending the HTML comment causes a syntax error.
