### ISSUE TITLE
Beacon is covering WordPress's menu when RTL languages are used

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3521]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When an RTL language, e.g. Hebrew is used in WordPress, the beacon is covering part of the menu when the user is on WP Rocket's options page.

**To Reproduce**

1. Set Hebrew as the WordPress language.
2. Visit WP Rocket's dashboard.
3. See the issue:
![](https://i.vgy.me/mDitTl.jpg)

**Expected behavior**

The Beacon should be on the left on RTL languages.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1404323697/233602?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
Beacon is configured by default to be set on the right side in the Beacon setup in Helpscout.

### Scope a solution ✅ 
We can override the default configuration for the position by adding the `config` object to the Beacon instantiation, like the following:
```
Beacon('config', {display:{position:"left|right"}});
```
We can determine the value to use for the position by using the `is_rtl()` function from WP.

There is 2 files to change:
- `views/settings/beacon.php` to add the `window.Beacon("prefill", <?php echo $data['config']; ?>);` line
- `inc/Engine/Admin/Beacon/Beacon.php` to send the `config` as part of the `$data` array. We can create a new private method `get_config_data()` to populate the value.

### Estimate the effort ✅
Effort `[XS]`
