### ISSUE TITLE
Add Missing Image Dimensions is not applied if only single attribute (width or height) is missing

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3523]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version 
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When image is missing width or height, Add missing image dimensions is not working (it only works only when both Height and Width are missing)

**Precondition**
Having a page with image that is missing height or width

**To Reproduce**
1. Enable add missing image dimensions in media page
2. Clear cache
3. Visit the page mentioned in precondition
4. In source image dimensions are still missing

**Expected behavior**
Image dimensions are added as same as that when both width and height were missing

**Screenshots**
![imgDimensions](https://user-images.githubusercontent.com/76941962/105961812-b2b52700-6087-11eb-955a-03f60372f1bb.png)

**Additional context**
Add missing image dimensions is working fine whenever **both** height and width are missing

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
The feature was tested against the Acceptance Criteria:
`When the option is enabled, any images with missing “width” and “height” attributes have the appropriate width and height added. `
https://github.com/wp-media/wp-rocket/issues/3301

Things to consider:
- Width or Height calculated by JS
- Height or Width provided by the customer is different than the real height or width of the image

**Comment by engahmeds3ed** [comment]
I think we need @wp-media/productrocket opinion here, if one of those attributes are there so we will need to calculate the new other attribute based on the aspect ratio as follows:-

Original image => width: 100px, height: 120px
Html img attribute => `<img src="image.jpg" width="50" >`
<strike>Aspect</strike> ratio => 1/2 (0.5)

So the missing height attribute should be `120 * 0.5 = 60`.

**Comment by arunbasillal** [comment]
@engahmeds3ed I think you are right. And this is what happens when no height is mentioned, i.e. the image scales to keep the aspect ratio. So from my side, I think we can go ahead with your plan. 

However, shall we wait a bit before we fix this? Are we getting support tickets about it? Maybe themes and plugins have a reason to specify only one dimension?

**Comment by arunbasillal** [comment]
@engahmeds3ed I think you are right. And this is what happens when no height is mentioned, i.e. the image scales to keep the aspect ratio. So from my side, I think we can go ahead with your plan. 

However, shall we wait a bit before we fix this? Are we getting support tickets about it? Maybe themes and plugins have a reason to specify only one dimension?

**Comment by GeekPress** [comment]
@engahmeds3ed I agree with you and @arunbasillal about the solution to adopt.

> However, shall we wait a bit before we fix this? Are we getting support tickets about it? Maybe themes and plugins have a reason to specify only one dimension?

Indeed, I will vote to wait for a little bit to know if this kind of issue will be reported by users. What could be the reason for a theme or a plugin to insert only one of these tags?

**Comment by jazir555** [comment]
> @engahmeds3ed I agree with you and @arunbasillal about the solution to adopt.
> 
> > However, shall we wait a bit before we fix this? Are we getting support tickets about it? Maybe themes and plugins have a reason to specify only one dimension?
> 
> Indeed, I will vote to wait for a little bit to know if this kind of issue will be reported by users. What could be the reason for a theme or a plugin to insert only one of these tags?

Please don't wait. There really shouldn't be a reason, how can adding missing dimensions hurt? This is clearly a bug that needs to be rectified immediately.

**Comment by GeekPress** [comment]
> This is clearly a bug that needs to be rectified immediately.

@jazir5 Please be moderate in your comments. You have added few rude comments recently...

**Comment by webtrainingwheels** [comment]
Related:https://secure.helpscout.net/conversation/1412441027/235892?folderId=377611

**Comment by naurissteins** [comment]
On my site, it only works on a few pictures.

**Comment by iCaspar** [comment]
✅ Reproduced
✅ The root cause is that this was initially designed to omit images where one or the other of height/width was missing (in order not to accidentally distort aspect ratio when adding dimensions). That intention is carried through in the [regex](https://github.com/wp-media/wp-rocket/blob/35c1cd12508e9f954fbb8e87fe4501d2eeb1e73c/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L85) used to select the images.
✅ Scope a solution:
1. The regex for selection can be modified to 
`<img(?:[^>](?!(width)=['|"]\S+['|"]))*+>|<img(?:[^>](?!(height)=['|"]\S+['|"]))*+>`
Which will catch all cases where either width or height is missing, rather than just cases where both are missing. (This expression _might_ be further optimized with some experimentation.) Then,
2. In `assign_width_height()` before making the replacement, calculate if either dimension should be adjusted: if either dimension is specified, calculate the ratio of the dimension original image dimension, then apply that ratio to the original image's opposite dimension just before doing the replacement.
3. Relevant tests will need to be adjusted to account for replacement of single-dimension images.

(An alternate solution to consider is to grab all the images, and use php to check width and height for each. However, on pages with a lot of images, getting all the images when only a small number of them need to be actually modified runs the risk of needlessly impacting performance.)

✅ Estimate 
[S] -- Most of the time will be messing about with regex here.

**Comment by viobru** [comment]
Related: https://secure.helpscout.net/conversation/1432944926/241442?folderId=3051575

**Comment by webtrainingwheels** [comment]
https://secure.helpscout.net/conversation/1432825992/241384?folderId=377611

**Comment by DahmaniAdame** [comment]
Related - https://secure.helpscout.net/conversation/1440116769/243447/

**Comment by camilamadronero-zz** [comment]
Related https://secure.helpscout.net/conversation/1448759061/245958/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1539752863/270765?folderId=3864740
