### ISSUE TITLE
AMP query string is not added during the AMP plugin activation

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3528]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When activating the official AMP plugin, we're not adding the `amp` query string automatically. We need to either disable WP Rocket or save settings in the AMP plugin.

**To Reproduce**
1. Enable WP Rocket
2. Enable AMP plugin
3. Check the WP Rocket config file
4. AMP is not there

**Expected behavior**
We should add the query string during the AMP activation

**Additional context**
The config file is regenerated, but the query string is not added.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
Possibly related ticket: 
https://secure.helpscout.net/conversation/1409931489/235255/

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced locally, but not always

### Identify the root cause ✅ 
The issue is not always happening, I believe there is kind of a race condition between the `get_subscribed_events()` and the activation/deactivation, which makes it unreliable.

If `get_subscribed_events()` is executed before the activation/deactivation of the AMP plugin, the function `is_amp_endpoint()` doesn't exist yet, so the config file is not changed.

### Scope a solution ✅
Move the `is_amp_endpoint()` check into the `is_amp_compatible_callback()` method instead of the `get_subscribed_events()`, to make sure the callback always runs.

### Estimate the effort ✅
Effort `[XS]`
