### ISSUE TITLE
Fix weak integration test related to rocket_get_purge_urls()

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#3535]
`WP_Rocket\Tests\Integration\inc\common\Test_RocketGetPurgeUrls::testShouldReturnUrls`

This test is failing often when automatically running in our GH actions, creating false negative errors.

```
Failed asserting that two arrays are equal.

     1 => 'http://example.org/blog/'
     2 => 'http://example.org/next_post/'
     3 => 'http://example.org/test/'
-    4 => 'http://example.org/test_parent/'
-    5 => 'http://example.org/test_parent_2/'
+    4 => 'http://example.org/test3/'
+    5 => 'http://example.org/test_parent/'
+    6 => 'http://example.org/test_parent_2/'
```

The test should be updated to be more robust and not create unexpected failures.

**Comment by iCaspar** [comment]
This one is particularly frustrating in that it is an intermittent issue, so while it reproduces sometimes, it is not always erring either.

My best guess here is that there is another test that is running either concurrently or previously (given tests don't always run in the same order) that is not completely resetting the WP environment. Within this test class, the only other case that involves the `/test3/` item is to test getting that the previous post in category is `purged_url` array. I suspected that first, since it is wrongly included when running this test on occasions when it fails (see sample output in OP). But the filter that sets that is being removed in `teardown()` -- besides being from the same fixture/provider these tests should run in order within the class.

That said, I've so far not found any other tests that are likely candidates for interference. ☹️

**Comment by piotrbak** [comment]
@Tabrisrp @MathieuLamiot Is it still the case?

**Comment by remyperona** [comment]
The tests have currently been completely removed for this function, so this can be closed.
