### ISSUE TITLE
Font-display option

### ISSUE THREAD

**Issue by geoffreycrofte** [wp-media/wp-rocket#3536]
Hello the Rocket Team 😊

I just saw this issue #3375 in the changelog.
I read lately that the best option by default would be "optional" https://simonhearne.com/2021/layout-shifts-webfonts/ for the font-display property to avoid Layout Shift.

This is a tricky option for WP Rocket because you are at the border between design of the website and performance (or at least one of the Google arbitrary indicator), and this choice clearly depend on the website design and your user (client) choice in this matter.

Optional make the font loading totally optional to avoid a shift. If the font doesn't load quickly enough the first time, it won't be displayed at all. The second time the user visit the page, the font should be in cache and loaded almost instantly.

I don't say this should be an option in the WP Rocket Options, it's up to you to evaluate that. I just say it's difficult to make the choice for the end-client.

Thanks for reading 🙂

**Comment by GeekPress** [comment]
Hi Geoffrey 🤚

It's nice to see you here :)

Indeed, I've read this excellent post. As you said we are at the border of the design & performance of the website.

Some Page Builders like Elementor sets the font-display to optional. In the meantime, these fonts don't have the right value for the « All text remains visible during webfont loads » PageSpeed Insight recommendation. To please this recommandation, the swap value needs to be set. And when Google says to do something... On our side, it generated some frustrations from our users and they opened tickets to know how to fix it. 

We have the preload fonts feature since 3.7. Thanks to the preload, the fonts should be loaded earlier and faster.
