### ISSUE TITLE
Compatibility with BuddyPress Activity Stream

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#356]
When updates are made, the user that posted the update sees it right away, until they reload the page and it reverts to the cached version. 

It's related to how BP handles this, it doesn't seem to trigger the usual WP hooks for updating pages. 
Not sure if we can fix, but possibly we can look into some BP-specific hooks to utilize?

Customer ticket example: https://secure.helpscout.net/conversation/274290350/?folderId=273766

In the past BP has recommended not caching any areas that they update with AJAX: 
https://buddypress.org/support/topic/cacheing-plugin-recommendations/

**Comment by rwkyyy** [comment]
Any updates on this? I do have wp rocket subscription and I'm interested on installing it on a 1k user buddypress website. Right now I got w3tc but it has bugs here and there.

Thank you!

**Comment by arunbasillal** [comment]
A helper to clear the user cache of the current user on any activity - https://www.dropbox.com/s/lw39vq0i9lenrij/wp-rocket-cache-clean-user-after-activity.zip?dl=1

Hooks on to `bp_activity_add` and uses `rocket_clean_user` to clear the user cache. 

Since only the cache of the current user is updated, the other users will not see the update until their cache is cleared. The solution is to clear the entire cache but clearing every cache on every activity is a lot of work making caching somewhat pointless on a social media style website.

**Comment by arunbasillal** [comment]
@GeekPress Requesting your input on this one as well. We do not have tickets related to the same. Furthermore, users can use the snippet from my previous reply to build compatibility if needed. Doesn't make sense to build this into WP Rocket. 

What do you think? Close for now?

**Comment by GeekPress** [comment]
@arunbasillal 3 years and half later we don't seem to have requests on this compatibility. We can close it.
