### ISSUE TITLE
DelayJS is not applied on large HTML pages

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3584]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When an HTML page is large, the **Delay JavaScript execution** feature may not be applied, because `preg_replace_callback()` returns `null` here:
https://github.com/wp-media/wp-rocket/blob/d9e74988945f35b4c6d7da3b4c7bf2867345e23d/inc/Engine/Optimization/DelayJS/HTML.php#L91 

In the specific case I checked, there was a really large `JSON` object, and the error returned from `preg_last_error()` was `PREG_BACKTRACK_LIMIT_ERROR`.

**To Reproduce**

1. Use the `sample.zip` file you'll find in the [Slack thread](https://wp-media.slack.com/archives/C43T1AYMQ/p1613025005136600)
2. Create a template from it.
3. Activate Delay JavaScript Execution.
4. Check if it's applied.

**Expected behavior**

Delay JavaScript Execution should work regardless of the page size/content.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1415502944/236679?folderId=2135277
**Slack Conversation**: https://wp-media.slack.com/archives/C43T1AYMQ/p1613025005136600

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by gevcen** [comment]
Can you ensure that any change performed here wouldn't restore the issue reported in the ticket below? I was impacted by the issue reported there and it has been resolved by implementing this exception, so I don't want to see this issue coming back. The Delay JS was exempted on large html page because it caused the page to load white. Please test this thouroughly. Thanks

https://github.com/wp-media/wp-rocket/pull/3097

@Tabrisrp can you have a look at my commen here please? thanks a lot

**Comment by remyperona** [comment]
Yes the error is unavoidable on this context. I don't think we will be able to go around it while using RegEx to parse the HTML. The current solution to bail-out if there is anything wrong during parsing is the safest one.

**Comment by gevcen** [comment]
@Tabrisrp ISo you're saying that you will revert the fix and not care about my problem? That workaround was applied here for large pages, whose issue was raised by myself, spent days with your support and developer to explain the problem, and finally find this workaround. Now suddenly someone raise this and wants this fix to be gone? That **cannot** happen. I've been a paying customer of WP Rocket for a long-term and do **not** want to see this problem come back. Either a solution if found to avoid it, or you keep everything as is by not changing anything at all. Thanks.

**Comment by remyperona** [comment]
You completely misread my comment, I said that the fix we implemented was necessary, and since it's the safest solution, we're not going to change anything.

Also, please watch your tone and words when commenting on our repository. Quickly jumping on conclusions and micro-aggressions will not be tolerated.

**Comment by gevcen** [comment]
I misunderstood your answer sorry.

**Comment by GeekPress** [comment]
With our new Delay JS option scheduled for 3.9, this problem will be automatically fixed. I'm closing this issue.
