### ISSUE TITLE
Use <noscript> fallback for LazyLoading background images

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#3630]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When JavaScript is disabled in the browser, background images that are being lazy-loaded will not be displayed.

**To Reproduce**
1. Create a post with a background image with a similar markup:
HTML:
```
<div class="myblock" style="background-image: url(image.jpg)">
</div>
```
Custom CSS:
```
.myblock {
	width: 100%;
	height: 400px;
}
```
2. Enable _LazyLoad for Images_ in the Media tab
3. Open Incognito browser window
4. Disable JavaScript in the browser. In Chrome you can click CTRL+Shift+P on Windows; start typing JavaScript and click _Disable JavaScript_ as in the screenshot: https://jmp.sh/gEPP72K
4. Open the post in this browser while JS is disabled.
5. The image will not be loaded.

**Expected behavior**
Background images have to be displayed when JavaScript is disabled.

**Screenshots**
https://jmp.sh/zYwugEd

**Additional context**
Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1614605411044700
Ticket: https://secure.helpscout.net/conversation/1438478021/243004/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
@wp-media/productrocket I think before grooming we need to set a plan for the approach we will take for adding this noscript:-

- For img tags we were adding noscript tag because when disabling the JS on the browser, the first image will not have the `src` attribute so it will not appear on the page and the second img (inside noscript) will appear as it has the main img tag without any change.
- For this background assume we have the following HTML
```
<div style="background-image: url(image.jpg);">
    <div class="div_1">content 1 is here</div>
    <div class="div_2">content 2 is here</div>
</div>
```
so the default behavior was generating the following HTML
```
<div style="" data-bg="image.jpg">
    <div class="div_1">content 1 is here</div>
    <div class="div_2">content 2 is here</div>
</div>
```

so if we added the full div inside noscript tag, this will duplicate the inner content when JS is disabled on the browser.

so what do you think about the solution here?

**Comment by GeekPress** [comment]
We don't have a valid workaround to do that. As we can't duplicate a div. Not having the <noscript> for a background image doesn't have any impact on SEO. The only con is when someone is navigating without JS, the background won't be applied, but here I'm afraid we won't have any solutions...

**Comment by remyperona** [comment]
I'm marking this as `wontfix` and closing the issue, as it's not something we can handle like the images fallback.

As a note, if it's an issue for one of our users, there is always the possibility to use the `rocket_lazyload_background_images` filter to disable this specifically.
