### ISSUE TITLE
@import CSS feature might go into infinite loop in very rare cases

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#3639]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Since 3.8.6 we're fetching and downloading the files added with `@import`. If in the minified file (`/wp-content/rocket-test-data/styles/import-css-first.css`) we will import the same file, it'll go to the infinite loop.

**To Reproduce**
1. Add an `@import` statement to any CSS file and point it to the same file
2. Enable CSS Minification
3. Visit the page

**Expected behavior**
We should bypass this file

**Additional context**
We also need to consider that the `style.css` file can import the `style2.css` file and in the second one we can have the import the first `style.css`.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
**Reproduce the problem**
Yes, I can see the issue locally in two cases:-
1. Use `@import` keyword with the same file name of the container file.
2. Use `@import` with a file that imports the first file on it

**Identify the root cause**
Because of the following recursion

https://github.com/wp-media/wp-rocket/blob/e31ed4ae4e060bd8bee45bffac54bfda50f1dd34/inc/Engine/Optimization/CSSTrait.php#L323

**Scope a solution**
We need to stop this recursion by creating local variable on this trait called `$imports` and fill it with paths of files to be imports and before calling this recursion we can check if this path is on this array or not.

**Estimate the effort**
[XS]

**Comment by engahmeds3ed** [comment]
@piotrbak You can test this one at the `feature/rucss` branch for both minify CSS and also RUCSS warmup.
