### ISSUE TITLE
Preload links: Exclude PDF links from being automatically preloaded

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#3720]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
If you have links to PDF files into a post andyou move the mouse hover the links, it will automatically download the PDF files to the browser’s cache memory. This can a performance issue with big PDF files.

**To Reproduce**
1. Enable Preload Links option
2. Upload a PDF and set a link into a post
3. Open this post in a Chromium Browser
4. Move your mouse hover the PDF link
5. You’ll see in the Network tab of the console that the PDF is automatically downloaded. 

**Expected behavior**
PDF shouldn’t be downloaded automatically if you don’t click on it.

**Additional context**
This doesn’t occur when CDN is enable

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by meow231a** [comment]
This is also happening for .doc, .docx, and .xls, but resulting in 404s since it tries to open them as webpages. It may also affect other document file types.

**Comment by juricazuanovic** [comment]
This still isn't resolved, but there is a workaround for this issue. You will need to use [WP Rocket | Regex Exclusions](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-no-cache-urls-regexes), helper plugin.

Open the file wp-rocket-no-cache-urls-regexes.php with text editor and add:

$uri[] = '(.*).doc';
$uri[] = '(.*).docx';

Or any other files extension. That will end up excluding the extension like this in RocketPreloadLinksConfig.


You can also use this snippet that will preload those links without error 404, because the *.doc will be considered as a file:
```
add_filter( 'rocket_preload_links_config', 'rocket_exclude_preload_links');
function rocket_exclude_preload_links( $config ) { 
	$config['fileExt'] .='|docx';
	return $config;
}
```

The $config['fileExt'] can be used to add extensions that need to be considered as files when preloaded. Otherwise, the .docx extensions are considered as URLs and we append the /, causing a 404: https://jmp.sh/9zbbWOd

This is how the [fileExt](https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Engine/Preload/Links/Subscriber.php#L131) will look after using the snippet: 
`"fileExt":"jpg|jpeg|gif|png|tiff|bmp|webp|avif|php|pdf|html|htm|doc"`

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue

### Identify the root cause ✅ 
PDF files are not excluded from preloading currently in the preload script configuration. Same for the reported doc/docx/xls.

### Scope a solution ✅ 
The quick and easy solution would be to add the pdf, doc, docx and xls extensions to the `$images_ext` variable value in `Engine/Preload/Links/Subscriber:get_preload_links_config()`

### Estimate the effort ✅
Effort `[XS]`
