### ISSUE TITLE
CDN isnot applied on images with relative url containing query string

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3724]
**Before submitting an issue please check that you’ve completed the following steps:**

- [x] Made sure you’re on the latest version

- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
CDN is not applied on paths containing query string

**To Reproduce**
Precondition:
- Having page with image URL containing query string i.e `<img src="/wp-content/rocket-test-data/images/fixtheissue.jpg?123" >`
1. In WPR settings -> CDN , enable CDN and add CDName i.e test.com
2. open the page incognito and check source
3. image URL didn't use CNAME

**Expected behavior**
CDN is applied and URL changes to `src="https://test.com/wp-content/rocket-test-data/images/fixtheissue.jpg?123"`

**Screenshots**
![Screenshot from 2021-03-26 19-01-17](https://user-images.githubusercontent.com/76941962/112667221-ae2da480-8e65-11eb-8a94-249fa4880902.png)

**Additional context**
If the image URL is absolute URL with query string i.e `<img src="http://new.rocketlabsqa.ovh/wp-content/rocket-test-data/images/fixtheissue.jpg?1234" >` , CDN will be applied normally

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Note: CDN not applied on js relative URL too (probably any relative internal URL)
i.e `<script src="/wp-content/rocket-test-data/scripts/testdummy2.js"> crossorigin='anonymous'</script>`

**Comment by mostafa-hisham** [comment]
### Identify the root cause ✅
 tested it on images locally
`<img src="/wp-content/download.jpeg" width="100" height="100">`
worked fine

did not work on
`<img src="../wp-content/download.jpeg" width="100" height="100">`

### Scope a solution ✅
To fix relative URLs starting with `.`
we need to change the regex in
https://github.com/wp-media/wp-rocket/blob/bb4ab38d0c2f551259bce097d77d7efa4f16fc37/inc/Engine/CDN/CDN.php#L69
to 
`|(\.+\/|\/)[^/](?:[^"')\s>]+\.[[:alnum:]]+)` (worked with maybe there is better one)

### Estimate the effort ✅
[xs]

**Comment by piotrbak** [comment]
We didn't receive enough customer feedback to implement this in the nearest future. Feel free to reopen.
