### ISSUE TITLE
Missing image dimensions conflicts with Penci lazyload, Soledad theme

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#3772]
[Soledad theme by PenciDesigns](https://themeforest.net/item/soledad-multiconcept-blogmagazine-wp-theme/12945398) includes a lazyload feature. 

When this is active with our missing image dimensions feature, we are applying the sizes on the placeholder image `penci-holder.png`, not the real image which is inside `data-src`. This results in the real image being displayed at a tiny size. 

Their markup is like this: 

`<img class="attachment-penci-full-thumb size-penci-full-thumb penci-lazy wp-post-image" src="https://example.org/wp-499a0-content/themes/soledad/images/penci-holder.png" alt="Starke Knochen Arzt mit Knochen" title="Starke Knochen" data-src="https://example.org/wp-499a0-content/uploads/Starke-Knochen-2-1170x658.jpg"></a>	
`

penci-holder.png is 6x4px
So the real image ends up that size. 

**To Reproduce**
1. Install Soledad theme, or use this template from an example site: https://drive.google.com/file/d/1W4PdniVg_1jGfb-wtNcfeEVi41q9LpGj/view?usp=sharing
2. Activate their LazyLoad and our Missing Image Dimensions
3. Behold! The featured image on a post will be tiny: https://jmp.sh/hTheos2

**Expected behavior**
The image to display at the correct size. 

**Screenshots**
Screenshot from the customer is here: https://secure.helpscout.net/conversation/1475980461/253808/

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1475980461/253808/

This ticket is likely related:
- https://secure.helpscout.net/conversation/1457664379/248837/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Identify the root cause ✅
We use the `src` image attribute to get the image source, Soledad theme is replacing it with a small image so we get its size which is wrong, and don't have a way to use a different image attribute

### Scope a solution ✅
I propose:
- Add a new filter `rocket_specify_images_src_attr` to set a different attribute before
https://github.com/wp-media/wp-rocket/blob/29b0d647b61724b4cea48d05d1c1b23ec0a01e0a/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L125-L129
- then use the value from the filter in  `can_specify_dimensions_one_image` function Regex instead of `src`
https://github.com/wp-media/wp-rocket/blob/29b0d647b61724b4cea48d05d1c1b23ec0a01e0a/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L388-L403

and if this solution is ok we need to create new third-party compatibility for the theme and use it


### Estimate the effort ✅
[M]

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
