### ISSUE TITLE
Replacing Auto With Swap (Font-Display) Also Happening in Fonts' URLs (Domain)

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#3813]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Y
- Used the search feature to ensure that the bug hasn’t been reported before - Y

**Describe the bug**
Replacing `auto` with `swap` (`font-display`) [enhancement ](https://github.com/wp-media/wp-rocket/issues/3375) is also happening in the fonts' URLs. The domain was partially modified and it generated an `ERR_NAME_NOT_RESOLVED` error.

**To Reproduce**
1. Have auto inside the domain, as https://www.autohaus-glienicke.de/ 
2. Enable **Minify CSS files** feature
3. Check the website
4. **Issue appears:** some fonts are not visible and  `ERR_NAME_NOT_RESOLVED` error messages for the fonts URLs.

URL changed from `https://www.autophaus-glienicke.de/wp-content/uploads/avia_fonts/type_fonts/barlow/barlow-regular.ttf `to `https://www.swaphaus-glienicke.de/wp-content/uploads/avia_fonts/type_fonts/barlow/barlow-regular.ttf` in this **minifie**d CSS file:  [autohaus.css](https://www.autohaus-glienicke.de/wp-content/cache/min/1/wp-content/uploads/dynamic_avia/autohaus.css?ver=1618868769).

The URLs `https://www.swaphaus-glienicke.de/wp-content/uploads/avia_fonts/type_fonts/barlow-semi-condensed/barlowsemicondensed-medium.ttf` and `https://www.swaphaus-glienicke.de/wp-content/uploads/avia_fonts/type_fonts/barlow/barlow-semibold.ttf` were also modified.

**Expected behavior**
Not to replace  or modify the domain name or URL when forcing the `swap` property in fonts inside CSS files.

**Screenshots**
The `ERR_NAME_NOT_RESOLVED`  errors in the console: https://i.imgur.com/yrdYdO7.png.

**Additional context**

- Ticket: https://secure.helpscout.net/conversation/1486030829/256704/
- Minify CSS files is currently disabled on the affected website, to ensure correct layout.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by girlie** [comment]
Related ticket: https://secure.helpscout.net/conversation/1580923906/282536/

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
In `CSSTrait::apply_font_display_swap()`, we perform a string replacement over the whole font-face declaration, instead of doing it only on the specific `font-display`property, so in some cases where there is `auto`, `block` and the like in the declaration block, they will also be replaced.

### Scope a solution ✅ 
Update the method to perform the replacement only on the `font-display` property instead of the whole declaration block.
Update the related tests

### Estimate the effort ✅
Effort `[S]`

Fixing this issue will also fix #4144 at the same time

**Comment by alfonso100** [comment]
Another case: https://secure.helpscout.net/conversation/1698075012/308111?folderId=2683093

In this one, the path of a plugin is modified because it contains the string **block** in it

The URLs are converted from:
_/wp-content/plugins/recipe-card-**block**s-by-wpzoom-pro/dist/assets/webfonts/fa-solid-900.woff2_

To:
_/wp-content/plugins/recipe-card-**swap**s-by-wpzoom-pro/dist/assets/webfonts/fa-solid-900.woff2_
