### ISSUE TITLE
Remove Unused CSS automatically restart warmup on SaaS demand

### ISSUE THREAD

**Issue by crystinutzaa** [wp-media/wp-rocket#3848]
**Is your feature request related to a problem? Please describe.**
In SaaS, in case we update anything in CSS Parser or JS Parser which might affect the stored parsed resources, we need to find a way to re-send automatically from the customer websites the resources to be re-parsed.

In case we don't do this automatically, the stored resources will always be the old ones and the fixes applied on SaaS side will not be reflected soon. It will need a manual clean of resources DB table in order to resend the files.

**Describe the solution you'd like**
The solution is to add 1 or 2 version coming from SaaS on optimize.
Store the versioning in `options` table and detect if the version changed since the last generation.
In case the version is changed, then clean from resources the corresponding data (eg. JS only if JS Parser was update, CSS only if CSS Parser was updated) and re-start the resources warmup process (display the loading bar & the progress of the resources which needs to be warmed up).

**Describe alternatives you've considered**
Another solution which was not accepted was that on click Remove Used CSS button to clean also resources.
However this is not accepted because the clients can abuse on Remove Used CSS button and SaaS will be triggered too many times. This will increase the API calls which is not the desired functionality.
Also, we can determine 100% if SaaS needs to re-parse some of the files based on type and request only those. With this solution the API calls are targeted and the server costs are lowered.

**Additional context**
-----

**Comment by iCaspar** [comment]
This issue has (at least) 2 parts SaaS side and WPR Side:

1. `The solution is to add 1 or 2 version coming from SaaS on optimize.` -- this needs to be done on the SaaS side on Central-Saas and in both of the Parsers.
  
- On each of the Parsers: (probably would be good to have on all the microservices eventually) need to add a `version` item to the `config/app.php` file -- which will need to be updated to match the tag for any future releases.
- On each of the Parsers: (again, probably would be good to have on all ms) add a new route `/version` that returns the current parser version.
- On CentralSaas: Need to add in `SaasController::run()` before calling the final gauges and endTiming(), calls to each of the new parser routes, and add the responses to 2 new entries (`CSSParserVer` and `JSParserVer` both values `(string) $version | false` into the `$treeshaker` array that will be returned by the `APIClient::respondSuccess()`

**Estimated Effort**
3x [S] -- 2x add version item and new accessor routes on each parser repo + 1x Call new routes from CentralSaaS and add to returned data.

2. `Store the versioning in options table and detect if the version changed since the last generation.
In case the version is changed, then clean from resources the corresponding data (eg. JS only if JS Parser was update, CSS only if CSS Parser was updated) and re-start the resources warmup process` -- needs to happen on the WPR side. To be further groomed in next comment.

**Comment by iCaspar** [comment]
On the WPR side:

In the `Frontend/APIClient::optimize()` 
- Add new items `CSSParserVer` and `JSParserVer` to the `$default['contents']` array with defaults of `false`
- Add these items into the returned array.

In the `Controller/UsedCSS::treeshake()
-  Initialize variables `$css_parser_version` and `$js_parser_version` at the start using with any saved option from the options
- Check in `$treeshaked_result` if the returned parser version matches the saved ones.
- for each comparison, if it is different:

1. Find and collect the URLs for all resources of the affected type(s) in the `wpr_rucss_resources` table -- will need a new method in `Controller/UsedCSS` to do this query.
2. Delete those affected rows from the `wpr_rucss_resources` table -- again a new method in `Controller/UsedCSS`.
3. Set treeshaker back to "locked" status (invoke the progress bar and set `prewarmup_stats` option) and re-queue the list of affected URLs we found in step 1 for warmup.

Add tests for new expectations.

**Estimated Effort**
[M]

**Comment by crystinutzaa** [comment]
This will be closed in favor of SaaS implementation
