### ISSUE TITLE
3.9 alpha4: Default exclusion list isn't added when it should

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3852]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version (3.9-alpha4)
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After updating to 3.9-alpha4 on a website that already has Delay JS turned on, the default exclusion isn't here by default. We need to refresh the option page to have the default exclusion added.

**To Reproduce**
1. Be sure the current configuration has Delay JS on.
2. Update to 3.9-alpha4
3. See error, the default exclusion isn't added.
4. Refresh the page a,d the default list will be added

**Expected behavior**
The default exclusion list on Delay JS should be added right after the update.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
This is an issue that has been discussed multiple times with the team, and we didn't find a solution for it. Note that it was also the case when we introduced the original delay JS with the inclusion list, support team was aware of it.

**Details of why it's happening:**

First, note that it doesn't happen if WP Rocket settings page is not the first admin page visited after updating.

In the case it is the first page:
- `admin_init` is triggered
- `wp_rocket_upgrade` is triggered in `rocket_upgrader()`
- the `set_options_on_update()` method is called by `wp_rocket_upgrade`
- The option is updated
- In parallel, the settings page was loaded, but getting the option values that were not yet updated
- The settings page is displayed with an empty field for the delay JS exclusion

Reloading the page will get the updated options value after `set_options_on_update()` is finished, and the display is correct.

We are in a race condition because multiple actions are happening in parallel.

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Check

### Identify the root cause ✅ 
Explained above

### Scope a solution ✅ 
A possible solution is to redirect the user once the `wp_rocket_upgrade` action is done, in `rocket_upgrader()`, like the following:
```
if ( did_action( 'wp_rocket_upgrade' ) && 'wprocket' === $page ) {
		wp_safe_redirect( esc_url_raw( admin_url( 'options-general.php?page=wprocket' ) ) );
		exit;
	}
```

### Estimate the effort ✅
This solution would be an `[XS]`

**Comment by iCaspar** [comment]
Seems like this *could* work and is small enough to implement on a test branch, make a zipped "update" and just try it out.
