### ISSUE TITLE
New UsedCSS is sometimes not applied until Clear Used CSS is done twice

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3900]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Yes
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
Clear used CSS after changing external CSS won't reflect new CSS on the page until we clear used CSS again

**To Reproduce**
Precondition:
- Using external CSS like this one https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/styles/rucss_styles.css in a template
- Enable RUCSS and visit the page template i.e https://new.rocketlabsqa.ovh/rucss-with-ext-int-css/

1. Change background image in the external CSS file
2. Clear the used CSS from the admin bar
3. Revisit the home page => new background color is not reflected

**Expected behavior**
Changes in external CSS are displayed after clear the used CSS and revisit the page

**Screenshots**

https://user-images.githubusercontent.com/76941962/117711746-d6822000-b1d3-11eb-9472-d6973a078f47.mp4

**Additional context**
- If we repeat step 2,3 => the new CSS will be reflected
- With the 1st clear of used CSS, when revisiting the page => there is no unprocessed files
- Sometimes if we revisit the page before the step => it will then update after the 1st clear for UCSS (seems it`s about timing too)

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Wasn't able to reproduce in alpha9, the CSS was updated after the first clear. Might be due to the timing

**Comment by Mai-Saad** [comment]
Still a problem at my side with alpha9.

**Comment by piotrbak** [comment]
@Mai-Saad This one can be closed, as this is the same problem as https://github.com/wp-media/wp-rocket/issues/3919, right?

**Comment by Mai-Saad** [comment]
@piotrbak Not sure if both scenarios have the same root cause, here edit of external CSS is not reflected on used CSS (OCD, safelist are done care) while on #3919 safelist with OCD cause the problem while safelist will normally reflect on inline used CSS which is not the case here. If we are sure that it's the same root cause then yes we can close one and mention both scenarios in 1 ticket.

**Comment by piotrbak** [comment]
It might not be the same, in fact. The resource itself in the `resources` table seems to be updated correctly, but the CSS in the `used CSS` table is not updated after the first used CSS clearing.

**Comment by remyperona** [comment]
Is the used CSS row not deleted, or is it deleted and recreated with the incorrect used CSS content?

**Comment by piotrbak** [comment]
@Tabrisrp There's no entry in the `wpr_rucss_used_css`

**Comment by Mai-Saad** [comment]
Note: fix here needs to be tested too when updated the js file that is using Elements i.e add class
=> currently with 1st clear cache and access the page , no entry added in used CSS table until cache is cleared again

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1599617308/287111

and the same on my test site

**Comment by iCaspar** [comment]
**Reproduced**
✅ Confirmed this is still the case on 3.9.3

**Root Cause**
**First - What is happening** Step-by-step:
1. Resource is changed.
2. First use of "Clear Unused CSS" is activated (page still not visited)
- `wpr_rucss_used_css` table is truncated.
- `wpr_rucss_resources` table is not updated yet with new content of the changed resource.
- page's cache is cleared.
3. Page is visited.
- page's cache is regenerated (using non-updated resource) and displayed with old regenerated usedCss, but using old source still.
- `wpr_rucss_resources` table is updated with new resource content.
4. Second use of "Clear Unused CSS" is activated.
- `wpr_rucss_used_css` table is truncated again.
- `wpr_rucss_resources` table is not updated (there was no change in resource, so this is expected now)
- page's cache is cleared again.
5. Page is visited a second time.
- page's cache is regenerated again and displayed (with updated resource now).

**Second - Cause in the Code**
The observation in (2) above originates at: https://github.com/wp-media/wp-rocket/blob/723d6c0181b7b3849c3e15bd60cdb2e0233a38f8/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L326-L327

**Scope for Solution**
At this point in order to have updated resources available immediately for the first time pages are sent for cache/usedCss regen, we should also add a check for changed resources and send to warmup, similar to what happens in the ResourceFetcherProcess: https://github.com/wp-media/wp-rocket/blob/723d6c0181b7b3849c3e15bd60cdb2e0233a38f8/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php#L183-L188

In this case, however, because we are truncating all usedCss, we will also have to check every item in the `rucss_resources` table, which will be a prohibitively expensive operation in cases where the table is large. (This is why we initially did not do this.)

**Comment by vmanthos** [comment]
Potentially related(?) as far as the background mechanism of not updated `wpr_rucss_resources` rows when resources changed is concerned: https://secure.helpscout.net/conversation/1629155029/294237?folderId=2135277

The customer updated plugins and after that sections of the homepage broke.
Disabling/enabling the option fixed the issues.

**Update**
Rethinking about this, in the case I mentioned, the change of the version of the resources could be involved: #4199

**Comment by iCaspar** [comment]
Indeed, disabling/re-enabling the feature will clear everything and start regenerating everything as for the first time, locking UsedCSS on the front-end until the pre-warmup completes (the initialization status bar reappears and all).

I think the end result of "turning it off and on again" is the result customers are expecting when they click the button. But as noted above, to actually do that requires scanning all the resources in the `rucss_resources` table for any changes all at once. It may be that the better way to handle "Clear Used CSS" button is, in effect, to automate dumping everything and re-running the pre-warmup.

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1661281740/301228/

**Comment by piotrbak** [comment]
Closed with 3.11
