### ISSUE TITLE
Provide the ability to only store gzipped HTML files

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3920]
**Is your feature request related to a problem? Please describe.**

We are currently storing both the GZIPped and non-GZIPped versions of HTML files.
If the following are enabled:
* **Separate cache for mobile devices**,
* The WebP feature
* Dynamic cookies

the number of HTML files stored for every URL can increase rapidly, especially in very large sites, **increasing the size** of the `/cache/wp-rocket/` folder.

**Describe the solution you'd like**

Nowadays, all browsers support GZIP:
https://caniuse.com/sr_content-encoding-gzip

It would make sense to at least allow disabling the creation of non-gzipped HTML files.

Keeping `.html` files would make sense as a fallback, e.g. in case of server incompatibility, where currently we suggest removing our gzip `htaccess` rules.

**Additional context**

**Related tickets:**
https://secure.helpscout.net/conversation/1515711595/264567/
https://secure.helpscout.net/conversation/1515325076/264449/

**Comment by DahmaniAdame** [comment]
From my testing, disabling the following two lines does the job: 

https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/classes/Buffer/class-cache.php#L335
https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/front/process.php#L359

And changing `.html` to `.html_gzip` on  https://github.com/wp-media/wp-rocket/blob/aea8f96b0725f900deaa337af2f87c37277676ff/inc/Engine/Preload/AbstractProcess.php#L242

does the job. 

Maybe we can add filters there with an option to tick in our UI?

**Comment by DahmaniAdame** [comment]
Related ticket - https://secure.helpscout.net/conversation/1521101198/266078/

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.

**Comment by placemania** [comment]
I would like to ask if this issue could be reconsidered/reopened.

This is becoming a real storage problem on large sites, especially when individual HTML documents are relatively large due to legitimate structured data.

On one production page I currently have:

* `index-https.html`: 674,802 bytes
* `index-https.html_gzip`: 94,381 bytes
* `index-mobile-https.html`: 674,799 bytes
* `index-mobile-https.html_gzip`: 94,381 bytes

That is about **1.54 MB of page cache for a single URL**.

I can disable the separate mobile cache, which removes one multiplier, but even then WP Rocket would still store:

* raw HTML: ~675 KB
* gzip HTML: ~94 KB

So the uncompressed copy represents roughly **88% of the storage used by that cache representation**.

On a site with many thousands of URLs, this becomes several GB of disk usage very quickly.

In my case, part of the HTML size comes from a large JSON-LD graph. I do not want to remove or reduce that structured data. The problem is simply that the same HTML is stored both compressed and uncompressed.

The site is also behind Cloudflare, so origin requests normally support gzip. For the extremely rare client that does not, falling back to an uncached WordPress response would be perfectly acceptable. There is no need to permanently store an uncompressed copy of every cached page just for that fallback case.

I also noticed that the technical solution was already identified in this issue in 2021:

* skip writing the uncompressed `.html` file
* keep generating `.html_gzip`
* make preload consider `.html_gzip` a valid existing cache

Even if adding a UI option is not desirable, a simple filter would already solve this for advanced users, for example:

`rocket_generate_uncompressed_cache_file`

with the default remaining `true`, so existing behavior would not change for anyone.

WP Rocket already knows how to serve the gzip cache directly, so this seems mainly to be a cache-generation/preload bookkeeping limitation rather than a delivery limitation.

For large sites, this small hook could reduce page-cache disk usage dramatically without changing frontend HTML, optimization behavior, or compatibility for existing users.

Would you consider reopening this issue, or at least adding a filter to disable generation of the uncompressed HTML cache file?
