### ISSUE TITLE
Delay JS - Automatically exclude scripts with invalid type 

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3944]
**Is your feature request related to a problem? Please describe.**

An invalid type will lead to a freeze during the delay JS process.

To fix that problem, we must not transform these scripts to be delayed.

Here a list of valid JS type:

```
'text/javascript',
'text/x-javascript',
'text/ecmascript',
'text/jscript',
'application/javascript',
'application/x-javascript',
'application/ecmascript',
'application/jscript'
'module'
```

**Describe the solution you'd like**
Detect and exclude automatically scripts with an invalid type.

**Comment by remyperona** [comment]
A future-proof approach instead could be to only allow scripts with a type corresponding to actual JavaScript, which is a check we already have in combine JS and we can re-use. And also if there is no type of course.

**Comment by GeekPress** [comment]
@Tabrisrp I have updated the issue to go on this way.

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :x: 
I couldn't reproduce it on local test site
the page didn't freeze Maybe because I use a theme without a lot of elements that use js

### Identify the root cause ✅ 
 delay JS work on all script types even if they are not valid

### Scope a solution ✅ 
We need to exclude the invalid js types from delay js

by adding a condition to check if JS type is valid or not here
https://github.com/wp-media/wp-rocket/blob/7606d7d737335854de9d0d633a9b4e6e4193c30d/inc/Engine/Optimization/DelayJS/HTML.php#L167-L177

the same condition used in combine JS
https://github.com/wp-media/wp-rocket/blob/7606d7d737335854de9d0d633a9b4e6e4193c30d/inc/Engine/Optimization/Minify/JS/Combine.php#L239

it will be like this

````
if ( strpos( $matches['attr'], 'type' ) !== false && ! preg_match( '/type\s*=\s*["\']?(?:text|application)\/(?:(?:x\-)?javascript|ecmascript|jscript)["\']|type\s*=\s*["\']?(?:module)[ "\']?/i', $matches['attr'] ) ) {
	return $matches[0];
}
````



### Estimate the effort ✅ 

Effort [XS]

**Comment by GeekPress** [comment]
> the page didn't freeze Maybe because I use a theme without a lot of elements that use js

@mostafa-hisham It's because the Delay JS inline script contains a part to avoid this bug. The goal is to remove the check in the inline script to be smaller and do the check directly when we are parsing the DOM.

**Comment by remyperona** [comment]
One addition to the RegEx we have in Combine, is that we also need to include the `module` type

**Comment by mostafa-hisham** [comment]
@Tabrisrp I updated the condition to include the `module` type and `jscript`
