### ISSUE TITLE
RUCSS - Display a notice when the API URL cannot be accessed

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#3947]
**Is your feature request related to a problem? Please describe.**

Currently, if a firewall is blocking outgoing connections to our RUCSS generator, nothing will be displayed to the user. This means a customer will have to reach out to our support for a solution.

**Describe the solution you'd like**

We should consider displaying error messages related to the API the way we already do for CPCSS.
Those will include URLs to our documentation and should reduce the number of tickets about RUCSS API issues.

**Additional context**

**Slack discussion:** https://wp-media.slack.com/archives/C43T1AYMQ/p1621863311062000

**Comment by GeekPress** [comment]
@vmanthos  @webtrainingwheels Do we have a doc about that particular problem we could redirect the user in the notice?

By the way, do you have any ideas about the text in this notice?

**Comment by vmanthos** [comment]
> Do we have a doc about that particular problem we could redirect the user in the notice?
We can redirect them here:
https://docs.wp-rocket.me/article/1529-remove-unused-css#basic-requirements
where we mention they need to allowlist the RUCSS IP.

> do you have any ideas about the text in this notice?

The following could work:

> It seems a security plugin or the server's firewall prevents WP Rocket from accessing the Remove Unused CSS generator. The following IP address `135.125.83.227` should be allowlisted:
>* in the security plugin, if you are using one
>* the server's firewall - your host can help you with this

If you prefer the message to be in one line maybe this will do:
> It seems a security plugin or the server's firewall prevents WP Rocket from accessing the Remove Unused CSS generator. Please allowist the following IP address `135.125.83.227` in your security plugin, if you are using one. Also, contact your host to allowlist the IP from the sever's firewall.

@webtrainingwheels may have a way to make this fancier/shorter.

**Comment by GeekPress** [comment]
@vmanthos Thanks a lot for the text. We can use the first one which will be easier to read.

**Comment by iCaspar** [comment]
Reproduce the Problem:
We do not currently display any notices when resources are not fetched and `WP_ROCKET_RUCSS_DEBUG` is not set.

Scope a solution:
Possible Solution 1:
We have a similar (nearly identical) issue #4126.
Should we implement the suggested `force_stop` in `rest_ensure_response()`, we could add the link to documentation into the `Pre-warmup could not finish.` notice.

Possible Solution 2:
In the reference to "the way we already do for CPCSS" -- CPCSS generates a collection of notices and displays them in the WP Admin notices section at the top of the page. In the case of RUCSS we decided during alpha against listing all the errors there. I recall 2 considerations for not doing it: The list of unprocessed files could be very long, the errors are being reported in conjunction with the status bar element via react rather than through the WP Notices and needed to be kept in the same react section of the page.

That said, we could:
1. In [`send_warmup_request()`](https://github.com/wp-media/wp-rocket/blob/2cb1b1d4952bc491f420e80dd4e97a39ba6bbde3/inc/Engine/Optimization/RUCSS/Warmup/ResourceFetcherProcess.php#L200), check for whether the response is an error and set a "resources_scanner_API_call_failed" flag in the options. 
2. When the pre-warmup hour is expired, after setting warmup status completed [here](https://github.com/wp-media/wp-rocket/blob/2cb1b1d4952bc491f420e80dd4e97a39ba6bbde3/inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php#L83), we can also check for the flag and if there has been a bad response, set a new WP Notice.

Note: Here we'd be setting the WP notice once at the end of the pre-warmup hour. I've considered that we could set the notice repeatedly every time there is a bad fetch response, however, it's likely that if there is an issue here, there will be multiple bad responses causing the WP notice to re-appear throughout the hour that the fetching process could run. On the other hand, we shouldn't short-circuit/stop the whole pre-warmup process for just a single bad fetch either. The down-side of setting it once at the end is that a user will have to wait the hour before seeing any notice appear.

Estimate Effort:
Either per solution for #4126 or [S] for "capture the flag."

**Comment by piotrbak** [comment]
This is going to be handled by:
https://github.com/wp-media/wp-rocket/issues/4338

**Comment by GeekPress** [comment]
@piotrbak Until to work on this which require some UI work too, we can display a notice like we are doing for CPCSS.

**Comment by jeawhanlee** [comment]
### Scope a solution
We can set a new option of an integer maybe `rocket_api_response_error` in this check that we will increment for each failed response.
https://github.com/wp-media/wp-rocket/blob/499eaf1bcfa79ef66191f287e3a63ea13851e378/inc/Engine/Optimization/RUCSS/AbstractAPIClient.php#L126
also reset option before this line when there is a successful call. https://github.com/wp-media/wp-rocket/blob/499eaf1bcfa79ef66191f287e3a63ea13851e378/inc/Engine/Optimization/RUCSS/AbstractAPIClient.php#L134

Then we create a new method in `WP_Rocket\Engine\Optimization\RUCSS\Admin\Settings` to check if `rocket_api_response_error` is >1 then we create a new notice and hook to `admin_notices` in `WP_Rocket\Engine\Optimization\RUCSS\Admin\Subscriber`

PS: With this I don't think the user will be getting this notice the first time they enable RUCSS though.

### Estimate Effort
[S]
what do you think @Tabrisrp
