### ISSUE TITLE
Used CSS folder shall be deleted when deleting the plugin

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#3966]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9
- Used the search feature to ensure that the bug hasn’t been reported before => No

**Describe the bug**
When deleting WPR, the used CSS folder is not deleted from the cache

**To Reproduce**
Precondition:
- RUCSS and OCD are on => having used CSS folder in cache

1. Deactivate WPR
2. Delete WPR
3. Check the cache folder => used CSS folder exists

**Expected behavior**
Used CSS folder is removed

**Screenshots**
![Screenshot from 2021-05-28 17-36-15](https://user-images.githubusercontent.com/76941962/120008447-3ef63d00-bfdb-11eb-9c61-51866447466c.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on local installation

### Identify the root cause ✅ 
The new `used-css` folder was not added in the list of folders to delete when uninstalling.

### Scope a solution ✅ 
In `inc/Engine/WPRocketUninstall.php`, add `used-css`  to the `$cache_dirs` property.

### Estimate the effort ✅
Effort `[XS]`
