### ISSUE TITLE
Don't apply Remove Unused CSS on pages protected by a password

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#3979]
**Is your feature request related to a problem? Please describe.**
When a page is protected by a password and RUCSS is turned on, the website is broken once the content is displayed after entered the password.

**Describe the solution you'd like**
Don't apply RUCSS on pages protected by a password to avoid broken layouts.

@wp-media/supportrocket This will require a mention in our documentation.

**Comment by remyperona** [comment]
There is a function we can use when we're on a post page to check if there is a password needed for the page: https://developer.wordpress.org/reference/functions/post_password_required/

**Comment by crystinutzaa** [comment]
### Reproduce the issue ✅ 
I did not checked it locally, but should be easy to be reproduced.

### Identify the root cause ✅ 
HTML content is updated after password is inserted, so SaaS will compute the used css for the password protected page and will never contain the full css.

### Scope a solution ✅ 
Don't apply RUCSS on pages protected by a password to avoid broken layouts.
Use the function :
`post_password_required( int|WP_Post|null $post = null )`
to identify if the post is protected or not. 
Add the check and bailout to TreeShake for the page in the `is_allowed()` function:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L117

### Estimate the effort ✅
Effort `[S]`

**Comment by GeekPress** [comment]
I'm decreasing the priority as protected pages aren't something common on websites, and users can easily turn off the option on the specific pages.

**Comment by engahmeds3ed** [comment]
We already exclude those pages from caching here: https://github.com/wp-media/wp-rocket/blob/44f9eae34f76dd75445f5b98ad9bc5c148cd0d9a/inc/functions/options.php#L331

So if this cookie is there, the page will not be cached and RUCSS isn't applied.

The only case that may be affected by that, if we use the filter `rocket_cache_reject_cookies` to remove `wp-postpass_` from this array but RUCSS can't reach this content.
