### ISSUE TITLE
RUCSS does not add the font-display="swap" property when Optimize CSS Delivery is not active

### ISSUE THREAD

**Issue by jorgemartine00** [wp-media/wp-rocket#3993]
**Before submitting an issue please check that you’ve completed the following steps:**
[x] Made sure you’re on the latest version
[x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In cases where origin font file is already minified and Optimize CSS Delivery is not enabled 

**To Reproduce**
1. Add a font with already minified data to website.
2. Enable minify CSS.
3. Leave Optimize CSS Disabled.
4. Enable Remove Unused CSS.
5. See font not getting font-display="swap" property added.

**Expected behavior**
When Optimize CSS Delivery is not enabled and font is already minified. Remove Unused CSS should add the font-display="swap" property.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced on local test site

### Identify the root cause ✅ 
RUCSS does not apply font display swap to font-family

### Scope a solution ✅ 
 use the apply_font_display_swap function in CSSTrait before saving used css in db or filesystem
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L350

we can do it like this

`$data['css'] = $this->apply_font_display_swap($minifier->minify());`

### Estimate the effort ✅ 

Effort [XS]
