### ISSUE TITLE
Partial cache clearing: Clear paginated taxonomies

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4035]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When we clear a post, we only clear the index page of the related taxonomy and not the paginated results (if any).

Example: 

- `/product-category/shoes` will be cleared
- `/product-category/shoes/2` won't be cleared (paginated taxonomy archive)

The same applies to any type of taxonomy. 

This would create stalled content on paginated taxonomy results. It's more inconvenient on WooCommerce (discounted prices not reflected for example).

**To Reproduce**
1. Have multiple posts/products on a taxonomy to enable the pagination
2. Pick an item from the second page
3. Change its name and update
4. Navigate to its related taxonomy 2nd archive page and see that the title wasn't updated
5. Alternatively, navigate to the taxonomy cache folder, and notice that the `/page` folder is still there, and browsing it will still show pages folders `/page/2`, `/page/3`... etc.

**Expected behavior**
WP Rocket should clear the full content of the taxonomy folder (including the sub-pagination pages) when updating a post or clearing a post-specific cache.

**Screenshots**
N/A

**Additional context**
This is unrelated and not resulting from the following issue as it covers other CPT taxonomies as well - https://github.com/wp-media/wp-rocket/issues/2068
Ticket - https://secure.helpscout.net/conversation/1535808661/269774/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by sriharsha-y** [comment]
seeing this issue on my website as well.....

**Comment by mostafa-hisham** [comment]
## Reproduce the problem :white_check_mark:
on local.

## Identify the root cause :white_check_mark:
After some digging with help of @engahmeds3ed
the `purge_post_terms_urls` function was not clearing pagination cache

## Scope a solution :white_check_mark:
we need to pass true as the second parameter to clear the pagination cache
https://github.com/wp-media/wp-rocket/blob/c53d551c38788c3ac1e171cf60b52af4c777c204/inc/Engine/Cache/Purge.php#L169
## Estimate the effort :white_check_mark:
effort: [XS]

**Comment by Apfelbiss** [comment]
Hello,

we also noticed this bug with fright last days. When can we expect a fix here?

The bug is only marked with priority "medium", but at least with effort "XS", so I hope this can be fixed soon.

In a large store with many paginated categories, there is a great risk of outdated information for up to 10 hours because of this bug. A complete deletion of the cache (or at least the shop category folder via FTP) is not a practical solution for a large store.

Thank you in advance.
