### ISSUE TITLE
Closing promotion banner will close congratulations banner

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4064]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version = > Yes 3.9.0.2
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
When the user closes the promotion banner, the congratulations banner is closed

**To Reproduce**
- Having an active promo displayed on the dashboard

1. Go to dashboard
2. Close the promotion banner
3. Congratulations banner is closed too

**Expected behavior**
Congratulations banner not closed

**Screenshots**

https://user-images.githubusercontent.com/76941962/122421787-edfbb800-cf8c-11eb-8b75-bb483731e576.mp4

**Additional context**
- Congratulations banner will be back after refresh

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on test site

### Identify the root cause ✅ 
This is happening because the selector to close the congratulations notice is shared with other notices. It should be more specific.

### Scope a solution ✅
in `views/settings/dashboard.php`, add `id="wpr-congratulations-notice"` to the link to close the notice
in `src/js/global/main.js`, replace `.wpr-notice-close` by `#wpr-congratulations-notice`
Run `gulp build` to regenerate the JS
 
### Estimate the effort ✅
Effort `[XS]`
