### ISSUE TITLE
Defer JS exclusions are still applied to Combine JS even if Defer JS is disabled

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4089]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When an exclusion is added to Defer JS it is automatically added as an exclusion to Combine JS. 
When Defer JS is disable, the exclusion is still applied to Combine JS. 

**To Reproduce**
1. Add an exclusion to Defer JS and turn the feature off
2. Enable Combine JS
3. See that the Defer JS exclusion is still applied to Combine JS

**Expected behavior**
When Defer JS is disabled, any of its exclusions shouldn't be applied to Combine JS. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1545856796/272249/
Slack discussion - https://wp-media.slack.com/archives/C08N8J6VC/p1624446092105300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
in `Combine::is_defer_excluded()`, we don't check to see if the defer JS option is enabled, so the exclusions are always applied

### Scope a solution ✅ 
A good approach would be to update the `DeferJS::get_excluded()` method, to add a conditional check for `can_defer_js()` at the start. If the condition fails, return an empty array.

Update related tests to validate the changes

### Estimate the effort ✅
Effort `[S]`
