### ISSUE TITLE
Enable HTTP Auth to Access the RUCSS and Optimize CSS delivery Generators

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#4098]
**Is your feature request related to a problem? Please describe.**
When a website (usually a staging site) is using HTTP Auth, it can't access or test the Remove Unused CSS and Optimize CSS delivery features.

**Describe the solution you'd like**
Add the option to set HTTP Auth details (user and password) to access the Remove Unused CSS and Optimize CSS delivery generator tools, while a website is using HTTP Auth. Similar to what [GTmetrix allows already](https://i.imgur.com/YjQFYtb.png).

This would allow users to test these two features in their stating environments, very safely.

**Additional context**
Related ticket here: https://secure.helpscout.net/conversation/1552152884/274117?folderId=2675957.

Thanks!

**Comment by piotrbak** [comment]
@mostafa-hisham can we set SaaS to go through the HTTP Auth? (asking just theoretically)

**Comment by GeekPress** [comment]
We are closing this issue as we won't do this enhancement.

Why?
- No other requests since a year
- Async CSS has been released for years, and it has been never discussed.
- It concerns a very few users
- Users still have the possibility to temporarily deactivate their htpassword.

For these reasons, we don't want to complexify our features.
