### ISSUE TITLE
Update DelayJS script to the latest version

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#4099]
For the 3.9.0.5 release, we need to update the delayJS script to the latest version available. This version fixes a bug related to successive `window.onload` events.

**Comment by ghost** [comment]
@Tabrisrp,

If you don't mind, prior to releasing 3.9.0.5, can you guys reactivate (re-allow) the simultaneous use of "Combine Javascript Files" and "Delay Javascript Execution."? (Ref: [Github Issue No. 4097](https://github.com/wp-media/wp-rocket/issues/4097))

The above change --introduced in 3.9.X.X -- caused our website to slow down due to additional HTTP Call Requests generated by the imposed limitation. Quite sure many other websites are experiencing the same.

Thank you!
