### ISSUE TITLE
Upgrade Monolog to version 2

### ISSUE THREAD

**Issue by Kilbourne** [wp-media/wp-rocket#4105]
I'm installing WpRocket via Composer and the monolog version conflicts with [another package](https://github.com/roots/acorn) which require v2 

Please update to monolog  ( should be pretty easy to update it and probably requires no changes [https://github.com/Seldaek/monolog/blob/main/UPGRADE.md](https://github.com/Seldaek/monolog/blob/main/UPGRADE.md)

**Comment by flosteve** [comment]
The same here. That would be nice. Many thanks

**Comment by remyperona** [comment]
### Scope a solution ✅ 
This should not cause any issue for us, based on what we use monolog for. Still, we will want to do it in the next major version just in case.

In `composer.json`, change the version number for monolog to `2.0`.

### Estimate the effort ✅
Effort `[XS]`

**Comment by remyperona** [comment]
I'm moving this back to grooming, as the version 2.0 requires PHP 7.2, and this might cause issue for our users on PHP 7.0/7.1  if we update.

**Comment by Kilbourne** [comment]
@Tabrisrp   Shouldn't Composer be able to choose the right version of the package  based on the php version defined inside the user's composer.json?

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1767587006/321585/

It is causing conflict with conflict with **Simple Schedule Appointments** plugin and fatal error due to different versions of Monolog are used:

`Fatal error: Declaration of Monolog\Handler\StreamHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in /srv/users/shepherdsloft/apps/shepherdsloft/public/wp-content/plugins/wp-rocket/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 93`

More details are in the ticket.

**Comment by kamilgrzegorczyk** [comment]
Is there any update on when that is going to be resolved?

**Comment by tombroucke** [comment]
In the last few websites I published (Using Sage 10), WP Rocket is not installed because of this issue. roots/acorn requires illuminate/log^8.70, which in turn requires monolog/monolog^2.0.

Is this issue still on your roadmap?

If it's not, all of us who use Bedrock + Sage 10 will need to find another solution (One way would be to handle the plugin through satispress, hoping that the different monolog versions won't conflict).

**Comment by lhall-amphibee** [comment]
I'm having the same issue on a Themosis install (using Illuminate as well).

**Comment by remyperona** [comment]
### Scope a solution ✅ 
In `composer.json`, change the version number for monolog to `^1.0 || ^2.0`.

In `.github/workflows/deploy_plugin.yml`, change the php version used to `7.1`, to ensure the deployed version uses the minimum supported version when building the zip file.

This solution should allow installation for anyone using composer, while still making sure our build version is working for users downlading the zip file via the usual way.

### Estimate the effort ✅
Effort `[XS]`
