### ISSUE TITLE
Add auto-exclusion for Divi

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4109]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Divi is adding a small inline script to add a `js` class to the body. We need to exclude this inline script as it could lead to not have a section or animation loaded until user interaction.

To reproduce the « issue », you just need to check on a website using Divi that the inline script is automatically delayed.

**Expected behavior**
Exclude automatically the inline script.

**Additional context**
The inline script:

<script type="text/javascript">
document.documentElement.className = 'js';
</script>

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by webtrainingwheels** [comment]
Just an FYI, I had a couple of cases of Divi animated elements not loading immediately, but excluding this inline script did not resolve it. 
Not sure if it's because I tried it on sites using Divi 4.10+  or something else. I needed to exclude these for the animated parts to work: 
/wp-includes/js/jquery/jquery.min.js
/wp-includes/js/jquery/jquery-migrate.min.js
/themes/Divi/js/scripts.min.js
Can be tested on mega.

**Comment by mostafa-hisham** [comment]
I think the work we did in this issue #4263  should fix this

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1702421034/308998?folderId=273766

This site was using the "Extra" theme.

@mostafa-hisham In #4263 I'm not seeing anywhere an exclusion for `document.documentElement.className` from the Delay JavaScript Execution feature. Am I missing something?

**Comment by piotrbak** [comment]
Fixed in the 3.13 backend

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
