### ISSUE TITLE
Don't add anymore the default exclusion list

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4111]
**Is your feature request related to a problem? Please describe.**
As explained on [our Slack](https://wp-media.slack.com/archives/G087NJ788/p1624905161247900), we decided to not add anymore the default exclusion which is breaking too many websites.

**Describe the solution you'd like**
Don't add the default exclusion for users who update from 3.7/3.8.

**Additional context**
For users who already updated to 3.9 and have the default exclusion list, we shouldn't remove the list.

**Comment by ghost** [comment]
Uh hum, we like the default JS file exclusion list. However, the plugin can be auto-loaded with the "Delay JS Execution"feld blank, but then offer customers a chance to add the recommend JS exclusion list provided in your knowledgebase. Your KB can start by listing what you already have in V3.8.8 and expanded later, as necessary.

**Comment by hamidpeya** [comment]
Delay JS is a great option and I would say the current update 3.9.0.5 is good for beginners as it will automatically delay all the JS. But upon my initial test, I have found that the plugin missed a few JS files that could be delayed. Those JS files were related to the plugins that came with the theme. And I think, for such cases, there should be an option to input such JS paths that were missed by auto delay.

**P.S** I vote for the old approach though. Where we could easily add the JS paths by closely analyzing the JS loading on the website.

**Comment by GeekPress** [comment]
@hamidpeya Hi 🤚

All JS files should be delayed, if it's not the case for you, it's an issue. Can you please the URL of the website? It will be very helpful to see the problem in reality.

Thanks

**Comment by hamidpeya** [comment]
@GeekPress Hi 👋 

Thanks for the reply, I have investigated it further and the issue is quite opposite. I have added the [given rule](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#advanced-ads) to exclude jquery for the plugin Advanced Ads, and that resulted in excluding all Jquery .js, the ones that could be delayed.

Site: docformats.com
JS didn't delay: https://cln.sh/olttOR
JS excluded: https://cln.sh/3LazY2

Issue: Jquery related to a few plugins, e.g PowerKit, Canvas, Easy TOC, could be delayed manually. In my case, I guess it will consume more time to find the correct Jquery to exclude while keep delaying the ones that should be delayed. The old method could allow me to just add the js that should be delayed.

**Comment by GeekPress** [comment]
Please add this line to exclude only the right jQuery => wp-includes/js/jquery/jquery.min.js

**Comment by hamidpeya** [comment]
It worked like a charm. Thanks 🙏

**Comment by GeekPress** [comment]
@hamidpeya Could you please contact me at jonathan [at] wp-media.me and share your WordPress credentials?

I would like to check something on your site.

**Comment by hamidpeya** [comment]
@GeekPress I will have to create a staging site. Once done, I will share it with you.

Cheers!

**Comment by GeekPress** [comment]
@hamidpeya You rock :) Thanks a million
