### ISSUE TITLE
Re-Opening Issue | Closed Without Fair Consultation (GH Issue No. 4097)

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4113]
[Subject GitHub issue](https://github.com/wp-media/wp-rocket/issues/4097) was closed without consultation or giving us the opportunity to interact with DevOps.

DevOps missed our point. Our specific request is to leave "Combine JS Files" and "Delay JS Execution" open for customers to use individually or in combination. Currently, WPR V3.9.0.4 removed that ability. Please reinstate the options as provided in V3.8.8.

Please review again and DO NOT close this topic before giving us a chance to explain better - if necessary.

Thank you!

**Comment by gevcen** [comment]
I'm a user like you but I think there are fair reasons why WP Rocket would not return back on this situation.

1. Combining is something that has no relevancy nowadays. It used to be useful when servers were only able to send requests one after the other with HTTP1, but now if you have a server that isn't on HTTP2 then you should probably change host because that means staying far behind on technologies. HTTP2 is a must today, let alone the fact that HTTP3 is currently rolling-out and already available on Cloudflare for instance. Even GTmetrix and PageSpeed Insights have deprecated this Combining requirement because it has no real added-value anymore.

2. You're requesting to allow users to use two features simulatenously while WP Rocket knows perfectly well that these two features may not work correctly if enabled at the same time. Considering that the target audience of WP Rocket are users who are not necessarily very much familiar with technical configurations, they have a fair point in disabling one of them while the other is enabled. They want to ensure that their program runs smoothly for their users, and it's understandable. Try contacting the support with a ticket and maybe they could provide a custom shortcode which could re-enable the option manually?

3. In #4097, WP Rocket has answered with some external documentation that gives quite some reasons to not combine anymore, which should be enough to answer your point.

**Comment by ghost** [comment]
@gevcen,

Thank you for your valuable information. Regardless, WP Rocket should still retain both options. Users can always "uncheck" the feature that is causing the issue or not working for them. For example, the option "Optimize CSS Delivery" does not work well for us so we don't select it.

Also, no matter how much we say about HTTP/1, HTTP/2, and HTTP/3, the final verdict is driven by website performance data which varies depending on each website's design and structure. 

The [article](https://wpjohnny.com/why-you-shouldnt-combine-css-js-performance-reasons/) shared by @GeekPress is useful (lots of words but no data to support it though), but if you read the comments section of the article, it is clear that combining JS assets and delaying JS execution simultaneously works better for "light" websites. Ergo, the reason for our request. There is no need to request a separate Code Snippet form WP Rocket (after the fact) when the function is already available within the plugin (well, up to V3.8.8).

Not trying to be smart, but have you conducted tests using Combine JS Files and Delay JS Execution together and separately? Do you have performance data noting the differences? Can you share it?

Again, thank you!

PS: Our host (and website) is HTTP/2 and HTTP/3 compliant.

**Comment by gevcen** [comment]
@Jetxpert

Let's try to make a theorerical thinking of the simultaneous use of those features.

Let's start from the premise that you use Delay JS in its latest version, that is delaying ALL scripts, except :

- certain specific that are automatically excluded by WP Rocket for auto-compatibility purpose,
- AND scripts manually added in the exclusion by the users for manual compatibility purpose (whose list certainly won't be very big as this feature will become more stable over time)

This means that already at least 90% or more of your website's scripts will be delayed. It's a guess number but I just think that an extremely high ratio of your scripts will already be delayed.

Therefore, it means that the other options Combine, Defer are there to take action only on the remaining 10% that cannot be delayed. In such case, the "issue" of Combine not being available simultaneously gets diminished.

**Comment by ghost** [comment]
@gevcen,

Let users have control of what we they need for their website(s). You're taking away what we liked. We're not alone.

Please read [GitHub Item No. 4023](https://github.com/wp-media/wp-rocket/issues/4023) for our recent input on this topic.

If no improvements are made based on our feedback (and many others), we'll just have to cancel our subscription and take our business elsewhere. It's that simple.

Thank you.
