### ISSUE TITLE
Multiple CSS files arenot removed from page source while RUCSS + Woocommerce are enabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4119]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.0.5
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
CSS external files aren't removed from the source while Woocommerce is enabled

**To Reproduce**
Precondition:
- Woocommerce enabled
- RUCSS enabled after fresh install

1. Either create a new page template and check the source or
2. Clear used CSS and access existing page template and check its source i.e https://new.rocketlabsqa.ovh/template4071/
3. Multiple CSS files are still in the source 

**Expected behavior**
CSS files are removed from the source

**Screenshots**
![Screenshot from 2021-06-30 18-50-08](https://user-images.githubusercontent.com/76941962/124000649-185d6480-d9d4-11eb-9903-22b39814f5d6.png)

**Additional context**
- Disable Woocommerce plugin will fix the problem
- After discussion with @engahmeds3ed it impacts from this change #4017 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
Using the following template
```
<!DOCTYPE html>
<html lang="de-DE" >
<head>
    <meta charset="UTF-8" />
    <title>template3813 &#8211; News Portal Elementor</title>
    <meta name='robots' content='max-image-preview:large' />

    <noscript></noscript>
    <link rel='stylesheet' id='avia-grid-css'  href='https://www.autohaus-glienicke.de/wp-content/themes/enfold/css/grid.css?ver=4.8.3' type='text/css' media='all' />
    <noscript></noscript>
</head>
<body>
<h1>Hi Ahmed</h1>
</body>
</html>
```

and the root cause is this regex
https://github.com/wp-media/wp-rocket/blob/1c126a97668b9bb6486bd0a1cc35b705900246cd/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L432-L438

you can find the regex test here: https://regex101.com/r/lAVZrF/1/

**Summary:**

Any linked resources between two noscript tags, will not be removed from the page.
```
<noscript></noscript>
XXXXXX
<noscript></noscript>
```

**Comment by iCaspar** [comment]
The following is close:
```
(?<=<noscript>).*(<link\s+([^>]+[\s"\'])?href\s*=\s*[\'"]\s*?([^\'"]+\.css(?:\?[^\'"]*)?)\s*?[\'"]([^>]+)?\/?>).*(?=<\/noscript>)(*SKIP)(*FAIL)|<link\s+([^>]+[\s"\'])?href\s*=\s*[\'"]\s*?([^\'"]+\.css(?:\?[^\'"]*)?)\s*?[\'"]([^>]+)?\/?
```
Play with it here: https://regex101.com/r/vhs2HJ/1

The issue is with the `(*SKIP)` -- including it will work correctly when there is a link inside the noscript, but NOT when there is any other noscript content without a link. On the other hand, removing (*SKIP) fails as all the links are matched by the link pattern after the `|`.

**Comment by engahmeds3ed** [comment]
I tried today the main regex and Caspar's regex and both are working in all cases but if we used the modifiers `gi` only.

We can pass `i` to `find` method call and everything would be fine, I will create a PR with that change and add some test fixtures.
