### ISSUE TITLE
Remove Unused CSS missing to clean @Keyframes

### ISSUE THREAD

**Issue by wpsumo** [wp-media/wp-rocket#4146]
Wanted to mention that I saw the RUCSS miss to remove unused `@keyframes`.

**To Reproduce**
1. Add some `@keyframe` css or install oxygen builder (which has several of predefined `@keyframes`)
2. Select 'Remove Unused CSS'

**Expected behavior**
The CSS should be removed from used CSS. As this is not used anywhere RUCSS should be able to remove this.

**Additional context**
I was testing with Oxygen builder so use it for testing.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@Tabrisrp Should we move it to Tree Shaker or CSS Parser?

**Comment by remyperona** [comment]
Preserving keyframes is a safety measure, because keyframes are declaring animations to be used inside other CSS properties.

This is different from what we are doing, where we are matching CSS declaration against CSS selectors.

It does increases the resulting CSS size a bit, but we make sure the animation declaration is there if needed.

**Comment by wpsumo** [comment]
@Tabrisrp Make sense maybe a "blacklist" feature would be useful where the user can insert selectors including keyframes to be removed?

**Comment by piotrbak** [comment]
@wpsumo this issue is resolved in the 3.11, we are removing unnecessary `@keyframe`
