### ISSUE TITLE
Exclude Autoptimizer's lazy loading from Delay JavaScript Execution

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4162]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When **Autoptimize lazy load for images** is activated in addition to **Delay JavaScript Execution**, images will only start showing after user interaction with the page. 

This applies also to all lazy-loaded images above the fold 

**To Reproduce**
1. Enable `Autoptimize > Images > Lazy-load images`
2. Enable `WP Rocket > File Optimization > Delay JavaScript Execution`
3. Check a page with images above the fold.
4. No image will be disabled on page load

**Expected behavior**
Images should be disabled on page load.

**Screenshots**
N/A

**Additional context**
Excluding the following script from Delay JavaScript Execution fixes the issue: 
```
/wp-content/plugins/autoptimize/classes/external/js/lazysizes.min.js
```

Ticket - https://secure.helpscout.net/conversation/1563176107/277006/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by GeekPress** [comment]
@Tabrisrp What about replacing EWWW exclusions (https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/DelayJS/HTML.php#L39) to just `lazysizes.min.js`?

**Comment by webtrainingwheels** [comment]
Can we do a regex?  Because Avada uses `lazysizes.js` which needs excluding. Or, should I make a separate issue for that?

**Comment by GeekPress** [comment]
> Or, should I make a separate issue for that?

A regex should be fine.

**Comment by iCaspar** [comment]
Grooming Notes:

### Can Reproduce: ✅ 
Note that on Rocket 3.9.1: In addition to the OP, the conditions for reproducing this happen locally only when the default exclusions are **_not_** added in the DelayJS UI. (ie, pasting the default exclusions resolves the issue.)

### Root Cause:
The autoptimize path for `lazysizes.min.js` is not part of our auto-excluded compatibility list: https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/DelayJS/HTML.php#L26

### Scope a Solution:
- Remove both ewww-specific paths from the already present exclusion, to be simply `lazysizes.min.js` per @GeekPress comment, above.
- Replace duplicate `lazysizes.min.js` entry with unminimized `lazysizes.js` (for additional Avada compat, per @webtrainingwheels request, above.)
- Add sample scripts to test fixture to varify script is excluded for all ewww / autoptimize / avada versions. 

### Estimated Effort:
[XS]
