### ISSUE TITLE
Cache clear notice shall be dismissed after clear the used CSS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4212]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version -> 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before -> yes

**Describe the bug**
Clear cache notice shall be removed if we clear used CSS as it already clears the cache

**To Reproduce**
Precondition:
- RUCSS is enabled

1. Enable/disable any plugin that will make clear cache notice of WPR be displayed i.e enable WPML plugin
2. Clear the used CSS from the Admin bar
3. Clear cache notice is still displayed

**Expected behavior**
Clear cache notice is automatically dismissed

**Screenshots**

https://user-images.githubusercontent.com/76941962/127625527-4db02cad-83bd-4030-b6cc-87574548d06e.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced on test site

### Identify the root cause ✅ 
We don't dismiss the notice when clearing the used CSS, even though we do clear the cache at the same time

### Scope a solution ✅ 
In `RUCSS\Admin\Subscriber::truncate_used_css_handler(), add a call to `rocket_dismiss_box( 'rocket_warning_plugin_modification' )` after the call to `rocket_clean_domain()`

### Estimate the effort ✅
Effort `[XS]`
