### ISSUE TITLE
Automatically exclude jQuery from being deferred when Revolution Slider is activated

### ISSUE THREAD

**Issue by GeekPress** [wp-media/wp-rocket#4229]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before - Yes

**Describe the bug**
Since the last Revolution Slider update (6.5.5), our Defer JS option isn't compatible anymore. We need to exclude jQuery and jQuery migrate to be compatible.

**To Reproduce**
1. Turn on Defer JS without any exclusion
2. Go to a page with a slider created with Revolution Slider
3. See error: The slider isn't displayed and a JS error is triggered

**Expected behavior**
The slider is correctly displayed when our Defer JS option is enabled. For that, we need to detect if Revolution Slider is activated and automatically exclude jQuery and jQuery Migrate from the Delay JS option.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
**Reproduce the problem**
No, but i can see the problem

**Identify the root cause**
We need to exclude jQuery and jQuery migrate to be compatible with the Revolution Slider update (6.5.5),.

**Scope a solution**
-We need to create a new third party for RevolutionSlider and exclude the jquery and jquery migrate if  RS_REVISION > '6.5.5'
```
	public static function get_subscribed_events() {
		if ( ! defined( 'RS_REVISION' ) || version_compare( RS_REVISION, '6.5.5', '<')) {
			return [];
		}

		return [
			'rocket_exclude_defer_js'              => 'exclude_defer_js',
		];
	}
```

```
	public function __construct( Options $options_api, Options_Data $options ) {
		$this->options_api = $options_api;
		$this->options     = $options;
	}
```

**Estimate the effort**
[S]
create tests

**Comment by Mai-Saad** [comment]
Note:
- couldn't reproduce it with Avada but it was reproducible using Twenty Twenty theme
- fixed when excluded jquery.js and jquery-migrate.js
![Screenshot from 2021-08-10 10-58-21](https://user-images.githubusercontent.com/76941962/128839542-19b5b9d7-4e14-4712-9f93-b53561360d71.png)

**Comment by piotrbak** [comment]
Revolution Slider loads his files on all pages, no matter if the slider is present on the page or not. With this PR we are excluding jQuery from Defer JS on all pages.

I can see a possible enhancement to this PR. On pages that contain Slider, we **need to** exclude jQuery files. However, on pages that do not contain the Slider, we could automatically switch their scripts to have `defer` attribute instead of `async` and we'll be able to defer the jQuery on those pages then without any errors in console.
![image](https://user-images.githubusercontent.com/26767037/129353699-b303d494-2fc3-4714-9aec-1ea68142cb5f.png)

What do you think @GeekPress ?

I'm not sure if we're able to detect whether the slider is present on the page or not though...

**Comment by GeekPress** [comment]
@piotrbak Changing their script to be loaded async or defer won't change our problem. We have the issue because of an inline JS.
