### ISSUE TITLE
Delay JS (Error 500):  Uncaught Error: Call to a member function get_gallery_image_ids() on bool

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#4255]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ - 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
We are using the function wc_get_product() and that function can return these possible values: WC_Product | null | false ([Reference](https://woocommerce.github.io/code-reference/namespaces/default.html#function_wc_get_product))

And here it seems that we are not handling all the possible return values: 

https://github.com/wp-media/wp-rocket/blob/a38f5b6aa1853d221b97ebbaa9ef9638cafd7e2c/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L515

That causes when the function returns false, we get and error when trying this:

https://github.com/wp-media/wp-rocket/blob/a38f5b6aa1853d221b97ebbaa9ef9638cafd7e2c/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php#L516

The full error is:

> PHP Fatal error:  Uncaught Error: Call to a member function get_gallery_image_ids() on bool in /srv/users/signetprelive/apps/signetprelive/public/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php:516

**Expected behavior**
The site shouldn't throw an error 500.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by sandyfzu** [comment]
Ticket: https://secure.helpscout.net/conversation/1598350594/286878/

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Don't need to

### Identify the root cause ✅ 
In the case where the function returned null or false, we are trying to use a class method on an object that doesn't exist, causing the fatal error

### Scope a solution ✅ 
in `inc\ThirdParty\Plugins\Ecommerce\WooCommerceSubscriber::product_has_gallery_images()`, add a conditional check to validate that the `$product` variable is not false or null (or to validate that it's an instance of WC_Product), before trying to use the class method.

If the condition fails, return `false`.

### Estimate the effort ✅
Effort `[XS]`

**Comment by vmanthos** [comment]
Related ticket: https://secure.helpscout.net/conversation/1614733415/290757/
