### ISSUE TITLE
WooCommerce link in Never Cache URL description isnot working

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4260]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.1.1
- Used the search feature to ensure that the bug hasn’t been reported before => Yes

**Describe the bug**
WooCommerce link in Never Cache URL description is not working

**To Reproduce**
1. Activate WooCommerce plugin
2. go to the Advanced rules tab in WPR
3. Click WooCommerce link in Never Cache URL description
4. There was a problem retrieving the article

**Expected behavior**
Article displayed correctly

**Screenshots**
![link](https://user-images.githubusercontent.com/76941962/130065202-7ece351c-8b0b-456a-9f24-dde96b494736.jpg)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on local site

### Identify the root cause ✅ 
The documentation page was removed, and its content migrated to https://docs.wp-rocket.me/article/27-using-wp-rocket-on-your-ecommerce-site

### Scope a solution ✅ 
In `inc\Engine\Admin\Beacon\Beacon::get_suggest()`, replace the old link in the `ecommerce` array key by the new link and ID for the english version.

### Estimate the effort ✅
Effort `[XS]`
