### ISSUE TITLE
WP Rocket NOT DISCLOSING Features Roadmap to Public | Impossible to Vote for Proposed Features

### ISSUE THREAD

**Issue by ghost** [wp-media/wp-rocket#4277]
Team WP Rocket continues to propose and implement plugin changes without consulting its customers. This forum serves as the BEST EXAMPLE of this finding.

Based on the above, we highly recommend the following:

(1) Team WP Rocket shall not implement any "EPIC" (many times disastrous) plugin changes unless they are put for a vote. The so-called WP Rocket "Public Roadmap" is either not active, not working, and/or there is no option to vote for any proposal.

Affected URLs:

https://wp-rocket.me/blog/development-roadmap-public/
https://trello.com/b/CrUcz6Jy/wp-rocket-roadmap
https://portal.productboard.com/wp-media/3-rocketcdn-portal/tabs/5-suggestion-box/1-wp-rocket-portal

(2) Team WP Rocket shall not implement any "EPIC" or major plugin changes until existing (and released) plugin BETA features are FIXED. A good example of this is RUCSS. Currently, there are approximately 55 unresolved RUCSS issues.

(3) Team WP Rocket shall compile data, develop charts, and publish metrics from [feature requests submitted by customers behind the scenes](https://wp-rocket.me/blog/development-roadmap-public/#section-1) and from this forum (i.e., GitHub).

(4) Team WP Rocket shall develop, implement, and publish a website dedicated to feature requests and offer the ability for its customers to vote on them. An EXCELLENT EXAMPLE of this much-needed, extremely successful tool is the [Feature Voting website offered by Theme-Fusion (Avada)](https://theme-fusion.com/feature-voting/). 

Above recommendations are aligned with world-renowned best community practices and [WordPress' philosophy](https://wordpress.org/about/philosophy/).

And if Team WP Rocket -- especially its decision makers and co-owners -- believe that a few, paying customers cannot make a difference in the positive development and growth of its plugin, please remember this:

"Even the greatest ships can sink one small leak at a time." -- Thomas A. Edison

**Comment by androidacy-user** [comment]
Why do you think you're more special than all the other paying customers?

You open issue after issue complaining the they didn't consult _you_ before doing anything. Do you notice a difference in tone between you and everyone else? You're acting entitled, that's what.

> [...] Team rocket shall [...]

> [...] WP Rocket shall not [...]

Wait, are you giving orders now? I don't recall the part where you were any leadership in WP Media.

> [...] believe that a few, paying customers cannot make a difference in the positive development and growth of its plugin [...]

And making threats too, nice.

Whenever you purchase a product, you are paying for the product as is. When buying software, you're acknowledging that the product may change, remove features, and otherwise be modified at the sole discretion of the developers. They are not obligated to listen to or follow your advice, orders, or suggestions, although many do listen, if not always implement, suggestions, once again at their own discretion. They are also under no obligation to share, divulge, or otherwise encourage you to participate or be knowledgeable about their roadmap.

At any rate, please keep this off GitHub. This repository is to track development of WP Rocket, not for you to air out your personal opinions on the actions WP Media takes. I believe there are other forms of contact for such issues.

**Comment by jbma** [comment]
Hi Jetxpert,
Thank's (again) for your contribution. Github isn't a forum, that's where our developpement, product and support team is working; 
This feedback isn't really accurate here, and I'm going to quote again the WordPress philosophy which we follow : 

> The Vocal Minority
> There’s a good rule of thumb within internet culture called the 1% rule. It states that “the number of people who create content on the internet represents approximately 1% (or less) of the people actually viewing that content”.
> 
> So while we consider it really important to listen and respond to those who post feedback and voice their opinions on forums, they only represent a tiny fraction of our end users. When making decisions on how to move forward with future versions of WordPress, we look to engage more of those users who are not so vocal online. We do this by meeting and talking to users at WordCamps across the globe, this gives us a better balance of understanding and ultimately allows us to make better decisions for everyone moving forward.

**Comment by Jetxpert** [comment]
@androidacybot,

We typically don't respond to Bots, but we'll make an exception in your case.

Did you read the first part of our entry? "... we highly recommend..."

Knock yourselves out.

Cheers!
