### ISSUE TITLE
Always Purge URL(s) box - prevent full cache clearing when adding a / 

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4280]
**Is your feature request related to a problem? Please describe.**
When a customer adds a `/` inside the **Always Purge URL(s)** textarea, the whole cache is deleted whenever a post or page is updated.
It can be the case when customers want to clear the homepage cache after any update/additon.

<img width="785" alt="Screen Shot 2021-08-24 at 11 49 43 AM" src="https://user-images.githubusercontent.com/229406/130638909-cc510f0b-d13c-4c94-950c-74b66caab905.png">

**Describe the solution you'd like**
We could prevent this by: 
- Invlude a green text warning saying that if the `/` is used it will clear the full cache.
- Automatically sanitize it and remove it.
- just ignore this parameter.
- suggest the usage of ` /(*)` for full cache deletion.

**Additional context**
This is a customer suggestion: 
https://secure.helpscout.net/conversation/1609717265/289471?folderId=2683093

**Comment by mostafa-hisham** [comment]
### Reproduce the issue ✅ 
Reproduced locally

### Identify the root cause ✅ 
when adding "/" inside the Always Purge URL(s) Textarea, the whole cache is deleted whenever a post or page is updated.

### Scope a solution ✅ 
edit the green notice under the textarea to say that if the / is used it will clear the full cache.
add "<br>Use / to clear the full cache." to the end of the text
https://github.com/wp-media/wp-rocket/blob/745167427c51a0766f63a97eec7c23ebfbbff2ef/inc/Engine/Admin/Settings/Page.php#L1384

### Estimate the effort ✅
Effort `[XS]`

### Another solution ✅ 
is to check if the URL is going to be deleted is "/" and don't add to purge URLs
inside the foreach
 https://github.com/wp-media/wp-rocket/blob/745167427c51a0766f63a97eec7c23ebfbbff2ef/inc/common/purge.php#L119-L131
```
			if ( '/' === $page) {
				continue;
			}
```
### Estimate the effort ✅
Effort `[XS]`

**Comment by vmanthos** [comment]
@mostafa-hisham In the alternate solution you suggested, maybe we can run `rocket_clean_home()` when `'/' === $page` to clear the cache of the homepage:
https://github.com/wp-media/wp-rocket/blob/745167427c51a0766f63a97eec7c23ebfbbff2ef/inc/functions/files.php#L579-L661

**Comment by mostafa-hisham** [comment]
@vmanthos the home page is going to be cleared after any post or page update
it will be called here rocket_clean_post line 242 (Update cache when a post is updated or commented)
 https://github.com/wp-media/wp-rocket/blob/745167427c51a0766f63a97eec7c23ebfbbff2ef/inc/common/purge.php#L186-L259
 so no need to call it in the condition

**Comment by vmanthos** [comment]
You are right. Thank you!

**Comment by blogtutor** [comment]
I don't think adding `Use / to clear the full cache` to the notes is a reliable solution. Most users don't read the fine print, and I think it's a bit confusing since `/` _should_ mean _only_ the homepage -- especially since the instructions explicitly say to use a wildcard for multiple paths.

Based on the proposed solutions so far, I think the best solution is "just ignore this parameter."

This will still have the desired effect for a customer who intends to purge the homepage with every cache clear (since that already happens), and it will not be possible for them to accidentally cause the full cache to be purged every time -- which is most likely unintended, and can be highly problematic. (In the case where we discovered this, it was a high traffic site -- millions of pageviews/day -- and the cache was being purged as frequently as every 15 seconds, and the server was getting overloaded.)

If the user truly wants to purge the entire cache every time, they can still enter `/(.*)`.

**Comment by alfonso100** [comment]
> Based on the proposed solutions so far, I think the best solution is "just ignore this parameter."
> 
> This will still have the desired effect for a customer who intends to purge the homepage with every cache clear (since that already happens), and it will not be possible for them to accidentally cause the full cache to be purged every time 

this approach sounds very logical to me. Silently ignore the parameter. 
Maybe users are just not aware the homepage is purged every time, so they are still going to achieve what they are trying to do, without any extra reading or causing any issues.

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
