### ISSUE TITLE
Created draft added via CLI added to Never Cache URLs when posted when home page is excluded

### ISSUE THREAD

**Issue by jorgemartine00** [wp-media/wp-rocket#4281]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When a draft is created via CLI and the home page has been added to the Never Cache URLs, it matches the rule and marks the "Never Cache URLs" meta box of the draft, and when published the exclusion is automatically added unless the meta box is manually unmarked.

**To Reproduce**
1. In WP Rocket options: "Never Cache URL(s)" add "/" to exclude the home page.
2. Create a new post draft through CLI:
`wp post create --post_title=draft --post_status=draft`
3. Open the new post through the WordPress UI. In the WP Rocket meta box, the "Never cache this page" checkbox will be checked.
4. Publish the post and Navigate to WP Rocket Options > Avanced Rules > Never Cache URL(s).
5. The published post will be added.

**Expected behavior**
Never cache URL(s) meta box shouldn't be marked and when posting the draft it shouldn't be added automatically to the never Cache URLs.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
# Grooming
## Reproduce the problem
Yes I can see the issue locally.

## Identify the root cause
When the post status is draft, the URL for it not being generated/saved yet so `get_permalink` function returns `/` so when we have `/` inside the WPR option `Never Cache URL(s)` inside the WP Admin page, it will detect that current page shouldn't be cached but it should. Then when save the page and publish it, it has a url and this option is saved on enabled status so it saves the new url inside the WPR option `Never Cache URL(s)` .

## Scope a solution
Here
https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L56

we need to change the condition to be
```
if ( 'post-new.php' !== $pagenow && 'draft' !== get_post_status( $post ) ) {
```

or if u have a way to detect if the post has already url, this will be more accurate.

## Estimate the effort
[XS]

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
