### ISSUE TITLE
CSS files added using link preload might not be detected by our regex and processed by RUCSS

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4284]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The following markup is not caught by our regex and stays in the HTML source:
`<link rel="preload" id='preload-test' href="https://domain.com/wp-content/rocket-test-data/styles/minifycss_style.css" media='all' as='style' />`

**To Reproduce**
1. Add CSS file to the source using the above markup
2. Enable RUCSS
3. Visit the page
4. The CSS file stays in the source

**Expected behavior**
This is correct markup, we should handle it

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1713221534/311778/

The customer was using the **Kadence** theme which allows to preload CSS files from the customizer:
_​Customize > General > Performance > Enable CSS Preload_

Disabling that feature allowed the CSS files to be removed.
​

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1837121277/335702/

**Comment by remyperona** [comment]
Is this still something that needs to be modified with the new approach?

**Comment by piotrbak** [comment]
@Tabrisrp Yes, we're not removing the `<link rel="preload" id='preload-test' href="https://domain.com/wp-content/rocket-test-data/styles/minifycss_style.css" media='all' as='style' />` from the source when RUCSS is enabled.

**Comment by CrochetFeve0251** [comment]
### Reproduce the problem
The issue is easy to reproduce just by adding into the foote or the header from a theme:
`<link rel="preload" id='preload-test' href="https://domain.com/wp-content/rocket-test-data/styles/minifycss_style.css" media='all' as='style' />`
### Scope a solution
The problem comes from the fact we are not searching for preload links in the `remove_used_css_from_html` from `RUCSS\Controller\UsedCSS`.

For that we can use the `$link_styles` variable that should already contains preload links and in the for loop line 311 add a new condition with the following regex:
` ((bool) preg_match( '/rel=[\'"]preload[\'"]/is', $style[0] ) && (bool) preg_match( '/as=[\'"]style[\'"]/is', $style[0] ))`

### Estimate effort
Effort `XS`

**Comment by vmanthos** [comment]
**Related:** https://secure.helpscout.net/conversation/1875622067/341710/
