### ISSUE TITLE
Security issue with WP Rocket

### ISSUE THREAD

**Issue by bastbra** [wp-media/wp-rocket#4289]
There seems to be a problem with WP Rocket which causes several tries of injections on websites.

The URL that is visited by a bot with the same hostname and IP is https://www.example.com/wp-admin/admin-ajax.php?action=rocket_rucss_warmup_resource_fetcher&nonce=11f068ee56

Wordfence is saying:
"(IP-Adress) left https://www.example.com/wp-admin/admin-ajax.php?action=rocket_rucss_warmup_resource_fetcher&nonce=… and was blocked by firewall for Directory Traversal in POST body: 32=https%3A%2F%2Fwww.example.com%2Fwp-content%2Fplugins%2Fyada-wiki%2Finc%2F..%2Fcss%2Fyadawiki.css%3…

I got this one like 64 times per Wordfence Mail, so there were at least 6 tries or so per minute. I guess it's even more. Yesterday Wordfence Blog released this, maybe this can help you: https://www.wordfence.com/blog/2021/08/nested-pages-patches-post-deletion-vulnerability/

Best regards. I hope you can figure out what this exactly is and fix it with an update.

**Comment by iCaspar** [comment]
Hi @bastbra 

First, we would kindly ask that to disclose a security issue to our team, please reach out to contact@wp-media.me rather than posting here.

To address your specific concern, these calls are to do with WP Rocket's Remove unused CSS feature. They are to be expected, but you will need to let WordFence know how to handle them. For more, please see https://docs.wp-rocket.me/article/1529-remove-unused-css#basic-requirements and if you still have issues, please [reach out to our support team](https://wp-rocket.me/support/).
