### ISSUE TITLE
Plugin Compat : WPML’s option “Use directory for default language”

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#431]
WP Rocket doesn’t work with WPML’s option “Use directory for default language”.

PHP Config files in /wp-content/wp-rocket-config/ are created for each languages but the extension of the tld is duplicate (e.g. : /domain.fr.fr.php & /domain.es.es.php) so pages are not cached.

**Comment by vmanthos** [comment]
I have a similar case where the content of the language-specific config files is the same and this affects the exclusion of URIs using the respective ADVANCED tab exclusion field.

**Example**
The default language is `au` and the `$rocket_cache_reject_uri` is like the following in all config files:
`$rocket_cache_reject_uri = '/au(/find-a-store/|/compare-our-features/|/(.+/)?feed/?|/wc-api/v(.*)|/(index\.php/)?wp\-json(/.*|$))';`

It should be ie in the case of `nl` like this:
`$rocket_cache_reject_uri = '/nl(/find-a-store/|/compare-our-features/|/(.+/)?feed/?|/wc-api/v(.*)|/(index\.php/)?wp\-json(/.*|$))';`

The exclusion takes place if I manually add the URIs to the main rocket config file or if manually change the language in the `$rocket_cache_reject_uri`.

This issue seems to be related to the fact that `$home_root` should be different when using WMPL's "Different languages in directories" option:
https://github.com/wp-media/wp-rocket/blob/33578f0dd568819d3e5912e38cafb9d51d5964d7/inc/functions/options.php#L180

**Related Ticket:**
https://secure.helpscout.net/conversation/691347098/83608/

**Comment by arunbasillal** [comment]
I did some investigation into this and Vasilis' discovery is right as far as I can see. 

He had generated a log from here (I think): 

https://github.com/wp-media/wp-rocket/blob/33578f0dd568819d3e5912e38cafb9d51d5964d7/inc/functions/options.php#L178-L237

Log: https://pastebin.com/vg00d2iu

And it shows the issue very closely. 

I think this is where the trouble is: 

https://github.com/wp-media/wp-rocket/blob/33578f0dd568819d3e5912e38cafb9d51d5964d7/inc/functions/options.php#L648

For WPML, they have `wpml_home_url` - https://wpml.org/wpml-hook/wpml_home_url/

We could filter the home_url in the wpml compat file. Needs testing.
