### ISSUE TITLE
Items added to settings_errors transient are not displayed on settings update

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4314]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.9.2
- Used the search feature to ensure that the bug hasn’t been reported before =>yes

**Describe the bug**
When using an invalid regex, it is removed from UI without displaying a notice

**To Reproduce**
1. Go to Advanced rules
2. Add `gtag(`  in Always Purge URLs
3. Save
4. `gtag(` removed and no notice is displayed

**Expected behavior**
Notice is displayed

**Additional context**
As per change here https://github.com/wp-media/wp-rocket/pull/4195#issuecomment-902888918 , the notice shall be `The following pattern has been escaped to prevent errors:`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by iCaspar** [comment]
This issue is blocking
#4472 
#4327 
#4013

**Comment by iCaspar** [comment]
Grooming Notes:

Reproduced: ✔️ 

Root cause: ✔️ 
Adding settings_errors to the transient does not persist them across the page load because other calls to the settings API  `get_settings_errors()` deletes the transient before we have a chance in our settings to get the contents.

Solution scope: ✔️ 
Instead of setting the transient, we can use WP's `add_settings_error()` to store the errors/notices.

Estimated effort:
[XS]
