### ISSUE TITLE
CSS rules added with inline JS script $("head").append are removed and not added to the Used CSS

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4331]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.9.3
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When _Remove Unused CSS_ option is enabled, the CSS rules that are added with inline JS script `$("head").append` are being removed from the source code and not added to the Used CSS. This leads to a broken layout.

**To Reproduce**

1. Add the script with CSS rules to the head as in example here:
```
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script type="text/javascript">
	(function($) {$("head").append("<style>.my-style{color:red;}</style>")})(jQuery);
</script>
```

2. Add an HTML element on a page like here:
`<h3 class="my-style">Hello world</h3>`
3. Check the page and make sure the style is applied.
4. Enable _Remove Unused CSS_ and wait until the process is completed and the used-css is generated.
5. Check the page in the incognito browser window - the style is not applied. 
It is removed, but not added to the Used CSS.
![image](https://user-images.githubusercontent.com/60236665/132297918-4a1f13f9-984e-4e34-a19b-6090bf724e55.png)
Screenshot: https://jmp.sh/7KLsoIj

Safelisting `.my-style` doesn't resolve the issue.

**Expected behavior**
CSS rules added with the inline script must be processed and added to the Used CSS the same way as with inline styles.

**Additional context**
Related ticket with notes: https://secure.helpscout.net/conversation/1620666496/292153/#thread-4732067758

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
yes, i was supposed to report this issue today after more testing. but finally it's reported 👍

**Comment by Mai-Saad** [comment]
Reproducible on test site using the mentioned script.

**Comment by mostafa-hisham** [comment]
### Reproduce the issue :heavy_multiplication_x: :  
No but i can see the issue
### Identify the root cause ✅ 
we remove all style tags from the HTML 
and in this case, it is in a script tag

### Scope a solution ✅ 
I don't think that we should process this kind of styling RUSS sass
we need to exclude styles inside `<script>` tags from being removed and keep them inside the HTML

we can handle it the same way we handled styles inside `<noscript> `tags
create new function
```
	private function hide_scripts( string $html ): string {
		$replace = preg_replace( '#<script[^>]*>.*?<\/script\s*>#mis', '', $html );

		if ( null === $replace ) {
			return $html;
		}

		return $replace;
	}
```
and remove `<script>` tags before removing used css from html `<style>` tags in HTML
https://github.com/wp-media/wp-rocket/blob/723d6c0181b7b3849c3e15bd60cdb2e0233a38f8/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L427-L433

### Estimate the effort ✅
create new test cases
Effort `[S]`

**Comment by iCaspar** [comment]
@mostafa-hisham I agree with this approach.
