### ISSUE TITLE
Add wp_next_scheduled() check for rocket_rucss_clean_rows_time_event

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4337]
Feedback from the customer: https://secure.helpscout.net/conversation/1624163812/292950

The current implementation calls `wp_clear_scheduled_hook` each time the WP init hook is called.

The reason is this code:

```
public function schedule_clean_not_commonly_used_rows() {
  if ( ! $this->settings->is_enabled() ) {
   wp_clear_scheduled_hook( 'rocket_rucss_clean_rows_time_event' );

  return;
}
```

It would be better to check for a scheduled event before trying to unschedule something. Like this:

```
public function schedule_clean_not_commonly_used_rows() {
  if ( ! $this->settings->is_enabled() ) {
   if ( wp_next_scheduled( 'rocket_rucss_clean_rows_time_event' ) ) {

    wp_clear_scheduled_hook( 'rocket_rucss_clean_rows_time_event' );
  }

return;
}
```

Slack thread: https://wp-media.slack.com/archives/C029G1B5HD2/p1631088167085200

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
## Notes before grooming
After checking the source code of `wp_next_scheduled` and `wp_clear_scheduled_hook` and found that both do the exact same checks

https://github.com/wordpress/wordpress-develop/blob/da835d6627315ba8c3eabf4ab4b9bb02d29d192d/src/wp-includes/cron.php#L526-L626

And

https://github.com/wordpress/wordpress-develop/blob/da835d6627315ba8c3eabf4ab4b9bb02d29d192d/src/wp-includes/cron.php#L800-L819

So please check the following comment to see that the code is the same: 

https://github.com/wordpress/wordpress-develop/blob/da835d6627315ba8c3eabf4ab4b9bb02d29d192d/src/wp-includes/cron.php#L593-L597

So I think this enhancement is useless, but I will groom it just in case.

## Reproduce the problem
Not a problem, this is an enhancement.

## Identify the root cause
We have two cases here:
1. When RUCSS option is enabled => we are using `wp_clear_scheduled_hook` to stop the schedule.
2. When RUCSS option is disabled => We are using `wp_schedule_event` to register the schedule.

In both cases, we need to check if the schedule is registered or not.

## Scope a solution
https://github.com/wp-media/wp-rocket/blob/207346f55a740a6f24f45a0c21e213e18eb5360e/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L170

Change the order of the bailout conditions to have

```
if ( wp_next_scheduled( 'rocket_rucss_clean_rows_time_event' ) ) {
	return;
}
```

## Estimate the effort
[XS]
