### ISSUE TITLE
jQuery regex excludes jQuery plugins

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4371]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.9.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
`/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js` regex has false positives for `jquery.string.js`,which is widely used as naming convention for jQuery plugins. 

This can lead to excluding files that don't need exclusions, potentially creating dependency conflicts.

**To Reproduce**
1. Use `/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js` for exclusions
2. Test against the following sample file names: 
```
jquery.js
jquery.min.js
jquery.slim.js
jquery.slim.min.js
jquery-123.min.js
jquery-123.slim.js
jquery-123.slim.min.js
jquery.123.min.js
jquery.123.slim.js
jquery.123.slim.min.js
jquery-skip.min.js
jquery-skip.slim.js
jquery-skip.slim.min.js
jquery.skip.min.js
jquery.skip.slim.js
jquery.skip.slim.min.js
```
3. See that all will return as a match, except for the `jquery-skip` ones.

**Expected behavior**
The REGEX should only match the jQuery library and skip anything else.

**Screenshots**
N/A

**Additional context**
Slack discussion - https://wp-media.slack.com/archives/C08N8J6VC/p1625757535079900

Maybe we could use 2 regexes to cover all cases? 

`/jquery(.min|.slim|.slim.min)?.js` will exclude all jQuery libraries without a version number on them.
`/jquery.*?([0-9]+)(.min|.slim|.slim.min)?.js` will exclude all jQuery libraries with a version number before the file extension. Avoids false positives if a plugin uses the version number as well. 

Managed to combine both regexes into one line: 

`/jquery((|.min|.slim|.slim.min)|.*?([0-9]+)(|.min|.slim|.slim.min))?.js`

Another variant that includes jquery-migrate as well: 

```
jquery(-migrate)?((|.min|.slim|.slim.min)|.*?([0-9]+)(|.min|.slim|.slim.min))?.js
```

It returns: 

```
jquery.js
jquery.min.js
jquery.slim.js
jquery.slim.min.js
jquery-123.min.js
jquery-123.slim.js
jquery-123.slim.min.js
jquery.123.min.js
jquery.123.slim.js
jquery.123.slim.min.js
```

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mehedihasanziku** [comment]
This one also 

`<script type="36de89d2284568ff01cdb4db-text/javascript" src='https://elementor.com/marketing/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.3.1' id='e-sticky-js'></script>`

**Comment by piotrbak** [comment]
The pattern should also exclude the unminified version:
`jquery.js`

**Comment by mostafa-hisham** [comment]
### Reproduce the problem :heavy_multiplication_x: 
we using the Regex in two areas in the code
- the placeholder for the` delay exclusions` textarea in the settings page
- in `MinimalistBlogger` theme third-party

### Identify the root cause ✅
As @DahmaniAdame explained above the regex needs to be updated to handle false positives for the widely used naming convention for jQuery plugins.

### Scope a solution ✅
- use new Regex in  the placeholder 
https://github.com/wp-media/wp-rocket/blob/ffac5d90e5a83bcb5a29b8e43f059a31adfae629/inc/Engine/Optimization/DelayJS/Admin/Settings.php#L147-L152

- and in third party class and tests
https://github.com/wp-media/wp-rocket/blob/ffac5d90e5a83bcb5a29b8e43f059a31adfae629/inc/ThirdParty/Themes/MinimalistBlogger.php#L37-L42
### Estimate the effort ✅
[XS]

**Comment by joejoe04** [comment]
Adding additional conversation and tests on this as we were discussing it here: https://wp-media.slack.com/archives/C60QX4FC1/p1680119799280529?thread_ts=1679577697.978529&cid=C60QX4FC1

Here is a possible Regex I've come up with for use with Delay JS since we always need to exclude them both:
`/jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?$`

For cases with LJD where maybe only jQuery needs excluded:
`/jquery-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?$`
`/jquery-migrate(.*)(.min|.slim|.slim.min)?.js(\?(.*))?$`

Using the current regex, if we test some of Adame's examples above, we can see that there are cases where it selects scripts that it should not:
https://regex101.com/r/H4R43M/1

But the Regex above does not:
https://regex101.com/r/1qZn7W/1

I did some more tests of random sites we've been working on too, and so far, I don't see any cases where there are false positives or any cases where jQuery and jQuery Migrate are missed:

[xlightmedia.com](http://xlightmedia.com/) - https://regex101.com/r/AZVwti/1
[blog.sportfishtrader.com](http://blog.sportfishtrader.com/) - https://regex101.com/r/t5Qknc/1
[decoforia.fi](http://decoforia.fi/) - https://regex101.com/r/LQg4QU/1
[www.kingsofcleaningservices.com.au](http://www.kingsofcleaningservices.com.au/) - https://regex101.com/r/bzHQQu/1
[www.onlinesolutionsgroup.de](http://www.onlinesolutionsgroup.de/) - https://regex101.com/r/DcwNV8/1
[qnextech.com](http://qnextech.com/) - https://regex101.com/r/ZtxzoI/1
[www.onlinesolutionsgroup.de](http://www.onlinesolutionsgroup.de/) - https://regex101.com/r/e1i2FH/1
[www.transportelanzarote.com](http://www.transportelanzarote.com/) - https://regex101.com/r/pm2RdI/1
[exoticfootwear.au](http://exoticfootwear.au/) - https://regex101.com/r/KO97lW/1
[considerant.fr](http://considerant.fr/) - https://regex101.com/r/6zR51R/1
[chanarchile.cl](http://chanarchile.cl/) - https://regex101.com/r/vh4Tce/1
[www.hypnosefrancophone.org](http://www.hypnosefrancophone.org/) - https://regex101.com/r/PDaalE/1
[beautybaskets.in](http://beautybaskets.in/) - https://regex101.com/r/ckLiWh/1
[amairaforyou.com](http://amairaforyou.com/) - https://regex101.com/r/XZsIGx/1
[meuvalordigital.com.br](http://meuvalordigital.com.br/) - https://regex101.com/r/JTi4wg/1

**Comment by camilamadronero** [comment]
Team, [here is a related case](https://secure.helpscout.net/conversation/2215539013/414712/#thread-6633121872) where using One-click exclusions for **Divi pixel** caused a problem to the **Ninja forms** plugin.

According to [our doc](https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions#divi-pixel), these are the Divi pixel exclusions:

> /jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
> /jquery-migrate(.min)?.js
> .dipi_preloader_wrapper_outer

The above regex was targeting other scripts causing the forms not to be displayed, with [these JavaScript errors](https://jmp.sh/bCYTZ5W6) in the console.

To fix the errors, additional exclusions were needed:

> /wp-includes/js/jquery/ui/core.min.js

Using Joe's regex avoided the errors:

> /jquery(-migrate)?-?([0-9.]+)?(.min|.slim|.slim.min)?.js(\?(.*))?$
> dipi_preloader_wrapper_outer

Slack thread:
https://wp-media.slack.com/archives/C43T1AYMQ/p1682430420911809

**Comment by piotrbak** [comment]
@wp-media/php Could you review the regex provided by @joejoe04 ?
https://github.com/wp-media/wp-rocket/issues/4371#issuecomment-1513415742
