### ISSUE TITLE
Lazyload video thumbnail isn't working on some static templates

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4438]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.1
- Used the search feature to ensure that the bug hasn’t been reported before => yes

**Describe the bug**
When using a static template, Video is not displayed on the page if replace Youtube with preview image is enabled

**To Reproduce**
Precondition:
- Active theme 2020
- Using this template http://snippi.com/s/5geczgb
1. Enable LL for iframe and replace Youtube with preview image
2. Open the page template and scroll to the video
3. Video is not displayed

**Expected behavior**
Video is displayed with its a preview image

**Screenshots**
![Screenshot from 2021-10-19 08-36-20](https://user-images.githubusercontent.com/76941962/137857118-b3e99622-ebaf-420a-b257-176bd679793e.png)

**Additional context**
Adding this class `wp-embed-responsive` in the  body, fixed the problem

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
The main issue is because this template doesn't use the function `body_class` to print the body class attribute so it doesn't add the class `wp-embed-responsive` which is used by block library stylesheet `wp-includes/css/dist/block-library/style.min.css` as in the following screenshot:

![image](https://user-images.githubusercontent.com/15707971/137859830-f5e2d43d-6872-4210-aca6-7e81a0e2569c.png)

So if this class isn't added to the body, this applied padding will not be applied so. And our CSS is targeting with just parent class as follows:

![image](https://user-images.githubusercontent.com/15707971/137860287-99c5c774-891d-4007-9713-26f5968946d0.png)

So our CSS will be applied even if the mentioned body class is there or not.

This is a corner case but we can solve that with just targeting with this main body class, so here
https://github.com/wp-media/wp-rocket/blob/f8579100d62581a99265198bb76e315a708fac2d/inc/Dependencies/RocketLazyload/Assets.php#L269

we can make it like that:

```
.wp-embed-responsive .wp-has-aspect-ratio .rll-youtube-player{position:absolute;padding-bottom:0;width:100%;height:100%;top:0;bottom:0;left:0;right:0}
```

Note: this needs to be changed inside our lazyload repo and this will be reflected here at our dependencies.

# Effort
[XS]

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
