### ISSUE TITLE
Lazyload back ground images is not working when using image relative URL

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4442]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.1 and the latest LL
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are not processing relative URLs for background image

**To Reproduce**
Precondition:
Having page with background image using relative URL  i.e 
```
<p style="background-image: url('../wp-content/rocket-test-data/images/Przechwytywanie.PNG');">
You can specify background images<br>
for any visible HTML element.<br>
In this example, the background image<br>
is specified for a p element.<br>
background image behaves.
</p>
```
1. Enable LL images
2. Open the page and check the source
3. background image is not processed

**Expected behavior**
Process background image even with relative URL

**Screenshots**
![LLversion](https://user-images.githubusercontent.com/76941962/138079479-ca5480c4-bde3-4335-9aba-6a7c4fbe411d.jpg)

**Additional context**
- Test page: https://new.rocketlabsqa.ovh/images_background/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
### Reproduce the problem
I was able to reproduce the problem locally.

### Identify the root cause
We have a couple of problems here
- **The first problem** is that we are not checking the `<P>` tag (@wp-media/php is this on purpose)
https://github.com/wp-media/wp-rocket/blob/5afc9584b9e57e550231f5a8bfe8ae91fbd0b0cf/inc/Dependencies/RocketLazyload/Image.php#L61

- **The second problem** is that we have an issue with relative URLs we need to convert the URL to Absolute 

### Scope a solution
- First issue (if we should work on p tags)
add `<p> `tag to regex 

- second issue
we can add a function to convert relative path to absolute path 
```
private function normalize_url( string $url ): string {

		$url_host = wp_parse_url( $url, PHP_URL_HOST );
		if ( empty( $url_host ) ) {
			$relative_url        = ltrim( wp_make_link_relative( $url ), '/' );
			$site_url_components = wp_parse_url( site_url( '/' ) );
			global $wp;
			$current_url = home_url( add_query_arg( array(), $wp->request ) );
			return $current_url. '/' . $relative_url;
		}

		return $url;
	}
```
I think it can be better than this but this worked with me :grin: 
### Estimate the effort
[s]

**Comment by Mai-Saad** [comment]
- using dev of 3.12.6 => can see this problem even for absolute URL inside <p> (not from listed supported tags in latest doc)
- note for test: we need to update test template to include types mentioned [here](https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket#background-images)

**Comment by piotrbak** [comment]
There's no feedback from customers regarding this one. It's not going to be implemented in the near future. We're open to discuss and reopen the issue though.
