### ISSUE TITLE
Lazyload images is removing the default LL of wordpress for iframe

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4460]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling LL image, the `loading="lazy"` for the iframe is removed. this will result in not delaying iframe scripts while delay js is enabled.

**To Reproduce**
Precondition:
- Having a page with some images/videos i.e https://new.rocketlabsqa.ovh/image-and-video/ 
- Notice iframe in source as follow with nowprocket 
`<iframe loading="lazy" title="Software Testing Tutorials for Beginners" width="750" height="422" src="https://www.youtube.com/embed/goaZTAzsLMk?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

1. Enable LL for images
2. Open the page and check the iframe in the source
`<iframe title="Software Testing Tutorials for Beginners" width="750" height="422" src="https://www.youtube.com/embed/goaZTAzsLMk?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

3. Try to enable Delay js
4. Scripts for  iframe aren't delayed

**Expected behavior**
Not changing iframe in source when LL image is enabled

**Screenshots**
Video for delay js with/without LL enabled

https://user-images.githubusercontent.com/76941962/139025126-2268047c-7045-4f9d-a42a-c5e2ba30f60f.mp4

https://user-images.githubusercontent.com/76941962/139025137-164ae55d-b171-4285-96e8-d0cea45c2af1.mp4

**Additional context**
- Enable LL for iframe and video will fix it

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on local site

### Identify the root cause ✅ 
This is happening because we are disabling core lazyload depending on the value of the lazyload images option. At the time this was done, core was applying lazyload on images, so it made sense.

But now it also applies to iframes, so we need to update the method to better handle both cases.

### Scope a solution ✅ 
Update the method `maybe_disable_core_lazyload()`, by using the `$tag_name` as second parameter, and using this value to check if we need to check for image or iframe.

### Estimate the effort ✅
Effort `[S]`, taking the opportunity to add automated tests for this method.
