### ISSUE TITLE
 Serve gzip files with process.php

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#45]
When using PHP fallback, the gzip file for the cached HTML is not served
https://secure.helpscout.net/conversation/106814300/5348/

**Comment by webtrainingwheels** [comment]
We may consider re-opening this since we still have some related issues, although slightly different. 
Seems in some cases, at least, the gzip file is served (e.g https://secure.helpscout.net/conversation/510871499/58364?folderId=273766#thread-1390548301), but because headers are missing (vary:accept-encoding, content-encoding) the browser and speed tools don't interpret it as gzip?

**Comment by arunbasillal** [comment]
Another case where this happened: https://secure.helpscout.net/conversation/527586267/60678?folderId=1724284

When served via .htaccess, gzip worked as expected. Failed via process.php
Only for HTML though. gzip worked as expected for all other file types.
