### ISSUE TITLE
Performance Hit with RUCSS

### ISSUE THREAD

**Issue by Androlax2** [wp-media/wp-rocket#4505]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

I used Removed unused CSS, performance hit on it was extreme : 1034823ms to load before sending the page to the client.

2021-11-16 11-18-24    200    -    1034823    10.20.30.31    POST    /wp/wp-admin/admin-ajax.php?action=rocket_saas_warmup&nonce=3005af8be8    HTTP/1.1    "https://www.example.com/wp/wp-admin/admin-ajax.php?action=rocket_saas_warmup&nonce=3005af8be8"    "2z2dt1vHHuue"
example.com   2021-11-16 11-18-24    200    70221    2065346    00.000.00.000    GET    /blog/    HTTP/1.1    "-"    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"

1034823 => 1,03s to process the **rocket_saas_warmup**

**To Reproduce**
1. Go to back office and use "Remove Unused CSS"

**Expected behavior**

To cache the unused CSS maybe, or make sure **rocket_saas_warmup** do not take to much time before handling the request.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @Androlax2 Used CSS need a bit of time to be generated, that's why we suggest to make sure pages are always preloaded and cached.

We're working to make the process as fast as possible, that's why we flagged this feature as beta. To make the process as fast as possible, make sure that the Used CSS is generated for all pages. Then it might be slower only when there's a change in the CSS/JS files.

Since we're already working on the solution and we're improving the feature each WP Rocket release, I'll close the issue. Thank you for being great customer.
