### ISSUE TITLE
Woocommerce product description not displayed till user interaction

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4521]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When accessing the product page while Delay JS is enabled, the product description is not selected by default but instead product review form is displayed with invalid CSS till user interaction results in hiding form and select product description

**To Reproduce**
1. Enable Delay JS
2. open product page (make sure part of description displayed)
3. Refresh the page 
4. review form displayed with the wrong CSS till user interaction

**Expected behavior**
The product description is selected by default with no user interaction

**Screenshots**
https://jmp.sh/WPzhoZX

**Additional context**
Tested on multiple themes Astra, 2021, OceanWP...

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅
Reproduced the issue
 
### Identify the root cause ✅ 
This is happening when `/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js` is delayed, as it is this script that is controlling the display of the tabs on the product page.

To fix the initial display, we would have to exclude this script, and also jQuery, from delay JS.

@piotrbak Do we want to go forward with this? It might be counter-productive if we didn't get any user feedback about it.

**Comment by piotrbak** [comment]
@Tabrisrp Yes, let's wait for the feedback. Tabs are usually at the bottom or even outside of viewport.

**Comment by piotrbak** [comment]
Handled in 3.13 using dynamic lists
