### ISSUE TITLE
Deactivate Separate Cache for Mobile Devices when WP Rocket is used on hosts not supporting separate cache for mobile

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#4529]
**Is your feature request related to a problem? Please describe.**
When using WP Rocket on hosting service with caching layers not supporting mobile-specific cache, enabling the corresponding feature on WP Rocket will mislead the user to think the site is serving mobile-specific cache.

**Describe the solution you'd like**
Graying the feature on hosts where we know for sure they don't support mobile-specific cache could be a good thing to consider.

**Describe alternatives you've considered**
N/A 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1677829538/304267/

**Comment by JerissCloudCenter** [comment]
Which hosts do you consider as not compatible "for sure" ?

**Comment by fidoboy** [comment]
> Which hosts do you consider as not compatible "for sure" ?

For example, when using the rocket-nginx module. It's not compatible with this feature. Also, in my particular case, it's very annoying that the plugin is detecting that I've wpDiscuz installed and then it forces the separate cache for mobiles, and I do not want to use that, but there is no way to disable the switch. Isn't there any hook to force disable separate mobile cache from theme functions.php?

This new feature that detects some plugin that COULD BE using a separate cache is not very user friendly. From my point of view, WP Rocket should only display a notice or a tip when detecting some of that plugins. That way the user decides if he wants to activate the separate cache or not. But right now it forces to have it activated when it detects a plugin from his list. So I believe that this behaviour should be changed on next releases of WP Rocket. I prever very much to have the control and I can decide if enable this or not (in my case it is NOT, because it works very fine without a separate cache)

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future.
