### ISSUE TITLE
LL image and LL video are removing loading="lazy" from ?nowprocket page

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4531]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
`loading="lazy" ` is removed from nowprocket view of the page when LL image / LL video is enabled

**To Reproduce**
1. Enable LL image and LL iframe
2. Open the ? nowprocket of the page containing video/image
3. Check the source

**Expected behavior**
Loading = "lazy" exists in nowprocket as same as if those features are disabled

**Additional context**
- Sample page with the issue (mainly when LL image is enabled ) https://new.rocketlabsqa.ovh/video-and-image/?nowprocket (tested on 3.15.7)
- The cached page while LL image is enabled contains `loading="lazy"` and our LL => Do we need to remove it as same as with LL image?

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
## Reproduce the problem
Yes I can see the issue locally.

## Identify the root cause
Here
https://github.com/wp-media/wp-rocket/blob/f48cb29346ab9a4f42c39d01f14e024b9a31086a/inc/Engine/Media/Lazyload/Subscriber.php#L84

we are adding callback to the filter `wp_lazy_loading_enabled` and here

https://github.com/wp-media/wp-rocket/blob/f48cb29346ab9a4f42c39d01f14e024b9a31086a/inc/Engine/Media/Lazyload/Subscriber.php#L467-L481

we don't check if we don't use the check of `rocket_bypass()` so bailout when we detect `nowprocket` on the requested url.

## Scope a solution
Here
https://github.com/wp-media/wp-rocket/blob/f48cb29346ab9a4f42c39d01f14e024b9a31086a/inc/Engine/Media/Lazyload/Subscriber.php#L468

we need to change this condition to be
```
if ( false === $value || rocket_bypass() ) {
```

## Estimate the effort
[XS]

**Comment by alfonso100** [comment]
when running the unit tests, I'm getting an error with the code above : `if ( false === $value || rocket_bypass() ) {`

7 errors: https://snippi.com/s/cb1ka4k
Maybe related to the fact that I need to update the tests?

thanks!🙏
