### ISSUE TITLE
JS delaying vs Autoptimize notice causes end-user confusion

### ISSUE THREAD

**Issue by futtta** [wp-media/wp-rocket#4558]
**Before submitting an issue please check that you’ve completed the following steps:**
:heavy_check_mark:  Made sure you’re on the latest version
:heavy_check_mark:  Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When JS is delayed in WPR and Autoptimize is aggregating JS a notice is shown that confuses our joint users.

**To Reproduce**
1. Go to enable Autoptimize > JS, CSS & HTML > JavaScript Options > Aggregate JS-files
2. Enable WP Rocket Delay JS
3. See notice on admin pages (screenshot below)

**Expected behavior**
1. ideally; have WPR delay the aggregated JS file from Autoptimize (hooking into e.g. the `autoptimize_filter_js_bodyreplacementpayload` filter, I'll be happy to provide more info)
2. if (1) is not possible, improve notice by 
2.1. making sure it is clear the notification is from WP Rocket (and not Autoptimize, I received multiple mails/ messages from people thinking the notification was Autoptimize's)
2.2. as nothing is actually broken (and as WPR & AO have a special relationship ;-) ) consider 
   - making this an `notice-info` instead of a `notice-warning`
   - only showing this on WP Rocket's own pages and not on every wp-admin screen

**Screenshots**
![image](https://user-images.githubusercontent.com/181297/144457782-1e47d53a-a670-4a47-b313-5f1eb7c440bc.png)

**Additional context**
* I'm Autoptimize's developer and an affiliate partner of WP Rocket ;-)
* see https://github.com/wp-media/wp-rocket/issues/4472 and https://github.com/wp-media/wp-rocket/pull/4501

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @futtta thank you for opening the discussion here, it's nice to meet you.

I believe that we'll firstly go with the `2nd` approach, leaving some time for compatibility and exploratory testing of the `1st` one.

My concern here is that we're forcing our customers not to use our own JS aggregation together with delay JS. When Autoptimize's JS aggregation will be used with our Delay JS, our autocompatibilities will not work as everything will be combined. It'll end up with content not being displayed until user interaction and things that we've already fixed when dealing with pure assets.

**Comment by piotrbak** [comment]
@wp-media/php Could you groom both scenarios, as the issue is important and we won't have time for a detailed exploration of the 1st approach during the upcoming sprint?

For the `2nd` approach:
1. Change the wording as in this https://github.com/wp-media/wp-rocket/pull/4551
2. Make it a notice instead of warning
3. Display it only on WP Rocket's screen

**Comment by futtta** [comment]
hey @piotrbak :)

re. 
> When Autoptimize's JS aggregation will be used with our Delay JS,

Although not _always_ the case, usually people have AO active already when adding WP Rocket/ activating "delay JS" (someone without AO who is running WPR + delay JS is unlikely to still need/ want to install AO afterwards), and in that default scenario it makes sense to warn people on the WP Rocket "delay JS" screens? ;-)

**Comment by iCaspar** [comment]
To implement "Approach 2":

**Reproduced:**
Yes, current behavior is how we built it for 3.10.4

**Root cause:**
Autoptimize compatibility class adds warning notices. Wording for those notices can be improved. Notices can be downgraded to info, and shown only on the WPR dashboard page.

**Solution:**
In the Autoptimize compat class:
1. Change `status` item in `rocket_notice_html` array in both notice methods to `info`.
2. Add a check for being on `'settings_page_wprocket' !== get_current_screen()->id` into `can_notify()`
3. Update the text for the info notices for both notice methods. @webtrainingwheels for new text here.

Also update the integration tests for Autoptimize compat class to expect new notice level, wording, appearance only on wpr dashboard.

**Estimate:**
[XS]
