### ISSUE TITLE
Images with data-skip-lazy and other excluded attributes get LazyLoaded

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#4576]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Images get lazy loaded even if they contain `data-skip-lazy` attribute, or other excluded attributes listed here: https://docs.wp-rocket.me/article/1421-some-images-are-not-lazyloaded
The issue started happening after we updated LazyLoad script in WP Rocket 3.10.2. This issue is not present in WP Rocket 3.10.1 and earlier version

**To Reproduce**
1. Install WP Rocket 3.10.4
2. Add an image to the post/page with `data-skip-lazy` attribute or one of the other attributes mentioned [here](https://docs.wp-rocket.me/article/1421-some-images-are-not-lazyloaded).
3. See the issue in source code of the post/page

**Expected behavior**
Images that contain attributes listed [here](https://docs.wp-rocket.me/article/1421-some-images-are-not-lazyloaded), should not be lazy loaded

**Screenshots**
https://i.imgur.com/OaGx9tZ.jpeg

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1720449792/313218/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Identify the root cause ✅ 
`data-skip-lazy` and `skip-lazy` have been removed from the exclusions array during development for native lazyload, and they have not been re-added when we switched the solution back.

### Scope a solution ✅ 
Add back `data-skip-lazy` and `skip-lazy` to the exclusions array in `Images::getExcludedAttributes()` in the lazyload common library.

Update the related tests too.

### Estimate the effort ✅
Effort `[S]`
