### ISSUE TITLE
Only regular price shall be displayed if Campaign banner isnot displayed

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#4595]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.5.10.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Discount price is displayed also no campaign banner when campaign name is not set

**To Reproduce**
- Having an active campaign but with no campaign name
1. Open the CDN tab
2. Discount price is displayed

**Expected behavior**
The regular price only displayed as long as no Campaign banner

**Screenshots**
![Screenshot from 2021-12-17 08-15-23](https://user-images.githubusercontent.com/76941962/146498388-3d2cad2e-4078-47de-bbda-8d98a93fb206.png)

**Additional context**
- Already exist in 3.8

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
I think we should make sure for this to set the campaign name in the API when setting the `is_discount_active` value to true, because it's this value that is handling the display of the discounted price.

The other alternative is to also check that `discount_campaign_name` is not empty in addition to the current checks we do.

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.
