### ISSUE TITLE
Delay JavaScript Execution compatibility with WS Form PRO

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4745]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [WS Form PRO](https://wsform.com/) is installed and activated the contact form is not displayed when WP Rocket Delay JavaScript execution is enabled. Even if /jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js and /wp-content/plugins/ws-form-pro/(.*) are added to the Excluded JavaScript Files, there is an JS error :
`GET https://www.gcc-deutschland.de/wp-ison/ws-form/v1/form/5/full 401`

This error comes from a WS Form PRO inline JS script that is being delayed when WP Rocket Delay JavaScript execution is enabled.

Adding the function `window.wsf_form_json_config` included in this JS inlinse  to the Excluded JavaScript Files under Delay JavaScript execution can resolve the issue. 

**To Reproduce**
1. install [WS Form PRO](https://wsform.com/)
2. Create a contact form
3. Add the contact form to a page
4. check the page in incognito window
5. see the ![WS Form PRO JS console error](https://user-images.githubusercontent.com/1954918/154457682-20dbfc70-57b5-4d93-be3f-b2b1fc11d6fb.png) in the console.

**Expected behavior**
The contact form should be displayed without having to exclude inline JS `window.wsf_form_json_config`

**Screenshots**

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1789440283/326583/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
### Reproduce the issue :heavy_multiplication_x:
As we can't have a version from the plugin and the lite version from this plugin doesn't have any problem, we couldn't reproduce the problem.

That's why we asked to the dev team from the plugin if it is possible to have it and we are waiting their answer.

Due to that the solution found is temporary. 
### Scope a solution ✅ 
As `window.wsf_form_json_config` is a specific script with not logic inside it is possible to exclude it directly in the core:
- Add `window.wsf_form_json_config` to the `DelayJS\HTML::$excluded` array

### Estimate the effort ✅
Effort `[XS]`
