### ISSUE TITLE
Add missing image dimensions feature breaks scripts that contain image

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4759]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
**Add missing image dimensions** feature is being applied within scripts when they append HTML. This may break the script due to mismatch of the single/double quotes.

**To Reproduce**
1. Add a script like this to a page:
```
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function(){ jQuery("#footer-info").text(' '); jQuery("<p align='center'><img src='https://your-site.com/image.jpeg' /></p>").insertAfter("#footer-info"); });
// ]]></script>
```
Make sure to have the image src leading to an existing image on the site where it is tested.
2. Enable **Add missing image dimensions** option
3. Check page source code in the incognito browser window. The script will be replaced by this:
```
<script type="text/javascript">// <![CDATA[
jQuery(document).ready(function(){ jQuery("#footer-info").text(' '); jQuery("<p align='center'><img width="1920" height="1080" src='https://testsite.nataliadrause.com/wp-content/uploads/2021/12/Pexels-Videos-1580455-1-poster.jpeg' /></p>").insertAfter("#footer-info"); });
// ]]></script>
```
4. Console will have this error:
`Uncaught SyntaxError: missing ) after argument list`
![image](https://user-images.githubusercontent.com/60236665/155185240-93eeecdf-29ee-4c07-a04b-1bf3ef169457.png)

This is because the double quote `''` from the image attribute is closing the HTML string too soon.

This is how it is interpreted:
![image](https://user-images.githubusercontent.com/60236665/155185769-55d119c8-7046-4be5-903d-a6ec25566759.png)

**Expected behavior**
Possibly we should not apply the feature within scripts.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/1794018812/327474?folderId=3864740

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
Scripts are not removed from the buffer when we do the parsing, so the feature can currently be applied to images contained in them.

### Scope a solution ✅ 
To be on the safer side, we should hide the scripts from the buffer before parsing it to find images. We can also do the same for comments and noscripts.

This could be a good opportunity to consolidate those methods we use to hide part of the HTML from the buffer in the same place, like in the `Optimization\RegexTrait`. Currently we have duplication of those methods in different parts of the code.

In `Optimization\RegexTrait`:
- Add `hide_scripts()` and `hide_noscripts()` methods

In `Media\ImageDimensions\ImageDimensions::specify_image_dimensions()`, use the hide methods before the `preg_match_all()` call to get all images on the HTML.

In `Optimization\RUCSS\Controller\UsedCSS`, remove the hide methods from the code.

In `CriticalCSSSubscriber` and `Optimization\AbtractOptimization`, use the `RegexTrait` and remove the `hide_comments()` method.

### Estimate the effort ✅
Effort `[S]` for the refactoring
