### ISSUE TITLE
Clear cache partially instead of globally when Never cache This Page is changed in the Edit screen metabox

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#4773]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When Never Cache This Page option is changed in Edit screen metabox, we clear cache for the entire domain. This is unnecessary and not desired.

**To Reproduce**
1. Go to Edit Screen setting
2. Change metabox value "Never cache this page" from true to false
3. Click Update
4. Entire cache will be cleared

**Expected behavior**
Cache should be cleared only for the related URL where the setting is being changed.

"Never Cache URL(s)" should be handled the same way, i.e. clear the cache only of the new URL(s) that's added in the field.

**Additional context**
By @engahmeds3ed 

> The journey starts [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L134-L138) when saving the post metabox values, when never cache this page option is changed (from true to false or from false to true) this will update our options [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L146) specifically the option named Never Cache URL(s) to have this page url and then this triggers [this callback](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L104) .

Slack: https://wp-media.slack.com/archives/C43T1AYMQ/p1646124958398979
Ticket: https://secure.helpscout.net/conversation/1787123848/326047/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Identify the root cause
The root cause has been found by @engahmeds3ed :
The journey starts [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L134-L138) when saving the post metabox values, when never cache this page option is changed (from true to false or from false to true) this will update our options [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L146) specifically the option named Never Cache URL(s) to have this page URL and then this triggers [this callback](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L104) .
## Scope a solution
To fix that problem first we need to remove the cleaning for all the cache by adding `cache_reject_uri` in the following [array](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L25).

Then the url linked with that post should be cleared when we update the post so we nott suppose to have something to do.
## Estimate the effort
Effort `XS`

**Comment by CrochetFeve0251** [comment]
> ## Identify the root cause
> 
> The root cause has been found by @engahmeds3ed : The journey starts [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L134-L138) when saving the post metabox values, when never cache this page option is changed (from true to false or from false to true) this will update our options [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L146) specifically the option named Never Cache URL(s) to have this page URL and then this triggers [this callback](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L104) .
> ## Scope a solution
> 
> To fix that problem first we need to remove the cleaning for all the cache by adding `cache_reject_uri` in the following [array](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L25).
> 
> Then the url linked with that post should be cleared when we update the post so we nott suppose to have something to do.
> ## Estimate the effort
> 
> Effort `XS`

Update from the grooming:
While implementing the solution I saw this was creating an issue with the field in the configuration area.
To fix this I will have to propose a new solution.
Instead of adding directly `cache_reject_uri` inside the [array](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L25) we will create a filter that will allow us to add dynamically some fields.
Then in a second type we will add a filter before [updating the option](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L145) and remove it after with the following logic:
```php
function($removed) {
$removed['cache_reject_uri'] = true:
 return $removed;
}
```
## Estimate the effort

Effort `S`

**Comment by CrochetFeve0251** [comment]
> > ## Identify the root cause
> > The root cause has been found by @engahmeds3ed : The journey starts [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L134-L138) when saving the post metabox values, when never cache this page option is changed (from true to false or from false to true) this will update our options [here](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L146) specifically the option named Never Cache URL(s) to have this page URL and then this triggers [this callback](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L104) .
> > ## Scope a solution
> > To fix that problem first we need to remove the cleaning for all the cache by adding `cache_reject_uri` in the following [array](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L25).
> > Then the url linked with that post should be cleared when we update the post so we nott suppose to have something to do.
> > ## Estimate the effort
> > Effort `XS`
> 
> Update from the grooming: While implementing the solution I saw this was creating an issue with the field in the configuration area. To fix this I will have to propose a new solution. Instead of adding directly `cache_reject_uri` inside the [array](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L25) we will create a filter that will allow us to add dynamically some fields. Then in a second type we will add a filter before [updating the option](https://github.com/wp-media/wp-rocket/blob/d833ad2e34dab92e3e58838fedf4b4d643d84ce8/inc/admin/ui/meta-boxes.php#L145) and remove it after with the following logic:
> 
> ```
> function($removed) {
> $removed['cache_reject_uri'] = true:
>  return $removed;
> }
> ```
> 
> ## Estimate the effort
> 
> Effort `S`

After a talk with @piotrbak  and @engahmeds3ed the finall grooming is the following one:
- Prevent the full cache from reloading on an update from the option.
- add a callback after saving settings and detect if this field is changed
- Get the newly added urls from the option
- Remove cache for those only 

For the first part we will have to remove the cleaning for all the cache by adding `cache_reject_uri` in the following [array](https://github.com/wp-media/wp-rocket/blob/bbadfba54d3a43501305659207b92840e480b417/inc/admin/options.php#L25).

Then we will need to create another function in the same file with the following logic:
```php
function reload_cache_reject_uri($old, $new) {
if(! key_exists('cache_reject_uri', $old) || ! key_exists('cache_reject_uri', $new)) {
	return;
}


$old_cache_reject_uri = $old['cache_reject_uri'];
$new_cache_reject_uri = $new['cache_reject_uri'];

$diff = array_diff($old_cache_reject_uri, $new_cache_reject_uri);

rocket_clean_files($diff);
}
```
That we will hook on the following filter: `'update_option_' . rocket_get_constant( 'WP_ROCKET_SLUG' )`
## Estimate the effort

Effort `S`

**Comment by Mai-Saad** [comment]
Recommend testing the fix after finishing https://github.com/wp-media/wp-rocket/issues/5519 to avoid confusion

**Comment by jeawhanlee** [comment]
Re-opening as https://github.com/wp-media/wp-rocket/issues/5519 is fixed.
