### ISSUE TITLE
Better Headers for tracking Caching

### ISSUE THREAD

**Issue by bhubbard** [wp-media/wp-rocket#481]
Hey guys, I found this great article on tracking cache hits with WordPress.
https://pressjitsu.com/blog/wordpress-cache-hit-rate/

I think this is great, I was wondering if it could be expanded on a bit though. I use WP Engine & CloudFlare, is there a way for me to know when a cache hit is from WP Rocket, CloudFlare, or WP Engine cache? Maybe with more detailed headers? or multiple headers? I believe the CloudFlare cache header already covers the CF cache.

**Comment by Tabrisrp** [comment]
Hi Brandon,

On WP Engine, WP Rocket doesn't handle cache at all, our caching part is deactivated, since WP Engine has its own Varnish solution implemented. Varnish does send hit or miss headers, so you could track that if you want.

With CF on top of it, it gets more complicated, since it will first hit CF, then Varnish if CF is missed. Still, CF does add header for that too.

On a setup without CF or Varnish, we could add our own header like described in this article, but by default WP Rocket will try to serve the cache file directly in the htaccess if possible, bypassing PHP execution completely. In this case we can consider sending the header in the htaccess, we have to see how best to implement it.
