### ISSUE TITLE
Clear WP Rocket cache on all sites on WP Multisite

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#4813]
**Is your feature request related to a problem? Please describe.**
It is not possible to clear the WP Rocket cache on all sites in a multisite installation.

**Describe the solution you'd like**
Have an option to clear WP Rocket cache on all sites in a multisite installation.

Admin bar: Clear cache on all sites:
![Screenshot 2022-03-15 at 13 11 46](https://user-images.githubusercontent.com/1954918/158375227-6ecbbe10-044c-409b-a3a0-77f5e8b9df5e.png)

Quick actions: Clear cache on all sites:
![Screenshot 2022-03-15 at 13 10 56](https://user-images.githubusercontent.com/1954918/158375231-0c066e67-28f1-41c2-b62f-5410985b655b.png)

**Describe alternatives you've considered**
An alternative is to install the plugin [Multisite Support for WP Rocket](https://wordpress.org/plugins/multisite-wp-rocket) but this plugin has not been updated in the last 2 years and has less than 10 installations.

**Additional context**
[helpscout ticket](https://secure.helpscout.net/conversation/1813702251/331096?folderId=5547167)

**Comment by beekelder** [comment]
Currently running in to the same issue; We're running a rather large webshop as a multisite-installation. 

In every build/deploy i'm creating a php-file to run the `rocket_clear_domain()` function to clear the cache (so that i dont have any manual actions). I have recently discovered that the function only clears one domains cache, so now i'm still required to run through all sites and clear the individual caches. 

I would like to refrain from running a loop through all blog-id's, using switch_to_blog to activate each site to clear each cache.

Is there any schedule for this enhancement?

-- EDIT --

Heres what i've written to clear ALL cache in one go.
```
<?php 
$dir = __DIR__."/wp-content/cache/wp-rocket";

if(is_dir($dir)){
    $di = new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS);
    $ri = new RecursiveIteratorIterator($di, RecursiveIteratorIterator::CHILD_FIRST);
    foreach ( $ri as $file ) {
        $file->isDir() ?  rmdir($file) : unlink($file);
    }
}
?>
```

-- EDIT V2 --
If you want to clear your cache, and reinitialize/preload it for all sites theres no getting around wp-load.
Heres a code-example for running this in a separate file.
```
require("wp-load.php");
if (function_exists('get_sites') && class_exists('WP_Site_Query')) {
    $sites = get_sites();
    foreach ($sites as $site) {
        switch_to_blog($site->blog_id);

        if(function_exists("rocket_clean_domain")){
            rocket_clean_domain(); 
            echo "cache cleaned".PHP_EOL;
        }

        if(function_exists("run_rocket_bot")){
            run_rocket_bot();
            echo "cache re-initialized".PHP_EOL;
        }

        if(function_exists("run_rocket_sitemap_preload")){
            run_rocket_sitemap_preload();
            echo "cache preloaded".PHP_EOL;
        }
    }
}
```

**Comment by yesh** [comment]
+1

same here, I've used `Wp super cache` and it had this feature.
my client now wanted to move to Wp rocket and, with a multisite of 6 instances, it has become super frustrating not having this option.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We'll reopen it when working on multisite.
