### ISSUE TITLE
Ensure text remains visible during webfont load. Version: 3.10.9

### ISSUE THREAD

**Issue by djohn151** [wp-media/wp-rocket#4858]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Since WP Rocket version 3.10.9 the following error is displayed in page speed tools: "Ensure text remains visible during webfont load."

This problem occurs when elementor and elementor pro are installed and a user custom font is set

**Comment by mehedihasanziku** [comment]
Expected Reason:

Now here #4760 excluded elementor post css from combine/minify, and it's fails to apply swap because swap will apply only if they passed through minify/combine #3375 
another issue will happen due to this #4806

**Comment by SuperHanss** [comment]
Can confirm this was introduced with 3.10.9

I've since discovered Elementor has a [filter](https://developers.elementor.com/elementor-pro-2-7-custom-fonts-font-display-support/?utm_source=google&utm_medium=cpc&utm_campaign=11138809851&utm_term=&gclid=Cj0KCQjw0PWRBhDKARIsAPKHFGiOUYAuy3qakY2sF0AWkFSq3z5KzLUiqRfhs28LN2OhkbsV9m-tWgMaAqCvEALw_wcB) which can be used to configure font-display.

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
