### ISSUE TITLE
Support older versions of Action Scheduler

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#4877]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When other plugins are using older versions of **Action scheduler** (below 3.3) it causes a fatal error: 

`
Fatal error: Uncaught Error: Call to undefined function WP_Rocket\Engine\Common\Queue\as_has_scheduled_action() in /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php:63 Stack trace: #0 /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/Queue.php(37): WP_Rocket\Engine\Common\Queue\AbstractASQueue->is_scheduled() #1 /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php(165): 
WP_Rocket\Engine\Optimization\RUCSS\Controller\Queue->is_pending_jobs_cron_scheduled() #2 /home/public_html/wp-includes/class-wp-hook.php(307): WP_Rocket\Engine\Optimization\RUCSS\Admin\Subscriber->schedule_rucss_pending_jobs_cron() #3 /home/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #4 /home/ in /home/public_html/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/AbstractASQueue.php on line 63
`

Here: 
https://github.com/wp-media/wp-rocket/blob/trunk/inc/Engine/Common/Queue/AbstractASQueue.php#L63

**To Reproduce**
1. Using WP Rocket 3.11.0.1
2. Install a plugin using an old version of Action Scheduler, for example: **Smart Manager For WooCommerce v5.38.0 PRO**
3. See the error

**Expected behavior**
We should avoid such errors. @engahmeds3ed discovered this,  I'm opening the issue so the PHP Team can think of a way to support older versions of Action Scheduler.

**Additional context**
related ticket: https://secure.helpscout.net/conversation/1830705808/334405/
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1648588936910049

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
https://secure.helpscout.net/conversation/1831206396/334473?folderId=273768

Another conflict with [imageseo](https://wordpress.org/plugins/imageseo) plugin.
They are loading the action scheduler with older version 3.1.6 and we use the latest one 3.4.0 and because they are loaded before us, they load the action scheduler from there and ours will be bypassed.
https://plugins.trac.wordpress.org/browser/imageseo/trunk/vendor/woocommerce/action-scheduler/action-scheduler.php#L8

Changing the priority here: https://plugins.trac.wordpress.org/browser/imageseo/trunk/imageseo.php#L121
to be any value above `10` will fix the issue.

**Comment by vmanthos** [comment]
**Related ticket:** https://secure.helpscout.net/conversation/1828622976/334011/

In this case, it's the [WooCommerce Smart Coupons](https://woocommerce.com/products/smart-coupons/) plugin that's using an outdated version of the Action Scheduler (3.1.6).

They are loading that in `/includes/class-wc-smart-coupons.php` with a priority of `-1`:
```PHP
add_action( 'plugins_loaded', array( $this, 'load_action_scheduler' ), -1 );
```
Changing that value to `11` allowed both plugins to work.

Name of their class: `WC_Smart_Coupons`

**Comment by engahmeds3ed** [comment]
# Grooming

## Reproduce the problem
Yes I saw it multiple times at customers' sites.

## Identify the root cause
The problem with full details are described here: https://developer.woocommerce.com/2021/10/12/best-practices-for-deconflicting-different-versions-of-action-scheduler/

## Scope a solution
We need to check if function `as_has_scheduled_action` exists otherwise use the function `as_next_scheduled_action` instead to check for the next scheduled action, this solution has a drawbacks on performance described here: 
https://github.com/woocommerce/action-scheduler/pull/688

this is the only new function that is used in our code and others are already there in older versions of Action Scheduler.

## Estimate the effort
[S]

**Comment by engahmeds3ed** [comment]
@wp-media/productrocket do u think we need to show admin notice when this conflict is detected or even health check message?

**Comment by piotrbak** [comment]
@engahmeds3ed If we're able to preserve 100% of our functionality, I don't think we'll need to inform customers about that 🤔
