### ISSUE TITLE
Disable Avada's combination features when Remove Unused CSS is active (>3.11)

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#4881]
**Is your feature request related to a problem? Please describe.**

When customers who are using Avada have its CSS/JavaScript combination features active, it won't be possible for them to benefit from the compatibility additions we are making in the RUCSS back-end.

This is because it depends on detecting specific files (CSS or JavaScript) to add the CSS selectors we found.

**Describe the solution you'd like**

Disable Avada's CSS/JavaScript combination when the Remove Unused CSS is active for WP Rocket > 3.10.

**Additional context**

This came up after an internal discussion with @piotrbak.

We can also document why enabling these features isn't helpful towards performance.

**Comment by GeekPress** [comment]
@piotrbak Can this be scheduled for 3.11.2?

**Comment by piotrbak** [comment]
@GeekPress Yes, we'll need to explore other solutions that are combining resources too.

**Comment by CrochetFeve0251** [comment]
## Reproduce the issue
Reproducing the issue is a bit disorienting as there is not real error but you can check the existance from the combined CSS file in the page to see if the constant is working.
`/wp-content/uploads/fusion-styles/{hash}.min.css`
## Scope a solution
Avada is well design so the solution to disable combine file is quite simple:

Add a constant `FUSION_DISABLE_COMPILERS` and set it to `true` will disable it.
My solution is to add a method `disable_compilers` to  the thirdparty class for Avada when the theme is activated:
```PHP
public function disable_compilers() {
    if(! is_defined('FUSION_DISABLE_COMPILERS') {
      define('FUSION_DISABLE_COMPILERS', true);
   }
}
```

## Estimate the effort
Effort `XS`

**Comment by CrochetFeve0251** [comment]
@piotrbak I confirm there is no other usage from that constant in the code.
