### ISSUE TITLE
Wp rocket plugin function

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#4918]
**Describe the solution you'd like**

hi

I wanted to ask if wp-rocket optimizes only the Large (widely used) plugin code, or all the plugins? For example, all pages designed with elementor open very quickly. But pages I made with jet plugins are slower than element pages.
Does not wp-rocket optimize jet plugins code? If not, can you add support for jet plugins? jet plugins are available on almost every website that uses elementor.

**Comment by piotrbak** [comment]
Hello @79ho3ein thanks for creating the issue. WP Rocket is a full page cache plugin, it means that the entire HTML output will be cached. However, some plugins can load additional resources with:
1. Ajax
2. JavaScript

And we can't improve that, since they're supposed to be dynamic. Moreover, Delay JavaScript feature might prevent JS from being executed until the user interaction. 

Please contact our support team for further investigation and possible solution for your specific case. Thank you!
