### ISSUE TITLE
Improve the control over rocket_rucss_pending_jobs_cron action

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#4960]
**Describe the bug**
Currently, we improved the behaviour described in the https://github.com/wp-media/wp-rocket/issues/4940 based on the https://github.com/woocommerce/action-scheduler/issues/698 suggestions. However, we can improve it even further by adding a health check cron.

**Expected behavior**
We'll schedule a permanent action/cron that will check the number of `pending` or `in-progress` `rocket_rucss_pending_jobs_cron` actions:
1. 0 actions - we need to schedule it
2. 1 action - we're just fine, no further action needed
3. 1+ actions - we need to reduce it to 1

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
## Grooming

**Reproduce the problem**
Sometimes I can see it using the following code:
```
add_action( 'rocket_rucss_pending_jobs_cron', function (){
    throw new Exception( 'Hiiii' );
} );

add_action( 'action_scheduler_failed_execution', function (){
	wp_remote_get( 'https://wp-rocket.me/?nowprocket' );
	wp_remote_get( 'https://rocketlabsqa.ovh/?nowprocket' );
} );
```

and then refresh on admin UI multiple times till reaching two rows in AS tools page for our hook `rocket_rucss_pending_jobs_cron` in `pending` status.

**Identify the root cause**

We are not 100% sure about that but as mentioned in the Action Scheduler's issue here: https://github.com/woocommerce/action-scheduler/issues/698 the issue is in this method:
https://github.com/wp-media/wp-rocket/blob/22b9aafffe55920aa40017007169fd3a3ab0849c/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L43-L80

so in some cases before scheduling the new action, our main hook to check if our hook is scheduled or not here:
https://github.com/wp-media/wp-rocket/blob/1d35d6aca4e0a042bfc6b178f2f40de978a138c7/inc/Engine/Common/Queue/AbstractASQueue.php#L48-L50

`is_scheduled` here returns false in those cases.


**Scope a solution**

As mentioned in the issue itself we need to get the number of `pending` and `in-progress` actions and if it's more than 1, we should cancel the only pending actions.
This can be added here: https://github.com/wp-media/wp-rocket/blob/e219e903953a9dc6c7077de15f9e85d5191eb011/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L185-L184

OR here:
https://github.com/wp-media/wp-rocket/blob/1d35d6aca4e0a042bfc6b178f2f40de978a138c7/inc/Engine/Common/Queue/AbstractASQueue.php#L50

and I recommend the second location so if not `is_scheduled` we can use the method `search` from the same class to get pending or in-progress statuses' actions and if this count is more than 1, we can use the method `cancel_all` and pass the hook to it, this method will cancel all scheduled actions for this hook and group, and then it'll be created with the next refresh in admin.

**Estimate the effort**
[S] to [M]
