### ISSUE TITLE
After restart of container app, cache fails to generate until Admin logs in.

### ISSUE THREAD

**Issue by Dalias96** [wp-media/wp-rocket#4977]
**Describe the bug**
After container restart plugin fails to generate any kind of cache untill admin logs in.

**To Reproduce**
1. Enable WP Rocket
2. Generate some cache
3. Restart app
4. Enter page without entering admin panel - cache will never be generated.

**Expected behavior**

**Screenshots**
n/a

**Additional context**
We are using wordpress running on nginx with fastCGI inside docker container. We run our app in Azure.

**Comment by Dalias96** [comment]
This issue is related to critical css as well, after container restart there is no generated css files, and these will not be generated until manual regeneration.

**Comment by kmiskiewicz** [comment]
Would be great if you could consider the scenario where the cache plugin is used in a multi instance environment where the number of instances is dynamic (depends on the current traffic load).  I suppose Wp-Rocket should generate the cache based on an automatically scheduled cron event rather than a manual trigger.

**Comment by piotrbak** [comment]
@kmiskiewicz symlinking WP Rocket's cache and config to directories shared between servers won't be enough? 🤔

**Comment by kmiskiewicz** [comment]
@piotrbak Thank you for your advice. Yes, it could do the job, however, I'm not sure about the performance of this approach. Reading files from a local directory is always much faster than from a remote disk.  As @Dalias96 said on the issue, we struggle with the plugin not starting generation of the cache as long as someone will not load the admin panel.

**Comment by Dalias96** [comment]
@piotrbak We found a way to fix that, I created a pull request for that.

**Comment by piotrbak** [comment]
@Dalias96 thank you for the PR. We'll discuss it shortly and when it passes the CR and QA, it'll be added to one of the upcoming releases.

**Comment by piotrbak** [comment]
This is not something that can be implemented soon. We might reopen this in the future, for people who are experiencing it now, feel free to use the function provided here:
https://github.com/wp-media/wp-rocket/pull/5015/files

**Comment by kmiskiewicz** [comment]
Up to you. This stops us from purchasing the PRO Version, and we need to stick to WP Supercache. The previous order number: 3915648, November 29, 2021

**Comment by piotrbak** [comment]
Hello @kmiskiewicz 👋 It doesn't mean that we'll not take care of it. It means that it's not planned in upcoming quarter. Please keep in mind that the problem you're facing here touches just a very small number of our customers. Proposed solution will be doing checks on `wp_loaded` on all websites though. 

Moreover, this is a moderate severity issue since you're able to resolve it by adding proposed code snippet to your website and it completely solves the problem then.
