### ISSUE TITLE
Content-Type header is being removed

### ISSUE THREAD

**Issue by Mecanik** [wp-media/wp-rocket#4992]
I have encountered the most unusual issue with a friend's WordPress installation using paid WP Rocket.

**Describe the bug**
The most important, very important, must have HTTP header Content-Type is being removed.

**To Reproduce**
Just use WP Rocket.

**Expected behavior**
Do not remove HTTP Content-Type?

**Screenshots**

With WP Rocket (caching ON):
![image](https://user-images.githubusercontent.com/12122357/166118698-ed075048-f543-4f5e-a8cd-acf17faa8f45.png)

With WP Rocket (caching OFF):
![image](https://user-images.githubusercontent.com/12122357/166118720-7bd528be-4d01-453a-a816-298397e90de3.png)

**Additional context**
I am trying to rewrite the HTML output serverless to alter some stuff. Due to the fact that Content-Type is being removed, I am unable to execute my script correctly.

**Comment by piotrbak** [comment]
@Mecanik Hello and thanks for creating an issue.

Have you already contacted our support team? It would be great if we could investigate this.

**Comment by Mecanik** [comment]
> @Mecanik Hello and thanks for creating an issue.
> 
> Have you already contacted our support team? It would be great if we could investigate this.

My friend did yes (the customer).

**Comment by Mecanik** [comment]
It's been more than 10 days without any resolution for my friend which is paying for WPRocket. Support has been very limited and with replies that are very... let's just say limited.

- On first access of the website: HTTP 200 - Content-Type header present.
- Subsequent access of the website: HTTP 304 - Content-Type header is missing.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

Basically WPRocket is instructing the browser to serve the page as CACHED HTML page, and the HTTP code is 304 with the Content-Type missing. This is extremely bad, I cannot comprehend why you are doing this or why you would offer such option to people.

Please reconsider what you are doing because serving cached HTML pages is a hard thing to do. I would understand a 1 second micro-cache on HTML content but this is crazy.

Now I`m left with an impossible situation and the only "fix" I can see is either disable this option or look into your code and comment out this bit.

**Comment by piotrbak** [comment]
@Mecanik when we are sure that the browser cache is valid, serving 304 status code is the most efficient optimisation. This issue is related:
https://github.com/wp-media/wp-rocket/issues/1423
We created it 4 years ago and there were just a couple of people asking for implementation.

**>This is extremely bad, I cannot comprehend why you are doing this or why you would offer such option to people.**
We're doing it since the beginning of the plugin, could you elaborate on why this is extremely bad?

To prevent 304 from being served, please comment out the followign lines:
https://github.com/wp-media/wp-rocket/blob/11b9f294e29d58f720fac9dae1bc1a17dc4f4322/inc/classes/Buffer/class-cache.php#L157-L177
https://github.com/wp-media/wp-rocket/blob/11b9f294e29d58f720fac9dae1bc1a17dc4f4322/inc/classes/Buffer/class-cache.php#L201-L221

Let me know if that helped.

**Comment by Mecanik** [comment]
Thank you for showing me where to comment out, this is really helpful. Regarding what I said, well... WP is a dynamic site, and you cannot HTML on dynamic sites; well you can but with "rules".

My friend (your customer) had to exclude like 50 pages from caching in WP Rocket otherwise his whole site broke.  I am really stunned that people use it "as is" because it's impossible to "just cache" the HTML output.

I really suggest you add a button for this so people can easily turn it of, other than that thanks for the help.

**Comment by devrasel** [comment]
This is not working though, in the light speed server, I have tested using cyberpanel in Digital Ocean VPS

**Comment by Mecanik** [comment]
> 

LiteSpeed is a super complex (and the best) caching system for WordPress. You can't use it properly with this plugin. I suggest you just use LSCache plugin.
