### ISSUE TITLE
Respect site's trailing slash 

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5003]
**Describe the bug**
Closing https://github.com/wp-media/wp-rocket/issues/1392 in favour of this one, since we have  abetter view of what's needed and what risks are.

When serving the cache page using PHP, we're not respecting the `/` settings in permalinks. We should respect that and the solution will solve this problem except the scenarios when:
1. Rewrite rules are present and working
2. Server-side cache is being used

**Expected behavior**
Respect the trailing slash rules when serving cache using PHP.

**Additional context**
When serving the cache using PHP WordPress is still not loaded. It's possible that we'll need to use WP Rocket configuration file to store the data related to permalinks settings.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
### Scope a solution
First we will have to add a new configuration by adding an new key to the configuration in the class [`Buffer\Config`](https://github.com/wp-media/wp-rocket/blob/81e5b989f9f4af1d7933c9637a3ca8e444578099/inc/classes/Buffer/class-config.php#L143) and saving domains where the trailing slash is activated and another that will store domains where non-trailing slash is activated.

Then in `Buffer\Cache` we need to create a new method `maybe_redirect_on_non_trailing_slash` that will check if the domain from the is one of the domain where trailing slash redirection is activated.
If it is not the case bail out.
Otherwise check if the URL has a trailing slash and redirect it to the one with the slash if it doesn't.
```php
protected function maybe_redirect_on_non_trailing_slash() {
   $host = $this->config->getHosts();
   $hosts_with_redirection = $this->config->get_configs()['trailing_slash_redirect'];
  if(! in_array($host, $hosts_with_redirection)) {
   return; 
 }
  $cookies          = $this->tests->get_cookies();
  $request_uri_path = $this->get_request_cache_path( $cookies );
  $last = substr($request_uri_path, -1); 
 if($last === '/') {
    return;
  }
 $protocol = $this->test->is_ssl() ? 'https://' : 'http://';
 
  header('Location: '. $protocol . $host . $request_uri_path . '/'. $this->test->get_query_string());
  exit;
}
```

The same way create a new `maybe_redirect_on_trailing_slash` that will check if the domain from the is one of the domain where trailing slash redirection is activated.
If it is not the case bail out.
Otherwise check if the URL has a trailing slash and redirect it to the one without the slash if it does. 
```php
protected function maybe_redirect_on_trailing_slash() {
   $host = $this->config->getHosts();
   $hosts_with_redirection = $this->config->get_configs()['non_trailing_slash_redirect'];
  if(! in_array($host, $hosts_with_redirection)) {
   return; 
 }
  $cookies          = $this->tests->get_cookies();
  $request_uri_path = $this->get_request_cache_path( $cookies );
  $last = substr($request_uri_path, -1); 
 if($last !== '/') {
    return;
  }
 $protocol = $this->test->is_ssl() ? 'https://' : 'http://';
  $new_path_uri = substr_replace($request_uri_path ,"", -1);
  header('Location: '. $protocol . $host . $new_path_uri . $this->test->get_query_string());
  exit;
}
```
We will call the new functions just before L84 in `maybe_init_process`.

Finally we will create a filter in `Admin\Settings\Subscriber` that would save the option that indicate on which domains we activate the redirection on trailing slash.

### Estimate effort
Effort `S`

**Comment by remyperona** [comment]
We also need to do the opposite action, redirect to non-trailing slash if the current permalink structure doesn't have one and the current URL has one

**Comment by piotrbak** [comment]
Closing it in favor of:
https://github.com/wp-media/wp-rocket/issues/5207

**Comment by Kilbourne** [comment]
Hi,
Any news about this? It was released and then reverted. Currently it doesn't redirect to the canonical version.

**Comment by maxplateau** [comment]
Hello, I think not respecting trailing slash is a huge issue and i have a solution :
You just need to add a test at the end of the function can_init_process() in class-tests.php file.

// Don't process if not trailing slash
if( substr($this->get_request_uri_base(),-1) != "/" ) {
	return false;
}

My code just check if the uri is ending with a slash and if it's not then the cache is not processed.

Please add this code in your next update. Thanks !

**Comment by piotrbak** [comment]
@maxplateau Unfortunately, that's not that easy. Please take a look at our discussions in related PRs to learn more about issues we were having. Thanks!

**Comment by Kilbourne** [comment]
Hi!
Checking the relates PRs seems that the reverted solution has issues only when this conditions are met:
_When permalinks are set to be without / and website is in the subdirectory we might experience redirect loop._
As this is a problem only for a (little?) part of the users, while not respecting site's slash is a big problem for most of the users, maybe you could start to release an utility plugin ( with big WARNING :) in the readme) so we can resolve  while you fix all possible cases. Is this possible?

**Comment by maxplateau** [comment]
I totally agree with @Kilbourne !
In the meantime, my code is working well and it's fixing this issue so I will using it until you find a solution.

**Comment by ugurcanbulut** [comment]
@piotrbak This is causing critical issues on SEO. Because, it doesn't even respect our custom 301 redirects. @maxplateau's solution is working. However, modifying the core files isn't what we want.

Can't you apply filter for the `can_init_process()` method. Something like;
```
add_filter( 'rocket_can_init_process', function ( $defult, $uri ) {
    if ( substr( $uri, -1 ) !== '/' ) {
        return false;
    }

    return $default;
}
```
