### ISSUE TITLE
Remove Unused CSS clears only up to 100 rows in specific conditions

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5017]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Remove Unused CSS feature can clear only up to 100 rows of Used CSS.

**To Reproduce**
1. Enable RUCSS on site with 200+ pages
3. Enable preload
4. Wait for the Used CSS to be generated on more than 100 pages. Some of them should be completed, pending, in-progress, etc.
5. Clear the Used CSS from top menu
6. Check the database and number of rows

**Expected behavior**
We should clear all completed Used CSS entries

**Additional context**
Let's groom and implement it since we still don't know the effort and timeline for moving to filesystem storage.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
yes, it deletes only 100 rows from completed/failed rows.

We need to pass the number attribute here:
https://github.com/wp-media/wp-rocket/blob/8318b7efde95a1d075d0dc2f015ecb121baa9ce7/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php#L324

and if not, it will fallback to the default 100 rows here on BerlinDB:
https://github.com/wp-media/wp-rocket/blob/7e03b2305c012202e330bbe2f57b0c7b0300c779/inc/Dependencies/Database/Query.php#L440

**Effort:** [S]

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1846812383/337290?folderId=3864740

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1862766086/339722/

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1870469756/341005/

To add more details: customer added a new element/functionality on the page that had missing CSS. Clearing Used CSS didn't resolve the issue because site has almost 700 pages and only 100 were cleared - so the "fix" was not visible until all the Used CSS was manually cleared from the table.

**Comment by NataliaDrause** [comment]
Same case: https://secure.helpscout.net/conversation/1884953725/343052/

Changes were not applied even after clearing used CSS. There are ~2600 pages.
The issue is resolved after manually clearing the table.

**Comment by NataliaDrause** [comment]
related: https://secure.helpscout.net/conversation/1886250247/343281/

~15000 pages

**Comment by engahmeds3ed** [comment]
I think it'd be better to use a raw query to delete all completed/failed rows instead of deleting one by one for many reasons:-
1. One query is always faster than multiple ones and u can notice that with huge sites.
2. To delete one by one we need to go into a loop which may take a lot of time and maximum execution time is reached and error would be triggered.
3. We took this approach before based on this issue: https://github.com/berlindb/core/issues/130 but after some thinking I found that we don't delete this cache when using truncate table! so we can safely delete using one query without touching the cache.
4. Also bear in mind that we are about to launch the usedCSS into filesystem and we need the deletion to be very fast to sync the DB with the filesystem.

@wp-media/php @wp-media/productrocket what do u think?

**Comment by remyperona** [comment]
I agree for our case it does seem better

**Comment by NataliaDrause** [comment]
Related: https://secure.helpscout.net/conversation/1871590138/341144/
Failed rucss for the homepage until I manually truncated the Used CSS table.
Site has 2000+ pages

**Comment by vmanthos** [comment]
Related: https://secure.helpscout.net/conversation/1914150627/347353/

**Comment by camilamadronero-zz** [comment]
related https://secure.helpscout.net/conversation/1914726953/347501?folderId=2675957
