### ISSUE TITLE
RUCSS - Automatically allowlist the SaaS IP(s) in Cloudflare's firewall

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5030]
**Is your feature request related to a problem? Please describe.**

In some cases, Remove Unused CSS cannot be created because Cloudflare blocks the used CSS generator's IP.

**Describe the solution you'd like**

Automatically, allowlist the SaaS IP(s) in Cloudflare's firewall.

Here is the API we can use:
https://developers.cloudflare.com/firewall/api/cf-firewall-rules/endpoints/

**Describe alternatives you've considered**

Connect with Cloudflare, and ask them to allowlist the IP(s) on their side.

**Additional context**

**Slack Convo:** https://wp-media.slack.com/archives/C029G1B5HD2/p1652177676248359

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
For the moment I can't reproduce it
## Find the root cause
It comes from the firewall from Cloudflare as @vmanthos said.
## Scope a solution
To fix this problem we will have to modify the Cloudflare Addon to add a rule to the  firewall.
The first class we will have to modify is `APIClient` where we will have to create a new method to call the firewall endpoint from Cloudflare API:
```php
public function add_firewall_rule(Rule $rule) {
   $this->request( "zones/{$this->zone_id}/firewall/rules", (array) $rule, 'post' );
}
```

We will also have to add another call  to retrive currents rules from Cloudflare:
```php
public function list_firewall_rules() {
 return $this->get("zones/{$this->zone_id}/firewall/rules");
}
```

Then we will have to create a presenter that will take your IP and a value 'block' or 'allow' as parameters and build the $rule data from it.

Finally we will have to create a method in the Subscriber that will check for  each IP address from the SAAS if it is already in the list of rules from Cloudflare.
For each rule not already present we will then add it with the function `add_firewall_rule`. 
This method will be hook on the `init` action and will have a check on a transient (two weeks duration) to prevent it to be runned at every run.

List of ips from the SAAS:

- 141.94.254.72
- 141.94.252.17
- 51.178.134.82
- 135.125.180.130
- 141.95.202.69
- 15.235.11.139
- 15.235.14.231
- 15.235.50.215
- 15.235.50.217

### Estimate effort
`S`

**Comment by vmanthos** [comment]
@CrochetFeve0251 @jeawhanlee @wp-media/productrocket 

I manually added a firewall rule using Cloudflare's UI. It included all IPs listed above:
```
(ip.src eq 141.94.254.72) or (ip.src eq 141.94.252.17) or (ip.src eq 51.178.134.82) or (ip.src eq 135.125.180.130) or (ip.src eq 141.95.202.69) or (ip.src eq 15.235.11.139) or (ip.src eq 15.235.14.231) or (ip.src eq 15.235.50.215) or (ip.src eq 15.235.50.217)
```
These have no effect in allowing the SaaS to reach a site where the **Bot Fight Mode** (BFM) is enabled. i.e. only disabling the latter allows our SaaS to reach the site and generate used CSS. 

Also, when that's disabled it doesn't matter whether the rule is active or not. Therefore we can safely assume that the only Cloudflare feature that prevented the SaaS from reaching my test site was **Bot Fight Mode**.

By the way, there is a way to add an allow-known-bots rule alongside allowlisting the IP(s) by appending the following to the previous conditions:
`or (cf.client.bot)`

but this requires the SaaS to be added to their known bots list.

It seems we don't need to allowlist the SaaS IP(s) through Cloudflare's firewall. We only need to take care of #5032.

**Update:**

This doesn't work because of how BFM works:
> The current version of BFM/SBFM has limited control. You can’t bypass or skip BFM/SBFM using Firewall Rules, Page Rules or IP Access Rules.

**Reference:** https://support.cloudflare.com/hc/en-us/articles/360035387431#5KX8t3C6SObnoWs5F6YOlU

**Comment by jeawhanlee** [comment]
@vmanthos So we can close this issue as fixing https://github.com/wp-media/wp-rocket/issues/5032 will also fix it?

**Comment by vmanthos** [comment]
Let's close it @jeawhanlee. We can reopen it if anything changes.
