### ISSUE TITLE
RUCSS compatibility with the BoomBox theme dark mode

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5064]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
BoomBox dark mode dynamically injects a stylesheet that overrides the light mode style. 

It's done using inline JavaScript that looks for a specific inline style ID: `boombox-primary-style-inline-css`

```
<script type="text/javascript">
...
if ( !!getCookie( 'boombox-theme-mode' ) ) {

var appendInterval = setInterval( function() {
	if ( document.getElementById( 'boombox-primary-style-inline-css' ) ) {
		clearInterval( appendInterval );
		appendThemeModeLink();
	}
}, 25 );
}
...
</script>
```

When the script doesn't find the target selector, the dark mode CSS file won't be added resulting in the following console error: 

```
Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at appendThemeModeLink (<anonymous>:37:16)
    at HTMLAnchorElement.<anonymous> (<anonymous>:57:9)
appendThemeModeLink @ VM281:37
(anonymous) @ VM281:57
```

Adding `boombox-primary-style-inline-css` to `rocket_rucss_inline_atts_exclusions` fixes the issue. 

We might consider a possible leaner approach by simply changing the target selector on the JavaScript code to our own `wpr-usedcss`. 

In this case, we will be hooking to the `rocket_buffer` and looking for: 
```
document.getElementById( 'boombox-primary-style-inline-css' )
```
and replacing it by: 
```
document.getElementById( 'wpr-usedcss' )
```

That way, we don't have to preserve the whole CSS.

**To Reproduce**
1. Use the BoomBox theme
2. Enable the dark mode + RUCSS
3. See error when trying to change to dark mode

**Expected behavior**
BoomBox dark mode should work out of the box when RUCSS is used.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1889250265/343784

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
That's a good idea of replacing the id of the style with our styles, but I don't like changing the user's own script in that way as this may reproduce other unknown issues, I'd take the safest approach as u did using the helper plugin installed on the customer's site.

@wp-media/productrocket @piotrbak I think this is a product decision to take if this plugin is widely used we can make third party compatibility class or waiting a bit to see if some clients ask for it?

# Grooming just in case

## Reproduce the problem
No, but I can see the issue on the customer's site.

## Identify the root cause
As Adame mentioned above, removing this style with id `boombox-primary-style-inline-css` will generate this JS error.

## Scope a solution
We need to preserve this style in the page by creating a thirdparty compatibility class and use the filter `rocket_rucss_inline_atts_exclusions` to preserve the pattern `boombox-primary-style-inline-css`.
and add some tests then make composer script to run its own integration tests.

## Estimate the effort
[S]

**Comment by DahmaniAdame** [comment]
@engahmeds3ed Preserving the stylesheet is indeed safer.
Maybe we could have a separate preservation mechanism to keep only the empty `<style>` to use in cases where the issue is related to JavaScript.
This will avoid duplicate CSS and extra unnecessary weight on the page. 
In this case, 1000 lines of code (CSS) is added to both the Used CSS and the preserved `<style>` tag. 
This could apply to https://github.com/wp-media/wp-rocket/issues/4598 as well and should solve https://github.com/wp-media/wp-rocket/issues/4598#issuecomment-1133601752 case without requiring extra style preservation.

**Comment by piotrbak** [comment]
@engahmeds3ed what do you think about the above? I think that it definitely makes sense 🤔

**Comment by engahmeds3ed** [comment]
Yes I like this idea, will update the grooming.

**Comment by DahmaniAdame** [comment]
Related (mechanics-wise) - https://secure.helpscout.net/conversation/1920150352/348451/

We exclude `divi-style-inline-inline-css` from RUCSS https://github.com/wp-media/wp-rocket/issues/4598, which causes it to overrule other styles. In this case, I had to exclude `et-critical-inline-css` as well.

Should be fixed when this issue is sorted out.
