### ISSUE TITLE
Exclude images from being lazy-loaded only on Desktop

### ISSUE THREAD

**Issue by paxtonpaxy** [wp-media/wp-rocket#5103]
**Is your feature request related to a problem? Please describe.**

Hi, after using WP Rocket on many sites, I noticed that there is no option to exclude images from being lazy-loaded on a specific device (Mobile / Desktop / maybe Tablet). 
In many cases, I had an issue with an LCP on the Desktop where the LCP was the image that was being lazy-loaded. So in order to improve the score on Desktop, I had to exclude it in "_Excluded images or iframes_" which affected the score on Mobile devices.
Maybe there is an option or a way that we can do that? I just could not find it.

**Describe the solution you'd like**

A way to exclude images from being lazy-loaded on specific breakpoints (Common breakpoints are 320px — 480px for mobile devices, 481px — 768px for iPads & tablets, 769px — 1024px for small screens like laptop, 1025px — 1200px for large screens like Desktops).

**Describe alternatives you've considered**

Maybe, as an alternative, there can be 3 fields where can we exclude images from being lazy-loaded.
Example: Universal (Mobile and Desktop like "_Excluded images or iframes_") - *new* Only for Mobile resolutions - *new* Only for Desktop resolution
Based on user data (and your expert opinion) we can determine the breakpoints for these two resolutions (breakpoints).  

**Additional context**

![example](https://user-images.githubusercontent.com/63547348/171365753-9b338d28-0023-410c-b7af-94212cd39fbd.jpg)

Here I added an example of what I mean and how I imagen it to look. Note, that the design is up to you.
I work on optimizing the performance of the site, 99% of which are WordPress sites. So I use WP Rocket quite frequently. 
I am looking forward to your feedback and I would be happy to help you in any way that I can.

**Comment by piotrbak** [comment]
Hello @risticaivan and thanks for creating the issue. We're planning to take care of auto-exclusions and preload of the images that are visible on the first paint. Because of that, we won't be implementing additional fields for that.

For now, you can easily use code similar to this one (+ `rocket_lazyload_excluded_attributes` or `rocket_lazyload_excluded_src` filters) to exclude images programatically:
https://github.com/wp-media/wp-rocket-helpers/blob/master/lazyload/wp-rocket-no-lazyload-mobile-cache/wp-rocket-no-lazyload-mobile-cache.php
