### ISSUE TITLE
Serve YouTube Thumbnail in WebP format.

### ISSUE THREAD

**Issue by sandyfzu** [wp-media/wp-rocket#5111]
**Is your feature request related to a problem? Please describe.**
YouTube can serve thumbnails in WebP format, but WP Rocket Lazyload is serving only JPG.

**Describe the solution you'd like**
Making a few changes in the URL, a WebP image can be served.

Example:

JPG: https://i.ytimg.com/vi/Fgvokdu74fw/hqdefault.jpg
WebP: https://i.ytimg.com/vi_webp/Fgvokdu74fw/hqdefault.webp

The only differences are: "vi_webp" and ".webp"

After some test with several videos, all of them had the WebP image available.

**Describe alternatives you've considered**

**Additional context**
Doing this, we can fix this kind of issues:
![image](https://user-images.githubusercontent.com/13713107/171924502-854ec214-0bbc-4c04-8abc-fb4997615ed8.png)

Also, in some images there are big differences in file size:
![image](https://user-images.githubusercontent.com/13713107/171924798-3abc5c79-23c8-4bfe-aa08-a6e6f2efb294.png)

**Comment by mostafa-hisham** [comment]
## Reproduce the problem
no need I can see the problem
## Identify the root cause
use webp for youtube instead of jpg

## Scope a solution
in https://github.com/wp-media/rocket-lazyload-common/blob/39f261a8e73f3a1666b6664aca8b5bf7b7b85c75/src/Assets.php#L253-L258
we can change the image URL 

form
`'https://i.ytimg.com/vi/ID/' . $args['resolution'] . '.jpg'`
to
`'https://i.ytimg.com/vi_webp/ID/' . $args['resolution'] . '.webp'`

## Estimate the effort
Effort `xs`

**Comment by piotrbak** [comment]
By default, we'll serve the `.jpg` version. Webp one will be served when:
1. Webp addon is enabled, on webp cache files
2. With the usage of new filter, webp addon doesn't need to be enabled

**Comment by mostafa-hisham** [comment]
## Reproduce the problem
no need I can see the problem
## Identify the root cause
use webp for youtube instead of jpg

## Scope a solution
in https://github.com/wp-media/rocket-lazyload-common/blob/39f261a8e73f3a1666b6664aca8b5bf7b7b85c75/src/Assets.php#L253-L258
we need to add another argument (extension) to control if we are going to return JPG (default) or webp
and return the image based on that
form
`'https://i.ytimg.com/vi/ID/' . $args['resolution'] . '.jpg'`
to
`'https://i.ytimg.com/vi_webp/ID/' . $args['resolution'] . '.webp'`

in 
https://github.com/wp-media/wp-rocket/blob/60b76bc8bc9a366bf5b9644894df8203bba103fd/inc/Engine/Media/Lazyload/Subscriber.php#L240-L246
we should create a new filter and use it as an extension argument

`$thumbnail_extension = apply_filters( 'rocket_lazyload_youtube_thumbnail_extension', $thumbnail_extension );
`
finally, we can use this new filter in `inc/classes/subscriber/Media/class-webp-subscriber.php`
to make youtube thumbnail webp
## Estimate the effort
Effort `S`
