### ISSUE TITLE
 Replace YouTube iframe with preview image alt attribute is empty 

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5127]
**Is your feature request related to a problem? Please describe.**
When Lazyload > Replace YouTube iframe with preview image is enabled the image has an empty alt attribute.
<img src="https://i.ytimg.com/vi/q_1D6wMXIAI/hqdefault.jpg" **alt=""** width="480" height="360">

**Describe the solution you'd like**
The alt attribute could have alt="youtube preview image" for instance
<img src="https://i.ytimg.com/vi/q_1D6wMXIAI/hqdefault.jpg" **alt="youtube preview image"** width="480" height="360">

**Describe alternatives you've considered**
dynamically add a relevant alt attribute related to the youtube video.

**Additional context**
demo: https://wpr.willychataigner.com/2022/06/09/1447/
related hs ticket: https://secure.helpscout.net/conversation/1906733696/346268/

**Comment by piotrbak** [comment]
It would be great to add alt attribute matching the Youtube vide title. Do we have access to it?

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
We can update https://github.com/wp-media/wp-rocket/blob/1746f4a99dfca830ea32d99a0976b683d364f094/inc/Dependencies/RocketLazyload/Iframe.php#L174 to also include `data-alt` having `$iframe['title']` as value.
Then we update https://github.com/wp-media/wp-rocket/blob/1746f4a99dfca830ea32d99a0976b683d364f094/inc/Dependencies/RocketLazyload/Assets.php#L218 to replace empty alt attribute.

### Estimate the effort ✅
[S]

**Comment by piotrbak** [comment]
We encountered some problems with this PR. The details are specified here:
https://wp-media.slack.com/archives/GUT7FLHF1/p1683577062117629
https://github.com/wp-media/wp-rocket/issues/5910

We need to make sure that special characters are sanitized:
- "
- '
- &
- $&

Their sanitization makes alt looking bad, we're not sure what's SEO impact on this. That's why we need more feedback and r&d here.

Related HS:
https://secure.helpscout.net/conversation/1281337585/194597/
https://secure.helpscout.net/conversation/1251310020/185973?folderId=2683093
https://secure.helpscout.net/conversation/1349453669/216575/
https://secure.helpscout.net/conversation/1913362632/347250?folderId=3864740
https://secure.helpscout.net/conversation/1976765678/361564

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
