### ISSUE TITLE
Update the list of default Delay JavaScript Execution exclusions

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5192]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.11.4`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

The current list of default Delay JavaScript Execution exclusions is this:
```HTML
/jquery-?[0-9.](.*)(.min|.slim|.slim.min)?.js
js-(before|after)
(?:/wp-content/|/wp-includes/)(.*)
```

If the WordPress version is `<5.7` we also display:
```HTML
/jquery-migrate(.min)?.js
```
**Code reference:**
https://github.com/wp-media/wp-rocket/blob/0413fa410ea220213ca98dc30c7edaf738cbf67f/inc/Engine/Optimization/DelayJS/Admin/Settings.php#L123-L167

**To Reproduce**

1. Enable Delay JavaScript Execution.
2. Check the list of default exclusions.

**Expected behavior**

We already exclude `js-extra` by default:
https://github.com/wp-media/wp-rocket/blob/69e2134a20d03c3a5857087c1b81dea3fbba9ad5/inc/Engine/Optimization/DelayJS/HTML.php#L34

We can replace `js-(before|after)` with `js-before`.

Also, the `jquery-migrate(.min)?.js` file can still be loaded from themes/plugins. In such a scenario, adding the default exclusions will result in an error. 

It would be safest if we displayed `jquery-migrate(.min)?.js` in the default exclusions. If the file is there, it will be excluded alongside jQuery. Otherwise, no harm is done.

**Additional context**

Props to @Mai-Saad for pointing out the lack of the `jQuery migrate` exlusion.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Identify the root cause
The root cause was described by @vmanthos .
## Scope a solution
A solution would be based on the code base from the develop branch that changed a bit compared to the one when @vmanthos did the issue to add the filter in the default inside the [`Settings.php`](https://github.com/wp-media/wp-rocket/blob/498e405a9eb0a7bc0aaf8f27e01406bf9470030e/inc/Engine/Optimization/DelayJS/Admin/Settings.php).
At the 150, we will have to add `jquery-migrate(.min)?.js` bellow other values:
https://github.com/wp-media/wp-rocket/blob/498e405a9eb0a7bc0aaf8f27e01406bf9470030e/inc/Engine/Optimization/DelayJS/Admin/Settings.php#L150
Also we will change line 150 to `'js-before',`
## Estimate the effort
Effort `XS`
