### ISSUE TITLE
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in debug.log with certain cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5194]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.11.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
`PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php on line 143` is added to debug.log in some cases

**To Reproduce**
Precondition:
- PHP 8.1.7 is used on the server

1. Fresh install to WPR
2. Enable all CSS optimizations
3. Save then refresh the dashboard
4. Check Debug.log (we may need to visit the home page, and refresh admin multiple times to see the msg in debug.log)

**Expected behavior**
No Deprecated msg added to debug.log

**Additional context**
- The same msg appeared on 3.11.3 when after fresh install activating all options and visiting the home page
- Another scenario https://github.com/wp-media/wp-rocket/pull/5130#pullrequestreview-1004796096

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
I was not able to reproduce the issue.
This is happening because we are validating to `null` in this ternary function here:
https://github.com/wp-media/wp-rocket/blob/d59db4d9d1854453c3c3af60b446c7e4a58376db/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php#L129-L130
and using it here:
https://github.com/wp-media/wp-rocket/blob/d59db4d9d1854453c3c3af60b446c7e4a58376db/inc/Engine/Optimization/Minify/CSS/AbstractCSSOptimization.php#L143
Since php 8.1 has deprecated passing null to a lot of functions this error is thrown
So we need to changes this to validate to an empty string `''`. Since this is an XS fix, I'll roll a PR for this.
