### ISSUE TITLE
RUCSS counter msg isnot displayed without refresh in certain case

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5195]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version =>. 3.11.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Counter msg for RUCSS is not displayed till refreshing the dashboard after activating RUCSS

**To Reproduce**
1. Fresh install to wpr
2. Activate RUCSS and save
3. Counter msg not displayed till refreshing dashboard

**Expected behavior**
Counter msg displayed after saving settings with no need to manually refresh the page

**Screenshots**
https://jmp.sh/zqxRj0D

**Additional context**
- Same with PHP 7.4.3 and 8.1.7
- The same scenario was working fine on 3.11.3
- Another case when permissions are read-only to cache folder then enable RUCSS, once permissions are back, we need to refresh twice so we can see the RUCSS msg => in this case, if we fixed permissions after RUCSS was enabled by > 90sec, the success msg will be displayed not the counter although nothing is completed yet in used CSS table
- Note: clear used CSS, reactivate RUCSS, change safelist => all displaying msg with no need to refresh

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
The problem is that the first time we enable the plugin and the RUCSS option, there we don't have the `used-css` directory inside the `cache` directory so when we check if this directory is writable to show the processing counter notice here:
https://github.com/wp-media/wp-rocket/blob/3830fc28818e1f46d465f994a9085cc31d8056df/inc/Engine/Optimization/RUCSS/Admin/Settings.php#L318-L320

it bails out as the directory isn't there but then in this callback:
https://github.com/wp-media/wp-rocket/blob/b1f4762b694c426f11a67debb4c187293e5a39b4/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L87

we are creating the directory but this is happening after the previous check so the notice will not appear in the first time and will appear in the second refresh.

## Solution
The solution is very simple :D we just need to change the order of the `admin_notices` hook callbacks to make `notice_write_permissions` be before `display_processing_notice`.

This will only affect the order of admin notices appear to the admin user, to show the used_css write permissions notice before all other notices.

Making the simple PR now.

**Comment by Mai-Saad** [comment]
Happening now on 3.12.1 and develop

**Comment by piotrbak** [comment]
@Mai-Saad Is this still an issue?

**Comment by piotrbak** [comment]
Works fine on 3.13.0.2
