### ISSUE TITLE
WP Rocket picks up the wrong URL to purge/use a referrer when Weglot is used

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5279]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.11.4.2`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When [Weglot](https://wordpress.org/plugins/weglot/) is used, and the user is on a translated page, we are picking up the original URL to `Purge this URL` and `Clear Used CSS of this URL` as well as their respective referrer. 

We are purging the original URL and redirecting to it when clicking the action button. The translated page is not purged.

**To Reproduce**
1. Use Weglot
2. Translate a URL
3. Go to the translated page URL

**Expected behavior**
WP Rocket should pick the right URLs/referrers for individual pages when Weglot is used.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1954490982/357041/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
Joseph found another issue with [Weglot](https://wordpress.org/plugins/weglot/) 

**Additional context**
[Slack](https://wp-media.slack.com/archives/C029G1B5HD2/p1674841585208609)

After some investigation when the `Auto redirect feature` is enabled in the `Weglot` plugin 
if you add a query parameter to the URL it redirects to translated page based on User language

```
https://example.de/?test
https://example.de/?nocache
```
and it redirects me
```
https://example.de/en/?test
https://example.de/?nocache
```

there is a filter in **weglot** plugin `weglot_autoredirect_skip` to skip auto redirect

this snippet 
will stop auto-redirect for URLs that has `nowprocket` which is used in the RUCSS process
```
function stop_autoredirect( $should_skip ) {
	if(isset($_GET['nowprocket']) && $_GET['nowprocket'] !== 0){
		return true;
	}
	return $should_skip;
}
add_filter( 'weglot_autoredirect_skip', 'stop_autoredirect');
```

**Comment by mostafa-hisham** [comment]
## Reproduce the problem :heavy_check_mark: 

## Identify the root cause
there is a code in weglot plugin that overrides the `$_SERVER['REQUEST_URI']` and removes the language from it

[https://plugins.trac.wordpress.org/browser/weglot/trunk/src/actions/front/class-translate-page-weglot.php#L264
](https://plugins.trac.wordpress.org/browser/weglot/trunk/src/actions/front/class-translate-page-weglot.php#L264
)
which is then used to generate the `referer` URL in the admin bar purge url

https://github.com/wp-media/wp-rocket/blob/ef300cf2d46e837789f9ad42ff8166c832a47dc3/inc/common/admin-bar.php#L18-L25

## Scope a solution

we need to check if the weglot plugin is enabled 
and the language code to the `$_SERVER['REQUEST_URI']`
this a function that gets the current language  `weglot_get_current_language()`
 
 @wp-media/php if anyone has time can have a second look at it 

- we need to update tests and also add a fix for the [RUCSS nowprocket auto-redirect problem](https://github.com/wp-media/wp-rocket/issues/5279#issuecomment-1413208971)
## Estimate the effort
Effort `S`

**Comment by joejoe04** [comment]
Have a case here I'm adding in case it might offer any additional insight into the issue:
https://secure.helpscout.net/conversation/2135497247/397124/

In this case, Weglot is in use and the CSS file for Borlabs Cookie notice plugin is not being included in the Used CSS at all. The CSS file is excluded from the page but its contents is not included in the Used CSS, so all those styles are missing and no safelist values will work at all to preserve them.

For now, the temporary solution was to use the [WP Rocket | Exclude CSS files from Remove Unused CSS](https://github.com/wp-media/wp-rocket-helpers/tree/master/rucss/wp-rocket-exclude-external-css-rucss) helper to exclude the file completely.

**Comment by piotrbak** [comment]
We'll also need to implement the RUCSS fix mentioned [here.](https://github.com/wp-media/wp-rocket/issues/5279#issuecomment-1413208971)
