### ISSUE TITLE
Fatal error when activate WPR while PHP version on WP not matching that on server

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5306]
**Before submitting an issue please check that you’ve completed the following steps:**
- Make sure you’re on the latest version => 3.12
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Fatal error when activate WPR while PHP version on WP != PHP on server

**To Reproduce**
1. Server with PHP 8.1.8
2. WP using PHP 7.4.3
3. Clone WPR `git clone https://github.com/wp-media/wp-rocket.git`
4. Install WPR `composer install --no-dev --no-scripts`
5. Activate WPR

**Expected behavior**
No fatal error

**Screenshots**
`[12-Aug-2022 09:35:50 UTC] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.30. in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/vendor/composer/platform_check.php on line 24`

**Additional context**
- installing using ` composer install --ignore-platform-reqs --no-dev --no-scripts -o` is working fine
- if PHP on WP matches that on the server i.e 8.1.8 in our case, It will work fine. (thanks to @engahmeds3ed )

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
This is because in this PR #5166 we added the use of Monolog V2.
The latest version of Monolog2 is `2.8.0` which loads this [psr/log package](https://github.com/Seldaek/monolog/blob/2.8.0/composer.json#L17)

So when you run the composer command from the terminal which has PHP version >=8 this will load psr/log V3 which requires php 8.0 as in here:
https://github.com/php-fig/log/blob/3.0.0/composer.json#L14

then if your wordpress installation has a different PHP version the application will throw the mentioned error.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
