### ISSUE TITLE
PHP Warning: Attempt to read property "id" on bool (Cache.php)

### ISSUE THREAD

**Issue by twwn** [wp-media/wp-rocket#5332]
**Describe the bug**
Minor new bug appeared (so far once) after updating to 3.12[.0.1]:
`PHP Warning:  Attempt to read property "id" on bool in /srv/wp-content/plugins/wp-rocket/inc/Engine/Preload/Database/Queries/Cache.php on line 257`

**To Reproduce**
No idea, wasn't caused by staff.

**Expected behavior**
No negative impact noticed.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @twwn thank you for creating the issue, we're looking into it.

**Comment by CrochetFeve0251** [comment]
@twwn @piotrbak unfortunately I wasn't able to reproduce the issue.

**Comment by twwn** [comment]
We've seen it almost a dozen times by now in the log.

**Comment by piotrbak** [comment]
@twwn Could you reach our Support Team and send WP/SFTP access to affected website?

**Comment by twwn** [comment]
> @twwn Could you reach our Support Team and send WP/SFTP access to affected website?

I'm afraid that's not possible due to customer data present.

But I did add a line that logs the URL for which the warning is emitted. From the one time it's happened since:

>`{our.site}/?post_type=postman_sent_mail&p=4449683`

We use Post SMTP. Seems that's only an issue under specific circumstances though, since there were dozens of mails sent today, not just that one. (Also, only more occurrences will tell if it doesn't happen with other URLs.)

*edit:* Second occurrence with logging now, also `?post_type=postman_sent_mail&p=* `.

*edit2:* … and a 3rd time, I dare say now that it's related to this interaction with Post SMTP.

*edit3:* A day later and over a dozen more warnings, every single one with `post_type=postman_sent_mail`

**Comment by Mai-Saad** [comment]
Can reproduce it on 3.12.0.4 with the following scenario:
1- Install and activate WPR
2- Delete any post permanently
Test env:https://new.rocketlabsqa.ovh/
PHP 8.1.8, Wp 6.0.2, active theme https://pcm.wordpress.org/themes/minimalistblogger/

**Comment by CrochetFeve0251** [comment]
@Mai-Saad did you done any other step cause even doing that doesn't generate the warning on my env?

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I was able to reproduce the problem.

## Identify the root cause
The problem is due to the fact [`get_rows_by_url`](https://github.com/wp-media/wp-rocket/blob/cdf8f7bd07a2566b800d13f0981bf5babfd5b63f/inc/Engine/Preload/Database/Queries/Cache.php#L248) use the cache when quering that seems to return  boolean value instead of the object as it is already deleted.

##  Scope a solution

The easy solution will be to guard for boolean before following [line](https://github.com/wp-media/wp-rocket/blob/cdf8f7bd07a2566b800d13f0981bf5babfd5b63f/inc/Engine/Preload/Database/Queries/Cache.php#L257).

## Estimate the effort
Effort `XS`
