### ISSUE TITLE
Bug related to preload process when user cache is enabled

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5369]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When User Cache is enabled, visiting URL while being logged-in changes the value in DB to `completed`.

**To Reproduce**
1. Make sure that page is in the database, User Cache is enabled, Separate cache for Mobiles is disabled
2. Clear the cache and visit specific URL while being logged-in
3. Entry related to this URL is set to `complete`, general cache is not generated

**Expected behavior**
When generating cache for logged-in users we should not change the value in db.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I can reproduce the problem.
## Identify the root cause
Problem comes from the fact the cache is loaded when a user is enabled and that there is no way to check if the user is connected.
## Scope a solution
In the [preload subscriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Subscriber.php) we can guard the method [`update_cache_row`](https://github.com/wp-media/wp-rocket/blob/1c2a690acf88429319f74a317cd79eda6a085390/inc/Engine/Preload/Subscriber.php#L167) with the `is_user_logged_in` that bail out when it returns that the user exists.

## Estimate the effort
Effort `XS`
