### ISSUE TITLE
Exclude pages ending with `.php` from getting added to the new preload module

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5382]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.0.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WP Rocket's Buffer skips processing pages ending with `.php`. 

https://github.com/wp-media/wp-rocket/blob/3a1dfedbf8937d084351be7a7e3f1b36b0b853f9/inc/classes/Buffer/class-tests.php#L449-L453

But they are still added to the new preload module table.

![image](https://user-images.githubusercontent.com/1289174/187901873-b97fdbc8-57dd-4e27-818e-721db8057177.png)

They will be stuck there as `in-progress` since their respective cache will never be created. 

It's best to simply not add them in the first place to avoid any unnecessary load trying to process them. 

In addition to that, we should notify the user that they have URLs ending with `.php` and that consequently, they won't be cached or optimized. 

In most cases, it's the permalink's structure that is at fault. 

**To Reproduce**
1. Add a permalink structure using `.php` as an extension to post names
2. See the issue on the `wp_wpr_rocket_cache` table

**Expected behavior**
`.php` URLs should not be added to preload.

**Screenshots**
Added to the description. 

**Additional context**
Ticket - https://secure.helpscout.net/conversation/1995216159/365250

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by PaulSchiretz** [comment]
Same is true for .kml(location data) files, they need to be present in the sitemap, but are stuck in "in progress" in the preload table, i currently excluded them via the exclude options in the cache & optimizations tab....

**Comment by CrochetFeve0251** [comment]
### Identify the root cause
The root issue is that we are not checking if the URL finishes by a `.php` in the query add the URL to the preload.
### Scope a solution
For fixing that a solution would be to guard against that inside the [`create_or_update`](https://github.com/wp-media/wp-rocket/blob/37319214bd835a6d1cee5dcdea8327a2f6f498cf/inc/Engine/Preload/Database/Queries/Cache.php#L124) method and [`create_or_nothing`](https://github.com/wp-media/wp-rocket/blob/37319214bd835a6d1cee5dcdea8327a2f6f498cf/inc/Engine/Preload/Database/Queries/Cache.php#L184) from the [`Cache`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Database/Queries/Cache.php) model.

for that we can use add the following code:
```php
$extensions = [ 
 	'php' => 1, 
 	'xml' => 1, 
 	'xsl' => 1, 
 ]; 

$extension  = pathinfo( $url, PATHINFO_EXTENSION );

$is_rejected = $extension && isset( $extensions[ $extension ] );

if(! $is_rejected) {
 return false;
}

```
We need also to update unit tests linked with theses methods and create a new test case for this scenario.

### Estimate the effort
Effort `S`
