### ISSUE TITLE
Hamburger menu mobile needs multiple touches to register click

### ISSUE THREAD

**Issue by bwafels** [wp-media/wp-rocket#5389]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: YES 
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Lately I have noticed this behaviour on your site and my site. The hamburger menu does not register the first touch because the site is not completely loaded. Clicks on menu's & buttons should react faster, as customers may think the site does not work.
It never happens on desktop because you always move your mouse to a button / menu. However, on mobile/touch a first action may be a click iso a movement.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your mobile version of your site "wp-rocket"
2. Click on the hamburger menu the first time you load (do not scroll)
3. The first click does not activate the menu

**Expected behavior**
Instant reaction to an action

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @bwafels thanks for creating the issue.

This issue is most likely related to Delay JS feature. Please find our documentation useful in order to exclude the correct scripts from being delayed:
https://docs.wp-rocket.me/article/1560-delay-javascript-execution-compatibility-exclusions

If that doesn't work, please reach our support to see if there's something we can do about it.
