### ISSUE TITLE
PHP fatal error with a fresh install when Action Scheduler tables don't exist 

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5396]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.0.5`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

With `3.12.*` the following PHP fatal error occurs with a fresh install when no Action Scheduler (AS) tables exist in the database:
https://snippi.com/s/v7iu8lz

This is happening with `3.12.*` but not with `3.11.5` where we display the notice to create the missing tables.

**To Reproduce**

1. Make sure no AS tables exist in the database.
2. Install the latest WP Rocket version.
3. Look into the `debug.log` to find the prementioned error.

**Expected behavior**

No PHP fatal error should occur even if AS tables don't exist.

**Additional context**

N/A.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We need to make sure there's no conflict there:
https://github.com/wp-media/wp-rocket/issues/5021

**Comment by jeawhanlee** [comment]
###  Reproduce the problem ✅
Reproduced locally.

### Identify the root cause ✅
@piotrbak, I don't think there is a conflict.
This is happening because the required AS tables are not present before we [activate](https://github.com/wp-media/wp-rocket/blob/b39567786ccc5c321ace147e1ff9dcfaa6fa2eed/inc/Engine/Preload/Activation/Activation.php#L40) the preload since this is enabled by default. 

### Scope a solution ✅
We can add a check here:
https://github.com/wp-media/wp-rocket/blob/b39567786ccc5c321ace147e1ff9dcfaa6fa2eed/inc/Engine/Preload/Activation/Activation.php#L40-L43
the same way we do for displaying incorrect AS table notice but this time we recreate the tables if the check returns false:
```
use ActionScheduler_StoreSchema;
use ActionScheduler_LoggerSchema;

$store_schema  = new ActionScheduler_StoreSchema();
$logger_schema = new ActionScheduler_LoggerSchema();
$store_schema->register_tables( true );
$logger_schema->register_tables( true );
```
that way we would have the tables ready before [this line](https://github.com/wp-media/wp-rocket/blob/b39567786ccc5c321ace147e1ff9dcfaa6fa2eed/inc/Engine/Preload/Activation/Activation.php#L45) runs.

### Estimate the effort ✅
Effort [XS]

Please can you validate this grooming 🙏 @CrochetFeve0251 @Tabrisrp @engahmeds3ed

**Comment by CrochetFeve0251** [comment]
@jeawhanlee that looks good to me

**Comment by Joliamendi** [comment]
Hi everyone What should we do if we see this error? This error keeps showing up in my WordPress dashboard.

**Comment by piotrbak** [comment]
@Joliamendi Please follow the following issue:
https://github.com/wp-media/wp-rocket/issues/5440

The message doesn't affect how WP Rocket works, it's an UI problem only.
