### ISSUE TITLE
Used CSS isnot automatically generated for home page if preload is disabled

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5410]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.0.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling RUCSS while preload is disabled, although success msg mentioned that the home page was processed. nothing exists in the used CSS table

**To Reproduce**
1. Activate WPR
2. Disable preload
3. clear cache
4. enable RUCSS
5. Success notice displayed => check the used CSS table

**Expected behavior**
RUCSS is processed automatically for the home page when enabling the RUCSS while preload is disabled

**Additional context**
- Manual visit for the home page will add an entry in used CSS table to be processed

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
### Identify the root cause ✅ 
We're missing in the new preload the code we had before:
https://github.com/wp-media/wp-rocket/blob/cb0ef908b6d0e1eace8545b96d23b0b93c44d1ec/inc/Engine/Preload/PreloadSubscriber.php#L391
https://github.com/wp-media/wp-rocket/blob/cb0ef908b6d0e1eace8545b96d23b0b93c44d1ec/inc/Engine/Preload/PreloadSubscriber.php#L59

### Scope a solution ✅ 
Add to the new preload a method to perform the homepage preload when the options are changed. We have the preload function in the controller, so we can use that in the subscriber

### Estimate the effort ✅
Effort `[XS]`
