### ISSUE TITLE
Exclude Rocket LazyLoad plugin from Delay JavaScript Execution

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5412]
https://wordpress.org/plugins/rocket-lazy-load/
For better user experience, we could exclude this LazyLoad script from Delay, so that images will load without interaction, as we do for other LazyLoad scripts. 

This is the file:
`/plugins/rocket-lazy-load/assets/js/16.1/lazyload.min.js`

Tested with WP Rocket version 3.12.0.5  - it's not excluded automatically

**Comment by MarcusFuto** [comment]
Hello @webtrainingwheels @Mai-Saad @piotrbak and @jeawhanlee .

I have a peculiar issue with this loading. The content on mobile doesn't load because it first needs interaction. We have tried adding a script for the mobile page to scroll but that also gets lazyloaded. Excluding the script results in script not being loaded at all. Here is a video on the issue: 

https://www.loom.com/share/b41d4d7fb4c84bc4805f4e875016e453

Hope somebody can lend a helping hand!

**Comment by webtrainingwheels** [comment]
@MarcusFuto We use Github for development and related discussions. It's not the right place to get custom support. Please open a support ticket and we can help you there: https://wp-rocket.me/support/
