### ISSUE TITLE
Catch Action Scheduler exceptions

### ISSUE THREAD

**Issue by remyperona** [wp-media/wp-rocket#5463]
Action Scheduler functions to enqueue or schedule action can throw exceptions when an error happens. Exceptions are going to create fatal errors on website if not caught. We have seen this happen when the tables were missing for example.

We added guards to recreate the tables when they are missing, but there is other cases where exceptions could be thrown, so we should guard against them wherever we use AS functions, with the use of try/catch clauses.

**Comment by CrochetFeve0251** [comment]
### Scope a solution

All Action Scheduler function are centralized into the [`AbstractASQueue`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Common/Queue/AbstractASQueue.php) class.
To fix that problem we will have to add the logger into the class as a property so we can use it later to log errors from AS.
Due to that we will have to add the logger as an argument from the following queues:
- Preload Queue [in this service provider](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Preload/ServiceProvider.php#L85) and [this one.](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Preload/Activation/ServiceProvider.php#L45)
- RUCSS Queue [in this service provider](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Optimization/RUCSS/ServiceProvider.php#L65).

Then for each call inside [`AbstractASQueue`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Common/Queue/AbstractASQueue.php) class we need to warp every AS functions in the following logic:

```php
try {

} catch (Exception $e) {
   $this->logger->error($e->getMessage());
} 
```

We need to do this for the following places:
- [`as_enqueue_async_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L25)
- [`as_schedule_single_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L37) and return `0`.
- [`as_schedule_recurring_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L80) and return `0`.
- [`as_has_scheduled_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L96) and return `false`.
- [`as_schedule_cron_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L123) and return `''`.
- [`as_unschedule_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L142)
- [`as_unschedule_all_actions`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L152)
- [`as_next_scheduled_action`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L165)
- [`as_get_scheduled_actions`](https://github.com/wp-media/wp-rocket/blob/478b6085c1353c13ba91a522ceca6c70bb27fad1/inc/Engine/Common/Queue/AbstractASQueue.php#L196) and return `null`.

Finally some test should be written to make sure theses functions won't let an exception make the global program crash.
### Estimate effort
Effort `S`
