### ISSUE TITLE
VAT missing in cached WooCommerce mobile product pages

### ISSUE THREAD

**Issue by twwn** [wp-media/wp-rocket#5487]
**Describe the bug**
Every other day cached WooCommerce mobile product pages will omit our VAT (Germany: 19%). Our prices are entered with VAT included on the backend, so something must have triggered WooCommerce to subtract it out.

Desktop pages are unaffected.

There are no errors/warning message whatsoever. The only thing that is any indication is that the problem temporarily ceases when I clear WP-Rocket's cache.  

**To Reproduce**
1. Have WP-Rocket active.
2. Wait.

**Expected behavior**
VAT shown correctly in prices.

**Additional context**
PHP 8.1.8
Wordpress 6.0.2
Wordfence 7.6.2
WP Rocket 3.12.1.1
WooCommerce 6.9.4
German Market 3.16

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @twwn this sounds like a problem with configuration, rather than a bug in the code. WP Rocket caches what was displayed on the screen or what was preloaded. If you allow prices without VAT being displayed (for people outside the EU, etc.), it's possible that WP Rocket cached it and shown for all customers afterward. For that kind of cases we usually suggest using ajax to dynamically update the prices or dynamic cookies to have different sets of cache for each version of your website:
https://docs.wp-rocket.me/article/1313-create-different-cache-files-with-dynamic-and-mandatory-cookies

If you're not sure what's happening, please reach our support for further investigation. Feel free to reopen the issue if it comes out that the bug is in the code.
