### ISSUE TITLE
PHP Warning: Undefined array key "host" in /wp-rocket/inc/Engine/Optimization/AssetsLocalCache.php

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5492]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.12.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before check

**Describe the bug**

A customer reported the following PHP warning:
```PHP
PHP Warning: Undefined array key "host" in/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/AssetsLocalCache.php
```

This is coming from here:
https://github.com/wp-media/wp-rocket/blob/ba69c9365ac25fe9eb3c09d6910799bdfa13e225/inc/Engine/Optimization/AssetsLocalCache.php#L112

**To Reproduce**

No way to reproduce the issue except for maybe hardcoding a `$url` without a host.

**Expected behavior**

No PHP warnings should occur.

**Additional context**

The customer didn't provide access to the site or even its URL so I wasn't able to really investigate this.

They are using [Azure Storage](https://wordpress.org/plugins/windows-azure-storage/)  to store images on CDN, and they think this can be related.

This is happening with PHP 8.0.

**Ticket:** https://secure.helpscout.net/conversation/2015029866/369818?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by MichaelRobb6** [comment]
I was experiencing the same issue. The error was being recorded in the logs multiple times a second. I was able to stop it by disabling the "Minify CSS files" option under "File Optimization".

Hope this helps with figuring out a solution to the issue.

**Comment by victoras** [comment]
+1 The same problem and [Azure Storage](https://wordpress.org/plugins/windows-azure-storage/) is used.

**Comment by agenceKanvas** [comment]
Same warning on a debian with PHP 8.1
07.46.13.211:0] PHP Warning:  Undefined array key "host" in /home/marsbetausr/www/wp-content/plugins/wp-rocket/inc/Engine/Optimization/AssetsLocalCache.php on line 112

**Comment by engahmeds3ed** [comment]
I can reproduce the issue by adding the following line to `wp-config.php` file:

```
define( 'WP_CONTENT_URL', '/wp-content/' );
```

The problem is coming from this part:
https://github.com/wp-media/wp-rocket/blob/42cb23f01f5ee7def30b8827b5e77e7ae913b391/inc/Engine/Optimization/AbstractOptimization.php#L96-L98

So if the content url is relative we will deal with all urls as external url, this affects minify and combine CSS at least.

We can fix that by not bailing out if the content_url is relative url (no host is there) but instead use the host of home_url to be added to `$hosts` array and restructure this part of code to move the declaration of `$hosts` variable to be above this condition.

Effort: [XS]

**Comment by vmanthos** [comment]
This hasn't been fixed for the following case. :disappointed:.

If:
1. CSS minification is enabled.
2. A stylesheet is added like:
```HTML
<link rel="stylesheet" href="/style.css">
```

the following pops up in the `debug.log`:
```php
PHP Warning:  Undefined array key "host" in /var/www/example.com/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/AssetsLocalCache.php on line 112
```

I'm reopening the issue.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem with the steps @vmanthos laid out.

### Identify the root cause ✅
We are doing a check [here](https://github.com/wp-media/wp-rocket/blob/b533e6c14d8b1bc6835c02289aa1af76bd3aaf28/inc/Engine/Optimization/AbstractOptimization.php#L145) which will return true if it is a relative url without the `wp-content` and pass urls like that to `get_filepath` which throws the warning.

### Scope a solution ✅
To solve this, I propose we return early when the url host is empty.
```
if ( empty( $file['host'] ) ) {
	return false;
}
```
### Estimate the effort ✅
[XS]
