### ISSUE TITLE
DJE issue: type="rocketlazyloadscript" is added to the code highlighter

### ISSUE THREAD

**Issue by worldwildweb** [wp-media/wp-rocket#5496]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 3.12.1.1
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When a code highlighter is on the page and DJE enabled, JS code within the code highlighter will be modified by DJE.
`<script>` will become `<script type="rocketlazyloadscript">`
 
The first reported issue occurred in Elementor but it also occurs in Gutenberg.

**To Reproduce**
1. create a page or a post
2. add a code highlighter on the page or post
![on Elementor](https://user-images.githubusercontent.com/1954918/194223187-5bd796b8-a6f9-4f3d-812d-4af29221bd67.png)
3. add `<script>` in the code highlighter
4. save and visit the front en
5. See the error:
```
<pre data-line="" class="highlight-height language-javascript line-numbers">				
<code readonly="true" class="language-javascript">
<xmp>
        <script>
</xmp>
</code>
</pre>
```
will become
```
<pre data-line="" class="highlight-height language-javascript line-numbers">				
<code readonly="true" class="language-javascript">
<xmp>
        <script type="rocketlazyloadscript">
</xmp>
</code>
</pre>
```

**Expected behavior**
type="rocketlazyloadscript" shouldn't be added within the code highlighter.

**Screenshots**
![image](https://user-images.githubusercontent.com/1954918/194221887-082564c8-7678-4ba3-b32f-f46ddb00cfba.png)

**Additional context**
related: https://secure.helpscout.net/conversation/2028107248/372821
Gutenberg demo: https://wphangar.com/2022/10/05/code-test
Elementor demo: https://wpr.willychataigner.com/code-highlight/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
More details:
https://wp-media.slack.com/archives/C60QX4FC1/p1665479576918649?thread_ts=1665479435.743559&cid=C60QX4FC1

**Comment by mostafa-hisham** [comment]
## Reproduce the problem
I couldn't reproduce the issue with Gutenberg :heavy_multiplication_x: 
Elementor  :heavy_check_mark: 



## Identify the root cause :white_check_mark:

- Gutenberg
we don't add the `type="rocketlazyloadscript`" to the script tags inside the code block
because `<script>` is converted to `&lt;script>` by Gutenberg so it doesn't get picked up by the regex
[DEMO](https://rocketlabsqa.ovh/code-highlight/)

- Elementor
is using a deprecated HTML element `<xmp>`
and it should be replaced and follow what Gutenberg do [(replace it with `<pre><code>` and convert  `<` to `&lt;`)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/xmp#summary)
[DEMO](https://rocketlabsqa.ovh/elementor-23972/)

@piotrbak should we open an issue in **elementor** to stop using the deprecated `<xmp>` tag?


## Scope a solution :white_check_mark:
We can edit the code skip scripts inside `<xmp>` when we collect <scripts> tags in the page
in
https://github.com/wp-media/wp-rocket/blob/46e6d87108cd02d3ed7f311b47c6dc9fd4790c95/inc/Engine/Optimization/DelayJS/HTML.php#L129-L144

## Estimate the effort :white_check_mark:
effort: [S]
