### ISSUE TITLE
Never Cache URL(s) exclusions work only when they match the existence or not of a trailing slash in permalinks

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5509]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅`3.12.1.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When adding URLs to the "Never Cache URL(s)" text area, for them to be excluded they will have to have a trailing slash or don't have one depending on whether one exists or not in the permalinks.

There is a **Should you use the trailing slash?** section in [Exclude Pages from the Cache and Optimizations](https://docs.wp-rocket.me/article/54-exclude-pages-from-the-cache) which describes how URLs should be added to the specific text area for the exclusions to work.

Users will add a trailing `/` or not, primarily based on habit, i.e. the way they write or paste URLs. Unless they read our doc beforehand, this may end up in URLs not being excluded which can be confusing/frustrating both for the customers and support.

**To Reproduce**
1. When permalinks have a trailing `/` exclude a URL without one.
2. The URL will be cached.
3. Remove the trailing `/` from the permalinks and exclude a URL that has one.
4. The URL will be cached.

**Expected behavior**

A URL added in the "Never Cache URL(s)" text area should be excluded regardless of whether it has a trailing `/` or not and the way the permalinks are set up.

**Additional context**

With WP Rocket `3.12.2` we are going to allow users to exclude URLs from preloading. "Never cache URLs" should be excluded from preloading as well but this won't happen given that the URLs may not be excluded from caching if they aren't formed correctly as far as the trailing `/` goes.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Identify the root cause
The root cause is due to the regex in the method [`can_process_uri`](https://github.com/wp-media/wp-rocket/blob/e6c18910a083ba92aefb07b352bd95d32865ad7a/inc/classes/Buffer/class-tests.php#L592) that only compare to the value without formatting the URL.
## Scope a solution
A solution would be adding the corresponding url with(out) the / inside the regex from  field if it is not present so we can exclude both urls in the same time.
For that we can add the following logic in `get_rocket_cache_reject_uri`:
```php
$uris = array_map(function ($uri) {
		return preg_replace('\\/$', '(\\/)?/', $uri);
	}, $uris);
```
Then we will have to check if tests break and as it is a central feature it can generate a lot of work.
## Estimate the effort
Effort `S`
