### ISSUE TITLE
Never cache this page is not applied immediately after saving a post

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5519]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When activating the "Never cache this page" option in WP Rocket's meta-box, e.g. for `/page-1/`, the change isn't added to the configuration file after saving the post despite the file being regenerated. This means the page can still be cached.

It will be added to the config file the next time it is regenerated, e.g. when the option is selected for another post/page, e.g. `/page-2/`. In this case, only `/page-1/` will be added, but not `/page-2/`.

I've confirmed the URI is added at this point:
https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/admin/ui/meta-boxes.php#L148

but when `rocket_generate_config_file()` runs it doesn't include it.
 
[get_rocket_cache_reject_uri()](https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/functions/options.php#L247), which is used when [regenerating the config file](https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/functions/files.php#L126), runs several times after updating the post. In [one of them](https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/Engine/Preload/Links/Subscriber.php#L177), the newly excluded URI exists, but when the `save_post` hook fires and we regenerate the config file it doesn't.

Although I've debugged this extensively I wasn't able to figure out why this is happening.

**To Reproduce**

1. Enable "Never cache this page" for a post.
2. Visit the post on the front end.
3. WP Rocket's signature will be there / a cached file will be in `/cache/wp-rocket/`.

**Expected behavior**

The URI should be excluded immediately after saving the post/page.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by Mai-Saad** [comment]
> It will be added to the config file the next time it is regenerated, e.g. when the option is selected for another post/page, e.g. /page-2/. In this case, only /page-1/ will be added, but not /page-2/

As a result, currently using 3.12.3.2, if we checked the Never Cache URL from post -> edit then we visited the post, it will be cached. 
Then if we unchecked the Never Cache URL and visited the post, it won't be cached

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
### Identify the root cause ✅
We are declared the variable - `$uri` as static [here](https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/functions/options.php#L248) and returning it back here which contains an old value of the cache_reject_uri option previously assigned.
### Scope a solution ✅
We can simply just pass `true` to `get_rocket_cache_reject_uri` like this: `get_rocket_cache_reject_uri( true )` in [get_rocket_config_file](https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/functions/files.php#L126) and this will force the static url to reverted to null like stated in the doc block https://github.com/wp-media/wp-rocket/blob/c417af78b06be599a0be626fa4586a04c105133c/inc/functions/options.php#L243
### Estimate the effort ✅
[XS]
