### ISSUE TITLE
Remove Unused CSS - Allow using a separate file for Used CSS

### ISSUE THREAD

**Issue by camilamadronero-zz** [wp-media/wp-rocket#5540]
**Is your feature request related to a problem? Please describe.**
Using a separate file to serve Used CSS could result in better performance because the HTML size won't increase, the CSS file can be cached in the browser, etc.
Additionally, other performance plugins include this as an option for customers to decide.

**Describe the solution you'd like**
Remove Unused CSS could have an option or filter to choose how to serve the Used CSS: inline or in a separate file.

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2054759324/378695?folderId=2675957
Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1667315073463089

**Comment by DahmaniAdame** [comment]
> Using a separate file to serve Used CSS could result in better performance because the HTML size won't increase

HTML size won't increase + the separate file that needs to be downloaded = the same size.

By separating both, here is what will happen:
- The server will have one request more that will need to be compressed and send.
- The browser will need to load the CSS file in order to parse it (extra task). 
- It will be render-blocking (extra inconvenience).
- It will require using CPCSS + RUCSS. Even under ideal conditions, there will be extra work for the browser to do (delayed parsing + layout calculation after transitioning from CPCSS to RUCSS) that might result in FOUCs. 

The inline CSS within the HTML file has fewer tasks to do with no inconveniences. 

> the CSS file can be cached in the browser, etc.

For what end? Chances are pretty low for the same CSS to be used on multiple pages. How would having the RUCSS file cache will benefit performance? 

The HTML page, which holds the inline CSS, will also be cached by the browser :) 

And even if the CSS file is cached, it still needs to be loaded by the browser in order to use it. It will take a few milliseconds, but it's still extra time to note.

If we go the CPCSS + RUCSS road, there are high risks of generating FOUCs. 

To lower that risk, we will need CPCSS for each page ideally. That will be one extra task to do for SaaS. 

Transitioning from CPCSS to RUCSS should be improved as well, but it will be hard to predict the outcome as the layout calculation will surely still trigger layout shifts when happening. 

Another thing to consider is that we will be forced to store the new CPCSS and the RUCSS uncompressed as we can't predict if the visitor's browser supports compression or not. That will drastically increase the disk size, especially on large websites. 

So far, I only see cons and no real benefits, even in the theoretical part 😅

We need a benchmark of a complex and long page to confirm.

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.

**Comment by suzoutlet** [comment]
Similiar request to externalize generated Used CSS(and inline script) and reduce HTML size: https://onecomhelp.zendesk.com/agent/tickets/17314532

**Comment by suzoutlet** [comment]
Another case: https://onecomhelp.zendesk.com/agent/tickets/17664844
