### ISSUE TITLE
CDN - CNAME field is emptied and can't be added anymore with https protocol.

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5577]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
After updating to 3.12.3, the CDN's CNAME field is emptied and the CNAME can't be added anymore to it if it contains the https:// protocol.

**To Reproduce**
1. Add a CNAME like https://xxxxxxxx.rocketcdn.me/
2. Update to 3.12.3
3. There's no more CNAME
4. try to add https://xxxxxxxx.rocketcdn.me and save
5. See the empty field
6. try to add xxxxxxxx.rocketcdn.me
7. CNAME is saved

**Expected behavior**
CNAME should be saved in any case.

**Additional context**
Per, Vasilis, this commit may involved: https://github.com/wp-media/wp-rocket/pull/5105/commits/2244ddcc7e79955170a26a8d4c85d1582a9e9ee2

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by vmanthos** [comment]
It's because of the following commit:
https://github.com/wp-media/wp-rocket/pull/5105/commits/2244ddcc7e79955170a26a8d4c85d1582a9e9ee2

When a CNAME has a scheme, `sanitize_cdn_cnames()` will return:
```PHP
array (
  0 => false,
  1 => false,
)
```

Removing the `FILTER_FLAG_HOSTNAME` flag will resolve this:
https://github.com/wp-media/wp-rocket/blob/5ae181cb176c520f7fc9990cd8f5c9e9f6281d5e/inc/Engine/Admin/Settings/Settings.php#L696
