### ISSUE TITLE
WordPress database error Table doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 AND a.hook='rocket_preload_job_check_finished'

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5582]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.3.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Preload is getting stuck and the following error occurs in debug.log:

`WordPress database error Table 'wp_faqz6ghts.a' doesn't exist for query SELECT a.action_id FROM  a WHERE 1=1 AND a.hook='rocket_preload_job_check_finished' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('after_setup_theme'), WP_Hook->do_action, WP_Hook->apply_filters, et_core_init, ET_Core_PageResource::remove_static_resources, ET_Core_PageResource::do_remove_static_resources, et_core_clear_wp_cache, rocket_clean_domain, do_action('after_rocket_clean_domain'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->clean_full_cache, WP_Rocket\Engine\Preload\Controller\Queue->add_job_preload_job_check_finished_async, WP_Rocket\Engine\Preload\Controller\Queue->job_preload_job_check_finished_async_exists, WP_Rocket\Engine\Common\Queue\AbstractASQueue->search, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions`

**To Reproduce**

We have a few reports, but no clear steps to reproduce the error.

One case reported that the error gets logged when Elementor plugin gets updated. However, the error occurs on sites that don't use Elementor as well.

@engahmeds3ed shared steps to see the error:

Use the following code in functions.php:
```
add_action( 'after_setup_theme', function() {
	as_get_scheduled_actions(
		array(
			'hook'   => 'rocket-preload',
		)
	);
} );
```

**Expected behavior**
No error and preload should not get stuck.

**Additional context**

Tickets:
https://secure.helpscout.net/conversation/2067516492/381563?folderId=3864740
https://secure.helpscout.net/conversation/2067475228/381549?folderId=3864740
https://secure.helpscout.net/conversation/2068336239/381721/

Slack thread: https://wp-media.slack.com/archives/C43T1AYMQ/p1668610775237889

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by engahmeds3ed** [comment]
**How can we reproduce this error?**

You can install an older version of Elementor like [v3.7.8](https://downloads.wordpress.org/plugin/elementor.3.7.8.zip) then update manually to [v3.8.0](https://downloads.wordpress.org/plugin/elementor.3.8.0.zip) or update to the latest release.
In my test I updated manually so I replaced the files using ftp or locally by copy/paste not from the UI.

**Notes when reproducing it**

- After update they may show a notice that that upgrade routine is happening in the background and if it takes some time you can click on a button to fire the routine now, in my case it took some time before automatically ran the routine so maybe you need to click on this button

![Screenshot from 2022-11-20 10-33-01](https://user-images.githubusercontent.com/15707971/202912255-13fb39fe-bfb3-4c5d-90f4-af92c837cfc8.png)

- I think after updating from the UI, you need to visit the admin at least once to trigger the update routine.

**What is the root cause?**

When updating Elementor plugin, t[here](https://github.com/elementor/elementor/blob/master/core/base/db-upgrades-manager.php#L72) is a background task that is working in the background to perform their update routine and once this routine is completed, they call cache clear [here](https://github.com/elementor/elementor/blob/master/core/base/db-upgrades-manager.php#L82) which calls this method [here](https://github.com/elementor/elementor/blob/master/core/files/manager.php#L106-L129) then calls this method here and you will notice at the end it fires the action elementor/core/files/clear_cache
and we do have compatibility code with elementor which clears our cache once the previously mentioned action is fired [here](https://github.com/wp-media/wp-rocket/blob/2129ac9f7748f1706b573f65459174a2b4fbc35d/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L61) that calls our function rocket_clean_domain [here](https://github.com/wp-media/wp-rocket/blob/2129ac9f7748f1706b573f65459174a2b4fbc35d/inc/ThirdParty/Plugins/PageBuilder/Elementor.php#L93) that fires the action after_rocket_clean_domain  [here](https://github.com/wp-media/wp-rocket/blob/2c33d12076f31c9d6b78696cb22e23e7b14358f0/inc/functions/files.php#L781)

Then in preload we use this action [here](https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Subscriber.php#L113) and t[here](https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Subscriber.php#L280) we are trying to check if preload is finished or not and then clear the whole cache in the preload database [here](https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Subscriber.php#L280)

and the main problem is happening inside this last method add_job_preload_job_check_finished_async [here](https://github.com/wp-media/wp-rocket/blob/a02e2986e8a940c254b82fdee3773c850f462dd4/inc/Engine/Preload/Controller/Queue.php#L67) which calls the method job_preload_job_check_finished_async_exists [here](https://github.com/wp-media/wp-rocket/blob/a02e2986e8a940c254b82fdee3773c850f462dd4/inc/Engine/Preload/Controller/Queue.php#L80-L86) and this happens as mentioned above in a background task which in most/all cases fires before init firing so it throws the error exactly like the code that I shared before (that we added into functions.php and it threw the same error in the log)

**What is the solution?**
I believe we need to guard against it [here](https://github.com/wp-media/wp-rocket/blob/a02e2986e8a940c254b82fdee3773c850f462dd4/inc/Engine/Preload/Controller/Queue.php#L79) to bailout once we find that init hook isn't fired yet, like the following:
```
if ( ! did_action( 'init' ) ) {
	return false;
}
```
