### ISSUE TITLE
Restore post from trash clears the entire cache

### ISSUE THREAD

**Issue by valmirselmani** [wp-media/wp-rocket#5585]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When you restore a post from the trash, the entire language cache is cleared. It will also clear the entire cache if WPML is not used.

After extensive debugging, i found the issue:

Function causing the issue:
inc/functions/files.php:rocket_clean_files

specifically:
get_rocket_parse_url( $url );

this function returns:
[host] => example.com
[path] => /de/
[scheme] => https
[query] => page_id=14136
[fragment] =>

After restoring the post from the trash, the URL of the post is https://example.com/de/?page_id=14136.
However, since only the path is used to determine the folder to delete, the entire cache folder for that language is deleted.

**To Reproduce**
1. Delete Post
2. Restore Post from Trash
3. go to wp-content/cache/wp-rocket/your-domain/
4. See folder is empty

**Expected behavior**
Should not do anything because the post is a draft when restored from the trash.

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The problem was easy to reproduce. I just had to follow steps.
## Identify the root cause
The root cause was also give and is located here:
https://github.com/wp-media/wp-rocket/blob/d0d700ace0c2f9e6262448489e2597697856d0a5/inc/functions/files.php#L531

We use the path which is not at the right format.

## Scope a solution
As a solution I propose to add a check for the `page_id` param and load the post to get the right permalink inside a new function `rocket_maybe_find_right_trash_url`:

```php
function rocket_maybe_find_right_trash_url(array $parsed_url) {
	if(! array_key_exists('query', $parsed_url) || array_key_exists('query', $parsed_url) === '') {
		return $parsed_url;
	}
	$query = $parsed_url['query'];
	$query = explode('&', $query);

	$params = [];

	foreach ($query as $item) {
		$item = explode('=', $item);
		if(count($item) < 2) {
			continue;
		}
		$params[$item[0]] = $item[1];
	}

	$post = get_post((int) $params['page_id']);

	if(! $post) {
		return $parsed_url;
	}
	$post->post_status = 'publish';

	$permalink = get_permalink( $post );
	
	if( ! $permalink ) {
		return $parsed_url;
	}
	
	$new_permalink = str_replace( '__trashed', '', $permalink );

	
	
	return get_rocket_parse_url( $new_permalink );
}
```

We will then call this function after [this line ](https://github.com/wp-media/wp-rocket/blob/d0d700ace0c2f9e6262448489e2597697856d0a5/inc/functions/files.php#L531) on `parsed_url`.

## Estimate the effort
Effort `XS`
