### ISSUE TITLE
Partial URL added to Never Cache URLs is excluded from preloading

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5588]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ `3.12.3.1`
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When adding URLs to the Never Cache URLs text area, those are removed from the `wpr_rocket_cache` table in order to avoid preloading them.

When the partial path of a URL is added, WP Rocket will not exclude it from caching, i.e. caching/optimizations are applied. However, the URL is removed from `wpr_rocket_cache` table.

**To Reproduce**
1. Change the permalinks to not include a trailing `/` (necessary after [this fix](https://github.com/wp-media/wp-rocket/pull/5565)).
2. For a URL `/example-url-to-exclude` add `/example-url-to` to the "Never Cache URLs" text area.
3. After preload finishes check the `wpr_rocket_cache` table for the `/example-url-to-exclude` URL. It will not be there.

**Expected behavior**

We should not exclude the URL from preload. Ideally, although this may not be possible, we should detect such URLs and display a notice.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem

### Identify the root cause ✅
When this check runs:
https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L47
it will return true because the regex looks similar to this: `/hello-|/(?:.+/)?feed(?:/(?:.+/?)?)?$|/(?:.+/)?embed/|/wc-api/v(.*)|/(index\.php/)?wp\-json(/.*|$)` and this will match with `https://example.com/hello-world` in the cache table.

### Scope a solution ✅
To make sure we are getting a precise match of the last section of the url and not part of it, we can update this method:
https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L13-L17
We will alter the never cache uri patterns that is returned to only update the user added patterns by matching with `$`:

```
$user_added_cache_reject_uri = (array) get_rocket_option( 'cache_reject_uri', [] );
$altered_user_added_cache_reject_uri = implode( '$|', $user_added_cache_reject_uri );

$user_added_cache_reject_uri = implode( '|', $user_added_cache_reject_uri );
$cache_reject_uri            = get_rocket_cache_reject_uri();

$regexes[] = str_replace( $user_added_cache_reject_uri . '|', $altered_user_added_cache_reject_uri . '$|', $cache_reject_uri );
```
That way only the exact end of the url will be matched. we need to do a check if there are user added patterns or not before we alter the pattern.

Also update tests.

### Estimate the effort ✅
[S]

**Comment by jeawhanlee** [comment]
> ### Reproduce the problem ✅
> I was able to reproduce the problem
> 
> ### Identify the root cause ✅
> When this check runs:
> 
> https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L47
> 
> 
> it will return true because the regex looks similar to this: `/hello-|/(?:.+/)?feed(?:/(?:.+/?)?)?$|/(?:.+/)?embed/|/wc-api/v(.*)|/(index\.php/)?wp\-json(/.*|$)` and this will match with `https://example.com/hello-world` in the cache table.
> ### Scope a solution ✅
> To make sure we are getting a precise match of the last section of the url and not part of it, we can update this method:
> 
> https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/Engine/Preload/Controller/CheckExcludedTrait.php#L13-L17
> 
> 
> We will alter the never cache uri patterns that is returned to only update the user added patterns by matching with `$`:
> ```
> $user_added_cache_reject_uri = (array) get_rocket_option( 'cache_reject_uri', [] );
> $altered_user_added_cache_reject_uri = implode( '$|', $user_added_cache_reject_uri );
> 
> $user_added_cache_reject_uri = implode( '|', $user_added_cache_reject_uri );
> $cache_reject_uri            = get_rocket_cache_reject_uri();
> 
> $regexes[] = str_replace( $user_added_cache_reject_uri . '|', $altered_user_added_cache_reject_uri . '$|', $cache_reject_uri );
> ```
> 
> That way only the exact end of the url will be matched. we need to do a check if there are user added patterns or not before we alter the pattern.
> 
> Also update tests.
> 
> ### Estimate the effort ✅
> [S]

After some discussion with @mostafa-hisham we agreed that it's better we add this logic during sanitization:
https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/functions/formatting.php#L175

We will create a new function to add the metachar `$` at the end of each path:

```
function rocket_match_path_end( $path ) {
	if ( ! $path ) {
		return '';
	}

	if ( preg_match( '#\$$#', $path ) ) {
		return $path;
	}

	return $path . '$';
}
```
then call new function here after `rocket_clean_wildcards`: https://github.com/wp-media/wp-rocket/blob/6a4e49d1173c921932ad5a3b5f94c89abc77a8c6/inc/functions/formatting.php#L180
