### ISSUE TITLE
Lazy Load Placeholder returning 404 error

### ISSUE THREAD

**Issue by kulterryan** [wp-media/wp-rocket#5613]
**Describe the bug**

**To Reproduce**
1. Enable lazy loading on the website.
2. Run a speed test on GTMetrix or WebPageTest.
3. Look into the watermark for the issue.
4. That's all.

**Expected behavior**

- Invalid request generated from the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/36154235/206364497-3c2a6708-bc88-4fed-90b6-a2cbb2ec7f6d.png)

**Additional context**
- We can locally host the placeholder image as well.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @kulterryan and thanks for creating the issue. The steps you provided don't allow me to reproduce the issue, it looks like the problem is somewhere else, possibly incompatibility between 3rd-party or faulty markup.

I'd suggest contacting our support team. Whenever we pin the culprit, we'll either reopen the issue or create new one with more detailed steps to reproduce.
