### ISSUE TITLE
Improve the logic of adding URLs to the preload queue

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5619]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 🆗 
- Used the search feature to ensure that the bug hasn’t been reported before 🆗 

**Describe the bug**
This logic is not correct:
https://github.com/wp-media/wp-rocket/blob/36f4b69222ac01aba6e267b1d950f5fb639f53d7/inc/Engine/Preload/Database/Queries/Cache.php#L320

We're looking for the entries in the database that are `in-progress`, if for any reason we reach the defined number, the preload process will be stuck until the cache is cleared or our 12h cron `rocket_preload_revert_old_in_progress_rows` runs.

**To Reproduce**
1. Enable preload
2. Change status of 45 URLs to `in-progress` in the database
3. The preload is stuck

**Expected behavior**
The preload should not be stuck then.

**Additional context**
We introduced this limit to make sure that we are not flooding AS with our actions and we allow 3rd-parties to run their own actions in timely manner.

Instead of [checking](https://github.com/wp-media/wp-rocket/blob/36f4b69222ac01aba6e267b1d950f5fb639f53d7/inc/Engine/Preload/Database/Queries/Cache.php#L320) the number of `in-progress` items in the database, we could check the number of `rocket_preload_job_preload_url` actions that are pending in the AS.

We could also consider other ways of fixing this problem, the discussion:
https://wp-media.slack.com/archives/GUT7FLHF1/p1670860166280739

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I skipped that part as I think @piotrbak already done that before creating the issue.
## Identify the root cause
The root cause are URLS that remains in `in-progress` status due to their preloading failing that can be due to multiple reasons:
- 2 level cache.
- wrong encoding from URLS.
- etc
The problem is that this URLS will slowing slowdown the preload process until in some cases block it totally the preload until the next 12h batch that will clean stuck in-progress tasks.
 
## Scope a solution
Multiple solutions have been proposed by the team but looking at all solutions proposed I guess this one can solve the problem and answer all issues.

We will then check before each batch if some URL have been send for more than 2 mins and if it is the case then pass all URLs to the new status `failed`. This should prevent the preload to be stuck and will allow us to keep the old logic.

Finally instead of checking `in-progress` in the 12h CRON, we will then check for `failed`.

For that we will have to add a method `make_status_failed` with the following content in the [Query class](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Database/Queries/Cache.php) :
```php

public function make_status_failed( int $id ) {
		return $this->update_item(
			$id,
			[
				'status' => 'failed',
			]
		);
}

```

We will have also to add a method `get_outdated_in_progress_jobs` with the following content:
```php

public function get_outdated_in_progress_jobs() {
                return $this->query(
			[
				'count'     => true,
				'status'    => 'in-progress',
				'is_locked' => false,
                                'date_query' => [
					[
						'column' => 'last_accessed',
						'before' => '2 minute ago',
					],
				],
			],
			false
		);

}

```
Finally we will have to add a method `update_last_access` with the following content:
```php
public function update_last_access( int $id ) {
return $this->update_item(
			$id,
			[
				'last_accessed' => current_time( 'mysql', true ),
			]
		);
}
```

Once we did that we need to update the `update_last_access` in the [PreloadUrl controller](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Controller/PreloadUrl.php) this way [after the logic](https://github.com/wp-media/wp-rocket/blob/1f30942192514822d57f319a5cef05adc42aba62/inc/Engine/Preload/Controller/PreloadUrl.php#L153) :
```php

$row = $this->query->get_rows_by_url( $url );
$this->query->update_last_access( $row->id );

```

Finally we need to change [`revert_old_in_progress`](https://github.com/wp-media/wp-rocket/blob/1f30942192514822d57f319a5cef05adc42aba62/inc/Engine/Preload/Database/Queries/Cache.php#L445) to `revert_old_failed` with the following content:
```php
	public function revert_old_failed() {
		// Get the database interface.
		$db = $this->get_db();

		// Bail if no database interface is available.
		if ( empty( $db ) ) {
			return false;
		}

		$prefixed_table_name = $db->prefix . $this->table_name;
		$db->query( "UPDATE `$prefixed_table_name` SET status = 'pending' WHERE status = 'failed' AND `modified` <= date_sub(now(), interval 12 hour)" );
	}
```

Then in the same class we need to add the logic to check for stuck `in-progress` rows before [this line](https://github.com/wp-media/wp-rocket/blob/1f30942192514822d57f319a5cef05adc42aba62/inc/Engine/Preload/Controller/PreloadUrl.php#L184) inside `process_pending_jobs` method:
```php
$stuck_rows = $this->query->get_outdated_in_progress_jobs();
foreach($stuck_rows as $row) {
   $this->query->make_status_failed( $row->id );
}
```

Finally we need to change the check inside the 12h CRON to `failed` by changing this code inside the method [`revert_old_in_progress_rows`](https://github.com/wp-media/wp-rocket/blob/1f30942192514822d57f319a5cef05adc42aba62/inc/Engine/Preload/Cron/Subscriber.php#L235) of [CRON subscriber class](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Preload/Cron/Subscriber.php):
```php
$this->query->revert_old_in_progress();
```

by:
```php
$this->query->revert_old_failed();
```

## Estimate the effort
Effort `S`
