### ISSUE TITLE
/wp-json/ is cached for language slugs that use TranslatePress

### ISSUE THREAD

**Issue by NataliaDrause** [wp-media/wp-rocket#5624]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.12.3.3.
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
When TranslatePress is used, URLs like `https://example.com/fr/wp-json/wp/v2/posts` is cached by default even after https://github.com/wp-media/wp-rocket/issues/5599 issue fix.

**To Reproduce**
1. Install and activate [TranslatePress](https://wordpress.org/plugins/translatepress-multilingual/) plugin
2. Add a language with a slug and save settings:
![image](https://user-images.githubusercontent.com/60236665/207431948-0e6a1bf2-f17c-4bbc-b63b-e8433a36425d.png)

4. Clear WP Rocket cache and visit URL like `https://example.com/fr/wp-json/wp/v2/posts` in the Incognito browser.
5. Check the cache directory - cache file will be created.

**Expected behavior**
`/wp-json/` for language directories should not be cached by default.

**Additional context**
The issue is present in version **3.11.5** as well.

Current workaround is to add the following code snippet to the `functions.php`:

```
if(strpos($_SERVER["REQUEST_URI"], 'wp-json/')) {
    define('DONOTCACHEPAGE', true);
}
```

Ticket: https://secure.helpscout.net/conversation/2093783859/388174?folderId=3864740

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the issue

### Identify the root cause ✅
We are not matching request uris that with characters before `/wp-json/`

### Scope a solution ✅
We can update this: https://github.com/wp-media/wp-rocket/blob/58784bd05e3919595ed453870f69aeb3f580e8b2/inc/3rd-party/plugins/wp-rest-api.php#L44
to become
`$uri[] = $prefix . '/(' . $index . '/)?(.*)' . $suffix . '(/.*|$)';`

### Estimate the effort ✅
[XS]
