### ISSUE TITLE
Used CSS isnot generated automatically for home page in certain cases

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5631]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version=> 3.12.3.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Home page used CSS is not automatically created when switching theme / clear used CSS in certain [states ](https://docs.google.com/spreadsheets/d/1xTmacsiqIIFxyuQVZLudokVBTrFJ3VjeT4rycUDuNWQ/edit#gid=0)

**To Reproduce**
- Preload is disabled
- The home page used CSS was generated and the page exists in the cache folder
1. switch theme or clear used CSS
2. Successful notice displayed while using CSS wasn't recreated for home

**Expected behavior**
Automatically create used CSS for the home page even while preload is disabled for all actions displaying used CSS success notice

**Additional context**
- Same on 3.12.2

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the issue
I succeeded to reproduce the issue following steps @Mai-Saad provided.

##  Identify the root cause
The problem is that we are not reloading the page when cleating.
## Scope a solution
A simple solution would be to add a preload from the homepage at [the end of the process to clean RUCSS and before the redirection](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/RUCSS/Admin/Subscriber.php#L315):
```php
wp_remote_get(
			home_url(),
			[
				'timeout'    => 0.01,
				'blocking'   => false,
				'user-agent' => 'WP Rocket/Homepage Preload',
				'sslverify'  => apply_filters( 'https_local_ssl_verify', false ), // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
			]
		);
```
And change tests.
## Estimate the effort
Effort `S`

**Comment by arjunsaini2966** [comment]
Still facing this issue.
