### ISSUE TITLE
In Elementor, the page transitions feature does not work well when wp rocket is enabled.

### ISSUE THREAD

**Issue by 79ho3ein** [wp-media/wp-rocket#5633]
**Describe the bug**

Hi

In Elementor, the page transitions feature does not work well when wp rocket is enabled. This disorder is such that the pages are loaded first, then the animation is executed. But when we disable wp rocket, everything works fine.

**wp rocket is active :** First the page is loaded and about 1 second later, the animation is executed.
**wp rocket is inactive :** When the page loads, the animation will run immediately.

In general, the problem is that wp rocket creates a delay of about 1 second between the page loading and the animation running.

**To Reproduce**

First, make sure wp-rocket is enabled.
1- In Elementor, enable page transitions like this : https://prnt.sc/Tu8lDllx0lIQ
2- Switch between pages in the frontend. When the page loads (before it is cached), the page first loads for 1 second and then the animation runs.

But when you disable wp-rocket, everything works fine.

**Comment by piotrbak** [comment]
Hello @79ho3ein and thanks for creating the issue. I've just tested it and things are okay. Please check if the issue is still present when Defer JS and Delay JS are disabled.

If it's okay, you'll need to exclude specific script from the affected feature. If you need further help with exclusions, please reach out Support Team.
