### ISSUE TITLE
Set minimum Action Scheduler required version to avoid conflicts with older versions

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#5638]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On sites running an older version of **Action Scheduler**, for example when using WooCommerce v3.5.4 which has AS v2.1.0, or they are using WooCommerce v3.9.5, which includes AS v2.2.5 the following fatal error will happen:

`
Fatal error: Uncaught Error: Class 'ActionScheduler_StoreSchema' not found in /public_html/wp-content/plugins/wp-rocket/inc/Engine/HealthCheck/ActionSchedulerCheck.php:45 Stack trace: #0 /public_html/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\HealthCheck\ActionSchedulerCheck->maybe_recreate_as_tables('') #1 /public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 /public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /public_html/wp-content/plugins/wp-rocket/inc/Engine/Activation/Activation.php(73): do_action('rocket_activati...') #4 /public_html/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Activation\Activation::activate_plugin('') #5 /home/ in /public_html/wp-content/plugins/wp-rocket/inc/Engine/HealthCheck/ActionSchedulerCheck.php on line 45
`

**To Reproduce**
1. Install an older version of WooCommerce
2. Activate WP Rocket
3. See error

**Expected behavior**
We should guard against this error by checking the minimum version of Action Scheduler 

**Additional context**

as a temporary fix, Installing the standalone Action Scheduler plugin solves the issue.

Woocommerce version: https://i.imgur.com/4B57apU.png
ticket https://secure.helpscout.net/conversation/2102275631/390086?folderId=2683093
slack https://wp-media.slack.com/archives/C43T1AYMQ/p1671562361670519

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Similar to https://github.com/wp-media/wp-rocket/issues/5620

**Comment by piotrbak** [comment]
It looks like the lowest AS version that we're compatible with is 3.0.0.

When we detect that lower version is used, we should:
1. Disable features that are using AS (RUCSS and Preload) before doing any operations with AS
2. Grey out RUCSS and Preload features, so it won't be possible to enable them
3. Display warning message with a link to documentation. Wording can be seen below:
`**WP Rocket:** We detected outdated version of Action Scheduler, some WP Rocket features are automatically disabled. To learn how to resolve this problem, please _read more_.`

**Comment by engahmeds3ed** [comment]
# Reproduce the problem
Yes I was able to reproduce the issue

# Identify the root cause
Here:
https://github.com/wp-media/wp-rocket/blob/41e3eddcaa34e679e495f3517745baa232232012/inc/Engine/HealthCheck/ActionSchedulerCheck.php#L45
We are checking if the tables are not created so we try to register and create those tables and this is happening mainly in three places:

1. On WPR activation
2. When updating WPR
3. When enabling WPR's features: remove unused CSS and preload.

The problem is that this class `ActionScheduler_StoreSchema` is added from Action Scheduler's version `3.0.0` so as @piotrbak mentioned above we need to support only from this version and above then show an admin notice to let the customers knows the issue and how to solve it.

# Scope a solution

1. Create two new filters to disable [RUCSS](https://github.com/wp-media/wp-rocket/blob/8144172d0e891a971d3e693187f237a0912a00f0/inc/Engine/Admin/Settings/Page.php#L721) and [Preload](https://github.com/wp-media/wp-rocket/blob/8144172d0e891a971d3e693187f237a0912a00f0/inc/Engine/Admin/Settings/Page.php#L1179-L1189) also we may need to the way we handle invalid license check [here](https://github.com/wp-media/wp-rocket/blob/8144172d0e891a971d3e693187f237a0912a00f0/inc/Engine/Admin/Settings/Page.php#L584) so we can use this new filter to disable RUCSS if the transient is found.
2. [Here](https://github.com/wp-media/wp-rocket/blob/41e3eddcaa34e679e495f3517745baa232232012/inc/Engine/HealthCheck/ActionSchedulerCheck.php#L34-L33) create a new method called `is_valid_action_scheduler_version` and inside it check if the current loaded Action Scheduler's version is more than `3.0.0` and here you can use WooCommerce code found [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php#L114-L117)
3. In the same above class `ActionSchedulerCheck` add a new callback for admin_notices to show the message 
```
**WP Rocket:** We detected outdated version of Action Scheduler, some WP Rocket features are automatically disabled. To learn how to resolve this problem, please _read more_.
```

@piotrbak I believe we need to mentioned the path of loaded AS to let the admin knows about which plugin is making this conflict, what do u think?

4. Also in the same class add callbacks to disable RUCSS and preload by using the new filters in point 1 above and also the filter `pre_get_rocket_option_` for each option from both.
5. Update tests.

# Estimate the effort
From [S] to [M]

**Comment by piotrbak** [comment]
```
I believe we need to mentioned the path of loaded AS to let the admin knows about which plugin is making this conflict, what do u think?
```
@engahmeds3ed Would it be possible to get the plugin name based on the AS path?

**Comment by engahmeds3ed** [comment]
> @engahmeds3ed Would it be possible to get the plugin name based on the AS path?

We can do like WooCommerce is doing like that:
![image](https://user-images.githubusercontent.com/15707971/211315776-3f6113d8-32e8-41bb-929b-42539d0fabbb.png)
OR
Yes we can get the plugin slug from this path.

**Comment by piotrbak** [comment]
@engahmeds3ed It would be great to have a plugin name listed in the message, if that's not possible, the path would work too.

**Comment by engahmeds3ed** [comment]
I found some interesting points as below:

When we have WC old version for example v 3.5.4 which has AS v2.1.0
While activating WPR, the activation code is called before loading our Action Scheduler's code (or the latest version) so only in this instance our activation code is loaded with the old version of AS but after enabling WPR, it loads our latest version.

So reproducing steps are like that:
1. Enable WC 3.5.4
2. Enable WPR
3. see the error with activation

I believe we have two options here:
1. Find a way to load our AS with activation (still checking that)
2. Add the guard into the activation code along with disabling preload with activation only if we detected older version of AS

First option is impossible because the action plugins_loaded is already loaded with the old action scheduler code so the instance of ActionScheduler classes are already there, so the new AS code will not instantiate those classes again.
everything is attached to this plugins_loaded hook like here

https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Dependencies/ActionScheduler/action-scheduler.php#L36

even if I called the functions manually before activation it'll not run because of this line:

https://github.com/wp-media/wp-rocket/blob/103abf7be9d8acd6ea3abae742b533bfd9cd4c32/inc/Dependencies/ActionScheduler/action-scheduler.php#L53

# What is the exact problem of having the old version of Action Scheduler?
We have two problems as below:

1. This [class](https://github.com/wp-media/wp-rocket/blob/41e3eddcaa34e679e495f3517745baa232232012/inc/Engine/HealthCheck/ActionSchedulerCheck.php#L45) isn't there, this part is responsible for creating AS's table again if they are not there => here we may skip this part if the action scheduler is old one.
2. This [function](https://github.com/wp-media/wp-rocket/blob/fbbc98f992c5aaf546ce581794aed90b63502966/inc/Engine/Common/Queue/AbstractASQueue.php#L28) is called in preload and it's not there in the old version of AS => here we can make a stub to define this function if it's not there.

And I checked the Action Scheduler history and this versioning feature (that always loads the most updated version of action scheduler) and found that this feature was there from version 1.0

@piotrbak Now, I believe we don't need to show the admin notice at all, what do u think?

**Comment by piotrbak** [comment]
@engahmeds3ed 
```
This class isn't there, this part is responsible for creating AS's table again if they are not there => here we may skip this part if the action scheduler is old one.
```
But if we skip this part, the table won't be there for our next operations, right?

```
This function is called in preload and it's not there in the old version of AS => here we can make a stub to define this function if it's not there.
```
Yes, that makes sense. We'll just need to be sure that the correct one is used when the new AS is present.

**Comment by engahmeds3ed** [comment]
> But if we skip this part, the table won't be there for our next operations, right?

This is a sanity check and we will only skip it when activating WPR, if u think that there is a case where action scheduler's tables are removed before enabling WPR and there is another plugin that has AS with a version older than v3.0, so it's up to u to decide if we need to handle this case or not (we may disable options with update once detecting this older version of AS)

> Yes, that makes sense. We'll just need to be sure that the correct one is used when the new AS is present.

Yes, we may need to define this method only when this function doesn't exist when it's called here:
https://github.com/wp-media/wp-rocket/blob/fbbc98f992c5aaf546ce581794aed90b63502966/inc/Engine/Common/Queue/AbstractASQueue.php#L28

**Comment by sabrina-zeidan** [comment]
Hi guys :) I want to add what behaviour I saw.

WPR 3.10.9 stopped generating Used CSS. I tried updating to the latest (3.12.5.3), got a Fatal error about ActionScheduler. Found out it was [Follow Up Emails Plugin](https://woocommerce.com/products/follow-up-emails/ ) of version 4.6.4 that was causing the conflict. Disabled it. Tried to regenerate Unused CSS (with WPR 3.10.9), it said "Remove Unused CSS is complete!"
But it got never actually updated on the database and in /cache dir and wasn't applied to the pages obviously.

Interestingly, I tried the following: switched to the default theme, disabled all WPR settings, deactivated all plugins including WPR, activated back WPR only, enabled Unused CSS -- and, the result was absolutely the same: "Remove Unused CSS is complete!" but DB tables were not updated, nothing happened.

Only after I updated WP Rocket to 3.12.5.3 it worked.

I see two things here: 

- ActionScheduler conflict might not obvious throwing an error on activation/update, but just quitely prevent Unused CSS from working.

- Disabling/updating the conflicting plugin might fix the problem in older versions of WPR.
