### ISSUE TITLE
Missing column on wp_wpr_rocket_cache during updates

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5645]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

During plugins updates, and if navigating away from the plugins page, the website might go down and show the following error: 

```
WordPress database error Unknown column 'is_locked' in 'field list' for query INSERT INTO `wp_wpr_rocket_cache` (`url`, `status`, `modified`, `last_accessed`, `is_locked`) VALUES ('some-url', 'completed', '2022-12-20T22:23:24Z', '2022-12-20 22:23:24', '0') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ob_end_flush_all, ob_end_flush, WP_Rocket\\Engine\\Optimization\\Buffer\\Optimization->maybe_process_buffer, do_action('rocket_after_process_buffer'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\\Engine\\Preload\\Subscriber->update_cache_row, WP_Rocket\\Engine\\Preload\\Database\\Queries\\Cache->create_or_update, WP_Rocket\\Dependencies\\Database\\Query->add_item
```

We should safeguard this:

https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Database/Queries/Cache.php#L124-L179

from doing any database update while a plugin update is ongoing. 

**To Reproduce**
Couldn't be reproduced at will. But it happened on 3 different websites.

**Expected behavior**
No issues should happen related to the Preload module while updates are ongoing, even if the user navigates away from the plugins page. 

**Screenshots**

**Additional context**
Related: 

https://secure.helpscout.net/conversation/2070564947/382216/
https://secure.helpscout.net/conversation/2070582927/382224/
https://secure.helpscout.net/conversation/2103762680/390369/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by astanar01** [comment]
Also getting the same thing. I get a PHP warning every 30 seconds or so. :o

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
I cannot reproduce the issue.

## Identify the root cause
The root cause from the issue seems to be that the preload is still running during update even we disabled the CRON.

## Scope a solution
We would need first to detect we are in an update for that I guess we could create an option 'wp_rocket_updating' that we will set to `true` on the filter `upgrader_pre_install` with the following logic:
```php
function set_option_plugin_before_upgrade_callback( $return, $plugin ) {

if ( is_wp_error( $return ) ) { //Bypass.
    return $return;
}

$plugin = isset( $plugin['plugin'] ) ? $plugin['plugin'] : '';
if ( empty( $plugin ) || plugin !== 'wp-rocket/wp-rocket.php' ) {
    return new WP_Error( 'bad_request', $this->strings['bad_request'] );
}

if ( is_plugin_active( $response ) ) {
   update_option('wp_rocket_updating', true);
}

return $return;
```
And set it to false with the filter `upgrader_post_install` with the following logic:
```php
function set_option_plugin_after_upgrade_callback($return, $plugin) {
if ( is_wp_error( $return ) ) { //Bypass.
    return $return;
}

$plugin = isset( $plugin['plugin'] ) ? $plugin['plugin'] : '';
if ( empty( $plugin ) || plugin !== 'wp-rocket/wp-rocket.php' ) {
    return new WP_Error( 'bad_request', $this->strings['bad_request'] );
}
   update_option('wp_rocket_updating', false);
}
```
Then we could use that option to safeguard the method [`create_or_update`](https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Database/Queries/Cache.php#L124-L179) 

Then we would have to update tests accordingly.

## Estimate the effort
Effort `S`

@Tabrisrp could you check if my grooming is right because I am not sure that function will run during or after the upgrade.

**Comment by remyperona** [comment]
This function runs after the upgrade
