### ISSUE TITLE
Improve webp detection on apple devices

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#5654]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Currently, WebP support detection is not working well for Safari browsers. Even for MacOS/Safari versions that do support WebP (Big Sur and later), the WebP cache is not being served.

The issue is due to Safari no longer sending the needed headers so WP Rocket can serve the WebP cache properly.

Related to this issue as well: https://github.com/wp-media/wp-rocket/issues/5524

**To Reproduce**
View any page in MacOS Big Sur or later where WebP images are supported with the WebP add-on enabled. Pages that have WebP versions of images available will still not have WebP cache served.

The user did some extensive testing on their end, and here were their specific results (seems on iOS it's not only happening for Safari, but also for other browsers like FF and Chrome since they are required to use the Safari rendering engine)

Windows, Chrome: html with webp links is provided (correct)
Windows, Edge: html with webp links is provided (correct)
Ubuntu, Firefox: html with webp links is provided (correct)
MacbookPro, Chrome: html with webp links is provided (correct)
MacbookPro, Firefox: html with webp links is provided (correct)
MacbookPro, Safari: html with JPG links is provided (WRONG)
iPhone 13 mini, Chrome: html with JPG links is provided (WRONG)
iPhone 13 mini, Firefox: html with JPG links is provided (WRONG)
iPhone 13 mini, Safari: html with JPG links is provided (WRONG) - same for iPhone 14 iOS 16.2, iPhone 12 iOS 14.2, etc.
iPad Mini 5, Chrome: html with JPG links is provided (WRONG)
iPad Mini 5, Firefox: html with JPG links is provided (WRONG)
iPad Mini 5, Safari: html with JPG links is provided (WRONG)

User agents for FF/Chrome/Safari/etc on iOS will be different, so these should be taken into account for the solution as well.

**Expected behavior**
According to Piotr in the Slack discussion, WP Rocket will need to regex user agents to detect specific apple browsers and serve our WebP cache based on that.

**Screenshots**
Safari 16 on Ventura
![image](https://user-images.githubusercontent.com/45705494/209974237-78c36e17-dec3-40ab-9c43-b8fbe8d23313.png)

Chrome on Windows
![image](https://user-images.githubusercontent.com/45705494/209974501-81be5381-8f60-4a59-8743-e8be8c0b9a2d.png)

**Additional context**
Slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1672325582266889
Ticket: https://secure.helpscout.net/conversation/2108559032/391269/
Test page where issue occurs: https://test.prodvomschaf.de/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mingendahl** [comment]
**Additional information**
In my tests, the same issue occurs for Safari mobile AND FF and Chrome mobile on Apple devices.
_Thus, it is not solely related to Safari._

Not serving webp even though it could be served is one issue.
The bigger issue is, though, that WP Rocket only pre-caches webp-versions of a page.

In combination with the existing flaw regarding webp-detection, this results in a huge amount of cache-misses, even if fully preloaded.

On our sites, this webp-detection/caching-issue applies to about 41% of all clients.
Thus, it not only does not serve web-images in these cases but basically renders the pre-loading-mechanism somewhat flawed, too.

This relates to #5524 , too.

**Comment by Mingendahl** [comment]
WP Rocket is not the only plugin having the issue: https://wordpress.org/support/topic/webp-support-detection-issue/

But there is a very simple solution, if you look into what user agent Safari (WebKit) browsers send:

- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version**/16.2 **Safari**/605.1.15
- Mozilla/5.0 (**iPad**; CPU OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version**/16.2 **Safari**/604.1
- Mozilla/5.0 (**iPhone**; CPU OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version**/16.2 **Safari**/604.1

I did some research and for what I discovered, this should do the trick for detecting _most_ of the browsers' capabilities correctly:

Pseudo code:

```
var browserSupportsWebP = 
	(accept header contains 'image/webp') ||
	(user agent contains 'Safari' && ('Version'>=16 || (('iPad, 'iPhone') && 'Version'>=14)))
```

Mobile Safari supports webP for V>=14.
Version 15 supports webp only on Big Sur or later, V16 on MacOS supports webp by 100%.

For more information about browsers supporting webp, check here: https://caniuse.com/webp

According to my tests, the above pseudo code would cover all browsers sending correct accept headers, all Safari on Apple mobile, Safari on desktop and FF Apple mobile.

The only exception would be (at least according to my tests), Chrome on Apple mobile, because it does neither send webP inside the accept header, nor Version info as part of the user agent.
But I think, that's an absolute corner case, as Apple has a market share of about 28% and 93% of these users use Safari, anyway.

With these two lines, you would be able to correctly detect 98% of Safari, FF, Chrome webP capabilities on desktop AND mobile.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
We already have a similar condition for Firefox, so I think a good idea would be to extract it to a separate method, and add the additional check to it.

We can also take the opportunity to move the WebP subscriber to the new architecture and clean up the class at the same time.

### Estimate the effort ✅
Effort [S]

**Comment by Mingendahl** [comment]
Hi @Tabrisrp,
I am curious about the impact of that change - would that also eliminate the issue that only webp pages get pre-loaded?
This is an issue, too, but maybe we need a different ticket for that

**Comment by remyperona** [comment]
That change would only ensure that WebP compatible browser which don't send the expected headers correctly get the WebP cache version.
