### ISSUE TITLE
CDN Incorrect path rewriting for relative paths

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#566]
CDN feature doesn’t recognize relative paths but still try to apply CNAME on an empty domain and it results in broken URLs like this one: **https:///wp-content/plugins/...**

**Comment by mikecann** [comment]
I have been looking into how to fix this because TBH its quite a fundamental flaw in the plugin as a very large proportion of websites would be using relative links. WooCommerce for example uses it in its default "storefront" theme.

I think the problem function is: https://github.com/wp-media/wp-rocket/blob/master/inc/functions/cdn.php#L34

I was just hoping it would be a matter of doing a check to see if the URL starts with "/" and isnt "//" then simply prepending the blog host url "https://aboveunder.com" then let it go through the usual CDN url transform process however for some reason some of the URLs dont  seem to work still, im wondering if hrefs in link tags are handled differently?

**Comment by losderpos** [comment]
Did you guys ever figure this out?
