### ISSUE TITLE
Clear cache when `discourage search engines from indexing this site` changes

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#5662]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.4`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the blogs visibility to search engines changes, we are not clearing page cache.

When `discourage search engines from indexing this site` is checked, WordPress will add:

`<meta name='robots' content='noindex, nofollow' />`

When unchecked, WordPress will remove that line.

It's important to clear cache as otherwise, the cache will either still be visible to search engines, or be hidden, depending on the status at the time. It doesn't reflect the setting change. 

WordPress has an action that fires after the setting is updated `update_blog_public`. We can use it to fire `rocket_clean_domain()`. 

**To Reproduce**
1. Change `discourage search engines from indexing this site`
2. See that `meta` tag managing `robots` won't change

**Expected behavior**
WP Rocket should reflect the right search engine visibility when it changes.

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2114816938/393071/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by mostafa-hisham** [comment]
## Reproduce the problem 
I didn't reproduce it I think it is clear

## Identify the root cause
we don't clear the cache after changing visibility to search engines 

## Scope a solution
Like Adame said we should use `update_blog_public` to fire `rocket_clean_domain()`.
I think it should be done here `inc/Engine/Cache/PurgeActionsSubscriber.php`

**FYI**
i tested it with `update_blog_public` action and it didn't work
but worked with `update_option_blog_public` action

## Estimate the effort
Effort `XS`

**Comment by engahmeds3ed** [comment]
> i tested it with update_blog_public action and it didn't work

Yes this action is related to multisite only.
