### ISSUE TITLE
Preload can get stuck when disabling Remove Unused CSS while there are pending jobs

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#5671]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.12.4`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

If Remove Unused CSS is disabled while there are still `pending` jobs for URLs, the valued of the `is_locked` column in the `wpr_rocket_cache` table will be set to `1`, thus preventing the preload of those URLs.

**To Reproduce**

1. On a website where the used CSS has been generated for several URLs, clear the used CSS using the admin bar menu item.
2. Disable Remove Unused CSS (some of the URLs in the `wpr_rucss_used_css` table should have a `pending` `status`).
3. Check the `wpr_rocket_cache` table.
4. The `is_locked` will be `1` for the URLs from step 2.

**Expected behavior**

When disabling Remove Unused CSS we should make sure that no URLs are "locked".

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The problem was easy to reproduce.

## Identify the root cause
The root cause is that we don't check for locked urls when disabling RUCSS.
## Scope a solution
A solution would be be to add a new action `rocket_preload_unlock_all_urls` inside the preload that change status from every rows to unlocked.
And in the RUCSS subscriber add a callback to `'update_option_' . WP_ROCKET_SLUG` that have the following logic:
```php
public function maybe_unlock_preload( $old_value, $value ) {
		if ( ! isset( $value['remove_unused_css'], $old_value['remove_unused_css'] ) ) {
			return;
		}

		if ( $value['remove_unused_css'] === $old_value['remove_unused_css'] ) {
			return;
		}

		if ( $value['remove_unused_css'] ) {
			return;
		}

		do_action('rocket_preload_unlock_all_urls');
	}
```
## Estimate the effort
Effort `XS`
