### ISSUE TITLE
GDPR: rocket_send_analytics_data is enabled by default, should be disabled

### ISSUE THREAD

**Issue by jmslbam** [wp-media/wp-rocket#5677]
**Describe the bug**
This should be of by default. Your not allowed to track data unless a person gives permission.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/145887/212292322-861fc97c-60d5-4a8a-9d2c-ed9e8a44add2.png">

**To Reproduce**
Install WP Rocket.

**Expected behavior**
It should be disabled.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Hello @jmslbam and thanks for creating the issue. We're not able to reproduce it though with regular website. What we can see is that it can happen with multisite due to the following issue:
https://github.com/wp-media/wp-rocket/issues/3889

Could you share a bit more information? Have you tried installing WP Rocket on a fresh, not multisite instance?

**Comment by jmslbam** [comment]
Yupp, sorry, can't seem to reproduce.

I indeed created a fresh install etc. 

Thank you for your time, I will close it!
