### ISSUE TITLE
Export settings before applying Safe Mode might not work

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#5684]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 3.12.5
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Export can be unreliable in some edgy scenarios (export file not downloaded, safe mode applied). We should do our best to guard against that kind of scenarios.

Exporting settings using Tools section works as expected.

**To Reproduce**
1. On the website where wp-json is not working correctly try to deactivate plugin
2. Try to use the Safe Mode + export settings options
3. Safe Mode is applied, export didn't start

**Expected behavior**
We should be reliable in that matter

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/212908154-ec00e44f-1a1c-4736-a04c-c4f05c113c08.png)

**Additional context**
It's happening on 2 of our test websites.

Also, when clicking on `Confirm`, the ✔️ disappears until the popup is closed. We should improve it too:
https://jumpshare.com/v/ZZCdCbiXW9Yx6bigllX2

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The problem is easy to reproduce by disabling the WordPress API.
## Identify the root cause
The root cause is that we are using the json api to export settings.
## Scope a solution
A solution would be to use an admin post action to export settings.

For that we will use the following action `rocket_export` instead of `wp-rocket/v1/options/export/'` endpoint by changing [on this line](https://github.com/wp-media/wp-rocket/blob/6b45039ddac481a58f5ce4a4f55d5d9815600b2c/inc/Engine/Admin/API/Subscriber.php#L34) to :
```php
				'rest_url_option_export' => wp_nonce_url( admin_url( 'admin-post.php?action=rocket_export' ), 'rocket_export' ),
```
## Estimate the effort
Effort `XS`
