### ISSUE TITLE
WP Rocket’s config files whose filenames don’t match the site’s domain are not removed upon plugin deactivation

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#5687]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (tested on 3.12.4 and 3.12.5)
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
The rules we add to the .htaccess file are not cleared when there is a PHP file left in the `/wp-rocket-config/` folder that has a different filename (i.e., it does not match the site’s domain).

This causes the cached files to still be served even after deactivating WP Rocket on the site (in those cases the rewrite rules are still present) causing the server to deliver the cached files.

**To Reproduce**
1. Visit a page while having WP Rocket enabled to see the cached file.
2. Duplicate the config file from the `/wp-rocket-config/ `folder and give it a filename different from the site’s domain.
3. Deactivate WP Rocket.
4. Check the .htaccess and see that our rules are astill there.
5. Visit the previoiusly visited page and see that the cached file is still served.

**Expected behavior**
The rules we place to the .htaccess file should be removed upon deactivating the plugin. 

We should make sure we remove all config files present in the /wp- rocket-config/ folder upon deactivating the plugin, no matter which filenames they have. Or find a way to remove the .htaccess rules if additional config files are kept, to avoid the issue.

**Screenshots**
Screencast: https://share.getcloudapp.com/E0uRXKbN

**Additional context**
Related HS ticket: https://secure.helpscout.net/conversation/2114970779/393122/
Props to @alfonso100

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [ ] Estimate the effort

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
Could be reproduced easily.

### Identify the root cause ✅
We are not deleting multiple config files for non multisite setup.

### Scope a solution ✅
We should delete multiple config files when setup is not multisite.
In this function: https://github.com/wp-media/wp-rocket/blob/136d94b9ea6eb33ba33c3e2143a623b4b37d86cc/inc/functions/files.php#L230 we will check if it's not multisite and delete multiple config files.
```
if ( rocket_get_constant( 'WP_ALLOW_MULTISITE', false ) ) {
      return;
}
```
and delete multiple files
```
try {
$config_dir = new FilesystemIterator( (string) rocket_get_constant( 'WP_ROCKET_CONFIG_PATH' ) );
} catch ( Exception $e ) {
return;
}

foreach ( $config_dir as $file ) {
if ( $file->isFile() && 'php' === $file->getExtension() ) {
	rocket_direct_filesystem()->delete( $file->getPathname() );
}
}
```
For this solution, we will be deleting the multiple config files which will allow wpr flush the .htaccess rules.

Another solution would also be to check for multisite setup in this function:
https://github.com/wp-media/wp-rocket/blob/136d94b9ea6eb33ba33c3e2143a623b4b37d86cc/inc/functions/files.php#L1418
Then return early if it is not a multisite setup.
```
if ( ! rocket_get_constant( 'WP_ALLOW_MULTISITE', false ) ) {
      return [];
}
```
For this solution we will keep the multiple config files for non multisite setup, only the .htaccess rules will be flushed. 

@piotrbak Which is better?
### Estimate the effort ✅
[XS]

**Comment by piotrbak** [comment]
@jeawhanlee I believe we should clean the config directory properly upon the deactivation.
