### ISSUE TITLE
Arabic slugs cannot be excluded from cache from Never Cache URL(s)

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5741]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
Arabic slugs cannot be excluded from cache from Never Cache URL(s). Replacing it by the encoded URL version exclude the page from caching.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/11939512/216924402-4043bcbf-f2c8-475d-80ec-c6c1ee59bdcb.png">

**To Reproduce**
1. Go to **Advanced Rules** > **Never Cache URL(s)**
2. Add an Arabic slug
3. Check the page
4. It's still cached
5. Add the same URL but encoded.
6. It's excluded from being cached as expected

**Expected behavior**
Arabic slugs should be excluded from cache

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2143721470/398840/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
We did not have any feedback from customers about this issue.

**Comment by addedlovely** [comment]
This is my issue, a customer.

**Comment by piotrbak** [comment]
Hello @addedlovely 

Yes, since 6th of February we received only one feedback from our customers about this problem, which is yours. We're currently clearing our backlog a little bit by closing issues that will not be solved in the midterm. However, please keep in mind that it doesn't mean that the issue will never get resolved. We'll reopen it if we receive more feedback or we'll be releasing minor version oriented on the similar topic. Thanks for understanding.
