### ISSUE TITLE
CPCSS of mobile isnot regenerated when switching theme

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5751]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.5.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When switching theme while a separate mobile cache is enabled, the CPCSS of the mobile is not regenerated

**To Reproduce**
1. Enable separate mobile cache and CPCSS
2. Wait until cache files are there in critical-css/1
3. Switch the theme
4. Only the desktop version is regenerated

**Expected behavior**
Both mobile and desktop versions shall be regenerated

**Additional context**
Clicking regenerate Critical CSS from the admin bar will regenerate both desktop and mobile

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by CrochetFeve0251** [comment]
@Mai-Saad  I tried to reproduce the issue with preload activated and I got both desktop and mobile generated after changing the theme.
Could you provide me more context for that error?

**Comment by engahmeds3ed** [comment]
# Reproduce the problem
Yes I can reproduce the issue on my test site

# Identify the root cause
Here
https://github.com/wp-media/wp-rocket/blob/2c33d12076f31c9d6b78696cb22e23e7b14358f0/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L92

we add a callback with `switch_theme` hook and inside this callback we call this method:
https://github.com/wp-media/wp-rocket/blob/2c33d12076f31c9d6b78696cb22e23e7b14358f0/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L708

without any argument so it uses the default value as in here:

https://github.com/wp-media/wp-rocket/blob/c3c54101be5a2a18232530b36ac586a458458ae4/inc/Engine/CriticalPath/CriticalCSS.php#L93

so it removes the default CPCSS files only

# Scope a solution
Here:
https://github.com/wp-media/wp-rocket/blob/2c33d12076f31c9d6b78696cb22e23e7b14358f0/inc/Engine/CriticalPath/CriticalCSSSubscriber.php#L703-L709

we need to check the option os separate mobile cache if enabled we need to send `all` argument to the method `$this->critical_css->process_handler();`

# Estimate the effort
[XS]

**Comment by Mai-Saad** [comment]
Blocked by https://github.com/wp-media/wp-rocket/issues/5891
![Screenshot from 2023-05-03 15-33-21](https://user-images.githubusercontent.com/76941962/235917613-54b5d937-de8e-41eb-8c1b-10da09d915e8.png)

**Comment by Mai-Saad** [comment]
Blocked by this error (already on trunk)
![Screenshot from 2023-05-10 12-13-09](https://github.com/wp-media/wp-rocket/assets/76941962/3bb79baf-8a58-4d80-a181-df3646e18fca)
