### ISSUE TITLE
Cache isn't cleared for URLs whose permalink contains uppercase letters in non-latin alphabets

### ISSUE THREAD

**Issue by luanluta** [wp-media/wp-rocket#5815]
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x]  Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

URLs that should have their cache cleared after updating a post aren't cleared if they contain an uppercase character in a non-latin alphabet.

**To Reproduce**
1. Install a plugin that allows you to have custom permalinks [(Permalink Manager Lite)](https://wordpress.org/plugins/permalink-manager/)
2. Create and publish a post and change its URL to contain an uppercase non-latin character (Γυναικείο, Производ)
Image here: https://jmp.sh/J06a6ta2
3. Load the post once to create a cache.
4. Change the post and update it.
5. Post page doesn't reflect the update as the cache files aren't cleared.

**Expected behavior**
When a user clicks the update button, the post's cache file should be deleted so it reflects the changes.

**Additional context**

The issue is happening when we store the URL on the server, we do it in lowercase [here](https://github.com/wp-media/wp-rocket/blob/60b76bc8bc9a366bf5b9644894df8203bba103fd/inc/classes/Buffer/class-cache.php#L392), but then we search for the URL with the uppercase characters [here](https://github.com/wp-media/wp-rocket/blob/0015d58087695811bf42138eba9dd914741a9519/inc/functions/files.php#L535) because we assume that the URL will be all lowercase.

Adding `$entry = strtolower( $entry );` after `$entry = strtolower( $entry );` [here](https://github.com/wp-media/wp-rocket/blob/0015d58087695811bf42138eba9dd914741a9519/inc/functions/files.php#L535) fixes the issue.

Related ticket: https://secure.helpscout.net/conversation/2177113016/406819?folderId=7469349
Initial Slack discussion: https://wp-media.slack.com/archives/C43T1AYMQ/p1678448004086059
Possible related issue #5561 

Currently working on a workaround for the user.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by luanluta** [comment]
Created a helper plugin that fixes the issue for now.

[wp_rocket_lowercase_permalinks.zip](https://github.com/wp-media/wp-rocket/files/10970656/wp_rocket_lowercase_permalinks.zip)

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem only when permalink contained all non-latin characters, when mixed, I wasn't able to reproduce.

### Identify the root cause ✅
Like @luanluta stated, we are saving cache path in lower case but not retrieving in lower case before cleaning files.

### Scope a solution ✅
Like @luanluta suggested again, we can simply just transform characters to lower case just before we delete cache.
Adding `$entry = strtolower( $entry )` after this line https://github.com/wp-media/wp-rocket/blob/0015d58087695811bf42138eba9dd914741a9519/inc/functions/files.php#L535

### Estimate the effort ✅
Effort [XS]
