### ISSUE TITLE
UI - Arrows to toggle Delay JavaScript Execution exclusions tabs are not visible in Safari

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#5842]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version: ✅ 3.13
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
In Safari, Delay JavaScript Execution exclusions tabs are missing the down arrows buttons. Since tabs are not fully clickable, it's like it cannot be toggled.

**To Reproduce**
1. Go to Delay JavaScript Execution option in Safari
2. Click on Plugins tab
4. See UI issue

**Expected behavior**
The whole tabs should be clickable to be toggled.

**Screenshots**
[Screenshot](https://wp-rocket.romainvincent.com/jV2YONnJ)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
QA also reported padding problem on Safari 14 BigSur
![image (28)](https://user-images.githubusercontent.com/26767037/228836614-39000a08-60ce-44f5-b98e-1651d030e111.png)

**Comment by mostafa-hisham** [comment]
### Reproduce the problem ✅
The problem was reproduced easily

### Identify the root cause ✅
Safari :grin: 

### Scope a solution ✅
To fix arrows
we need to add `height="100%" width="100%"` to svg tag

and for safari 14 problem
we need to add to `max-height:32px` `.wpr-list-header`

### Estimate the effort ✅
[XS]
