### ISSUE TITLE
isdefault for plugins/themes shall work as same as for scripts

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5871]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.13
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Changes for `isdefault` are reflected for switched theme / activated plugin. 

**To Reproduce**
1. Fresh install to WPR (ninja plugin  active,  astra theme used)
2. Check the Delay JS exclusion list
3. Exclusion of ninja /astra isnot checked in UI
4. set ninja/astra to isdefault from backend
5. update dynamic list from tools page
6. reactivate ninja plugin or switch to 2021 then to astra
7. check Delay JS exclusion list

**Expected behavior**
astra theme exclusion and ninja form plugin exclusion arenot automatically checked in UI (`isdefault `only reflected with fresh installs like with  scripts as per discussion with @piotrbak )

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I did not reproduce the issue but I could see the reason in the codebase. Thanks to @Mai-Saad for the explanation.

### Identify the root cause ✅
We are updating `delay_js_exclusions_selected` on theme switch or plugin activation or deactivation. This will cause a UI change anytime dynamic list is updated and a theme is switched or plugin is activated.
https://github.com/wp-media/wp-rocket/blob/de8a826764482f7518ffa9596141362ec1a96c0f/inc/Engine/Optimization/DelayJS/Admin/Subscriber.php#L54-L56

### Scope a solution ✅
Removing the hooks and the corresponding callbacks should fix this.

### Estimate the effort ✅
[XS]

**Comment by piotrbak** [comment]
We'll leave this behaviour for now, it's the correct behaviour. If we'll have negative feedback about it, we might get back and rethink our conception.
