### ISSUE TITLE
Preload: Don't try to preload private pages

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5885]
**Is your feature request related to a problem? Please describe.**
WP Rocket will try to preload pages that have been set to Private in WordPress. This generates unnecessary requests and results in 404 errors. If there are a lot of them, it would also slow down the whole process. 

**Describe the solution you'd like**
We could check if a page is private, and if so, automatically exclude it from Preload. 

**Describe alternatives you've considered**
Customers could manually exclude these URLs, but that's not ideal from a UX point of view.

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/2219018645/415412?folderId=377611

**Comment by piotrbak** [comment]
**To reproduce:**
1. Enable Preload 
2. Go to the `Add new page` section (or update the private page)
3. Switch the `Visibility` to `Private`
4. Observe access.log

**Additional context**
The preload happens only once, after it it's not added to the cache table

**Acceptance Criteria:**
1. The URL should not be preloaded after being added as private nor when the private page is updated
2. Regular, public URLs should still be preloaded and added to cache table after being published or updated
3. The same should apply to all post types
4. To clarify the 1st point, when editing the public post and setting it as private, the request should not happen either

**Comment by webtrainingwheels** [comment]
> The preload happens only once, after it it's not added to the cache table

Just to add, it happens once per each time that preloading is triggered. i.e so we'll also try again when the page is updated.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem.

### Identify the root cause ✅
We are not checking post status before adding urls to be preloaded in the cache table.

### Scope a solution ✅
We can create a new method in https://github.com/wp-media/wp-rocket/blob/fbfdfed79ca924284394fa53f84bec7b61413587/inc/Engine/Preload/Controller/ClearCache.php
```
is_private( $url ) {
    $post_id = url_to_postid( $url );
    return 'private' == get_post_status( $post_id );
}
```
Then use new method in https://github.com/wp-media/wp-rocket/blob/fbfdfed79ca924284394fa53f84bec7b61413587/inc/Engine/Preload/Controller/ClearCache.php#L31
```
if ( is_private( $url ) ) {
    continue;
}
```

Update tests too.

### Estimate the effort ✅
[S]
