### ISSUE TITLE
The activation notice shows up after every update

### ISSUE THREAD

**Issue by simkoG** [wp-media/wp-rocket#5889]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔
- Used the search feature to ensure that the bug hasn’t been reported before ✔

**Describe the bug**
There is a message after plugin activation, that says "WP Rocket is now activated...". This message should not be displayed after every plugin update if the user is dismissed it earlier.

**To Reproduce**
1. Install an older version of WR Rocket.
2. Open the `/wp-admin/options-general.php?page=wprocket#dashboard` page.
3. Click on the Dismiss `×` icon.
4. Update the plugin. 
5. Open the `/wp-admin/options-general.php?page=wprocket#dashboard` page again.
6. The Welcome notice is visible again.

**Expected behavior**
If the message is dismissed, never show it again. We know that the plugin is working. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10430702/234234325-b57aae98-dcf0-41a8-b000-a994d5dbb286.png)

**Additional context**
–

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. Welcome banner should be displayed only after the install
2. **(edit)** It should not be displayed after dismissing it and deactivation/activation
3. It should not be installed after the updates

**Comment by engahmeds3ed** [comment]
## Reproduce the problem
Yes, it's easily reproducible by clicking the X in the banner then change the plugin version constant manually to trigger the upgrade routine.

## Identify the root cause
With fresh install or upgrade we clear all rocket boxes except for `rocket_warning_plugin_modification` so even if the customer clicked the X to ignore this welcome message, with upgrade it will show again.

Exactly here: https://github.com/wp-media/wp-rocket/blob/136d94b9ea6eb33ba33c3e2143a623b4b37d86cc/inc/admin/upgrader.php#L28

## Scope a solution

Just add this box to the boxes to preserve.

## Estimate the effort
[XS]
