### ISSUE TITLE
Sanitize custom permalink settings

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#5893]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Since version 3.13 we are using the permalink structure in `$rocket_permalink_structure`
If the customer is using a custom structure with a weird input, it can cause a fatal error, because we don't sanitize this. 
Example of an input that causes problems: `/'/%year%/%monthnum%/%day%/%postname%/' `
https://i.imgur.com/2rZIyea.png

**To Reproduce**
1. Go to _Settings → Permalinks_. Choose custom structure and enter: `/'/%year%/%monthnum%/%day%/%postname%/'`
2. Activate WP Rocket
3. Check the wp-rocket-config file and you will see: 
`$rocket_permalink_structure = '/'/%year%/%monthnum%/%day%/%postname%/'';`
4. Go to the frontend of the site and you will have a critical error. 
5. In the error log you will see: `Parse error: syntax error, unexpected token "%" in /wp-content/wp-rocket-config/yourdomain.php on line 82`

**Expected behavior**
If WordPress accepts a permalink structure, we should be able to as well. We should sanitize this so it doesn't cause an error, even if it's an edge case. 

**Screenshots**

**Additional context**
Ticket: https://secure.helpscout.net/conversation/2207611833/412789?folderId=377611
Slack:https://wp-media.slack.com/archives/C43T1AYMQ/p1682465607573189

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

**Comment by piotrbak** [comment]
@wp-media/php What do you think about that sanitization? Do you see this one risky?

**Comment by remyperona** [comment]
We can escape the `'` character before adding the structure to the file, this should avoid the error. We can test with that solution if the behaviour is correctly preserved.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem.

### Identify the root cause ✅
Unescaped quotes in the config file.

### Scope a solution ✅
Like @Tabrisrp proposed, we can escape these kind of quotes before adding the permalink structure to the config file
on this line https://github.com/wp-media/wp-rocket/blob/10e82c0af9670f20b48150a89d858108ee2834a1/inc/functions/files.php#L158:
we can escape like this `wp_slash( get_option( 'permalink_structure' ) )`

Though for a structure like this we will not be redirecting with a trailing slash.

### Estimate the effort ✅
[XS]
