### ISSUE TITLE
Fatal Error UsedCSS::revert_to_pending()

### ISSUE THREAD

**Issue by ablears** [wp-media/wp-rocket#5927]
On version 3.13.2 I get the following fatal error:

`PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::revert_to_pending(): Argument #1 ($id) must be of type int, string given, called in /var/www/zzz/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 803 and defined in /var/www/zzz/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:444"
Stack trace:"
#0 /var/www/zzz/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(803): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->revert_to_pending()"
#1 /var/www/zzz/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php(121): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->clear_failed_urls()"
#2 /var/www/zzz/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\RUCSS\Cron\Subscriber->cron_remove_failed_jobs()"
#3 /var/www/zzz..."`

PHP Version 8.1.14

Maybe you need to explicitly set id to an int, eg `$this->used_css_query->revert_to_pending( intval($row->id) );`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by DahmaniAdame** [comment]
@ablears thanks for reporting that. 

> Maybe you need to explicitly set id to an int, eg $this->used_css_query->revert_to_pending( intval($row->id) );

That would be the easy fix, indeed. But we need to find the root cause for it. 

Would it be possible to open a support ticket related to that if it's not too much trouble?

**Comment by piotrbak** [comment]
@engahmeds3ed Were you able to reproduce this issue on the environment we received?

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed What do you think about using magic method to access properties instead of accessing the property directly.
That would allow us to cast value with the right type whenever the user (constructor is casted so the error can't come from there) set it and without breaking all the existing code by adding getters and setters on the object.

https://www.php.net/manual/en/language.oop5.overloading.php#object.get
https://www.php.net/manual/en/language.oop5.overloading.php#object.set

**Comment by engahmeds3ed** [comment]
> @engahmeds3ed Were you able to reproduce this issue on the environment we received?

Yes I was able to see it in action and talked with BerlinDB author.

@CrochetFeve0251 you mean doing that in berlinDB core or in the our query class?

The issue itself I believe will be easily handled by casting the id before sending it to the method `UsedCSS::revert_to_pending`

also for support, I used the following snippet to fix it temporary

```
add_filter( 'the_used_css', function( $args ) {
    if ( empty( $args ) ) {
        return [];
    }

    foreach ($args as $row_key => $row) {
        if ( empty( $row->id ) || is_int( $row->id ) ) {
            continue;
        }

        $args[$row_key]->id = (int) $row->id;
    }

    return $args;
} );
```

**Comment by maruhe** [comment]
hi, since some weeks I get a may similar error every 2-3 days from wp-cron
	
Fatal error: Uncaught TypeError: WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS::revert_to_pending(): Argument #1 ($id) must be of type int, string given, called in /***htroot***/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php on line 827 and defined in /***htroot***/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php:444
Stack trace:
#0 /***htroot***/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php(827): WP_Rocket\Engine\Optimization\RUCSS\Database\Queries\UsedCSS->revert_to_pending('350')
#1 /***htroot***/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php(121): WP_Rocket\Engine\Optimization\RUCSS\Controller\UsedCSS->clear_failed_urls()
#2 /***htroot***/wp-includes/class-wp-hook.php(308): WP_Rocket\Engine\Optimization\RUCSS\Cron\Subscriber->cron_remove_failed_jobs()
#3 /***htroot***/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#4 /***htroot***/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#5 /***htroot***/wp-cron.php(188): do_action_ref_array('rocket_remove_r...', Array)
#6 {main}
thrown in /***htroot***/wp-content/plugins/wp-rocket/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php on line 444 

I don't remember which version it was exactly but I came up with a wprocket-update and never happened before

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
No

### Identify the root cause ✅
After some discussion with @engahmeds3ed this could be caused by object caching from hosting or plugins with related issues [here](https://github.com/pantheon-systems/wp-redis/issues/181)

### Scope a solution ✅
We can guard against this kind of error and also type cast in https://github.com/wp-media/wp-rocket/blob/76031e933feeaf45162c904bab5f25043c985692/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L825 
```
if ( empty( $row->id ) || ! is_int( $row->id ) ) {
    continue;
}

$id = (int) $row->id;
$this->used_css_query->revert_to_pending( $id );
```

### Estimate the effort ✅
[XS]

**Comment by DahmaniAdame** [comment]
The issue occurs on a website where Object Cache is not being used. Which excludes it as a trigger. 
Won't change the scope of the fix, though.
