### ISSUE TITLE
Deprecated Class Property search_url used with Polylang

### ISSUE THREAD

**Issue by stephaniecot** [wp-media/wp-rocket#5967]
**Describe the bug**
Since the most recent update of Polylang, the use of WP Rocket to clear the cache for all language throws a deprecated error from the get_rocket_i18n_uri() function. It uses the search_url property that is now deprecated. get_search_url() should be used instead.

**To Reproduce**
1. Clear the cache for all languages 
2. The error should appear in de debug.log

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced the issue on my local install

### Identify the root cause ✅ 
Accessing the class property directly is deprecated since version 3.4, because the property is now private. getter method has been added instead.

### Scope a solution ✅ 
We can resolve the issue  by using the following:
```
$languages = $pll->model->get_languages_list();

			foreach ( $languages as $language ) {
				$urls[] = $language->get_home_url();
			}
```

but this is valid only starting from 3.4, because the getter method didn't exist before. So we will also need to add a conditional to use the previous code for the earlier versions, and the new one for 3.4 and higher.


### Estimate the effort ✅
Effort `XS`
