### ISSUE TITLE
Product sorting in WooCommerce backend does not work when WP Rocket is active

### ISSUE THREAD

**Issue by camilamadronero** [wp-media/wp-rocket#5984]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - Y
- Used the search feature to ensure that the bug hasn’t been reported before - Y

**Describe the bug**
It's not possible to **sort** products within WooCommerce products page. Instead, you can see `524 error` in the console.

**To Reproduce**
1. In a site with WooCommerce, WP Rocket and hosted on Cloudways (not sure what other requirements may be)
2. Go to WooCommerce product page
3. Click on a product's checkbox to try to sort it 
4. The checkbox will show a loading icon that never goes away, and sorting won't be possible

**Expected behavior**
Product sorting should work as expected

**Screenshots**
Product sorting error with the loading icon stuck: https://capture.dropbox.com/drH0ISsNLOK4zhCb (@markonikolic985 screenshot)

**Additional context**
From @engahmeds3ed:

> the problem starts in WooCommerce exactly [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#L2073)
> they get all posts (in this site the number of those posts are +500) with their menu order and loop on them and after updating their menu_order , they clean post cache [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#LL2090C5-L2090C29) and then set the main product menu_order and also clean post cache [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#L2111)
> so this is taking lots of time to update and clear post cache.
> My temporary fix is to disable cleaning post cache inside this method only.
> 

```
add_action( 'wp_ajax_woocommerce_product_ordering', function(){
	global $_wp_suspend_cache_invalidation;
	$_wp_suspend_cache_invalidation = true;
}, 9 );

add_action( 'wp_ajax_woocommerce_product_ordering', function(){
	global $_wp_suspend_cache_invalidation;
	$_wp_suspend_cache_invalidation = false;
}, 11 );
```
> you can know more about the feature here:
> https://github.com/woocommerce/woocommerce/issues/31389

Also:

> both sites are on cloudways 

Slack Dev-team escalation thread: https://wp-media.slack.com/archives/C056ZJMHG0P/p1685433858614039
Tickets: https://secure.helpscout.net/conversation/2237699192/419020?folderId=424682 and https://secure.helpscout.net/conversation/2254739596/421844/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. WP Rocket's cache should not be cleared when sorting products in the backend
2. The functionality added by WooCommerce in the https://github.com/woocommerce/woocommerce/issues/31389 should be preserved.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
Did not reproduce the issue.

### Identify the root cause ✅
Like @engahmeds3ed WC clears posts cache during the product sorting process by calling the function - `clean_post_cache` which has the `clean_post_cache` action in it. Then we are hooking to this action to clear post cache when required [here](https://github.com/wp-media/wp-rocket/blob/4819ee5065c08f16c2ca48e952e81b88adb3bb5c/inc/common/purge.php#L279) so whenever WC clears post and `clean_post_cache` is fired, `rocket_clean_post` will run.

### Scope a solution ✅
We can add a new filter in https://github.com/wp-media/wp-rocket/blob/4819ee5065c08f16c2ca48e952e81b88adb3bb5c/inc/common/purge.php#L174 and return early
```
if ( ! apply_filters( 'rocket_allow_clean_post', true ) ) {
  return false;
}
```
Then we will use `wp_ajax_woocommerce_product_ordering` hook in `ThirdParty\Plugins\Ecommerce::WooCommerceSubscriber` with a call back function that retuns false for the new filter - `rocket_allow_clean_post`.

```
public function stop_post_cache_clearing() {
  add_filter( 'rocket_allow_clean_post', [ $this, 'return_true' ] );
}
```

Estimate the effort ✅
[XS]
