### ISSUE TITLE
Error displayed when enable CF optimal settings + add key data at the same time

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#5988]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.14
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Error notice is displayed when enabling optimal settings at the time we add the CF addon data

**To Reproduce**
1. Fresh install/ activation of 3.14
2. Enable the CF addon
3. Click Modify options
4. Add valid key, id, and email and enable optimal settings then save => error displayed

**Expected behavior**
No error is displayed as the data is valid

**Screenshots**
![Screenshot from 2023-06-19 11-17-17](https://github.com/wp-media/wp-rocket/assets/76941962/56478df0-875b-47ce-8364-25acd251e56c)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alfonso100** [comment]
A possible variant of this issue here: 
https://secure.helpscout.net/conversation/2591270980/490366?folderId=2952229

In this case, when you try activating the CF Addon with all the toggles disabled, and adding the correct CF credentials, you get only one error: `Missing Cloudfare Zone ID`

Logging the values, the **$zone_id** is empty at [is_auth_valid()](https://github.com/wp-media/wp-rocket/blob/2b088a335a85cb013d8186d2fc7e36f28d152c29/inc/Addon/Cloudflare/Cloudflare.php#L70) and also the values at [save_cloudflare_options()](https://github.com/wp-media/wp-rocket/blob/c7a7149548afa175a43428adb1e33da790108d02/inc/Addon/Cloudflare/Subscriber.php#L514).

Enabling **Optimal Settings** before saving, allowed the addon activation

Related Slack Thread
https://wp-media.slack.com/archives/C43T1AYMQ/p1715197524274279

**Comment by piotrbak** [comment]
We did not have enough feedback from customers related to this issue. We might reopen this in the future.
