### ISSUE TITLE
Get and apply the same Used CSS for similar pages/posts

### ISSUE THREAD

**Issue by WordPresseur** [wp-media/wp-rocket#6011]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When a site has pagination, archive pages, and single pages from the same post type in some cases, and they have the same style, it would be worth to have a way to define a sample page to get the style from and apply it to all similar pages.

This would reduce the load on servers and low request to SaaS.

**Additional context**
HS tickets:
- https://secure.helpscout.net/conversation/2253719564/421696/
- https://secure.helpscout.net/conversation/2273098471/424855?folderId=1213662

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
@wp-media/php Would be good to do some research here. As a beginning, we could start with adding the same Used CSS to the child pagination pages, without sending more requests to the SaaS. The request would be sent only for the 1st page.

Not adding AC yet, since it needs some R&D

**Comment by ivptr** [comment]
You could also send request once per category post. E.g. it is enough to scan https://website/category/subcategory/article1 and apply the same Used CSS for all posts inside https://website/category/subcategory.

So for 10 different categories you could scan 10 posts only, instead of hundreds/thousands of posts.

**Comment by piotrbak** [comment]
@ivptr That could be an improvement for the future, for now, it'd introduce too many possible layout issues to be enabled by default.

**Comment by piotrbak** [comment]
We'll need more R&D here, basic AC in order to begin this enhancement:
1. When Used CSS is generated for the first taxonomy page related to specific term: `example.com/taxonomy_name/term_name/`, pagination pages related to this term (`example.com/taxonomy_name/term_name/page/[2-*]`) will use the same Used CSS without need of sending the request to Used CSS
2. We'll introduce filter in order to disable this enhancement
3. This enhancement will also work when custom pagination base will be used

What ifs to brainstorm:
1. What if pagination Used CSS is created before the main page's one? (if we decide that main page should use the Used CSS of paginated ones, it'd be good to display the URL of the page that was processed by saas to make the troubleshooting easier)
2. What if `Clear Used CSS of this URL` is used against main page/pagination page?

**Comment by piotrbak** [comment]
@DahmaniAdame Checking with you on this one, pagination pages look like easy win here, do you have any input?

**Comment by ivptr** [comment]
> 1. What if pagination Used CSS is created before the main page's one? (if we decide that main page should use the Used CSS of paginated ones, it'd be good to display the URL of the page that was processed by saas to make the troubleshooting easier)
> 2. What if `Clear Used CSS of this URL` is used against main page/pagination page?

We should store single Used CSS for main/paginated page, so this won't matter.

**Comment by DahmaniAdame** [comment]
@piotrbak, it's a good candidate to have the same Used CSS.

**Comment by piotrbak** [comment]
@DahmaniAdame What do you think about `What Ifs`?

**Comment by DahmaniAdame** [comment]
> What if pagination Used CSS is created before the main page's one?

The main page will usually have fewer elements than child pages. 

Example, the `previous` arrow won't show on the main page.

![image](https://github.com/wp-media/wp-rocket/assets/1289174/621ecee6-bc50-4914-baf3-708a2b26c09e)

There is also a risk that the last page won't have the `next` arrow as well. 

I would say we base it on page `1` to be safe. It will be the main CSS applied to all other pages. 

> What if Clear Used CSS of this URL is used against main page/pagination page?

That would be a signal the Used CSS is no longer accurate. The clearing should apply to all paginated pages.

What do you think?

**Comment by piotrbak** [comment]
This is not something that can be implemented in the nearest future.
