### ISSUE TITLE
The mobile version of the homepage isn't preloaded in priority when separate cache for mobile devices is enabled

### ISSUE THREAD

**Issue by vmanthos** [wp-media/wp-rocket#6040]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version :heavy_check_mark: `3.14.1`
- Used the search feature to ensure that the bug hasn’t been reported before :heavy_check_mark: 

**Describe the bug**

On certain occasions, e.g. when activating WP Rocket, or when clearing the used CSS, we are preloading the homepage in priority:
https://github.com/wp-media/wp-rocket/blob/4c697c3ff0487337a1ede10946d4b2a97b41395d/inc/Engine/Activation/Activation.php#L94-L102

If the "Separate cached files for mobile devices" is enabled we aren't preloading that version. Eventually, the mobile-specific file will be preloaded but that can take a while.

**To Reproduce**

1. Enable "Separate cached files for mobile devices" and Optimize CSS Delivery.
2. Clear the used CSS.
3. Look into the `/cache/wp-rocket/` folder.
4. The desktop version of the homepage is created immediately while for the mobile version, it takes a while.

**Expected behavior**

Preload the mobile-specific cached file of the homepage whenever we do that for the desktop version.

**Screenshots**

N/A

**Additional context**

The `user-agent` we use is `WP Rocket/Homepage Preload`. We need to add a request using a mobile `user-agent` wherever that one is used.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by piotrbak** [comment]
**Acceptance Criteria:**

**1. When separate cache for mobiles is enabled when activating the plugin:**
- We should send two requests, to desktop and mobile with defined pause between them: https://github.com/wp-media/wp-rocket/blob/7ff6ad04a6ad1b9c86bc032165d0a131eda9582a/inc/Engine/Preload/Controller/PreloadUrl.php#L149
- The user agent for both requests will be the same as in the preload: https://github.com/wp-media/wp-rocket/blob/7ff6ad04a6ad1b9c86bc032165d0a131eda9582a/inc/Engine/Preload/Controller/PreloadUrl.php#L160

**2. When separate cache for mobiles is enabled when clearing the Used CSS:**
- We should send two requests, to desktop and mobile with defined pause between them: https://github.com/wp-media/wp-rocket/blob/7ff6ad04a6ad1b9c86bc032165d0a131eda9582a/inc/Engine/Preload/Controller/PreloadUrl.php#L149
- The requests should be sent after clearing the cache, so the just preloaded cache is present
- The user agent for both requests will be the same as in the preload: https://github.com/wp-media/wp-rocket/blob/7ff6ad04a6ad1b9c86bc032165d0a131eda9582a/inc/Engine/Preload/Controller/PreloadUrl.php#L160

**3. When separate cache for mobiles is disabled when activating the plugin:**
- We should send only desktop request

**4. When separate cache for mobiles is disabled when clearing the Used CSS:**
- We should send only desktop request after clearing the cache

**Comment by remyperona** [comment]
@vmanthos When clearing the used CSS, did you do it from the admin side or from the front side via the admin bar?

The homepage preload is hooked on the used CSS clear, but only on the admin side.

**Comment by vmanthos** [comment]
@Tabrisrp I cleared it using the admin bar menu item while in WP Rocket's dashboard.
I believe the same would happen if the theme is switched or the permalinks are changed.

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Reproduced

### Identify the root cause ✅ 
There is 2 different parts in this issue, the activation one and the RUCSS clean one.

For the activation, we do a request to the homepage when activating, but we do not do the request for mobile.

For the RUCSS clean one, I noticed that we do have a method hooked on the related action, but right after in the `truncate_used_css_handler()` method, there is a call to `rocket_clean_domain()`, so the preload happens and is deleted right away.

There is only a cache file for the desktop version because there is a manual call to the homepage in the method after.

### Scope a solution ✅ 
in `WP_Rocket\Engine\Activation\Activation.php`
- remove the call to the homepage
- add a new action `rocket_after_activation`

in `WP_Rocket\Engine\Preload\Activation.php`
- Add the PreloadUrl controller as a dependency to the class
- In the activate method, add a new add_action on `rocket_after_activation`, to preload the homepage
- add a method `preload_homepage()`, which will call `$this->preload_url->preload_url( home_url() );`

in `WP_Rocket\Engine\Optimization\RUCSS\Admin\Subscriber`
- Remove no longer necessary preload calls to the homepage in `truncate_used_css_handler()`, and `truncate_used_css()`
- in `truncate_used_css_handler()`, switch the calls to `$this->delete_used_css_rows();` and `rocket_clean_domain();` to make sure the clean happens before the preload.

### Estimate the effort ✅
Effort [S]

**Comment by MathieuLamiot** [comment]
@vmanthos, @Mai-Saad, @piotrbak: following Tabrisrp's investigation, he pointed out 2 issues. Would it be interesting to rework the acceptance criteria here? I might not understand everything, but it seems the AC cover the activation part (checking we send the right requests on activation), but not the RUCSS side-effect.
A few e2e scenarios might be needed to cover Tabrisrp's proposal?

**Comment by piotrbak** [comment]
@MathieuLamiot @vmanthos Updated the AC
