### ISSUE TITLE
Improve the cleaning process for the failed preload actions

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6059]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
It looks like our implementation of actions clearing is not taking into the consideration `failed` actions in the database.

**To Reproduce**
1. Make sure there are some failed preload actions in the AS
2. Wait a couple of minutes or trigger manually `rocket_preload_process_pending` event.
3. Check the failed actions in the AS, they're not reduced.

**Expected behavior**
We should also clean the failed actions, as they can stuck in the logs for a very long time. In my case, it looks like AS is not clearing them at all as this one is in the logs for 7 months.

**Additional context**
Not sure if we should use the same cleaner or different one, it might be useful to have ability to disable this cleaner for debugging purposes.

It's a part of this issue:
https://github.com/wp-media/wp-rocket/issues/6052

And database health in general can be improved by implementing also those issues:
https://github.com/wp-media/wp-rocket/issues/6057
https://github.com/wp-media/wp-rocket/issues/6058

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Mai-Saad** [comment]
Note: the same is happening with RUCSS when executing `action_scheduler_run_queue_rucss` while having  failed RUCSS entries in the actions table => only completed jobs are removed from the table

**Comment by piotrbak** [comment]
**Acceptance Criteria:**
1. When `rocket_preload_process_pending` cron is triggered, we should also clean the `failed` AS jobs related to WP Rocket Preload and RUCSS
2. Cleaner batch size (default 100) should apply for both, `failed` + `completed`
3. When `rocket_preload_process_pending` cron is triggered, we should **not** clean the `failed` AS jobs related to 3rd parties
4. With `rocket_action_scheduler_retention_period` filter, we should be apply to change the lifetime of items in the AS log

**Comment by piotrbak** [comment]
@Mai-Saad For RUCSS we have https://github.com/wp-media/wp-rocket/blob/9bdfa2f8d74c612101b3776c710270a2d171faa6/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L120

**Comment by CrochetFeve0251** [comment]
Currently we are using the [`Cleaner`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Common/Queue/Cleaner.php) class to clean our AS actions.
However inside that class we didn't listed `failed` tasks: https://github.com/wp-media/wp-rocket/blob/9bdfa2f8d74c612101b3776c710270a2d171faa6/inc/Engine/Common/Queue/Cleaner.php#L62

If we don't want to keep them then we would just have a add them inside that logic.
If we want to have a different lifespan we would need to reimplement the logic from that for loop with a different cutoff: https://github.com/wp-media/wp-rocket/blob/9bdfa2f8d74c612101b3776c710270a2d171faa6/inc/Engine/Common/Queue/Cleaner.php#L66

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
As we already discussed and reproduced the issue during a meeting last week I consider this as done.

## Identify the root cause
The root cause is that the cleaner is not clearing errors cf: 
https://github.com/wp-media/wp-rocket/blame/219a0989dc6ec41db29b47ac38f0869da57a3e86/inc/Engine/Common/Queue/Cleaner.php#L62

## Scope a solution
The solution from @piotrbak is related to the wrong table (wpr table instead of AS table).
Instead for the similar fashion solution in RUCSS we need to look at the `RUCSSQueueRunner` on this line: 
https://github.com/wp-media/wp-rocket/blob/219a0989dc6ec41db29b47ac38f0869da57a3e86/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L75

As per discussion with @piotrbak we need to support RUCSS failed action if possible and we do  not need a specific filter for failed action retention.

Due tot that the solution will be to add the failed actions to the statuses to clean:
https://github.com/wp-media/wp-rocket/blame/219a0989dc6ec41db29b47ac38f0869da57a3e86/inc/Engine/Common/Queue/Cleaner.php#L62

For that we just have to add `\ActionScheduler_Store::STATUS_FAILED,` to that array.

## Estimate the effort
Effort `XS`

**Comment by remyperona** [comment]
Looks good to me 👍🏼
