### ISSUE TITLE
PHP Fatal error: Uncaught InvalidArgumentException: The group "rocket-rucss" does not exist.

### ISSUE THREAD

**Issue by khalilgharbaoui** [wp-media/wp-rocket#6119]
There is a conflict with woocommerce and wp-rocket, if you have the “remove unused CSS feature” in wp-rocket checked. 
You will get the error you have noted. 

Workaround:  

Uncheck the “remove unused CSS” in wp-rocket and the problem goes away.

```
PHP Fatal error: Uncaught InvalidArgumentException: The group "rocket-rucss" does not exist. in /srv/users/stgleather/apps/stgleather/public/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:907
```

also see: https://wordpress.org/support/topic/the-group-rocket-rucss-does-not-exist/#post-17004056

**Comment by piotrbak** [comment]
Related issue on Action Scheduler repo:
https://github.com/woocommerce/action-scheduler/issues/972

**Comment by piotrbak** [comment]
Thanks for creating the issue @khalilgharbaoui have you contacted our support team about this issue? It would be good to have access to the affected website in order to investigate it further.

**Comment by piotrbak** [comment]
@khalilgharbaoui Is this happening to you even after reactivating RUCSS? If so, could you share with us credentials to your website + SFTP, so we could investigate this? You could reach our support or send them directly to piotr[at]wp-media.me.

**Comment by CrochetFeve0251** [comment]
## Reproduce the issue
I succeeded to reproduce the issue after looking at the logic.
To recreate the issue we need to:
- Make sure the group doesn't exists in the table `actionscheduler_groups`.
- Prevent the RUCSS to add any element to the queue.
- Make sure the logic from the plugin [Action Scheduler](https://wordpress.org/plugins/action-scheduler/) is loaded.

To prevent any element to be added to the Queue can bail out at the beginning of the method [`process_pending_jobs](https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L576)`.

To load the Action Scheduler plugin we need to comment the line `require_once WP_ROCKET_INC_PATH . 'Dependencies' . DIRECTORY_SEPARATOR . 'ActionScheduler' . DIRECTORY_SEPARATOR . 'action-scheduler.php';
` in the file [`inc/main.php`](https://github.com/wp-media/wp-rocket/blob/develop/inc/main.php) and install AS plugin.

Then activate RUCSS and you should see the exception when the Queue is running.

## Identify the root cause
The root cause of this issue is that the group is created when an element is added and not when the queue is runned.

## Scope a solution
A way to solve that issue is to check for the group being created before executing the queue.
The method `get_group_ids` could provide us an clean way to add it but it is protected.
Due to that what I propose is to create an adapter that will extend DataStore that will wrap around a DataStore and provide us the method we need thought reflection when the wrapped DataStore is an instance of `ActionScheduler_DBStore`.
It is a bit dirty but the only other way would be to request to AS to change the visibility of that method.

What do you think @engahmeds3ed ?

**Comment by engahmeds3ed** [comment]
# Reproduce the issue

This issue happens when: 
1. Our RUCSS queue runner is running before Action Scheduler's default queue runner
This can happen in very rare cases but to simulate it, you need to change [this line](https://github.com/wp-media/wp-rocket/blob/e0c2e719a47fd6801f825a4e227f4f94361473cc/inc/Engine/Optimization/RUCSS/Cron/Subscriber.php#L53) to be:
```
[ 'initialize_rucss_queue_runner', 0 ],
```
You need to do this change to the plugin while it's not active.

2. RUCSS is enabled but no job is created yet.
You can simulate this as @CrochetFeve0251 mentioned by adding the following return line in the start of [this method](https://github.com/wp-media/wp-rocket/blob/ce175a3ad1cc3bd42c2c303f8dc6b3c8d1477e3e/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L576):
```
return;
```

Also you need to remove the rocket-rucss group from `wp_actionscheduler_groups` database table.

3. Action scheduler's standalone plugin with version >= 3.6.0 is active.
You need to enable WPR before enabling this Action Scheduler standalone plugin.

# Identify the root cause
As per our investigation on that, this is what we think:

we are not setting the store object so it's null exactly like the default queue runner [here](https://github.com/woocommerce/action-scheduler/blob/d1a5342a3ff80b07e97432d3f652f8c61beb816f/classes/ActionScheduler_QueueRunner.php#L39-L47)
and both (custom runner and default runner) are running every_minute.

So Based on [that code](https://github.com/woocommerce/action-scheduler/blob/d46040b02d21c054ef7193a24cf2b76c39d1cde2/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L38), both runners will share the store instance (because it's singleton design pattern and both CRONs are on the same request)

What happens here is that the custom runner is running before the default runner passing the group to the store stake_claim method [here](https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L197)

and based on [that code](https://github.com/woocommerce/action-scheduler/blob/8643e7fbca68d1927a00b2591cea66b7925b3bf6/classes/data-stores/ActionScheduler_DBStore.php#L880-L884) that was added in this https://github.com/woocommerce/action-scheduler/pull/905 you are setting the group item inside claim_filters and as we use the same object for store in both queue runners, the group will be kept the one that added in the custom queue runner.

# Scope a solution
We don't need to create the group (after a discussion with AS team, they don't like creating the group till a job comes up), we just need to fix the root cause not to let out queue runner interfere with the default or any other runners.
So [here](https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L216) and [here](https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L220) we need to add the following line:

```
$this->store->set_claim_filter( 'group', '' );
```

I tested the fix locally with @CrochetFeve0251 help and it worked.

# Estimated effort
[XS]

**The hard part of this issue is to reproduce the issue in a consistent way.**

**Comment by khalilgharbaoui** [comment]
> @khalilgharbaoui Is this happening to you even after reactivating RUCSS? If so, could you share with us credentials to your website + SFTP, so we could investigate this? You could reach our support or send them directly to piotr[at]wp-media.me.

Hi @piotrbak,

Unfortunately, I can not provide you with the credentials, the system I am working on is private.
I did however make a PR https://github.com/wp-media/wp-rocket/pull/6156 with the changes suggested by @engahmeds3ed and also applied the change and tested it on my live code, which works fine as we speak. 
I no longer see the error or its related issues. Thanks, @engahmeds3ed 

Hope that helps, and would be nice if that gets merged in, so I don't have to edit my files on the next update.

Salaam 👋🏽

**Comment by AghaFarokh** [comment]
@engahmeds3ed 
Hello dear
I've added this line 
`$this->store->set_claim_filter( 'group', '' );`
in [here](https://github.com/wp-media/wp-rocket/blob/e98eb93e55d55bb7d2ad4310ab59d2e69bc97a72/inc/Engine/Common/Queue/RUCSSQueueRunner.php#L220)
and now I'm getting this error

> PHP Fatal error:  Uncaught Error: Call to undefined method ActionScheduler_HybridStore::set_claim_filter() in /var/www/html/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php:220
> Stack trace:
> #0 /var/www/html/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php(175): WP_Rocket\Engine\Common\Queue\RUCSSQueueRunner->do_batch()
> #1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Rocket\Engine\Common\Queue\RUCSSQueueRunner->run()
> #2 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
> #3 /var/www/html/wp-includes/plugin.php(565): WP_Hook->do_action()
> #4 /var/www/html/wp-cron.php(191): do_action_ref_array()
> #5 {main}
>   thrown in /var/www/html/wp-content/plugins/wp-rocket/inc/Engine/Common/Queue/RUCSSQueueRunner.php on line 220

**Comment by engahmeds3ed** [comment]
@AghaFarokh This means that you have an older version of Action scheduler, can u plz try installing action scheduler's standalone plugin (version >= 3.6.0).

We need also to guard against that in our code to have something like:
```
if ( method_exists( $this->store, 'set_claim_filter' ) ) {
    $this->store->set_claim_filter( 'group', '' );
}
```

**Comment by AghaFarokh** [comment]
Actually I didn't have a separate standalone AS plugin and my WordPress is updated to the latest version
But thank you, since I've installed the Action Scheduler standalone plugin it has been fixed
