### ISSUE TITLE
Remove LazyLoad CSS Background Images script from not processed pages

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6133]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When there's no WP Rocket buffer involved in processing the page, we should not inject the script

**To Reproduce**
1. Enable LazyLoad CSS Background Images feature
2. Add `define('DONOTCACHEPAGE', true)` to wp config
3. Go to the website in incognito mode and check the source
4. The script is there

**Expected behavior**
When buffer is not involved, the script should not be added

**Acceptance Criteria (for WP Media team use only)**
1. The script should not be injected when `define('DONOTCACHEPAGE', true)` is set
2. The script should not be injected when the page is excluded from being processed (never cache URLs, or from the page editor point of view)
3. The script should be added when the cache is not generated but optimisations are there (`add_filter( 'do_rocket_generate_caching_files', '__return_false' );`)
4. The same goes for LazyLoad Images script, no regression here
5. The script should be added in regular circumstances

**Comment by CrochetFeve0251** [comment]
## Reproduce the problem
The issue was easy to reproduce.

## Identify the root cause
The root cause is that we are not checking `DONOTCACHEPAGE` constant inside `should_lazyload` from [`CanLazyloadTrait`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Media/Lazyload/CanLazyloadTrait.php).
## Scope a solution
To solve that we will have to check the `DONOTCACHEPAGE` at [this level](https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Media/Lazyload/CanLazyloadTrait.php#L14) inside `should_lazyload` from [`CanLazyloadTrait`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Media/Lazyload/CanLazyloadTrait.php).

To support excluded URI we can use the following logic inside the same method: 
```php
		global $wp;

		if ( is_user_logged_in() ) {
			return false;
		}

		$url = home_url( add_query_arg( [], $wp->request ) );
		$cache_reject_uri            = get_rocket_cache_reject_uri();
                if (! preg_match( "@$cache_reject_uri$@m", $url ) ) {
				return false;
			}

```

Then tests concerning lazyload will have to be modified and for that the code inside the lazyload not merge will help.
## Estimate the effort
Effort `XS`
