### ISSUE TITLE
Send LazyLoad Background CSS Images feature data to the Support endpoint

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6139]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When sending support ticket we're automatically getting data about enabled features on the website. We should include the latest feature too.

**To Reproduce**
1. Create a ticket and choose the website
2. Check the HelpScout
3. The option is not listed

**Expected behavior**
The option should be listed in the HelpScout

**Additional context**
It's about this array:
https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Support/Data.php#L20

**Acceptance Criteria (for WP Media team use only)**
1. If the option is enabled, it should be listed in the HelpScout ticket

**Comment by jeawhanlee** [comment]
### Reproduce the problem ❌
Did not reproduce the problem as I can see it in the code.
### Identify the root cause ✅
Like @piotrbak stated above, the LL CSS Background Images option is not added to the array.
### Scope a solution ✅
Add the LL CSS Background images option to be sent in the support data
`'lazyload_css_bg_img' => 'Lazyload CSS Background Images'`
https://github.com/wp-media/wp-rocket/blob/b520071b602528ea2af6b1fae3280f36a45d7e78/inc/Engine/Support/Data.php#L20-L44
### Estimate the effort ✅
[XS]
