### ISSUE TITLE
Lazyload for CSS background images - do not modify excluded images markup

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#6146]
**Is your feature request related to a problem? Please describe.**
Currently, when an image is excluded from the feature, the `data-rocket-lazy-bg="loaded"` is still added to it, and the `background-image` value is still switched to a variable, like if the feature was applied to it, although the excluded image is indeed loaded without lazyload.

**Describe the solution you'd like**
Excluded images could have the attribute not added and the background-image value not changed; i.e. the excluded images markup could not be modified to prevent confusion.

**Describe alternatives you've considered**
If applying all these changes is too complex, we should document this properly informing the customers that all this will still be applied, but that they can check in the network tab that excluded images are indeed excluded.

**Additional context**
Screenshots:
[https://share.getcloudapp.com/RBuzexNE](https://share.getcloudapp.com/RBuzexNE)
[https://share.getcloudapp.com/RBuzexrl](https://share.getcloudapp.com/RBuzexrl)

**Comment by piotrbak** [comment]
Acceptance Criteria:
1. If image was excluded, we'll add the following attribute `data-rocket-lazy-bg="excluded"`, that applied to source and attribute exclusions, not CSS external files.
2. If image was processed correctly, it'll still have `data-rocket-lazy-bg="loaded"` attribute

**Comment by CrochetFeve0251** [comment]
## Reproduce
To reproduce there is just to exclude an image.

## Root cause
The root cause from the issue is that for the moment excluded images are still in the mapping list.

## Propose a solution
I will cut the solution into two parts.
The first one will be to remove the loaded attribute on the excluded element.
The second one will be to add the excluded attribute on the excluded element.

To prevent adding the loaded attribute on the excluded elements we will have to remove them from the mapping inside the [TagGenerator](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Media/Lazyload/CSS/Front/TagGenerator.php) class.

Then to add the excluded the strategy will be the following.
It would consist to add a tag with the mapping for excluded URLs inside the [add_lazy_tag](https://github.com/wp-media/wp-rocket/blob/50680560d9371981fdfdcbda23b7b45592d5d54c/inc/Engine/Media/Lazyload/CSS/Subscriber.php#L363) and add the logic to add the attribute excluded on each node which has an excluded attribute inside the JS script.

## Estimate effort

Effort `S`
