### ISSUE TITLE
Move staging domains list into backend

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6173]
**Is your feature request related to a problem? Please describe.**
There's another array that we could move to our backend:
https://github.com/wp-media/wp-rocket/blob/2281a63c7d5c8931ef16e3d61fe2cb65660bf0d9/inc/functions/api.php#L119

**Describe the solution you'd like**
This should be moved to the backend, we should also make sure to include the newest domains there:
https://github.com/wp-media/wp-rocket.me/issues/3480

**Acceptance Criteria**
1. We'll have a new section in the `Exclusions` tab
2. When the specific domain is detected we'll not display the RocketCDN banners

**Comment by CrochetFeve0251** [comment]
## Scope a solution
To make this possible first we will have to delete the old hard coded values:
https://github.com/wp-media/wp-rocket/blob/2281a63c7d5c8931ef16e3d61fe2cb65660bf0d9/inc/functions/api.php#L119
Then we will work on a new logic based on the SAAS:
- Register a new dynamic list
-  Link it to a filter `rocket_staging_list`
- Use filter `rocket_staging_list` to generate the logic to detect the staging

### Register a new dynamic list

The first will be to create a new client for the dynamic list at the following path `inc/Engine/Optimization/DynamicLists\StagingLists\APIClient.php` with that content:
```php
<?php
declare(strict_types=1);

namespace WP_Rocket\Engine\Optimization\DynamicLists\StagingLists;

use WP_Rocket\Engine\Optimization\DynamicLists\AbstractAPIClient;

class APIClient extends AbstractAPIClient {

	/**
	 * Specify API endpoint path.
	 *
	 * @return string
	 */
	protected function get_api_path() {
		return 'staging-exclusions/list';
	}
}
```
And a data manager at the following path `inc/Engine/Optimization/DynamicLists\StagingLists\DataManager.php` with the folowing content:
```php
<?php
declare(strict_types=1);

namespace WP_Rocket\Engine\Optimization\DynamicLists\StagingLists;

use WP_Rocket\Engine\Optimization\DynamicLists\AbstractDataManager;

class DataManager extends AbstractDataManager {

	/**
	 * Get cache transient name.
	 *
	 * @return string
	 */
	protected function get_cache_transient_name() {
		return 'wpr_dynamic_lists_staging';
	}

	/**
	 * Get lists json filename.
	 *
	 * @return string
	 */
	protected function get_json_filename() {
		return 'dynamic-lists-staging';
	}
}
```

Once we did that we will then register it in the service provider at [that level](https://github.com/wp-media/wp-rocket/blob/2281a63c7d5c8931ef16e3d61fe2cb65660bf0d9/inc/Engine/Optimization/DynamicLists/ServiceProvider.php#L52):
```php
		$this->getContainer()->add( 'dynamic_lists_staging_data_manager', AbstractDataManager::class )
			->addArgument( $this->getContainer()->get( 'options' ) );

		$this->getContainer()->add( 'dynamic_lists_staging_api_client', APIClient::class )
			->addArgument( $this->getContainer()->get( 'options' ) );

```
Then add it to the list of providers at [this level](https://github.com/wp-media/wp-rocket/blob/2281a63c7d5c8931ef16e3d61fe2cb65660bf0d9/inc/Engine/Optimization/DynamicLists/ServiceProvider.php#L55): 
```php
			'staging' =>
				(object) [
					'api_client'   => $this->getContainer()->get( 'dynamic_lists_staging_api_client' ),
					'data_manager' => $this->getContainer()->get( 'dynamic_lists_staging_data_manager' ),
					'title'        => __( 'Staging Lists', 'rocket' ),
				],
```
### Link it to a filter `rocket_staging_list`
For that we have to add a new method `get_staging` inside [`DynamicLists`](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/DynamicLists/DynamicLists.php) with the following content:
```php
	/**
	 * Get the staging list
	 *
	 * @return array
	 */
	public function get_stagings() {
		$lists = $this->providers['staging']->data_manager->get_lists();

		return isset( $lists ) ? $lists : [];
	}
```
Then inside [the subscriber](https://github.com/wp-media/wp-rocket/blob/develop/inc/Engine/Optimization/DynamicLists/Subscriber.php) we need need to add that event `rocket_staging_list` with a callback `add_staging` and add the following method:
```php
	/**
	 * Add the staging exclusions to the array
	 *
	 * @param array $excluded Array of staging urls.
	 *
	 * @return array
	 */
	public function add_staging_exclusions( $stagings = [] ): array {
		if ( ! is_array( $stagings ) ) {
			$stagings = (array) $stagings;
		}

		return array_merge( $stagings, $this->dynamic_lists->get_staging() );
	}
```
### Use filter `rocket_staging_list` to generate the logic to detect the staging
At [this level](https://github.com/wp-media/wp-rocket/blob/2281a63c7d5c8931ef16e3d61fe2cb65660bf0d9/inc/functions/api.php#L119),  instead of the hard coded array we gonna call the new filter:
```php
$default_staging = [];

$staging = apply_filters('rocket_staging_list', $default_staging);

if( ! is_array($staging) ) {
   $staging = $default_staging;
}
```

### fallback json file we need a new item like that in our github workflow:

https://github.com/wp-media/wp-rocket/blob/b73125b94b5ccb4c835a3128f52963b8caa10c44/.github/workflows/deploy_dynamic_lists_fallback.yml#L50-L56

## Estimate effort
Effort `S`

**Comment by engahmeds3ed** [comment]
@CrochetFeve0251 thanks, that's awesome.

Add to that, for the fallback json file we need a new item like that in our github workflow:

https://github.com/wp-media/wp-rocket/blob/b73125b94b5ccb4c835a3128f52963b8caa10c44/.github/workflows/deploy_dynamic_lists_fallback.yml#L50-L56

I sent it to Todo column so could u plz update the grooming to have that part also so we have all needed work in one comment?

**Comment by mostafa-hisham** [comment]
@Miraeld @wordpressfan @CrochetFeve0251 

I don't think we need a new API endpoint for the staging domains
and the staging domains should be added to the `exclusions/list` API
`https://b.rucss.wp-rocket.me/api/exclusions/list` 

which sends back multiple lists
- rucss_inline_atts_exclusions
- rucss_inline_content_exclusions
- defer_js_inline_exclusions
- defer_js_external_exclusions
- delay_js_exclusions
- js_minify_external
- js_move_after_combine
- js_excluded_inline
- cache_ignored_parameters
- preload_exclusions
- exclude_js_files

all of them at the same time, we will just add the `staging_domains` list to them

If we went with this solution we would not need to create a new fallback JSON file for staging domains
all lists from this API should be covered here
https://github.com/wp-media/wp-rocket/blob/de505f3494aee990ac24fb7af0643d0e26426e99/.github/workflows/deploy_dynamic_lists_fallback.yml#L39

Please let me know if this solution is ok. if not I will create the new API endpoint `https://b.rucss.wp-rocket.me/api/staging-exclusions/list` for `staging_domains`

**Comment by wordpressfan** [comment]
That's a very good idea @mostafa-hisham and I think this default list json file are not that large to have one more list in.

**Comment by Miraeld** [comment]
I've modified my code to adapt with what you were saying :)
I've used the default list endpoint as @mostafa-hisham mentioned, and I've used the name `staging_domains` as he also mentioned. So it can be added to the SaaS :)

**Comment by wordpressfan** [comment]
> I've modified my code to adapt with what you were saying :) I've used the default list endpoint as @mostafa-hisham mentioned, and I've used the name `staging_domains` as he also mentioned. So it can be added to the SaaS :)

Awesome, that was very quick, many thanks @Miraeld 
The work there still in progress, correct?

**Comment by Miraeld** [comment]
Yes it was, I was finishing the integration testing implementation, I've going to move it to review in a few minutes ;)
