### ISSUE TITLE
Lazyload CSS Background Images triggers DOMException errors because of incorrect selector

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6199]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Lazyload for CSS Background Images tries to process some specific HTML markup, it picks an incorrect CSS selector:
`css\">.jet-listing-dynamic-post-223`

This part: **css\">** causes a console error. This is inside the JSON code we are generating at `const rocket_pairs`. in a place where only the classname should be.

The console error: 
`DOMException: Failed to execute 'querySelectorAll' on 'Document': 'css">.jet-listing-dynamic-post-223 .elementor-element.elementor-element-f4d134b .elementor-flip-box__front' is not a valid selector.
`
The CSS validator does not like the location of the original style tag:
https://www.dropbox.com/s/ocgm2wy0ux4kb96/Screen%20Shot%202023-09-25%20at%209.10.17%20AM.png?dl=0

**To Reproduce**
1. Clone the markup of https://australiaswdv.wpenginepowered.com/, more info in the [Dev escalation](https://github.com/orgs/wp-media/projects/104/views/15?pane=issue&itemId=39713696)
2. Enable Lazyload CSS Background Images
3. see the console error

**Expected behavior**
We should pick the correct CSS selector, or sanitize it. 

**Screenshots**
![Xfd0beX](https://github.com/wp-media/wp-rocket/assets/229406/50f3308d-ee2d-4a33-8ca9-9fb8a7d43f7f)

https://i.imgur.com/Xfd0beX.png

**Additional context**
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1695649742150079
Dev escalation: https://github.com/orgs/wp-media/projects/104/views/15?pane=issue&itemId=39713696

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by webtrainingwheels** [comment]
Another example here: https://secure.helpscout.net/conversation/2386043065/447617/
Site: https://www.opcoach.com/
Error: https://jmp.sh/6qodr69A
`{"selector":"=menu-item])"`
Slack: https://wp-media.slack.com/archives/C08N8J6VC/p1696964154638169
Markup: https://jmp.sh/hWI2R293

**Comment by vmanthos** [comment]
The following markup can be used to reproduce the issue @webtrainingwheels reported:

```HTML
<style>
[title~="wp-rocket"] {
    background: url("/wp-content/rocket-test-data/images/wp-rocket.svg") no-repeat;
}
</style>
<div>
    <p title="wp-rocket">This is a paragraph with a <code>title</code> attribute.</p>
</div>
```

Alternatively, the following template can be used:
https://github.com/wp-media/rocket-test-data/blob/96275d79fe307c7cb4f00a2d2504b7b38eff662a/templates/lazyload_css_background_images.php

**Comment by Miraeld** [comment]
## Reproduce the problem
On a page, add a custom HTML block and add the snippet that @vmanthos provided: 
```html  
<style>
[title~="wp-rocket"] {
    background: url("/wp-content/rocket-test-data/images/wp-rocket.svg") no-repeat;
}
</style>
<div>
    <p title="wp-rocket">This is a paragraph with a <code>title</code> attribute.</p>
</div>
```
Load the page, with Lazyload enabled, and you should get an error in your console. 


## Identify the root cause

The issue stems from the regular expression, in the [Extractor class](https://github.com/wp-media/wp-rocket/blob/bb1cfe579266f527df8a807d40540201d5060cfa/inc/Engine/Media/Lazyload/CSS/Front/Extractor.php), used to match CSS selectors. [This regex](https://github.com/wp-media/wp-rocket/blob/bb1cfe579266f527df8a807d40540201d5060cfa/inc/Engine/Media/Lazyload/CSS/Front/Extractor.php#L40) was originally designed to handle standard CSS selectors but lacks support for attribute selectors, a more complex subset of selector patterns. Consequently, when attribute selectors like [title~="wp-rocket"] are encountered, the regex misinterprets them, leading to unexpected characters in the extracted selector, such as "="wp-rocket"]. 

## Scope a solution
To address the issue, we need to enhance the regular expression to support attribute selectors in CSS. This involves modifying the regex pattern as follows:

```php
$background_regex = '(?<selector>(?:[ \-,:\w.()\n\r^>[*"\'=\]#]|(?:\[[^\]]+\]))+)\s?{[^{}]*background\s*:(?<property>[^;}]*)[^}]*}';
```

## Development steps:
- [] Modify the regex
- [] Add tests to handle these attribute selectors

## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

**Comment by CrochetFeve0251** [comment]
@Miraeld we also need to make sure to add the new scenario to unit tests from that class. Otherwise that seems good to me.
