### ISSUE TITLE
 PowerPress Feeds Getting Cached

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#62]
Sample ticket: https://secure.helpscout.net/conversation/162671678/10426/?folderId=377611
Customer using PowerPress plugin says his feeds are cached. But, since WP Rocket 2.6, they shouldn't be.....

**Comment by arunbasillal** [comment]
I tested this on our Mega site and the generated [feed url](http://mega.wp-rocket.me/feed/podcast/) didn't have any issues. It redirected to the latest podcast, hopefully that is by design. We also do not have any further reported cases for this on HelpScout. 

I recommend we close this one. (cc: @GeekPress)

**Comment by GeekPress** [comment]
Closing this issue as recommended by @arunbasillal
