### ISSUE TITLE
Conflict with Advanced Ads plugin causes fatal error when viewing Popular tab in the Ad New plugins page

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6206]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
When both WP Rocket and the [Advanced Ads plugin](https://wordpress.org/plugins/advanced-ads/) are enabled, there is a fatal error if the Add New Plugin page is visited using the 'Popular' tab: 
![image](https://github.com/wp-media/wp-rocket/assets/45705494/405f8348-bfd9-4eee-90e0-211263a0a65b)

This occurs for the customer site in the referenced ticket, and I can also reproduce it here: https://support.rocketlabsqa.ovh/

The error reports the issue occurs here:
https://github.com/wp-media/wp-rocket/blob/bb1cfe579266f527df8a807d40540201d5060cfa/inc/Engine/Plugin/InformationSubscriber.php#L180

![image](https://github.com/wp-media/wp-rocket/assets/45705494/b1773e15-d71e-494b-b29d-6a5a2545be2a)

**To Reproduce**
1. Install most recent versions of WP Rocket and Advanced Ads plugins.
2. Go to the Add New Plugins page and click the 'Popular' tab.

**Expected behavior**
No error should occur when the 'Popular' tab is clicked.

**Additional context**
https://secure.helpscout.net/conversation/2378881255/446313?folderId=3985609

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Mai-Saad** [comment]
Reproducible since 3.14.3 (working fine on 3.14.2.1)
 Note: The file that throws the error was changed in 3.14.3 at this PR https://github.com/wp-media/wp-rocket/pull/6029 (may help for fix)

**Comment by Miraeld** [comment]
## Reproduce the problem
Like it's been said in the first message.

## Identify the root cause
As mentioned in the first message, the error lies here : 
https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Plugin/InformationSubscriber.php#L180

It appears that the plugin `Advanced Ads` comes as an object rather than an array like most of other plugins. 

## Scope a solution
To solve the issue, we can add a verification if the variable is an object or not, and cast it to array if it is: 

https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/Engine/Plugin/InformationSubscriber.php#L179 

```php
foreach ( $result->plugins as $index => $plugin ) {
	if ( is_object( $plugin ) ) {
		$plugin = (array) $plugin;
	}
	if ( $slug === $plugin['slug'] ) {
		$move = $plugin;
		unset( $result->plugins[ $index ] );
		array_unshift( $result->plugins, $move );
	}
}
```

## Development steps:

## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

**Comment by CrochetFeve0251** [comment]
@Miraeld seems good to me.
