### ISSUE TITLE
Avoid clearing cache once per language

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6214]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
WPML Team reported that when translating a single post we're clearing the cache once per language. It's possible to do it only once to avoid resources problems.

**To Reproduce**
Included in https://github.com/wp-media/wp-rocket/issues/6214#issuecomment-1757574484

**Expected behavior**
Included in https://github.com/wp-media/wp-rocket/issues/6214#issuecomment-1757574484

**Acceptance Criteria (for WP Media team use only)**
- We should launch `rocket_clean_domain` only once, not once per language
- No regression at clearing the translated posts
- No regression at clearing the specific languages

**Comment by zeopix** [comment]
Thanks for creating this ticket @piotrbak . 

You can reproduce this issue with some simple steps:
- Create a clean WP site.
- Add WPML Plugin, register it, add few languages.
- Install WP Rocket, go to Settings > Wp Rocket > Cache > "Enable cache for logged-in wordpress users".
- In the following request, the problem already occurs.
- It can also occur when applying a translation, and many other cinrcumstances (whatever hook ends up calling ``rocket_clean_domain`` in ``inc/functions/files.php``).

The problem is because in this method, the cache is cleared for each $url, and $url is retrieved using the function ``get_rocket_i18n_uri`` or ``get_rocket_i18n_home_url``,  which retrieves one URL per language.
This seems fine because some hooks are fired per URL, this logic seems to be correct, but later, a hook ``after_rocket_clean_domain`` is fired per URL, which is bound to ``clear_full_cache`` hook.

This later one, will do the same query on every step, so we propose to extract this hook from the ``foreach ( $urls as $url ) {``


([Se how we tweaked this function in this gist](https://gist.github.com/zeopix/55f4689978f07d92998cc33f576e3843))

An update query like this on every row of the wpv_table, repeated n times (where n=number of languages) locks this table and saturates mysql in large sites causing a significant performance impact.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
We can add a new filter outside of the loop `rocket_after_clean_domain`, and update the hook used in the preload subscriber (Could be also good to investigate other usages of the `after_rocket_clean_domain` filter to see if they could be changed and reduce the number of calls to the hooked methods).

### Estimate the effort ✅
Effort [S]

**Comment by CrochetFeve0251** [comment]
Seems good to me

**Comment by wordpressfan** [comment]
Small discussion: https://wp-media.slack.com/archives/CUT7FLHF1/p1698656302149819

We need to create a new action not filter exactly here: https://github.com/wp-media/wp-rocket/blob/06381b8860eb46e570911b2812652f54a676dd6d/inc/functions/files.php#L870
