### ISSUE TITLE
Modified date isnot changed when change status / retries of RUCSS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6229]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version =>3.15.2
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The modified date isnot changed while status/retries change during the generation of used CSS

**To Reproduce**
1. Enable RUCSS
2. Use the following snippet to see retries
`if ( is_user_logged_in() )
	return;
$slug = 'hello-world'; // Change this to match the slug of the page you want to delay its loading.
if ( false === stripos( $_SERVER['REQUEST_URI'], $slug ) )
	return;

add_action( 'wp_loaded', function(){
	sleep( 60 ); // The number of seconds WordPress loading will be stalled.
});`
3. Access the URL in snippet i.e domain/hello-world => entry is added to used CSS table (notice modified date)
5. Refresh admin and notice database => changing status/retries is not changing the modified date

**Expected behavior**
Modified timestamp shall change when status/retries change

**Screenshots**
![Screenshot from 2023-10-17 11-11-37](https://github.com/wp-media/wp-rocket/assets/76941962/46bdb5a4-7a45-4002-9144-ab990727d424)
![Screenshot from 2023-10-17 11-13-13](https://github.com/wp-media/wp-rocket/assets/76941962/9537cdd8-4b04-4d9f-b29e-f437ec17b1c3)
![Screenshot from 2023-10-17 11-13-39](https://github.com/wp-media/wp-rocket/assets/76941962/16465fc1-6b9c-431f-9a0f-2f2c5cd8aaca)

**Additional context**
- This will prevent switching failed to pending

**Acceptance Criteria (for WP Media team use only)**
- Whenever the row is updated, modified date should match the timestamp of the change
- It should include actions like injecting Used CSS, incrementing retries, changing the status of the URL

**Comment by Miraeld** [comment]
## **Reproduce the problem**

Like @Mai-Saad have explained: 

1. Enable RUCSS
2. Use the following snippet to see retries
```php 
if (!is_user_logged_in()) {
    $slug = 'hello-world'; // Change the slug depending on your page
    if (false === stripos($_SERVER['REQUEST_URI'], $slug)) {
        add_action('wp_loaded', function () {
            sleep(60);
        });
    }
}
```

3.  Access the URL in snippet i.e domain/hello-world => entry is added to used CSS table (notice modified date)
4. Refresh admin and notice database => changing status/retries is not changing the modified date

## **Identify the root cause**

The issue is that we are not modifying the `modified` date when we update the item. 

## **Scope a solution**

To address this issue, we can update the **`modified`** field within multiple functions responsible for modifying the database entry. These functions can be found in the following file: https://github.com/wp-media/wp-rocket/blob/a23c147b38baeb51d6a0039e190dc514ec994605/inc/Engine/Optimization/RUCSS/Database/Queries/UsedCSS.php

The functions requiring modification are: **`make_status_failed`**, **`make_status_completed`**, **`make_status_pending`**, **`increment_retries`**, and **`make_status_inprogress`**.

Each of these functions contains a call to `$this->update_item()` where the second parameter is an array of key / values that has to change in the database. We need to add the key value as follow : `’modified’ => current_time(’mysql’, true’)` .

## **Development steps:**

## **Effort estimation:**

XS

## **Is a refactor needed in that part of the codebase?**

No

**Comment by CrochetFeve0251** [comment]
Seems good to me

**Comment by MathieuLamiot** [comment]
@CrochetFeve0251, @Miraeld It might be worth investigating the update_item function first: https://github.com/wp-media/wp-rocket/blob/87aead4865858f90a43bd63b8c8b4f26ffa1fdcd/inc/Dependencies/Database/Query.php#L1963

From what I see, it is supposed to take care of the `modified` column. This abstraction makes sense so that we don't have to manually add the `modified` value every time we use `update_item`. But somehow it does not work.

I would prefer that we fix the issue at this level. WDYT?

**Comment by Miraeld** [comment]
Well, that's true, it should take care of it, however, in some of the functions in the file I mentioned takes care of `modified` directly there. 

I totally agree we should probably fix it at the level you mentioned, which I did not see while investigating, rather than the solution I've scoped.

**Comment by Miraeld** [comment]
After a quick investigations, it seems like  `$modified = $this->get_column_by( array( 'modified' => true ) );` should returns either the columns exists or not. But it doesn't work as it should. Even when it does exists it returns an empty response, and that's why `modified` doesn't get updated. 

I think, but I am not sure, this is because it's trying to match the value `true` to the `modified` column, and as `modified` doesn't equal `true` it returns an empty response. 

As @Tabrisrp developed that part within [this file](https://github.com/wp-media/wp-rocket/blob/efde659598ff6d1f28030b6b068e96d10059898f/inc/Dependencies/Database/Query.php), and as it is within a dependency, that would be great to get a second opinion on it. 

As this snippet : 
```php
		$modified = $this->get_column_by( array( 'modified' => true ) );
```
Only verify if `modified` exists and equal `true` within `$this->columns` I am wondering why don't we use an `isset($this->columns['modified'])` or an `array_key_exists('modified', $this->columns)`.

**Comment by wordpressfan** [comment]
Checking that now...

**Comment by wordpressfan** [comment]
@Miraeld 
The bug is in our code, exactly here: 
https://github.com/wp-media/wp-rocket/blob/a23c147b38baeb51d6a0039e190dc514ec994605/inc/Engine/Optimization/RUCSS/Database/Schemas/UsedCSS.php#L143

try changing this line to be
```
'modified'    => true,
```

I tested it locally and it's working, this key is the modified identifier which lets berlinDB know which column is the modified column so it's value to be changed with each update.

We may need also to remove this `created` from the column `last_accessed` and keep it only with the column `submitted_at`

Can u plz give it a try and see how it goes?

**Comment by Miraeld** [comment]
I confirm the change works.  Here is an updated version of the grooming : 
## **Reproduce the problem**

Like @Mai-Saad have explained: 

1. Enable RUCSS
2. Use the following snippet to see retries
```php 
if (!is_user_logged_in()) {
    $slug = 'hello-world'; // Change the slug depending on your page
    if (false === stripos($_SERVER['REQUEST_URI'], $slug)) {
        add_action('wp_loaded', function () {
            sleep(60);
        });
    }
}
```

3.  Access the URL in snippet i.e domain/hello-world => entry is added to used CSS table (notice modified date)
4. Refresh admin and notice database => changing status/retries is not changing the modified date

## **Identify the root cause**

The issue is that we are not modifying the `modified` date when we update the item. 

## **Scope a solution**
We need to modify this line:
https://github.com/wp-media/wp-rocket/blob/a23c147b38baeb51d6a0039e190dc514ec994605/inc/Engine/Optimization/RUCSS/Database/Schemas/UsedCSS.php#L143

to be
```
'modified'    => true,
```


## **Development steps:**

## **Effort estimation:**

XS

## **Is a refactor needed in that part of the codebase?**

No

**Comment by hanna-meda** [comment]
This issue came back with `3.16`. More details in this [thread](https://wp-media.slack.com/archives/CUKB44GNN/p1721377228517209)
