### ISSUE TITLE
RUCSS SASS user agent

### ISSUE THREAD

**Issue by viobru** [wp-media/wp-rocket#6245]
**Is your feature request related to a problem? Please describe.**
Customers who are managing a large number of sites running WPR with a WAF enabled have to manually update all our IPs on each site each time they change.

**Describe the solution you'd like**
Identify all requests from the RUCSS crawler with a dedicated user agent.

**Describe alternatives you've considered**
From @DahmaniAdame: _We can't do the updates ourselves as last time some customers complained about allowing our IPs on Wordfence. It makes sense to make the IPs available and leave to the customer to do the updates themselves. Either as part of the dynamic lists or have an endpoint for that purpose._

**Additional context**
HS ticket: https://secure.helpscout.net/conversation/2399910452/450291
Slack thread: https://wp-media.slack.com/archives/C08N8J6VC/p1698236250084859

**Comment by mostafa-hisham** [comment]
## Identify the root cause
After discussing this with @DahmaniAdame 
the main problem with firewalls in general is that they might block our requests.
Still, we can't do the update ourselves, and we can't ask the customer to continuously go check if there are new IPs to safelist.
What we need is consent to update automatically firewall rules when possible. At least, cover the most known firewalls.

## Scope a solution
- IPs dynamic list
Add a new section rucss backend for the [IP/domain lists](https://docs.wp-rocket.me/article/1628-which-ip-do-i-need-to-allow-for-wp-rocket) that needs to be whitelisted and a new endpoint for them.

- implement a consent mechanism
we can create an admin notice for it and set a new option in the plugin `approve_allow_whhitlist_ips` to true.

- automatically update the firewall 
 - we need to list the most known firewalls
 - create third-party classes for each one to whitelist our IPs/domains
 
## Effort estimation: 
@piotrbak @MathieuLamiot @DahmaniAdame 
I can't give an estimation because I don't know  if this solution is ok with @wp-media/productrocket team or not and
how many firewalls or security plugins we will work on?

**Comment by CrochetFeve0251** [comment]
@mostafa-hisham Is it possible to add a rule to WordFence using a filter? If yes with what filter?

**Comment by mostafa-hisham** [comment]
@CrochetFeve0251 
I have no idea. 
but it is not just wordfence
we need to check how we are going to do it in each common security plugin or firewall.

**Comment by piotrbak** [comment]
It sounds good from my point of view. Let's wait for @DahmaniAdame confirmation. 

We could start with creating backend section for this one and later on we'd be going with firewall software one by one

**Comment by ablears** [comment]
Hi, I was the original requestor. You're not going to be able to dynamically whitelist your IPs at third party WAFs like Cloudflare. Please also consider setting a unique user agent string for your RUCSS crawler; a single static target is much easier to whitelist than constantly changing IP addresses. 

You could also submit your crawlers to Cloudflare to get on their Known Good Bots list which would automatically bypass most firewall rules.

**Comment by DahmaniAdame** [comment]
@piotrbak @mostafa-hisham looks good to me. 

@CrochetFeve0251 No filters, but they have a function for that - https://www.wordfence.com/help/advanced/wordfence-api/#wordfencewhitelistip

@ablears 
> You could also submit your crawlers to Cloudflare to get on their Known Good Bots list which would automatically bypass most firewall rules

We already submitted the info to Cloudflare last year, but we don't have any control over the process. 

> You're not going to be able to dynamically whitelist your IPs at third party WAFs like Cloudflare.

Cloudflare has an API for their Firewall rules. It can be used to apply and maintain IPs to allow. This can be added to the Cloudflare-addon as we deploy that to known firewalls.

**Comment by CrochetFeve0251** [comment]
Ok so that seems good to me

**Comment by MathieuLamiot** [comment]
Hey team, to all who participated into this grooming: while the automated solution could be a long-term feature, it seems quite complex and high maintenance. The value added is great, but it seems the original suggestion has been overlooked. Is there a reason why it was not further discussed?
Using a user-agent would be a very quick win for us and seems to be usable on most firewall systems. From a user perspective, it would be much easier to maintain than a list of IPs too.
Any thoughts on that specific solution?
Thanks

**Comment by ablears** [comment]
Any update on this? We are still struggling with RUCSS being blocked, and as @MathieuLamiot mentioned, adding a dedicated user agent string is way simpler than directly amending customer's WAF rules.

**Comment by DahmaniAdame** [comment]
@ablears the enhancement has been deployed. All requests coming from SaaS will have a user agent starting with `WP-Rocket/SaaS`.

**Comment by piotrbak** [comment]
1. Desktop: WP-Rocket/SaaS Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
2. Mobile: WP-Rocket/SaaS Mozilla/5.0 (Linux; Android 13; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36
