### ISSUE TITLE
Purging cache from post/page editor redirects to posts/pages list when using Classic Editor

### ISSUE THREAD

**Issue by juricazuanovic** [wp-media/wp-rocket#6301]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
We have three separate reports, ([one](https://secure.helpscout.net/conversation/2427287687/456004/), [two](https://secure.helpscout.net/conversation/2431551480/457262?folderId=3572910), [three](https://secure.helpscout.net/conversation/2438505643/460986?folderId=273761)) that in WPR 13.15.4 with Classic Editor on post/page edit screen, when you click on Clear cache in the admin bar, they get redirected to the list of posts.
Version 3.15.3 and earlier don't seem to be having this issue, but I can reproduce it with 3.15.4 & 3.15.5.
In version 13.15.3 when performed the same action, the post edit screen would reload, and you don't get redirected to the list of posts.

**To Reproduce**
1. Install [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin
2. Open any post or page in Classic Editor
3. In the admin bar, click on WP Rocket → Clear and preload cache

**Expected behavior**
User shouldn't be redirected to the post/page list after clearing cache

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
Thanks @Tabrisrp 🙏 

Most likely related to this change:
https://github.com/wp-media/wp-rocket/pull/6197/files#diff-9284efdd8c1b65a0780bf7f9d51498e015458ad87cd113ef08edc04b62db7dbe

**Comment by JerissCloudCenter** [comment]
Yes I confirm, I have the same problem.

**Comment by Miraeld** [comment]
## Reproduce the problem
To reproduce the issue, follow the step in the problem explanation. 

## Identify the root cause
The issue is that, as @piotrbak mentioned, at the line: 
https://github.com/wp-media/wp-rocket/blob/develop/inc/common/admin-bar.php#L25
We are escaping the url, which removes some characters from it and because of this we get redirected to the post/page list.

## Scope a solution
To solve the issue, we must replace `esc_url()` by `sanitize_url()` 

## Effort estimation: 
XS

## Is a refactor needed in that part of the codebase?
No

**Comment by remyperona** [comment]
Looks good to me
