### ISSUE TITLE
Conflict with ABEConnector plugin, regression of private posts changes

### ISSUE THREAD

**Issue by joejoe04** [wp-media/wp-rocket#6315]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
There seems to be a regression starting in WP Rocket version 3.15.4 from https://github.com/wp-media/wp-rocket/pull/6218 where some pages receive a fatal error, display a blank white page, and cause the following error to log:

`[08-Dec-2023 17:46:03 UTC] PHP Fatal error:  ob_start(): Cannot use output buffering in output buffering display handlers in /nas/content/live/dunespropstg/wp-content/plugins/ABEConnector-master/lib/VRPConnector.php on line 976`

The error only seems to happen while the ABEConnector plugin is also installed and enabled.

**Ticket**
https://secure.helpscout.net/conversation/2435826231/460350

**Escalation**
https://wp-media.slack.com/archives/C056ZJMHG0P/p1702058807689159

In the escalation, Ahmed mentioned this is the full trace:

`'shutdown_action_hook, do_action(\'shutdown\'), WP_Hook->do_action, WP_Hook->apply_filters, Nextend\\WordPress\\OutputBuffer->closeOutputBuffers, ob_end_flush, WP_Rocket\\Engine\\Optimization\\Buffer\\Optimization->maybe_process_buffer, do_action(\'rocket_after_process_buffer\'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\\Engine\\Preload\\Subscriber->update_cache_row, WP_Rocket\\Engine\\Preload\\Subscriber->is_excluded_by_filter, apply_filters(\'rocket_preload_exclude\'), WP_Hook->apply_filters, WP_Rocket\\Engine\\Preload\\Subscriber->exclude_private_url, rocket_url_to_postid, WP_Query->__construct, WP_Query->query, WP_Query->get_posts, apply_filters_ref_array(\'the_posts\'), WP_Hook->apply_filters, Gueststream\\VRPConnector->filterPosts, Gueststream\\VRPConnector->loadTheme'`

Ahmed also mentioned it might be fixed from our side by trying adding the following line exactly [here](https://github.com/wp-media/wp-rocket/blob/87aead4865858f90a43bd63b8c8b4f26ffa1fdcd/inc/functions/posts.php#L243-L242):
`$query['suppress_filters'] = true;`

**Expected behavior**
This error should not occur regardless of what page is viewed and what other plugins are enabled.

**To Reproduce**
1. Update WP Rocket to at least version 3.15.4
2. Install and activate the ABEConnector plugin
3. View a page with this issue and see the error (not sure why some pages have the error and some not)
https://dunespropstg.wpengine.com/vrp/favorites/show

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by wordpressfan** [comment]
## Reproduce the issue
Yes I can reproduce it by having the following snippet:
```
add_filter( 'the_posts', function( $posts ) {
    ob_start();
    echo 'wordpressfan';
    $final = ob_get_clean();
    return $posts;
} );
```

## Root cause
With this PR: https://github.com/wp-media/wp-rocket/pull/6218 we created a new function `rocket_url_to_postid` to get the post ID from url to be able to detect the private urls to be excluded from preload.
We use WP_Query class there to get that post ID, and we have a case that inside our buffer with the hook `rocket_after_process_buffer` we use this function to check preload exclusions and this fatal error happens because inside the main buffer we are using another buffer.

## Provided solution
As mentioned in the issue, we can suppress filters inside this function when using WP_Query class or at least add a new filter to filter the args being passed to WP_Query here:
https://github.com/wp-media/wp-rocket/blob/87aead4865858f90a43bd63b8c8b4f26ffa1fdcd/inc/functions/posts.php#L243

so without affecting any other user we can provide a helper to suppress filters there.

## Estimation
[XS]

What do u think @wp-media/php-team ?

**Comment by Miraeld** [comment]
Seems okay to me

**Comment by Mai-Saad** [comment]
For testing we need to:
- Validate the problem [here](https://github.com/wp-media/wp-rocket/issues/6315#issuecomment-1860415644) with the mentioned snippet is fixed
- rerun this for regression https://wpmediaqa.testrail.io/index.php?/runs/view/779&group_by=cases:section_id&group_order=asc
