### ISSUE TITLE
[R&D] Defer subscriber instantiation to when the first event it is subscribed to is received.

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6366]
**Context**

Reduce the plugin CPU usage: https://wp-media.slack.com/archives/CUT7FLHF1/p1704447166535709

**Expected behavior**
When loading the plugin, subscribers should not be instantiated straight away. Subscriptions to their events should be made with a lazy load approach so that the subscriber and its dependencies are loaded only when the first event is received.
As a result, the loading sequence of the plugin should be reduced, as seen through XDebug.
It would be nice to be able to selectively apply this approach to some subscribers so that [we lazy load the biggest/less used ones](https://wp-media.slack.com/archives/CUT7FLHF1/p1704728703474109).

**R&D ideas**
- [Build a proxy to the actual subscriber](https://wp-media.slack.com/archives/CUT7FLHF1/p1704714510432669?thread_ts=1704447166.535709&cid=CUT7FLHF1)
OR
- Register an anonymous function as a callback to the events, returning `container->get('the_subscriber')->the_actual_callback` (should work since subscribers are declared with `share` and not `add` in the service providers).
OR any other approach.

**How to check results with XDebug**
https://wp-media.slack.com/archives/CUT7FLHF1/p1704728991213049

**Comment by MathieuLamiot** [comment]
Seems promising: https://wp-media.slack.com/archives/CUT7FLHF1/p1704729468901559?thread_ts=1704728703.474109&cid=CUT7FLHF1

To test how it can be used with Container League.

**Comment by MathieuLamiot** [comment]
Here are the results: https://wp-media.slack.com/archives/CUT7FLHF1/p1705062835645899

To do:
- Check the results on Divi::class. If it is better, make this production-ready and move forward for the next minor. Otherwise, let's drop it for now.

In the future, we might want to:
- Try it on specifically selected classes
- Try at subscriber level without using the library.

**Comment by CrochetFeve0251** [comment]
@MathieuLamiot this is not the right results here (it is not the process we described on that issue) as they are using the container and the library to proxy.
Instead I did a quick and dirty change to make it functionnal on some subscribers on this branch and @wordpressfan gonna test it when he got some time: https://github.com/wp-media/wp-rocket/tree/dev-initave/proxy-subscribers

Metrics @wordpressfan did are more related to that issue: https://github.com/wp-media/wp-rocket/issues/6368

Also as I told @wordpressfan earlier today I am not surprised about the results he got. If we want to have interesting results for #6368, we need to lazyload only few dependencies and not all dependencies that will have to be lazyloaded in the app.
That's why having #6366 would be vital to reduce the memory usage from #6368 and potentially have some gains from that issue.

**Comment by MathieuLamiot** [comment]
Your proxy-subscribers PR is what I meant with "Try at subscriber level without using the library."

If it is easier to understand like this, let's:
- Keep this issue for https://github.com/wp-media/wp-rocket/tree/dev-initave/proxy-subscribers. -> To be R&D later on (if we have time this sprint? but there are other identified quick wins before)
- Renamed #6368 to specifically check the results with lazy load of Divi, and assigned it to @Tabrisrp.

**Comment by piotrbak** [comment]
@MathieuLamiot Is it still relevant?

**Comment by MathieuLamiot** [comment]
It's probably a lot of effort for not much at this point.
