### ISSUE TITLE
[R&D] Defer Divi dependency instantiation to when the first call to it is done.

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6368]
**Context**

Reduce the plugin CPU usage: https://wp-media.slack.com/archives/CUT7FLHF1/p1704447166535709

**Expected behavior**
When loading the plugin, class dependencies (for example subscriber dependencies, but could apply to all other classes managed with ServiceProviders and Containers) should not be instantiated straight away. A lazy load approach should be used: as an example, when instantiating the Divi::class, its UsedCSS dependency should not be instantiated until the corresponding callback is called. As a result, the loading sequence of the plugin should be reduced, as seen through XDebug.
It would be nice to be able to selectively apply this approach to some dependency so that [we lazy load the biggest/less used ones](https://wp-media.slack.com/archives/CUT7FLHF1/p1704728703474109).

**R&D**
- Wrap the dependencies in an interface that takes care of loading the actual class when needed. (Similar to the factory/proxy approach?) To be further explained with example.

**Comment by MathieuLamiot** [comment]
Seems promising: https://wp-media.slack.com/archives/CUT7FLHF1/p1704729468901559?thread_ts=1704728703.474109&cid=CUT7FLHF1

This could be used when declaring a heavy class in a container?

**Comment by MathieuLamiot** [comment]
Here are the results: https://wp-media.slack.com/archives/CUT7FLHF1/p1705062835645899

To do:

Check the results on Divi::class. If it is better, make this production-ready and move forward for the next minor. Otherwise, let's drop it for now.
In the future, we might want to:

Try it on specifically selected classes
Try at subscriber level without using the library.

**Comment by remyperona** [comment]
It does gives an improvement, as it's reducing the number of Container methods called to instantiate the class (because of the dependency on the delay JS and RUCSS controllers).

Though the theme resolver is providing a bigger improvements, since it's not loading the themes subscribers at all if the current theme doesn't need one.

Implementing the theme resolver will require changes in this PR after as it's touching the same files. It could give an improvement in the specific case of Divi as the current theme.

On another note, for this specific case, in my opinion this feels like hiding the issue. At the root, the Divi class should not have the delay JS and RUCSS controllers as dependencies, but use alternative methods to get what is needed (like filters).

**Comment by MathieuLamiot** [comment]
Thanks for the details @Tabrisrp, it make sense.
I would suggest then that we:
- try to release the Divi lazyload + the theme resolver in the next minor.
- Open a GitHub issue to rework the dependencies of Divi, possibly avoiding RUCSS & Delay JS controllers. @Tabrisrp can you open this issue with the details you have in mind, and mentioning that we should consider then un-doing the lazyload around Divi class (if it does not make sense anymore).

(cc @piotrbak)
