### ISSUE TITLE
As a support team member,  I want to know the last time an entry was added to wpr_rucss_used_css table with the status on-submit so that I can check if the RUCSS feature is properly triggered 

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6372]
**Context**

As part of building a RUCSS Debug tool, some information must be stored while in WP Rocket Debug mode so that it can be monitored easily by the support team.
More details here: https://www.notion.so/wpmedia/RUCSS-Issues-7adc4ed750fd4dc7902bb6881ed1204b?pvs=4#38398060400d4fcf97f27aa563483d68

**Expected behavior**
- When in debug mode (WP_ROCKET_DEBUG?), a timestamp must be updated in the DB every time the `UsedCSS::create_new_job` method is successful. We only need to keep the last time it happened.
- When not in debug mode, nothing special happens. If there is a timestamp stored, it can stay there.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
- For storing the debug data, I think we can create a new option for this like the way we do for the `wp_rocket_settings` which holds a set of serialized array. Then we can create a new element in the option as `last_rucss_added`.
- Just like @Tabrisrp  stated [here](https://github.com/wp-media/wp-rocket/issues/6372#issuecomment-1892717056) To manage this option, we can still utilise our `Options` and `Options_Data` classes, so instead of parsing `settings` to `$options_api->get( 'settings', [] )` we can parse `debug` where our option name would `wp_rocket_debug`

We can allow for Separation of Concerns.
- Add a new namespace `WP_Rocket\Engine\Debug\RUCSS`
- Add a subscriber to the new namespace
- Replace the conditional check with an action hook that returns the value of add_item()
- Then add a new event and callback in the subscriber to save timestamp when arg is not false and WP_ROCKET_DEBUG is not false

Like @Tabrisrp stated, 

Estimate the effort ✅
[S]

**Comment by remyperona** [comment]
> Replace the conditional check with an action hook that returns the value of add_item()

Where is this in the code?

> NB: If we decide to go with adding a separate option for the debug data, we will not have the leisure of using our helper classes and functions like the WP_Rocket\Admin\Options_Data, WP_Rocket\Admin\Options, get_rocket_option, update_rocket_option

We can use the `Options` and `Options_Data` classes, there are not limited to the settings option, we can create new instances with a different option value.

**Comment by jeawhanlee** [comment]
> Where is this in the code?

My bad, This was based on my first grooming before I updated it, it's imaginary.

> We can use the Options and Options_Data classes, there are not limited to the settings option, we can create new instances with a different option value.

You are right @Tabrisrp

**Comment by remyperona** [comment]
Can you update your grooming to match our discussion?
