### ISSUE TITLE
add gad_source query string to default ignore rules/logic for query string handling so this does not bypass caching/optimization

### ISSUE THREAD

**Issue by tullibo** [wp-media/wp-rocket#6399]
Google is now appending the string ?gad_source=1 to Google Ad traffic which appears to be related to GA4 integration

This query string does not appear to be ignored by WPRocket like other common query strings such as gclid 

Consequently, the TTFB and overall speed of traffic coming from sessions using this query string is really bad.

This is an issue especially for sites with a lot of paid traffic as they're failing core web vitals but also a broader issue because this expensive traffic is getting some of the slowest sessions.

We've seen this behaviour across 100s of sites at our agency https://wpspeedfix.com where we specialize in site speed optimization

Our solution is to use the ignore query strings plugin/code but ideally this should be part of WPRocket core. The core plugin should not bypass caching for gad_source query strings

Screenshot attached from our core web vitals tracking software highlighting the issue - you'll see for the homepage and /nl page, the regular traffic is fast and generally passing core web vitals however paid traffic is incredibly slow with a TTFB that is skiy high **Timings are in milliseconds to 9842 is 9.842 seconds

![speed tracking example](https://github.com/wp-media/wp-rocket/assets/11812903/6bbe6674-de51-48b5-a029-ba5e4e8b7d8e)

**Comment by DahmaniAdame** [comment]
@tullibo thank you for reporting that. 
It seems indeed like something that can be added to our ignore list. 
I went ahead and added it on our side on our dynamic lists. 
The dynamic lists update every week. In order to apply the change sooner, you will need to manually update it on `WP Rocket > Tools > Update Inclusion and Exclusion Lists`.
@piotrbak I checked the parameter, safe to ignore. Went ahead and added it to the backend to speed up the process.
