### ISSUE TITLE
Maybe optimize lookups of tables in DB to stop using SHOW TABLES LIKE

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6460]
**Context**
Reported by a user through the support: https://wp-media.slack.com/archives/C43T1AYMQ/p1709561232039849

**Expected behavior**
Investigate the possibility to rework the `exists()` (and related) methods in the codebase, that are using `SHOW TABLES LIKE`, to something using `SELECT table_name FROM information_schema.tables WHERE table_name like '%s' LIMIT 1` to reduce the compute time on the DB when there are many tables to parse from.

**Acceptance Criteria**
Non-regression tests on the impacted features.

**Additional information**
The issue comes from BerlinDB, not WP Rocket code itself: https://github.com/berlindb/core/blob/9c4d1fe588b4bff7b9f45091d7890bbbef9c0bc4/src/Database/Table.php#L351
We received 2 suggestions:
- `SELECT table_name FROM information_schema.tables WHERE table_name = '%s' LIMIT 1` 
- SHOW TABLES =
The main risk here are regressions from changing from a `LIKE` statement to an `=` (maybe with prefixes, etc. ?). There is probably a reason why LIKE is used in BerlinDB, so it's much safer to stick with it for now. That being said, I think the SHOW TABLES is a high-level instruction that will first list all tables, and then apply filters if any.
Going with an explicit SQL statement should be much faster already, hence my suggestion:

`SELECT table_name FROM information_schema.tables WHERE table_name like '%s' LIMIT 1`

**Comment by ScottE-BME** [comment]
This is still an issue.  If you have a database with 150k+ tables, it destroys performance.  It goes from 2-3 seconds per query to .02.

**Comment by ScottE-BME** [comment]
What is happening with this?  The 3.16 update to your plugin completely crippled our sites as you added even more of these statements with the Optimize Critical Images feature.

We are stuck on 3.15.10 until this is handled.

**Comment by alfonso100** [comment]
related https://secure.helpscout.net/conversation/2685036291/508480/

**Comment by Miraeld** [comment]
### Context:
The objective is to replace the current usage of `SHOW TABLES LIKE` with a more efficient `SELECT table_name FROM information_schema.tables WHERE table_name LIKE '%s' LIMIT 1` query. This change aims to reduce the database load and improve performance when there are many tables in the database.

### Reproduce the problem:
1. Simulate a database with a large number of tables.
2. Use the existing BerlinDB code that checks for table existence using `SHOW TABLES LIKE %s`.
3. Measure the time it takes to execute this query.

### Identify the root cause:
The `SHOW TABLES LIKE` method lists all tables and applies a filter afterward, making it less efficient for databases with many tables. The issue is caused by the need to parse through all the tables in the database before filtering for the specific one.

### Scope a solution:
Replace the `SHOW TABLES LIKE` query with:
```sql
SELECT table_name FROM information_schema.tables WHERE table_name = '%s' LIMIT 1
```

This query directly checks the information_schema.tables and is more efficient since it only retrieves the necessary data.

### Development Steps: 

1.  **Modify [`table_exists() from AbstractQuery.php](https://github.com/wp-media/wp-rocket/blob/7cab3aa6e7a3d8566e4f8abb7e575f7f9d4c4a50/inc/Engine/Common/Database/Queries/AbstractQuery.php#L509)**
Updated code: 
``` php
protected function table_exists(): bool {
    if ( self::$table_exists ) {
        return true;
    }

    // Get the database interface.
    $db = $this->get_db();

    // Bail if no database interface is available.
    if ( ! $db ) {
        return false;
    }

    // Query statement to check the information schema.
    $query    = 'SELECT table_name FROM information_schema.tables WHERE table_name = %s LIMIT 1';
    $prepared = $db->prepare( $query, $this->table_name );
    $result   = $db->get_var( $prepared );

    // Does the table exist?
    $exists = $this->is_success( $result );

    if ( $exists ) {
        self::$table_exists = $exists;
    }

    return $exists;
}
```

2. **Modify [`table_exists()` from AbstractQueries.php](https://github.com/wp-media/wp-rocket/blob/24751d72bc15ed4ef58371c0caf6c86050207167/inc/Engine/Common/PerformanceHints/Database/Queries/AbstractQueries.php#L110)**
Updated code: 
``` php
protected function table_exists(): bool {
    if ( self::$table_exists ) {
        return true;
    }

    // Get the database interface.
    $db = $this->get_db();

    // Bail if no database interface is available.
    if ( ! $db ) {
        return false;
    }

    // Query statement to check the information schema.
    $query    = 'SELECT table_name FROM information_schema.tables WHERE table_name = %s LIMIT 1';
    $prepared = $db->prepare( $query, $this->table_name );
    $result   = $db->get_var( $prepared );

    // Does the table exist?
    $exists = $this->is_success( $result );

    if ( $exists ) {
        self::$table_exists = $exists;
    }

    return $exists;
}
```

### Effort Estimation
* **Size**: **Small (S)** — Only three files need modifications, and the changes are straightforward.Size: Small (S) — Only three files need modifications, and the changes are straightforward.

### Non-Regression Testing:

- Ensure tests cover scenarios where tables:
	- Exist and are queried using prefixes.
	- Do not exist, to confirm the correct return values.
- Test with databases containing many tables to validate performance improvements.

**Comment by MathieuLamiot** [comment]
@Miraeld It's worth mentioning that the 1st point is from a dependency

**Comment by Miraeld** [comment]
Yes true, I didn't pay attention to the full path of that file, I edited the grooming accordingly.

**Comment by wordpressfan** [comment]
As @MathieuLamiot mentioned, this is inside dependency, so we may need to fix it from berlindb side or at least in its fork, what do u think?

**Comment by arekm** [comment]
This change (https://github.com/wp-media/wp-rocket/commit/975503df515ea4650cc4791e7018519315e32c86) kills performance on mysql < 8.0 (like mysql 5.7) because there using information schema is very expensive while "show tables like" is cheap:

https://github.com/wp-media/wp-rocket/pull/7831

https://wp-media.slack.com/archives/C43T1AYMQ/p1709561232039849 link is unfortunately dead, so root cause of the change is unknown. Was the problem on >= 8.0?
