### ISSUE TITLE
clear critical images inside admin bar is duplicated in edit page view

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6509]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16-alpha-1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Clear critical images exists twice in admin bar

**To Reproduce**
1. install/activate 3.16-alpha1
2. check wpr admin bar
3. Clear critical images is there twice

**Expected behavior**
single clear critical cache is there

**Screenshots**
![Screenshot from 2024-03-25 15-18-50](https://github.com/wp-media/wp-rocket/assets/76941962/21c79e15-7616-483d-ba90-35af83858849)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by remyperona** [comment]
It's not unexpected, there is one to clear all, and one to clear images for this specific URL, since we're on a post edit view.

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
- Install & Activate Classic editor
- Open a post
- Check WPR dropdown and see duplicated (Clear critical images & Clear critical images of this URL)

This is also happening for RUCSS.

### Identify the root cause ✅
We are bailing out if in admin view [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/AdminBar.php#L116) but we are also checking for invalid post and and absence of other query string that is expected in the post view of the admin which will not trigger the bail out, Currently on trunk we don't check these.

### Scope a solution ✅
I believe we don't need the extra checks [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/AdminBar.php#L118-L124), so we can simply take it out.

### Estimate the effort ✅
[XS]

**Comment by jeawhanlee** [comment]
@Tabrisrp It seemed like its expected, but we are currently not doing this on trunk, so this is a regression as it also affects RUCSS. On trunk, we only show `Clear Used CSS` in the post view but with 3.16 branch we show both(`Clear Used CSS & Clear used CSS for this URL`).
PS: This is for post view not preview and it's not noticeable until the classic editor is used.

**Comment by remyperona** [comment]
I think we would need product direction on this, because for the clear cache, we can see there is the 2 options:
- clear cache
- clear cache for this post

So the current behaviour is the same for the critical images.

**Comment by jeawhanlee** [comment]
@Tabrisrp Yes, this was confusing at first because it was expected. 
Pinging @MathieuLamiot @piotrbak

**Comment by MathieuLamiot** [comment]
I have no idea about the expected behavior here, let's wait for product on this. Maybe @wp-media/qa-team had some info on this? Thanks for pointing this out. I'm putting this to Blocked for now.

**Comment by piotrbak** [comment]
That part is covered by this [paragraph](https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#9f0c97784b7444b3a21a21749f6d0e9e).

So:
- When RUCSS is enabled, we're bounding the clearing actions to its buttons (Clear Used CSS + Clean Used CSS for This URL)
- When RUCSS is disabled, we're adding global button Clear Critical Images, and it'll be displayed only in the WP Admin (just like Clear Used CSS). It'll clear Critical Images data + cache
- When visiting the post on the frontend while logged-in as admin + RUCSS enabled, we'll bound clearing critical images data to `Clean Used CSS for This URL` button
-  When visiting the post on the frontend while logged-in as admin + RUCSS disabled, we'll add a new button ‘Clear Critical Images of this URL’, it'll clear Critical Images data of this URL + cache of this URL
- In the editor, we'll **not** add `Clear Critical Images of this URL` button
- The above is because clicking on Update Post will clear the Critical Images data of this URL and its cache. It's important that it should clear critical image data only for this URL, not for the all URLs that are in the partial purge array. (that may change in the future, but not for now)

Does it completely address the concerns?

**Comment by remyperona** [comment]
sounds good to me, so that means on the post editor view, it's the single clear item that needs to be removed, not the other one.

Adding a check for `! is_admin()`should do the trick

**Comment by MathieuLamiot** [comment]
Marking this test by devs, there are clear AC [here](https://github.com/wp-media/wp-rocket/issues/6509#issuecomment-2056546224)
