### ISSUE TITLE
Messages of LCP/ATF isnot working correctly

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6526]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => commit f488281de0de219b5db95ce5f29bc167fea903ad (HEAD -> 6519-316-bug-front-end-optimizations-are-not-applied-even-when-lcpatf-data-is-in-the-db
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
- With fresh install of 3.16 , the success message of rucss is displayed => no message while Rucss is off
- when enable RUCSS, no message is displayed at all =>  updated counter message shall be displayed then updated success message shall be displayed
-  when external request is blocked, no message is displayed => updated message shall be displayed while rucss is on

**Expected behavior**
Apply the messages mentioned here https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#c6830acbda4a44fbb723749c9116211f

**Screenshots**

**Additional context**
- Currently after clear used CSS while RUCSS is on, message is `WP Rocket: Used CSS cache cleared!`, shall we change this too @piotrbak ? if yes, to what?

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem with a fresh install of 3.16

### Identify the root cause ✅
We updated the transient `rocket_rucss_processing` to `rocket_saas_processing` [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/Notices.php#L88), The ids as well as has been updated but we didn't change this here:
https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/src/js/global/countdown.js#L51-L52

### Scope a solution ✅
- Update `rocket_rucss_processing` to `rocket_saas_processing` [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/Notices.php#L88)
- Update these lines to use the new ids:
https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/src/js/global/countdown.js#L51-L52
- Update this: https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/Notices.php#L304
- Update notices with this here: https://www.notion.so/wpmedia/Beacon-Auto-optimize-LCP-image-Auto-exclude-images-above-the-fold-from-LazyLoad-56226bccec874b45aed4a57f08690029?pvs=4#c6830acbda4a44fbb723749c9116211f
- Update related tests.

### Estimate the effort ✅
[S]

**Comment by remyperona** [comment]
LGTM
