### ISSUE TITLE
Inconsistency between Clear used CSS / Critical Images vs. Clean […] buttons

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6533]
Before submitting an issue please check that you’ve completed the following steps:

Made sure you’re on the latest version: 3.16-alpha1 ✓
Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
Currently, we have a couple of discrepancies in UI regarding the Clear used CSS / Critical Images accessible from either Admin top bar or from WPR Dashboard - Quick Actions section. 

Case 1:
While RUCSS enabled, visit a Page URL while being logged in and check the Admin bar.
Notice that the button reads "Clean Used CSS of this URL".
<img width="263" alt="Screenshot 2024-04-01 at 13 34 42" src="https://github.com/wp-media/wp-rocket/assets/93833759/542b1208-7abb-4419-b4cd-db2e54c71a00">

Case 2:
With RUCSS disabled, go to the WPR Dashboard and inspect the Quick Actions section.
Notice that the button for Critical Images Cache reads "Clean Critical Images" (meanwhile in Admin bar it is used "Clear").
<img width="795" alt="Screenshot 2024-04-01 at 13 26 31" src="https://github.com/wp-media/wp-rocket/assets/93833759/09d00d61-2c4f-4bd7-b4ec-89acade2f8bf">

**Expected behavior**
The button should read in all places and for all cases, "Clear" instead of "Clean".

**Comment by jeawhanlee** [comment]
Reproduce the problem ✅
I can see the problem in the code.

Identify the root cause ✅
We use Clean [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/AdminBar.php#L172) & [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/AdminBar.php#L204) instead of Clear

Scope a solution ✅
We need to update the text [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/AdminBar.php#L172) & [here](https://github.com/wp-media/wp-rocket/blob/b459f191a348426b2b1a3cf656a4db577e76800f/inc/Engine/Saas/Admin/AdminBar.php#L204) to use Clear

Estimate the effort ✅
[XS]

**Comment by MathieuLamiot** [comment]
Valdiated by QA: https://wp-media.slack.com/archives/CUT7FLHF1/p1712740637476069?thread_ts=1712715812.742159&cid=CUT7FLHF1
