### ISSUE TITLE
ATF image in root directory isnot excluded from LL with specific markup

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6536]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16-alpha1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Having atf image in the root directory with the following markup , is not excluded from LL 
`<img src="test.png" alt="test1"  width="200" height="500">` or 	
```
<picture>
<img src="test.png">
</picture>
```

**To Reproduce**
1. install/activate 3.16 + activate lazyload feature
2. permalinks without `/`
3. page template with image in the root directory 
4. visit the page template
5. clear cache and revisit the page

**Expected behavior**
ATF/LCP is excluded from LL

**Screenshots**

**Additional context**
- adding `/ `before the image will work

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Mai-Saad** [comment]
The image isnot detected as ATF here https://e2e.rocketlabsqa.ovh/lcp_img_loadedbyjs_template

**Comment by remyperona** [comment]
What is the related DB data entry for this case looks like?

**Comment by jeawhanlee** [comment]
### Reproduce the problem ✅
I was able to reproduce the problem with the steps below:
1. install/activate 3.16 + activate lazyload feature
2. page template with image in the root directory without a forward slash(`<img src="image.jpg" alt="image" />`)
3. visit the page template
4. clear cache and revisit the page
5. Check the markup, you'll still find lazyload applied: `<img src="image.jpg" data-lazy-src="image.jpg" data-ll-status="loaded" class="entered lazyloaded">`
When you log the entries of excluded patterns with the filter - `rocket_lazyload_excluded_src` You'll get:
```
Array
(
    [0] => /wpcf7_captcha/
    [1] => timthumb.php?src
    [2] => woocommerce/assets/images/placeholder.png
    [3] => /id/10/2500/1667.jpg
    [4] => /image.jpg
)
```
### Identify the root cause ✅
The reason for this behaviour is because `wp_parse_url` returns a path with a forward slash like so - `/image.jpg` here:
https://github.com/wp-media/wp-rocket/blob/699c3fcdb7dab29174747cea9d2b23c78bd45ee7/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L215
With that there would be a mismatch when matching `/image.jpg` with `image.jpg` to exclude.

### Scope a solution ✅
We can `ltrim` the forward slash off the returned paths here: https://github.com/wp-media/wp-rocket/blob/699c3fcdb7dab29174747cea9d2b23c78bd45ee7/inc/Engine/Media/AboveTheFold/Frontend/Controller.php#L215

### Estimate the effort ✅
[XS]

**Comment by MathieuLamiot** [comment]
@jeawhanlee Have you performed basic checks to ensure the code does not break on happy path and that the reported failing cases are fixed? In which case, we can merge so that we only have to work on the feature branch. OK? Thanks 🙏

**Comment by MathieuLamiot** [comment]
@jeawhanlee Kind reminder. It seems like an issue that could be "Test by devs" @wp-media/qa-team no? In which case, if @jeawhanlee validated already, we could merge and close I think :)

**Comment by jeawhanlee** [comment]
I have validated and adapted tests that works.

**Comment by MathieuLamiot** [comment]
Let's merge then! :rocket:
