### ISSUE TITLE
Should fetch the 1st 10 links in home page on multisite

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket#6578]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 5.16-alpha1 ✓
- Used the search feature to ensure that the bug hasn’t been reported before ✓

**Describe the bug**
Warm-up link fetching does not work on multisite. 

**To Reproduce**
1. Log as an admin on:
- http://newmulti.rocketlabsqa.ovh/ (multisite with subdirectories)
- http://subdomain.rocketlabsqa.ovh/ (multisite with subdomains)
3. Clear Critical Images from WPR Admin bar (either on main or secondary site, does not matter)
4. Search for **Add yo queue request arguments** logs inside wp-rocket-debug.log.html file
5. Notice that there are no links fetched. 

**Expected behavior**
Should fetch the homepage URL + 1st 10 links from home page on multisite.
Related TestRail TC [HERE](https://wpmediaqa.testrail.io/index.php?/tests/view/41694)

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Khadreal** [comment]
While trying to reproduce this I noticed the reason links aren't fetch on these multisites is because of the ssl error. This line below will usually fail once there's an expired/faulty ssl. The ssl are renewed on the sites and I can see the **Add your queue request arguments** in wp-rocket-debug.log.html. You can check the log or clear critical images to confirm.
https://github.com/wp-media/wp-rocket/blob/715e19cf5eb38fa51ae566422015b74d947f55b5/inc/Engine/Media/AboveTheFold/WarmUp/Controller.php#L89

**Comment by MathieuLamiot** [comment]
@hanna-meda would you be able to re-check to confirm @Khadreal's findings? Thanks 🙏

**Comment by hanna-meda** [comment]
@Khadreal, @MathieuLamiot, @piotrbak checked on both multisites. 
[TC](https://wpmediaqa.testrail.io/index.php?/tests/view/41694) is passing on http://newmulti.rocketlabsqa.ovh/ 
For http://subdomain.rocketlabsqa.ovh/ I could only partially check, for the main site, and all was good. For subdomains, the certificate could not be renewed for some reason, so I could not properly test. I will revisit when the certificate issue will be solved for subdomains there as well.
But this can be closed.
