### ISSUE TITLE
Preload tag has incorrect markup if LCP element has at least 2 background-images among pseudo-elements

### ISSUE THREAD

**Issue by alfonso100** [wp-media/wp-rocket#6634]
**Before submitting an issue please check that you’ve completed the following steps:**
Yes - Made sure you’re on the latest version
Yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When LCP image is added as BG image via CSS with a relative path, we might include incorrect chars at the end: `%20url`

EDIT Mathieu Lamiot: I don't think that the use of a relative path is creating the issue here. See below, but I think the issue is that one element has 2 pseudo-elements with background-image and we "merge" the beginning of the 2nd with the 1st one.

example markup code. 
`<link rel="preload" as="image" href="https://www.site.com/wp-content/themes/image/img/home.jpg%20url" fetchpriority="high">
`

in the database it will be similar to this (is not the same image on my test site): 
`{"type":"bg-img","bg_set":[{"src":"https:\/\/site.com\/2022\/02\/img\/home.jpg url"}]}`

Per @MathieuLamiot research: 

> this is a bug on the beacon script. We'll need a dedicated GH issue, not the #6599
> The issue happens because of the syntax mentioned by Piotr with the url(...) to declare the background images.

> On this page: https://www.softactivity.com/, I retrieved the element featured-line:
```
let list = document.querySelectorAll('div')
let element = list[4]
```
> Then, I applied a few lines from the beacon script:
```
const computed_style = window.getComputedStyle(element, null);
			const bg_props = [
				computed_style.getPropertyValue("background-image"),
				getComputedStyle(element, ":after").getPropertyValue("background-image"),
				getComputedStyle(element, ":before").getPropertyValue("background-image")
			];

			const full_bg_prop = bg_props.filter(prop => prop !== "none").join("");
```
This gives` full_bg_prop = 'url("https://www.softactivity.com/wp-content/themes/soft-activity/img/home.jpg")url("https://www.softactivity.com/wp-content/themes/soft-activity/img/bg_slider_s.png")'`

I think this is then badly handled by those lines:
```
const matches = [...full_bg_prop.matchAll(css_bg_url_rgx)];
element_info.bg_set = matches.map(m => m[1] ? {src: m[1].trim() + (m[2] ? " " + m[2].trim() : "")} : {});
```

**To Reproduce**
1. Add an HTML element.
2. With a CSS background image: `background-image: url(../img/home.jpg);`
3. Generate the Critical images
4. See the markup error

**Expected behavior**
We should correctly extract relative images to avoid broken markup. 

**Screenshots**
https://i.imgur.com/ljn2ItQ.png

**Additional context**
Slack thread: 
https://wp-media.slack.com/archives/C072P5EU5DF/p1715797306772669

Ticket: 
https://secure.helpscout.net/conversation/2598679615/491736?folderId=2683093

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by frhtslyn** [comment]
İ've been trying to figure out why the load average value of my server has been high for days. Then I realized that my 404 page dynamically loads to visitors via %20url without caching for thousands of visitors. This is very bad. Pleast fix it.

**Comment by MathieuLamiot** [comment]
Same issue on [this report](https://wp-media.slack.com/archives/C072P5EU5DF/p1716226234924279).

`elementor-motion-effects-layer` & `elementor-motion-effects-layer::before`

the issue is that for a given element, there are `background-image` declared for at least 2 pseudo-types so `full_bg_prop` becomes the concatenation of 2 background-image values and the beginning of the 2nd is kept in this:

```
const matches = [...full_bg_prop.matchAll(css_bg_url_rgx)];
element_info.bg_set = matches.map(m => m[1] ? {src: m[1].trim() + (m[2] ? " " + m[2].trim() : "")} : {});
```

**Comment by MathieuLamiot** [comment]
To @wp-media/engineering-plugin-team when grooming this: I am not sure to understand why we use those lines:

```
const computed_style = window.getComputedStyle(element, null);
			const bg_props = [
				computed_style.getPropertyValue("background-image"),
				getComputedStyle(element, ":after").getPropertyValue("background-image"),
				getComputedStyle(element, ":before").getPropertyValue("background-image")
			];

			const full_bg_prop = bg_props.filter(prop => prop !== "none").join("");
```
Wouldn't it be better to take the first, if empty, the second, if empty the third?

@DahmaniAdame @piotrbak What would be the expected behavior if an element has a before and/or an after pseudo-element as well as its own background image? Which one should be take?

**Comment by piotrbak** [comment]
As per @DahmaniAdame let's ignore the pseudo elements if the image has its own background. and stick with the regular background image.

If we collect a lot of feedback from customers, we might need to change the behaviour here to preload and treat as LCP all of them.

**Comment by Miraeld** [comment]
## Reproduce the problem
To reproduce the issue, simply create a new page and add a custom html block with the following code: 
``` html
<div class="multiple-bg">
<h2> Hello world</h2>
<p>Lorem ipsum</p>
</div>
<style>
.multiple-bg {
background-image: url(https://placehold.co/400x600/EEE/31343C);
}

.multiple-bg:after {
background-image: url(https://placehold.co/600x400/EEE/31343C);
}
</style>
```

Then load the page and check the LCP data. 

## Identify the root cause
The issue seems to be coming from the regex [here](https://github.com/wp-media/wp-rocket/blob/38775324e680d7358bf0e60280abefffeb2f056e/assets/js/lcp-beacon.js#L151) which returns the wrong value when several `background-image` are detected. 


## Scope a solution
To solve the issue, we need to modify the regex with:
``` php
		const css_bg_url_rgx = /url\(\s*?['"]?\s*?(.+?)\s*?["']?\s*?\)/ig;
```
This will ensure the correct matches. 

## Effort estimation: 
XS
## Is a refactor needed in that part of the codebase?
No
