### ISSUE TITLE
 WooCommerce AJAX Filter query strings caching

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#67]
You should be able to reproduce it by: 1. Check the following under "Files optimisation": - HTML - Inline CSS - Inline JS - Google Fonts - CSS 2. Enable CDN. 3. Add a query string parameter to the field labeled "Cache pages that use the following query strings (GET parameters):" under Advanced options. 4. Visit a page or two that use that query string parameter. 5. View source to make sure CDN is active. 6. Disable CDN. 7. Visit one of those query string pages when logged into WP admin. Page should load fine. 8. View source to make sure CDN is disabled. 9. Visit one of those query string pages in a different browser, NOT logged into WP admin. Page won't load properly - some resources (like CSS) fail and the page is broken. 10. View source to see some of what's going on. Header is broken.
NOTES: Check on the live site, there is an issue on staging -

**Comment by arunbasillal** [comment]
@jbma Do you happen to remember which is the `WC ajax filter` plugin? 
I tried with this one: https://wordpress.org/plugins/wc-ajax-product-filter/ and I couldn't replicate the issue. 

Since there aren't any further reports of the same, and if you do not remember more details at this point, let's close this issue for now and deal with it if it happens in the future.

**Comment by GeekPress** [comment]
@arunbasillal I suppose that we can close the issue. After 4 years, the issue could be fixed since then.

Let's re-open it if a new case come up.
