### ISSUE TITLE
Prewarmup home in certain scenarios where it shouldn't

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6850]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.16.3
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Home page prewarmup occurs when switch theme/change permalinks and clear critical images for license expired > 15d 

**To Reproduce**
1. license expired > 15d
2. fresh install ===> no warmup
3. clear critical images
4. check WPR log and ATF table ==> home page added to log and ATF table in DB

**Expected behavior**
Prewarmup shouldn't work for license > 15

**Screenshots**

**Additional context**
- Currently for license expired > 15 , only home is added to logs/atf table when clear critical images is triggered

**Acceptance Criteria (for WP Media team use only)**
**Updated intervals which was expected based on discussion with PO before**
- Warmup occurs for valid license  and expired license <15 d
- No warmup to home nor links at home for license expired > =15d

**Comment by remyperona** [comment]
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
There is no check for the grace period in the method handling the homepage warmup

### Scope a solution ✅ 
in `Common\PerformanceHints\WarmUp\Controller`
- update `warm_up_home()` to add the grace period check
- also add the check for the environment type which is missing
- update `warm_up()` to add the grace period check in this method instead of in the `fetch_links()` method

### Estimate the effort ✅ 
Effort S
