### ISSUE TITLE
3.17: LRC style isnot added to used CSS when enable RUCSS

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6901]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => feature/6840-lcr-frontend-subtask
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When enabling RUCSS while LRC is already created, the used CSS does not contain the LRC CSS

**To Reproduce**
1. Visit a page => LRC added to DB
2. Clear cache and revisit the page => LRC style added to the page
3. Enable RUCSS 
4. revisit the page and wait till the used CSS is created then revisit the page => LRC style is not in the source
```
[data-wpr-lazyrender] {
content-visibility: auto;
} 

```
**Expected behavior**
LRC style is preserved in used CSS

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Khadreal** [comment]
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
This is happening in https://github.com/wp-media/wp-rocket/blob/7999ed2618d11d7fa9b63fc78a7810789072d4b9/inc/Engine/Optimization/RUCSS/Controller/UsedCSS.php#L290 at its remove internal styles from the page. 

### Scope a solution ✅ 
Add `rocket-lazyrender-inline-css` as an attribute to LazyRenderContent CSS here https://github.com/wp-media/wp-rocket/blob/fb50ef3b9db98b09b4b90797f5c16117a1560435/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L96  for backend to exclude it from being remove during RUCSS process

### Estimate the effort ✅ 
[XS]

**Comment by jeawhanlee** [comment]
For clarity sake, we're adding and id attribute to the style tag like so: `<style id="rocket-lazyrender-inline-css">`
LGTM
