### ISSUE TITLE
Data for mobile URLs will no longer be present under ATF & LRC tables under specific steps

### ISSUE THREAD

**Issue by hanna-meda** [wp-media/wp-rocket#6905]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅  3.17-alpha1 - `feature/lrc`
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
Data for mobile URLs will no longer be present under ATF & LRC tables after activating  filter `pre_get_rocket_option_do_caching_mobile_files` with Preload ON, then turning off Preload & filter. 

**To Reproduce**
1. With Preload enabled, activate filter `pre_get_rocket_option_do_caching_mobile_files`:
`add_filter( 'pre_get_rocket_option_do_caching_mobile_files', '__return_zero' );`
2. Perform any action that triggers data clearing, such as: switch Theme, change Permalink, Clear Performance Hints data from Admin bar. Check the DB, LRC & ATF tables => Tables populating only with desktop warmup links. ✅ 
3. Disable Preload.
4. Turn off filter. 
5. Repeat data clearing (any action mentioned at Step 2). Check the DB, LRC & ATF tables => Tables will still be populated only with the desktop version of URLs. :x:

*Notes:*
:grey_exclamation: Manual mobile visits will still not add mobile data to the tables.
The issue reproduces consistently on both  3.16.4 & 3.17,  rocket and new.rocket test envs.
Warmup on fresh installs can be affected after reproducing this issue once on an env. 

**Expected behavior**
Deactivating the `pre_get_rocket_option_do_caching_mobile_files` filter (that disables Separate Mobile Cache), should enable again the fetching of mobile versions of URLs.

**Comment by jeawhanlee** [comment]
### Reproduce the issue ✅
I was able to reproduce the issue and it turns out that we have this from 3.16 major, but it's sort of an edgy case. @hanna-meda if I'm right.
To reproduce this:
- Open code snippets on a new tab
- With Preload enabled, activate filter `pre_get_rocket_option_do_caching_mobile_files`: `add_filter( 'pre_get_rocket_option_do_caching_mobile_files', '__return_zero' );`
- Open WPR dashboard on another tab
- Perform any action that triggers data clearing, such as: switch Theme, change Permalink, Clear Performance Hints data from Admin bar. Check the DB, LRC & ATF tables => Tables populating only with desktop warmup links.
- Move back to the other tab with code snippets
- Disable the snippet
- Move back to the tab with WPR dashboard
- Without refreshing the page, Disable preload
- Perform any action that triggers data clearing, such as: switch Theme, change Permalink, Clear Performance Hints data from Admin bar. Check the DB, LRC & ATF tables => Tables will still be populating only with desktop warmup links.

### Identify the root cause ✅
This is happening because when we update the filter to disable separate mobile cache files, the WPR settings form will have this settings value to 0 in the hidden input and if the filter is later disabled and the dashboard is not refreshed before saving settings, we will end up with the old value saved in the DB.

### Scope a solution ✅
A solution I see would be to preserve the DB value of `do_caching_mobile_files` if it is already enabled during settings update. The only draw back I see is that, if the option is disabled using a filter, when the settings is updated, the regenerated wpr config will not have the filter value and so it will always be enabled.

### Estimate the effort ✅
[XS]

CC @piotrbak

**Comment by hanna-meda** [comment]
@jeawhanlee, on rocketlabsqa with `3.17-alpha1`, I was able to reproduce this without opening new tabs, all actions done in a subsequent order in the same window. Here's a video of it:

https://github.com/user-attachments/assets/01c1a872-23ce-489b-9e03-645adaed698a

**Comment by jeawhanlee** [comment]
@hanna-meda I can see the order you followed and I think we might still be on to the same thing

What if you took this order instead:
- Enable filter
- Go to WPR dashboard
- Clear performance hints data
- Check DB
- Disable filter
- Disable preload or enable/disable any settings on WPR
- Check DB

You should still see mobile data for LRC & ATF

All these steps accordingly on the same tab.

**Comment by hanna-meda** [comment]
@jeawhanlee, yes, by this order things are working fine:

1. Enable filter
2. Go to WPR dashboard
3. Clear performance hints data
4. Check DB
5. Disable filter
6. Disable preload or enable/disable any settings on WPR
7. Clear performance hints data
8. Check DB

And by inverting steps 5. with 6., disabling/enabling preload first and then disabling filter, will have the issue occuring.

**Comment by jeawhanlee** [comment]
Pinging @piotrbak @MathieuLamiot

**Comment by MathieuLamiot** [comment]
Thanks for the details. It seems like very edge case to me, I am not sure this is something we want to work on @piotrbak ?

**Comment by piotrbak** [comment]
@MathieuLamiot @hanna-meda Agreed, that sounds too edgy and it's a moderate severity one.

**Comment by piotrbak** [comment]
It sounds too edgy to work on it in upcoming months
