### ISSUE TITLE
3.17 - regex to remove `data-rocket-location-hash` mismatch

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6910]
**Before submitting an issue please check that you’ve completed the following steps:**
Tested in 3.17 alpha 1

**Describe the bug**
The current regex to clear `data-rocket-location-hash` has mismatches and removes whole elements.

https://github.com/wp-media/wp-rocket/blob/21261f3563744b2aec34542460ccf23c24f95b4a/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L79

https://gist.github.com/DahmaniAdame/92f8f5aeb6ffeffda846585bea6c20fa

Changing the regex pattern to `/data-rocket-location-hash="[^"]*"/i` picked the right elements (to be further tested by QA): 

https://gist.github.com/DahmaniAdame/8f2ce6da9d1ee052f2c1d155776645d9

Testing sample: https://gist.github.com/DahmaniAdame/2146eec70321898bf1e8f42cd2cdf0f6

**To Reproduce**
N/A

**Expected behavior**
`data-rocket-location-hash` should be dismissed accurately without causing any missing elements.

**Screenshots**
N/A

**Additional context**
N/A

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Mai-Saad** [comment]
Can reproduce the issue here for elements below/above the fold when having 3 or more nested elements https://newer.rocketlabsqa.ovh/lrc_similive/
Here 
```
    <header> header in body totally atf
        <div class="container"> div in header in body <div> div in div in header in body
            <h1>Powerful Electrical LLC</h1> </div>
            <nav>
                <ul>
                    <li><a href="#about1">About Us</a></li>
                    <li><a href="#services1">Services</a></li>
                    <li><a href="#contact1">Contact</a></li>
                </ul>
            </nav>
        </div>
        end header in body
    </header>
    <div> div in body <div> another div in body <header> header in div in div in body<div>another div in header in div in div in body</div></header></div></div>
```
and here `<div> div in body<section>section in div<footer>footer in section in div</footer></section></div>`

**Comment by Khadreal** [comment]
### Reproduce the issue ✅ 
Yes

### Identify the root cause ✅ 
https://github.com/wp-media/wp-rocket/blob/fb50ef3b9db98b09b4b90797f5c16117a1560435/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L79
The pattern here doesn't handle values on a same line well which is why it break some nested elements, rightly changing to this `/data-rocket-location-hash="[^"]*"/i` as suggested by @DahmaniAdame fix the problem.

### Scope a solution ✅ 
Change regex pattern to `/data-rocket-location-hash="[^"]*"/i` and add test

### Estimate the effort ✅ 
[S]

**Comment by jeawhanlee** [comment]
LGTM
