### ISSUE TITLE
3.17: Hashes arenot removed from the source when there is no LRC data

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket#6922]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => feature/lrc
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When accessing a page that is totally above the fold and having lrc as [] in DB , hashes aren't removed from source

**To Reproduce**
1. Clear performance hints
2. Visit a page that is all is ATF => LRC is [] in DB
3. Clear cache
4. Visit the page again => hashes are there

**Expected behavior**
Hashes should be removed when visiting uncached page that have [] LRC in DB

**Screenshots**

**Additional context**
- slack https://wp-media.slack.com/archives/CUT7FLHF1/p1724850889231899
- If screen size is unacceptable, the script will bailout and hashes will always be there in the source => expected

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
@piotrbak I think the case where the LRC row contains a status different than "completed" should be added here too. I think currently, if the row is failed, it will have the same issue.

**Comment by piotrbak** [comment]
@MathieuLamiot Yes, this is how it should work.

**Comment by jeawhanlee** [comment]
### Reproduce the issue ✅
I was able to reproduce the issue with the same steps in this issue.

### Identify the root cause ✅
There are 2 reasons for this:
- The first is [here](https://github.com/wp-media/wp-rocket/blob/d7a5719c9211d080f22af8594480b3f260219196/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L62), so for a situation when [] is saved in DB, it would pass the has_lrc check but will not pass here and return back the same html without removing hashes
- The second is [here](https://github.com/wp-media/wp-rocket/blob/d7a5719c9211d080f22af8594480b3f260219196/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L46), even when `has_lrc` fails (status is not complete or below_the_fold is empty or below_the_fold is 'not found' which we don't do at the moment) we will return back the same html buffer without removing the hashes.

### Scope a solution ✅
- We either update `WP_Rocket\Engine\Optimization\LazyRenderContent\AJAX\Controller::add_data` to set `below_the_fold` to `not found` if empty or we update `WP_Rocket\Engine\Optimization\LazyRenderContent\Database\Rows\LazyRenderContent::has_lrc` to replace 'not found' with `'[]'
`- Then we remove hashes every time we do a early return [here](https://github.com/wp-media/wp-rocket/blob/d7a5719c9211d080f22af8594480b3f260219196/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L46), [here](https://github.com/wp-media/wp-rocket/blob/d7a5719c9211d080f22af8594480b3f260219196/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L52) & [here](https://github.com/wp-media/wp-rocket/blob/d7a5719c9211d080f22af8594480b3f260219196/inc/Engine/Optimization/LazyRenderContent/Frontend/Controller.php#L62)

- Update tests for this.

### Estimate the effort ✅
[S]

**Comment by Miraeld** [comment]
Looks good to me

**Comment by hanna-meda** [comment]
Related TP here => https://wpmediaqa.testrail.io/index.php?/runs/view/894&group_by=cases:section_id&group_order=asc
