### ISSUE TITLE
Add query string to force LRC hash injection

### ISSUE THREAD

**Issue by piotrbak** [wp-media/wp-rocket#6944]
**Is your feature request related to a problem? Please describe.**
It's a plugin part of this [issue](https://github.com/wp-media/wpr-inspector/issues/38) for the Inspector. We want to allow the LRC feature to inject hashes to the HTML elements.

**Describe the solution you'd like**
When visiting the URL with `wpr_lazyrendercontent` query string, we'll inject hashes to the HTML elements without caching the page.

**Acceptance criteria**
1. When visiting the URL with `wpr_lazyrendercontent` query string, hashes will be added to the HTML elements. Filter related to the depth (currently `rocket_lazy_render_content_depth` [more info](https://wp-media.slack.com/archives/CUT7FLHF1/p1725391453414419)) will be respected.
2. It should be possible to use `wpr_lazyrendercontent` together with `wpr_imagedimensions` query string. Both of them should be operational when used together.
3. The page cache should not be created when using this query string
4. The LRC data should not be added to the database when using this query string

**Comment by Khadreal** [comment]
### Scope a solution ✅

- In [here](https://github.com/wp-media/wp-rocket/blob/4d7b54b0796449ab88a10a756266faebf9c4c339/inc/Engine/Optimization/LazyRenderContent/Frontend/Subscriber.php#L31) add 
```
'template_redirect' => [ 'force_lrc_buffer' ]

'rocket_critical_lrc_force_visit_buffer' => [ 'add_hashes', 16 ]
```

Add new methods in the subscriber [class](https://github.com/wp-media/wp-rocket/blob/4d7b54b0796449ab88a10a756266faebf9c4c339/inc/Engine/Optimization/LazyRenderContent/Frontend/Subscriber.php)
```
public function force_lrc_buffer() {
      if ( empty( $_GET['wpr_lazyrendercontent'] ) ) { 
      	return;
      }
      ob_start( [ $this, 'prepare_force_lrc_visit' ] );
}

public function prepare_force_lrc_visit( $buffer ) {
              if ( ! isset( $_GET['wpr_lazyrendercontent'] ) ) {
			return $buffer;
		}

		return apply_filters( 'rocket_critical_lrc_force_visit_buffer', $buffer );
}
```

- Update test

### Scope a solution ✅
[S]

**Comment by MathieuLamiot** [comment]
Discussed with @jeawhanlee and @Khadreal after testing @Tabrisrp's PR. The current PR has `wpr_lazyrendercontent` working fine, but the "SaaS query string" with no_wprocket & wpr_imagedimensions does not work anymore as expected because `rocket_critical_image_saas_visit_buffer` is no longer triggered.

The current ACs seem very hard to achieve, or even not really possible:
- With the "SaaS query string", we must inject the beacon and save to DB if needed.
- with wpr_lazyrendercontent, we must not save to DB
So we can't have both functional at the same time as per AC 2.

Since @piotrbak is off, we decided to do the following:
- Bring back `rocket_critical_image_saas_visit_buffer` in the code, while keeping the addition of `rocket_performance_hints_buffer` so that both query strings can work.
- The risk is that if we ever use `?nowprocket=1&no_optimize=1&wpr_imagedimensions=1&wpr_lazyrendercontent` maybe hash injection will be triggered twice? It's an edge case but we'll check if we can just bail out of the `rocket_performance_hints_buffer` if `nowprocket` is set. As a result, AC 2 won't be fulfilled but if both query strings are there, then the Saas one is taking priority.

**Comment by MathieuLamiot** [comment]
Refinement to the AC1: https://wp-media.slack.com/archives/CUT7FLHF1/p1725641341581969 With the query string, hashes should be injected even if the feature is deactivated with a filter.
