### ISSUE TITLE
Exclude `svg use` targets from ALR

### ISSUE THREAD

**Issue by DahmaniAdame** [wp-media/wp-rocket#6978]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version [x]
- Used the search feature to ensure that the bug hasn’t been reported before [x]

**Describe the bug**
SVG `use` might call a lazy rendered elements on the page. In such case, the SVG won't look as expected as it still inherits the skipped layout and painting work from the originally lazy rendered element. 

**To Reproduce**
Case discussed here - https://wp-media.slack.com/archives/C07LKLTKBG8/p1726606365110269

**Expected behavior**
Elements targeted by `svg use` shouldn't be lazy rendered. The exclusion should include any of their parents eligible for LRC. 

We don't know where exactly the target element is located. Example, the instructing `use` element might come from an element below the fold, but the target element is still further down on the page. Consequently, we should go with a systematic dismissal of targeted elements.

**Screenshots**
N/A

**Additional context**
https://wp-media.slack.com/archives/C07LKLTKBG8/p1726606365110269

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Miraeld** [comment]
## Reproduce the issue:

- Be on latest version of WP Rocket
- Clear Cache + priority elements
- Load the page https://new.rocketlabsqa.ovh/lrc_live_3-17/
- You should see an infinite loading screen
- Clear the cache
- Reload the page
- Loading screen disappear and while scrolling you should see a corrupted logo

## Identify the root cause
The issue is that SVG use elements might call lazy rendered elements on the page, causing visual regression as they inherit the skipped layout and painting work from the originally lazy rendered element.

## Scope a solution
To solve the issue, we need to create a new function `_getSvgUseTarget()`: 
``` javascript
    _getSvgUseTargets() {
        const useElements = document.querySelectorAll('use');
        const targets = [];

        useElements.forEach(use => {
            const href = use.getAttribute('href') || use.getAttribute('xlink:href');
            if (href) {
                const target = document.querySelector(href);
                if (target) {
                    targets.push(target);
                    let parent = target.parentElement;
                    while (parent) {
                        targets.push(parent);
                        parent = parent.parentElement;
                    }
                }
            }
        });

        return targets;
    }
``` 
in [BeaconLrc.js](https://github.com/wp-media/rocket-scripts/blob/8e25bbfddce70e1c142bb879f9467061f6696dd7/src/BeaconLrc.js) and modify the function `_getLazyRenderElements` to:
``` javascript
    _getLazyRenderElements() {
        const elements = document.querySelectorAll('[data-rocket-location-hash]');
        const svgUseTargets = this._getSvgUseTargets();

        if (elements.length <= 0) {
            return [];
        }

        const validElements = Array.from(elements).filter(element =>
            !this._skipElement(element) && !svgUseTargets.includes(element)
        );

        return validElements.map(element => ({
            element: element,
            depth: this._getElementDepth(element),
            distance: this._getElementDistance(element),
            hash: this._getLocationHash(element)
        }));
    }
```

This will ensure we exclude svg elements from LRC as it can cause visual regression. 

## Development steps:
- [] Create a new function `_getSvgUseTargets()`
- [] Modify `_getLazyRenderElements()` 
- [] Ensure it's working as expected.

## Effort estimation: 
XS
## Is a refactor needed in that part of the codebase?
No

**Comment by jeawhanlee** [comment]
LGTM for this scenario but isn't the idea trying to have a generic exclusion for things like this or not? @MathieuLamiot @piotrbak

**Comment by piotrbak** [comment]
@jeawhanlee For now we didn't see any other similar exclusion
