### ISSUE TITLE
Add compatiblity with LiteSpeed Server cache

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#73]
Is it possible to auto-purge Litespeed cache along with WP Rocket cache? example plugin: https://wordpress.org/plugins/litespeed-cache/

**Comment by Tabrisrp** [comment]
Apparently the litespeed cache can receive the same purge command as Varnish, so checking the Varnish purge option is enough.

**Comment by GeekPress** [comment]
I re-open it at the support team reported it doesn't work.

**Comment by WordPresseur** [comment]
Related discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1559054508123400?thread_ts=1559048031.097600&cid=C08N8J6VC

**Comment by arunbasillal** [comment]
Romain has a Litespeed server to learn more about this - https://wp-media.slack.com/archives/CBJ2KQ0MU/p1563800295000400

**Comment by arunbasillal** [comment]
For 3.4.1, @crystinutzaa worked on this one. Here is what we have now. Thanks for all the explanation Cristina :)

- LightSpeed stores HTML, CSS, JS, and images in it's own folder in the server. 
- When WP Rocket is enabled, we list `LightSpeed Cache` as conflicting plugin and request to disable it. 
- Once LightSpeed Cache is disabled, the `x-lsadc-cache` header is missing for HTML. Other assets still have this header. 
- The LightSpeed Cache plugin also adds [rules into .htaccess](https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:no-plugin-setup-guidline).
- None of these affects the assets and they still have the `x-lsadc-cache` header. 
- There are multiple ways to clear LightSpeed cache. We use the header method and send the `X-LiteSpeed-Purge` header to clear the cache. 
- With `3.4.1-alpha1`, when the cache for a post is cleared, the header shows a `MISS` for some assets and `HIT` for others immediately. This is okay because LightSpeed cache is cleared asynchronously and can take a while to catch up. 
- If the entire cache is cleared, every asset is cleared immediately. 

**The main reason why we wanted this compatibility is so that customers didn't have to clear their LightSpeed cache manually when they clear WP Rocket cache. This is achieved with the work that is put into `3.4.1-alpha1`.** 

HTML files missing it's header shouldn't affect real world performance, because in the end WP Rocket serves a static file as well. More testing and learning needs to happen on this one if we try to do this in the future. 

Related conversation - https://wp-media.slack.com/archives/CBJ2KQ0MU/p1571152454014200
