### ISSUE TITLE
Activate caching on multisite even when using mapped domain

### ISSUE THREAD

**Issue by jbma** [wp-media/wp-rocket#74]
When you have multisite with domain mapping, caching doesn't get activated unless you log in to the admin area using the mapped url, and activate WP Rocket that way. If you log in using the original URL, WP Rocket doesn't detect the mapped domain.

**Comment by 21stcn** [comment]
To expand on this, it is my experience that not only do you have to activate the plugin through the mapped domain admin, any subsequent actions performed from within the admin area, be they manual or cron or ajax might fail. For example, clearing the cache button does not work from the unmapped admin domain. Switching to the mapped admin domain and clearing works. And the cache can be built when users visit the mapped domain on the frontend. It is basically all admin action performed from the unmapped domain which cause complications.

My situation: my site is a subdomain multisite. The main site is:
http://blog.something.com

A sub site is:
http://store.something.com
(http://store.blog.something.com without domain mapping)

I am using a MU plugin, WordPress MU Domain Mapping, which I need to use, because I require Remote Login in order to have single sign on (SSO) working for the network.

The domain options that are critical for the network are:
[x] Remote Login
[x] Redirect administration pages to site's original domain (remote login disabled if this redirect is disabled)

This means that the domain for the store sub site admin area is and has to be:
store.blog.something.com/wp-admin/

The entire network is built around this, meaning the frontend is store.something.com and the admin store.blog.something.com/wp-admin/, and it works well for everything except for WP rocket.

I have read your documentation entry (https://docs.wp-rocket.me/article/874-how-to-use-wp-rocket-in-a-multisite-environment) and turned off domain mapping to ACTIVATE the plugin as described. So it was activated from store.something.com/wp-admin/plugins.php, with domain mapping disabled.

" Domain Mapping
If you use a domain mapping plugin on your multisite, when activating WP Rocket, you must access your wp-admin area using the mapped domain, that is, the domain that will be used on the front-end of the site. Otherwise WP Rocket will not be able to detect the correct URL to update our configuration files. "

So far so good. I set the settings and the caching appeared to be working fine. Folders and files were being created in /wp-content/cache/wp-rocket/store.something.com/ when users visited the site FROM THE FRONTEND.

However, the problem is that I am unable to clear the cache, and minification appears not to be working, with domain mapping reactivated. When I press the clear cache button from store.blog.something.com/wp-admin/ and then use a ftp client to access /wp-content/cache/wp-rocket/store.something.com/ , I can see that all the cached files and folders are still there. Nothing has been deleted.

If I disable domain mapping and press the clear cache button from store.something.com/wp-admin/ the cache is emptied successfully.

I could live without being able to manually clear the cache in the admin area, HOWEVER my concern is that the automated cache clearing after expiry of the cache lifecycle, will not successfully clear the cache. So the cache will in essence never be cleared.

It would appear that, when any cache related function is run from the frontend (store.something.com) such as building the cache when a user visits the site, everything works fine. But when any function is run from the admin area (store.blog.something.com), it fails because presumably it is using unmapped url.

So, if this is the case, in the very least, your documentation article linked above does not adequately address the issue because it is not just a case of the plugin being activated from the mapped domain, but all admin functions need to be performed from that mapped domain. 

I am going to try to resolve this using the filters provided such as rocket_clean_domain_urls  . Hopefully it won't actually be too difficult to just chop out the one part before action occur on the unmapped domain.
