### ISSUE TITLE
no matching package for wp-background-processing 1.1

### ISSUE THREAD

**Issue by goaround** [wp-media/wp-rocket#741]
Hi,

tried to load wp-rocket 2.11.5 via composer but it seems that a5hleyrich/wp-background-processing 1.1 does not exist? There is only 1.0: https://packagist.org/packages/a5hleyrich/wp-background-processing#1.0 

> wp-media/wp-rocket v2.11.5 requires a5hleyrich/wp-background-processing 1.1 as 1.0 -> no matching package found.

**Comment by Tabrisrp** [comment]
As WP Background Processing won't be updated anymore, the package is aliased in the configuration on a fork containing the latest community fixes.

I didn't have an issue when doing a composer install/update, but I'll test this again

**Comment by goaround** [comment]
I see. I only have the issue when I load WP Rocket via my own composer.json (with wpstarter). I just added https://github.com/tabrisrp/wp-background-processing as a repository there and now it works again.

**Comment by Tabrisrp** [comment]
Great, I'm closing this then

**Comment by PUncle** [comment]
Sorry to resurrect, but I'm relatively new to composer and I'm not sure how to fix this.

`$ composer require wp-media/wp-rocket`
`wp-media/wp-rocket v3.0.4 requires a5hleyrich/wp-background-processing 1.1 as 1.0 -> no matching package found.`

How would I go about adding https://github.com/tabrisrp/wp-background-processing as a repo to my composer.json as mentioned by @goaround

I'd really appreciate a point in the right direction! Thanks!

**Comment by goaround** [comment]
Just add this as to repositories in your composer.json file

`
"repositories": [
{
"type": "vcs",
"url": "https://github.com/tabrisrp/wp-background-processing"
}
],
`

Than composer require wp-media/wp-rocket should work fine

**Comment by PUncle** [comment]
Scrub that, I'm not exactly sure why, but I got it working after closing my iTerm session and starting a new one. I have a feeling this may have been a bug in iTerm.

Thanks for the help with the extra repo though, much appreciated.

**Comment by tyrann0us** [comment]
@Tabrisrp, why not make a PR to merge your fork back into the [upstream repository](https://github.com/A5hleyRich/wp-background-processing)? This would prevent us from adding
```json
{
  "type": "git",
  "url": "https://github.com/tabrisrp/wp-background-processing"
}
```
into the `repository` property of every project that uses WP Rocket. That makes even more sens give the fact that your fork is currently already 8 commits behind the upstream.

I bet @A5hleyRich will happily merge.

Thanks!

**Comment by sitdev** [comment]
@Tabrisrp, I second @tyrann0us's suggestion. We use WP Rocket on dozens of our sites, and we would like to reference the official Packagist repo in our projects, but it's more difficult right now because of the additional overhead of remembering to add this to all of our existing composer files and any new ones in the future. As a second alternative, if you have no intentions of merging back upstream, then create a new composer file for this and add it to Packagist, like most other independently-maintained forks do.

**Comment by rreynier** [comment]
Agreed with @sitdev @tyrann0us  . It would be nice to see this resolved properly without needing to add custom repositories to composer.json (especially if not documented in your readme).

**Comment by Jeppeskovsgaard** [comment]
+1 for @tyrann0us suggestion.

**Comment by mike-source** [comment]
+1 to @sitdev suggestion... getting the original dependency author of "A5hleyRich/wp-background-processing" to accept a PR may be tricky since it's been dead for over a year.

Surely the simplest solution is to just add your maintained fork to wpackagist.org and require that as the dependency, rather than people having to add an extra custom repo to their composer.json. It's counter-intuitive even if documented, would just be nice to eliminate that extra step!

**Comment by catgofire** [comment]
Why has this not been fixed yet? Offering wp-rocket as a composer package that doesn't install out of the box is kind of silly... Can we either get the maintained fork on wpackagist or list this as `wontfix`? This issue isn't "Closed".

**Comment by lancojoe** [comment]
Problem 1
    - The requested package a5hleyrich/wp-background-processing (locked at 1.0.1, required as 1.3) is satisfiable by a5hleyrich/wp-background-processing[1.0.1] but these conflict with your requirements or minimum-stability.
