### ISSUE TITLE
Add check for pll_get_post_language() to prevent error

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/wp-rocket#804]
Sample ticket: https://secure.helpscout.net/conversation/539674804/62247?folderId=377611
(contains full error)

Customer gets fatal error when using WPLR Sync plugin because, presumably, the pll_get_post_language() function isn't available when WPLR is triggering. 
Add check with function_exists to prevent that.

**Comment by arunbasillal** [comment]
Adding a simple check fixed the issue, hard to identify the root cause of the issue.

Line 87 of: wp-content/plugins/wp-rocket/inc/common/purge.php
https://github.com/wp-media/wp-rocket/blob/master/inc/common/purge.php#L87 to:

`} elseif ( ( rocket_is_plugin_active( 'polylang/polylang.php' ) && function_exists( 'pll_get_post_language' ) ) || ( rocket_is_plugin_active( 'polylang-pro/polylang.php' ) && function_exists( 'pll_get_post_language' ) ) ) {`
