### ISSUE TITLE
LazyLoad fails on search page images

### ISSUE THREAD

**Issue by arunbasillal** [wp-media/wp-rocket#977]
Lazyload is failing on WPtouch search result pages. `data-lazy-src=` is missing. 

![01](https://user-images.githubusercontent.com/5751474/39637579-187c0df2-4fe1-11e8-85a4-c07a4fc86a14.PNG)

Related ticket: https://secure.helpscout.net/conversation/573248978/67095?folderId=1724284

Short term fix - http://snippi.com/s/lihidq2

**Comment by webtrainingwheels** [comment]
May not be specific to WP Touch. 
I have another case where search page is not cached but LazyLoad is active and breaking the images:
![view-source_https___www_foodfirefriends_com__s_brisket_rubs](https://user-images.githubusercontent.com/1043076/44047288-ca37faa6-9ee2-11e8-8865-11cb3f260c6c.jpg)

https://secure.helpscout.net/conversation/640353287/76766?folderId=273761

**Comment by iCaspar** [comment]
Indeed, this is apparently a wider issue than WPTouch. I've updated the Issue title.
Here is another ticket with some helpful debugging and possible solution:
https://secure.helpscout.net/conversation/1360482918/221158

Copying most of it without site-specifics here:

-----

Hi, I was debugging a client issue this morning where none of the images were appearing in search results.
It would work fine if you were logged in, but normal visitors were not getting the images.

Looking at the page source, the image src was the lazy load 'data:image/gif' like this:
(See ticket for html)

But when I looked for the lazyload script (both the inline script and the normal script) it was missing.

Walking through the code, in inc/Engine/Media/LazyloadSubscriber.php:should_lazyload() line 332-339 your
developers chose to skip lazyloading if the page is a search results page. On the one hand, that's fine...
so long as the code that replaced the image 'src' attributes also adhered to the same rule.

However, it is perfectly valid to not cache the search results but still want to lazyload the images on the page.

So this 'should_lazyload()' method needs to be reviewed by QA and your senior developers.

I used the following to work around it:

```
add_action('wp_footer', 'lec_fix_lazyload_on_search', PHP_INT_MAX - 1);
function lec_fix_lazyload_on_search() {
if (!is_search())
return;

add_filter( 'rocket_cache_search', '__return_true');
}
```

Note that I did it this way because I don't want to set 'rocket_cache_search' to be true at any other time..
because I don't actually want to cache the search results. I just want the lazy load scripts to be inserted
into the page.

Please review and let me know if you have any questions.
