### ISSUE TITLE
Force trailing slash works only for logged-in users

### ISSUE THREAD

**Issue by Kleindberg** [wp-media/wp-rocket#983]
The part of code in .htaccess:
```
# BEGIN WP Rocket v3.0
# Force trailing slash
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !(.*)/
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1/ [L,R=301]
```
works only if user logged-in. So Google and other bots indexing page duplicates because there is no force trailing slash in fact. When I turn-off plugin, but leave this part of code - all works fine. I think reason in WP Rocket.

**Update:**
I find a fresh code [in documentation](https://docs.wp-rocket.me/article/131-redirection-to-enforce-trailing-slash-on-urls):
```
# Force trailing slash
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{REQUEST_URI} !(.*)/$
RewriteRule ^(.*)$ http://%{HTTP_HOST}/$1/ [L,R=301]
```
and put it above # BEGIN WP Rocket v3.0 line. All works five, but it crash all GET queries to my site (for ex. WooCommerce API doesn't works with this code).

**Comment by arunbasillal** [comment]
@Kleindberg With the original .htaccess configuration (with WP Rocket rules above everything else in .htaccess) can you clear the WP Rocket cache and check if redirection works? 

Testing in the browser may not be reliable, please use something like http://wheregoes.com to see if it actually redirects. 

For SEO, its best to rely on the Canonical URL tag - https://moz.com/blog/canonical-url-tag-the-most-important-advancement-in-seo-practices-since-sitemaps

Please [open a support ticket](http://wp-rocket.me/support/) if this issue persists as we do not provide product support over here.
